/* Server version: LI-V6.3.3.4870 Firebird 1.5 
   SQLDialect: 3. ODS: 10.1. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 75 (300 Kb). Read-only: False. */
SET SQL DIALECT 3;

SET AUTODDL ON;

ALTER TABLE CPCOTACAO ADD DTVALIDCOT DATE DEFAULT 'today' NOT NULL;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Data de validade da proposta de preço.'
WHERE RDB$RELATION_NAME = 'CPCOTACAO' AND RDB$FIELD_NAME = 'DTVALIDCOT';

ALTER TABLE CPITCOMPRA ADD APROVPRECO CHAR DEFAULT 'N';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se o preço da compra foi aprovado (veio de cotação anterior);'
WHERE RDB$RELATION_NAME = 'CPITCOMPRA' AND RDB$FIELD_NAME = 'APROVPRECO';

ALTER TABLE SGPREFERE1 ADD CASASDECPRE SMALLINT;

ALTER TABLE SGPREFERE1 ADD USAPRECOCOT CHAR;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se deve utilizar o preço de cotações para pedidos de compras.'
WHERE RDB$RELATION_NAME = 'SGPREFERE1' AND RDB$FIELD_NAME = 'USAPRECOCOT';

ALTER TABLE SGPREFERE1 ADD BLOQPRECOAPROV CHAR;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se deve bloquear o faturamento de pedido de compra com preço não aprovado.'
WHERE RDB$RELATION_NAME = 'SGPREFERE1' AND RDB$FIELD_NAME = 'BLOQPRECOAPROV';

ALTER TABLE VDCLIENTE ADD INSCMUNCLI CHAR(20);

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Inscrição municipal do cliente.'
WHERE RDB$RELATION_NAME = 'VDCLIENTE' AND RDB$FIELD_NAME = 'INSCMUNCLI';

ALTER TABLE VDITCONTRATO ADD KEYLIC VARCHAR(500);

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Chave de licenciamento do produto/contrato.'
WHERE RDB$RELATION_NAME = 'VDITCONTRATO' AND RDB$FIELD_NAME = 'KEYLIC';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'''PE'' - Pendente;
''FN'' - Finalizada;'
WHERE RDB$RELATION_NAME = 'CPCOTACAO' AND RDB$FIELD_NAME = 'SITCOMPITSOL';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'''PE'' - Pendente;
''AP'' - Aprovada;'
WHERE RDB$RELATION_NAME = 'CPCOTACAO' AND RDB$FIELD_NAME = 'SITAPROVITSOL';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'''PE'' - Pendente;
''FN'' - Finalizada;'
WHERE RDB$RELATION_NAME = 'CPCOTACAO' AND RDB$FIELD_NAME = 'SITITSOL';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Situação do item da solicitação:
PE - Pendente
FN - Solicitação finalizada
CA - Cancelada'
WHERE RDB$RELATION_NAME = 'CPITSOLICITACAO' AND RDB$FIELD_NAME = 'SITITSOL';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'PE - Pendente
CT - Em Cotação
EF - Finalizada
CA - Cancelada'
WHERE RDB$RELATION_NAME = 'CPSOLICITACAO' AND RDB$FIELD_NAME = 'SITSOL';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
' Inscrição estadual do cliente.'
WHERE RDB$RELATION_NAME = 'VDCLIENTE' AND RDB$FIELD_NAME = 'INSCCLI';

/* Alter Procedure... */
/* Alter (CPADICITCOMPRARECMERCSP) */
SET TERM ^ ;

ALTER PROCEDURE CPADICITCOMPRARECMERCSP(CODEMP INTEGER,
CODFILIAL SMALLINT,
TICKET INTEGER,
CODEMPCP INTEGER,
CODFILIALCP SMALLINT,
CODCOMPRA INTEGER,
QTDITCOMPRA NUMERIC(15,5))
 AS
declare variable usaprecocot char(1);
declare variable codemppd integer;
declare variable codfilialpd integer;
declare variable codprod integer;
declare variable codprodant integer;
declare variable coditrecmerc integer;
declare variable codnat char(4);
declare variable codfilialtm smallint;
declare variable codtipomov integer;
declare variable codempfr integer;
declare variable codfilialfr smallint;
declare variable codfor integer;
declare variable codempax integer;
declare variable codfilialax smallint;
declare variable codalmox integer;
declare variable precoitcompra numeric(15,5);
declare variable aprovpreco char(1);
begin
    
    -- Carregamdo variaveis
    aprovpreco = 'N';

    -- Buscando preferências
    select coalesce(p1.usaprecocot,'N') usaprecocot
    from sgprefere1 p1
    where p1.codemp=:codemp and p1.codfilial=:codfilial
    into :usaprecocot;

    -- Buscando informações da compra
    select cp.codfilialtm, cp.codtipomov,
    cp.codempfr, cp.codfilialfr, cp.codfor
    from cpcompra cp
    where cp.codemp=:codempcp and cp.codfilial=:codfilialcp and cp.codcompra=:codcompra
    into :codfilialtm,  :codtipomov, :codempfr, :codfilialfr, :codfor;

    for select ir.codemppd, ir.codfilialpd, ir.codprod, ir.coditrecmerc
        from eqitrecmerc ir
        where
        ir.codemp=:codemp and ir.codfilial=:codfilial and ir.ticket=:ticket
        into :codemppd, :codfilialpd, :codprod, :coditrecmerc
        do
        begin

            if(:codprod <> :codprodant or :codprodant is null) then
            begin

                -- Buscando a natureza da operação
                select codnat from lfbuscanatsp(:codfilial,:codemp,:codfilialpd,:codprod,:codemp,null,null,
                :codempfr,:codfilialfr,:codfor,:codfilialtm,:codtipomov,null)
                into :codnat;

                -- Buscando informações do produto
                select pd.codempax, pd.codfilialax, pd.codalmox from eqproduto pd
                where pd.codemp=:codemppd and pd.codfilial=:codfilialpd and pd.codprod=:codprod
                into :codempax, :codfilialax, :codalmox;

                -- Buscando preço da ultima compra
--                select custounit from eqcustoprodsp(:codemppd, :codfilialpd, :codprod,
--                cast('today' as date),'U',:codempax, :codfilialax, :codalmox,'N')
--                into :precoultcp;

                -- Se deve buscar preço de cotação.
                if( 'S' = :usaprecocot) then
                begin
                    -- Deve implementar ipi, vlrliq etc... futuramente...
                    select first 1 ct.precocot
                    from cpcotacao ct, cpsolicitacao sl, cpitsolicitacao iso
                    where
                    iso.codemp = sl.codemp and iso.codfilial=sl.codfilial and iso.codsol=sl.codsol
                    and ct.codemp=iso.codemp and ct.codfilial=iso.codfilial and ct.codsol=iso.codsol and ct.coditsol=iso.coditsol
                    and iso.codemppd=:codemppd and iso.codfilialpd=:codfilialpd and iso.codprod=:codprod
                    and ct.codempfr=:codempfr and ct.codfilialfr=:codfilialfr and ct.codfor=:codfor
                    and ct.dtvalidcot>=cast('today' as date)
                    and ct.sititsol not in ('EF','CA')
                    order by ct.dtcot desc
                    into :precoitcompra;

                    if(:precoitcompra is not null) then
                    begin
                        -- Indica que o preço é aprovado (cotado anteriormente);
                        aprovpreco = 'S';
                    end

                end

                -- Se não conseguiu obter o preço das cotações
                if(precoitcompra is null) then
                begin
                    -- Buscando preço de compra da tabela de custos de produtos
                    select custounit from eqcustoprodsp(:codemppd, :codfilialpd, :codprod,
                    cast('today' as date),'M',:codempax, :codfilialax, :codalmox,'N')
                    into :precoitcompra;

                end

                -- Inserir itens
                insert into cpitcompra (
                codemp, codfilial, codcompra, coditcompra,
                codemppd, codfilialpd, codprod,
                codempnt, codfilialnt, codnat,
                codempax, codfilialax, codalmox,
                qtditcompra, precoitcompra, aprovpreco)
                values (:codempcp, :codfilialcp, :codcompra, :coditrecmerc,
                :codemppd, :codfilialpd, :codprod,
                :codemp,:codfilial,:codnat,
                :codempax,:codfilialax,:codalmox,
                :qtditcompra, :precoitcompra, :aprovpreco) ;

                -- Inserindo vínculo entre compra e recebimento

                insert into eqitrecmercitcp(codemp, codfilial, ticket, coditrecmerc, codempcp, codfilialcp, codcompra, coditcompra)
                values(:codemp,:codfilial,:ticket,:coditrecmerc,:codempcp,:codfilialcp,:codcompra,:coditrecmerc);

                codprodant = codprod;

            end
        end



  --  suspend;
end
^

/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.3.2 (27/07/2010)';
    suspend;
end
^

SET TERM ; ^

ALTER TABLE CPCOTACAO ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE CPCOTACAO ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE CPCOTACAO ALTER COLUMN CODSOL POSITION 3;

ALTER TABLE CPCOTACAO ALTER COLUMN CODITSOL POSITION 4;

ALTER TABLE CPCOTACAO ALTER COLUMN CODCOT POSITION 5;

ALTER TABLE CPCOTACAO ALTER COLUMN DTCOT POSITION 6;

ALTER TABLE CPCOTACAO ALTER COLUMN DTVALIDCOT POSITION 7;

ALTER TABLE CPCOTACAO ALTER COLUMN IDUSUCOT POSITION 8;

ALTER TABLE CPCOTACAO ALTER COLUMN CODEMPFR POSITION 9;

ALTER TABLE CPCOTACAO ALTER COLUMN CODFILIALFR POSITION 10;

ALTER TABLE CPCOTACAO ALTER COLUMN CODFOR POSITION 11;

ALTER TABLE CPCOTACAO ALTER COLUMN QTDCOT POSITION 12;

ALTER TABLE CPCOTACAO ALTER COLUMN QTDAPROVCOT POSITION 13;

ALTER TABLE CPCOTACAO ALTER COLUMN PRECOCOT POSITION 14;

ALTER TABLE CPCOTACAO ALTER COLUMN SITCOMPITSOL POSITION 15;

ALTER TABLE CPCOTACAO ALTER COLUMN SITAPROVITSOL POSITION 16;

ALTER TABLE CPCOTACAO ALTER COLUMN SITITSOL POSITION 17;

ALTER TABLE CPCOTACAO ALTER COLUMN MOTIVOCANCCOT POSITION 18;

ALTER TABLE CPCOTACAO ALTER COLUMN MOTIVOCOTABAIXO POSITION 19;

ALTER TABLE CPCOTACAO ALTER COLUMN DTINS POSITION 20;

ALTER TABLE CPCOTACAO ALTER COLUMN HINS POSITION 21;

ALTER TABLE CPCOTACAO ALTER COLUMN IDUSUINS POSITION 22;

ALTER TABLE CPCOTACAO ALTER COLUMN DTALT POSITION 23;

ALTER TABLE CPCOTACAO ALTER COLUMN HALT POSITION 24;

ALTER TABLE CPCOTACAO ALTER COLUMN IDUSUALT POSITION 25;

ALTER TABLE CPCOTACAO ALTER COLUMN VLRFRETEITCOMPRA POSITION 26;

ALTER TABLE CPCOTACAO ALTER COLUMN PERCIPIITCOMPRA POSITION 27;

ALTER TABLE CPCOTACAO ALTER COLUMN VLRBASEIPIITCOMPRA POSITION 28;

ALTER TABLE CPCOTACAO ALTER COLUMN VLRIPIITCOMPRA POSITION 29;

ALTER TABLE CPCOTACAO ALTER COLUMN VLRLIQITCOMPRA POSITION 30;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODCOMPRA POSITION 3;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODITCOMPRA POSITION 4;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODEMPPD POSITION 5;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFILIALPD POSITION 6;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODPROD POSITION 7;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODEMPLE POSITION 8;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFILIALLE POSITION 9;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODLOTE POSITION 10;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODEMPNT POSITION 11;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFILIALNT POSITION 12;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODNAT POSITION 13;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODEMPAX POSITION 14;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFILIALAX POSITION 15;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODALMOX POSITION 16;

ALTER TABLE CPITCOMPRA ALTER COLUMN QTDITCOMPRA POSITION 17;

ALTER TABLE CPITCOMPRA ALTER COLUMN PRECOITCOMPRA POSITION 18;

ALTER TABLE CPITCOMPRA ALTER COLUMN PERCDESCITCOMPRA POSITION 19;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRDESCITCOMPRA POSITION 20;

ALTER TABLE CPITCOMPRA ALTER COLUMN PERCICMSITCOMPRA POSITION 21;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRBASEICMSITCOMPRA POSITION 22;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRICMSITCOMPRA POSITION 23;

ALTER TABLE CPITCOMPRA ALTER COLUMN PERCIPIITCOMPRA POSITION 24;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRBASEIPIITCOMPRA POSITION 25;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRIPIITCOMPRA POSITION 26;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRBASEFUNRURALITCOMPRA POSITION 27;

ALTER TABLE CPITCOMPRA ALTER COLUMN ALIQFUNRURALITCOMPRA POSITION 28;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRFUNRURALITCOMPRA POSITION 29;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRLIQITCOMPRA POSITION 30;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRADICITCOMPRA POSITION 31;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRFRETEITCOMPRA POSITION 32;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRISENTASITCOMPRA POSITION 33;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLROUTRASITCOMPRA POSITION 34;

ALTER TABLE CPITCOMPRA ALTER COLUMN VLRPRODITCOMPRA POSITION 35;

ALTER TABLE CPITCOMPRA ALTER COLUMN CUSTOITCOMPRA POSITION 36;

ALTER TABLE CPITCOMPRA ALTER COLUMN CUSTOVDITCOMPRA POSITION 37;

ALTER TABLE CPITCOMPRA ALTER COLUMN REFPROD POSITION 38;

ALTER TABLE CPITCOMPRA ALTER COLUMN OBSITCOMPRA POSITION 39;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODEMPIF POSITION 40;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFILIALIF POSITION 41;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFISC POSITION 42;

ALTER TABLE CPITCOMPRA ALTER COLUMN EMMANUT POSITION 43;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODITFISC POSITION 44;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODEMPNS POSITION 45;

ALTER TABLE CPITCOMPRA ALTER COLUMN CODFILIALNS POSITION 46;

ALTER TABLE CPITCOMPRA ALTER COLUMN NUMSERIETMP POSITION 47;

ALTER TABLE CPITCOMPRA ALTER COLUMN NADICAO POSITION 48;

ALTER TABLE CPITCOMPRA ALTER COLUMN SEQADIC POSITION 49;

ALTER TABLE CPITCOMPRA ALTER COLUMN DESCDI POSITION 50;

ALTER TABLE CPITCOMPRA ALTER COLUMN DTINS POSITION 51;

ALTER TABLE CPITCOMPRA ALTER COLUMN HINS POSITION 52;

ALTER TABLE CPITCOMPRA ALTER COLUMN IDUSUINS POSITION 53;

ALTER TABLE CPITCOMPRA ALTER COLUMN DTALT POSITION 54;

ALTER TABLE CPITCOMPRA ALTER COLUMN HALT POSITION 55;

ALTER TABLE CPITCOMPRA ALTER COLUMN IDUSUALT POSITION 56;

ALTER TABLE CPITCOMPRA ALTER COLUMN EMITITCOMPRA POSITION 57;

ALTER TABLE CPITCOMPRA ALTER COLUMN APROVPRECO POSITION 58;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAREFPROD POSITION 3;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV POSITION 4;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTM POSITION 5;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTM POSITION 6;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPEDSEQ POSITION 7;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAORCSEQ POSITION 8;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILTRO POSITION 9;

ALTER TABLE SGPREFERE1 ALTER COLUMN USALIQREL POSITION 10;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOPRECOCUSTO POSITION 11;

ALTER TABLE SGPREFERE1 ALTER COLUMN ANOCENTROCUSTO POSITION 12;

ALTER TABLE SGPREFERE1 ALTER COLUMN OBSORCPAD POSITION 13;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV2 POSITION 14;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT2 POSITION 15;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT2 POSITION 16;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSORC POSITION 17;

ALTER TABLE SGPREFERE1 ALTER COLUMN TITORCTXT01 POSITION 18;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV3 POSITION 19;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT3 POSITION 20;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT3 POSITION 21;

ALTER TABLE SGPREFERE1 ALTER COLUMN ORDNOTA POSITION 22;

ALTER TABLE SGPREFERE1 ALTER COLUMN SETORVENDA POSITION 23;

ALTER TABLE SGPREFERE1 ALTER COLUMN PREFCRED POSITION 24;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOPREFCRED POSITION 25;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMO POSITION 26;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMO POSITION 27;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMOEDA POSITION 28;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV4 POSITION 29;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT4 POSITION 30;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT4 POSITION 31;

ALTER TABLE SGPREFERE1 ALTER COLUMN USACLASCOMIS POSITION 32;

ALTER TABLE SGPREFERE1 ALTER COLUMN PERCPRECOCUSTO POSITION 33;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODGRUP POSITION 34;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALGP POSITION 35;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPGP POSITION 36;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMARCA POSITION 37;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMC POSITION 38;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMC POSITION 39;

ALTER TABLE SGPREFERE1 ALTER COLUMN RGCLIOBRIG POSITION 40;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABFRETEVD POSITION 41;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABADICVD POSITION 42;

ALTER TABLE SGPREFERE1 ALTER COLUMN TRAVATMNFVD POSITION 43;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOVALIDORC POSITION 44;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLIMESMOCNPJ POSITION 45;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTBJ POSITION 46;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTJ POSITION 47;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTJ POSITION 48;

ALTER TABLE SGPREFERE1 ALTER COLUMN CNPJOBRIGCLI POSITION 49;

ALTER TABLE SGPREFERE1 ALTER COLUMN JUROSPOSCALC POSITION 50;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPFR POSITION 51;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALFR POSITION 52;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFOR POSITION 53;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTN POSITION 54;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTN POSITION 55;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTRAN POSITION 56;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTF POSITION 57;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTF POSITION 58;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOFOR POSITION 59;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT5 POSITION 60;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT5 POSITION 61;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV5 POSITION 62;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTLOTNEG POSITION 63;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTNEG POSITION 64;

ALTER TABLE SGPREFERE1 ALTER COLUMN NATVENDA POSITION 65;

ALTER TABLE SGPREFERE1 ALTER COLUMN IPIVENDA POSITION 66;

ALTER TABLE SGPREFERE1 ALTER COLUMN CUSTOSICMS POSITION 67;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPPG POSITION 68;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALPG POSITION 69;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANOPAG POSITION 70;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTB POSITION 71;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTB POSITION 72;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTAB POSITION 73;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPCE POSITION 74;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALCE POSITION 75;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODCLASCLI POSITION 76;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDEC POSITION 77;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDECFIN POSITION 78;

ALTER TABLE SGPREFERE1 ALTER COLUMN COMISPDUPL POSITION 79;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT6 POSITION 80;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT6 POSITION 81;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV6 POSITION 82;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQVENDA POSITION 83;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQCOMPRA POSITION 84;

ALTER TABLE SGPREFERE1 ALTER COLUMN VENDAMATPRIM POSITION 85;

ALTER TABLE SGPREFERE1 ALTER COLUMN VENDAPATRIM POSITION 86;

ALTER TABLE SGPREFERE1 ALTER COLUMN PEPSPROD POSITION 87;

ALTER TABLE SGPREFERE1 ALTER COLUMN CNPJFOROBRIG POSITION 88;

ALTER TABLE SGPREFERE1 ALTER COLUMN INSCESTFOROBRIG POSITION 89;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCAPRODSIMILAR POSITION 90;

ALTER TABLE SGPREFERE1 ALTER COLUMN MULTIALMOX POSITION 91;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT8 POSITION 92;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT8 POSITION 93;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV8 POSITION 94;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTNEGGRUP POSITION 95;

ALTER TABLE SGPREFERE1 ALTER COLUMN USATABPE POSITION 96;

ALTER TABLE SGPREFERE1 ALTER COLUMN TAMDESCPROD POSITION 97;

ALTER TABLE SGPREFERE1 ALTER COLUMN DESCCOMPPED POSITION 98;

ALTER TABLE SGPREFERE1 ALTER COLUMN OBSCLIVEND POSITION 99;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONTESTOQ POSITION 100;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIASPEDT POSITION 101;

ALTER TABLE SGPREFERE1 ALTER COLUMN RECALCPCVENDA POSITION 102;

ALTER TABLE SGPREFERE1 ALTER COLUMN RECALCPCORC POSITION 103;

ALTER TABLE SGPREFERE1 ALTER COLUMN USALAYOUTPED POSITION 104;

ALTER TABLE SGPREFERE1 ALTER COLUMN VERIFALTPARCVENDA POSITION 105;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCACODPRODGEN POSITION 106;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENPROD POSITION 107;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENREF POSITION 108;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODBAR POSITION 109;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODFAB POSITION 110;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODFOR POSITION 111;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCAVLRULTCOMPRA POSITION 112;

ALTER TABLE SGPREFERE1 ALTER COLUMN ICMSVENDA POSITION 113;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPRECOZERO POSITION 114;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIMGASSORC POSITION 115;

ALTER TABLE SGPREFERE1 ALTER COLUMN IMGASSORC POSITION 116;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTCPFCLI POSITION 117;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIECLI POSITION 118;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIEFOR POSITION 119;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTECPFFOR POSITION 120;

ALTER TABLE SGPREFERE1 ALTER COLUMN USANOMEVENDORC POSITION 121;

ALTER TABLE SGPREFERE1 ALTER COLUMN SISCONTABIL POSITION 122;

ALTER TABLE SGPREFERE1 ALTER COLUMN ATBANCOIMPBOL POSITION 123;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCODBAR POSITION 124;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICORCOBSPED POSITION 125;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMENSORC POSITION 126;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMENSORC POSITION 127;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMENSORC POSITION 128;

ALTER TABLE SGPREFERE1 ALTER COLUMN CUSTOCOMPRA POSITION 129;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABTRANSPCP POSITION 130;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABTRANSPORC POSITION 131;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABSOLCP POSITION 132;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICFRETEBASEICM POSITION 133;

ALTER TABLE SGPREFERE1 ALTER COLUMN PRECOCPREL POSITION 134;

ALTER TABLE SGPREFERE1 ALTER COLUMN DESCORC POSITION 135;

ALTER TABLE SGPREFERE1 ALTER COLUMN MULTICOMIS POSITION 136;

ALTER TABLE SGPREFERE1 ALTER COLUMN USUATIVCLI POSITION 137;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPHISTREC POSITION 138;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALHISTREC POSITION 139;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODHISTREC POSITION 140;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPHISTPAG POSITION 141;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALHISTPAG POSITION 142;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODHISTPAG POSITION 143;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTC POSITION 144;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTC POSITION 145;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOCLI POSITION 146;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTITRECALTDTVENC POSITION 147;

ALTER TABLE SGPREFERE1 ALTER COLUMN LCREDGLOBAL POSITION 148;

ALTER TABLE SGPREFERE1 ALTER COLUMN VDMANUTCOMOBRIG POSITION 149;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSPED POSITION 150;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCLASSPED POSITION 151;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGECLI POSITION 152;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGEFOR POSITION 153;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGETRANSP POSITION 154;

ALTER TABLE SGPREFERE1 ALTER COLUMN SOMAVOLUMES POSITION 155;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCACEP POSITION 156;

ALTER TABLE SGPREFERE1 ALTER COLUMN URLWSCEP POSITION 157;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSCP POSITION 158;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS01CP POSITION 159;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS02CP POSITION 160;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS03CP POSITION 161;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS04CP POSITION 162;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIEPF POSITION 163;

ALTER TABLE SGPREFERE1 ALTER COLUMN CREDICMSSIMPLES POSITION 164;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMS POSITION 165;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMS POSITION 166;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMENSICMSSIMPLES POSITION 167;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERACOMISVENDAORC POSITION 168;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERACODUNIF POSITION 169;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV9 POSITION 170;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT9 POSITION 171;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT9 POSITION 172;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPJP POSITION 173;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALJP POSITION 174;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANJP POSITION 175;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPJR POSITION 176;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALJR POSITION 177;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANJR POSITION 178;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPDR POSITION 179;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALDR POSITION 180;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANDR POSITION 181;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPDC POSITION 182;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALDC POSITION 183;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANDC POSITION 184;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERAPAGEMIS POSITION 185;

ALTER TABLE SGPREFERE1 ALTER COLUMN LANCAFINCONTR POSITION 186;

ALTER TABLE SGPREFERE1 ALTER COLUMN LANCARMACONTR POSITION 187;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDECPRE POSITION 188;

ALTER TABLE SGPREFERE1 ALTER COLUMN VISUALIZALUCR POSITION 189;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSNFE POSITION 190;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIRNFE POSITION 191;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIRNFELIN POSITION 192;

ALTER TABLE SGPREFERE1 ALTER COLUMN FORMATODANFE POSITION 193;

ALTER TABLE SGPREFERE1 ALTER COLUMN AMBIENTENFE POSITION 194;

ALTER TABLE SGPREFERE1 ALTER COLUMN PROCEMINFE POSITION 195;

ALTER TABLE SGPREFERE1 ALTER COLUMN VERPROCNFE POSITION 196;

ALTER TABLE SGPREFERE1 ALTER COLUMN KEYLICNFE POSITION 197;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTVENCTONFE POSITION 198;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFADPRODNFE POSITION 199;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPNF POSITION 200;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALNF POSITION 201;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMAILNF POSITION 202;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFCPDEVOLUCAO POSITION 203;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFVDREMESSA POSITION 204;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERARECEMIS POSITION 205;

ALTER TABLE SGPREFERE1 ALTER COLUMN RETENSAOIMP POSITION 206;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCUSTOLUC POSITION 207;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABIMPORTCP POSITION 208;

ALTER TABLE SGPREFERE1 ALTER COLUMN HABVLRTOTITORC POSITION 209;

ALTER TABLE SGPREFERE1 ALTER COLUMN USABUSCAGENPRODCP POSITION 210;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICOBSORCPED POSITION 211;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPRECOCOT POSITION 212;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQPRECOAPROV POSITION 213;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTINS POSITION 214;

ALTER TABLE SGPREFERE1 ALTER COLUMN HINS POSITION 215;

ALTER TABLE SGPREFERE1 ALTER COLUMN IDUSUINS POSITION 216;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTALT POSITION 217;

ALTER TABLE SGPREFERE1 ALTER COLUMN HALT POSITION 218;

ALTER TABLE SGPREFERE1 ALTER COLUMN IDUSUALT POSITION 219;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCLI POSITION 3;

ALTER TABLE VDCLIENTE ALTER COLUMN RAZCLI POSITION 4;

ALTER TABLE VDCLIENTE ALTER COLUMN NOMECLI POSITION 5;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPCC POSITION 6;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALCC POSITION 7;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCLASCLI POSITION 8;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPVD POSITION 9;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALVD POSITION 10;

ALTER TABLE VDCLIENTE ALTER COLUMN CODVEND POSITION 11;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTC POSITION 12;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTC POSITION 13;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTIPOCOB POSITION 14;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPPG POSITION 15;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALPG POSITION 16;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPLANOPAG POSITION 17;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTN POSITION 18;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTN POSITION 19;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTRAN POSITION 20;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPBO POSITION 21;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALBO POSITION 22;

ALTER TABLE VDCLIENTE ALTER COLUMN CODBANCO POSITION 23;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPSR POSITION 24;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALSR POSITION 25;

ALTER TABLE VDCLIENTE ALTER COLUMN CODSETOR POSITION 26;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTI POSITION 27;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTI POSITION 28;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTIPOCLI POSITION 29;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTPCRED POSITION 30;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTR POSITION 31;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTR POSITION 32;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFISCCLI POSITION 33;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPFC POSITION 34;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALFC POSITION 35;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPEC POSITION 36;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALEC POSITION 37;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTBEC POSITION 38;

ALTER TABLE VDCLIENTE ALTER COLUMN CODITTBEC POSITION 39;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPHP POSITION 40;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALHP POSITION 41;

ALTER TABLE VDCLIENTE ALTER COLUMN CODHIST POSITION 42;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPCB POSITION 43;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALCB POSITION 44;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCARTCOB POSITION 45;

ALTER TABLE VDCLIENTE ALTER COLUMN DATACLI POSITION 46;

ALTER TABLE VDCLIENTE ALTER COLUMN PESSOACLI POSITION 47;

ALTER TABLE VDCLIENTE ALTER COLUMN ATIVOCLI POSITION 48;

ALTER TABLE VDCLIENTE ALTER COLUMN CNPJCLI POSITION 49;

ALTER TABLE VDCLIENTE ALTER COLUMN INSCCLI POSITION 50;

ALTER TABLE VDCLIENTE ALTER COLUMN CPFCLI POSITION 51;

ALTER TABLE VDCLIENTE ALTER COLUMN RGCLI POSITION 52;

ALTER TABLE VDCLIENTE ALTER COLUMN SSPCLI POSITION 53;

ALTER TABLE VDCLIENTE ALTER COLUMN ENDCLI POSITION 54;

ALTER TABLE VDCLIENTE ALTER COLUMN NUMCLI POSITION 55;

ALTER TABLE VDCLIENTE ALTER COLUMN COMPLCLI POSITION 56;

ALTER TABLE VDCLIENTE ALTER COLUMN BAIRCLI POSITION 57;

ALTER TABLE VDCLIENTE ALTER COLUMN CIDCLI POSITION 58;

ALTER TABLE VDCLIENTE ALTER COLUMN UFCLI POSITION 59;

ALTER TABLE VDCLIENTE ALTER COLUMN CEPCLI POSITION 60;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDCLI POSITION 61;

ALTER TABLE VDCLIENTE ALTER COLUMN FONECLI POSITION 62;

ALTER TABLE VDCLIENTE ALTER COLUMN RAMALCLI POSITION 63;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFAXCLI POSITION 64;

ALTER TABLE VDCLIENTE ALTER COLUMN FAXCLI POSITION 65;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILCLI POSITION 66;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILCOB POSITION 67;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILENT POSITION 68;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILNFECLI POSITION 69;

ALTER TABLE VDCLIENTE ALTER COLUMN CONTCLI POSITION 70;

ALTER TABLE VDCLIENTE ALTER COLUMN ENDCOB POSITION 71;

ALTER TABLE VDCLIENTE ALTER COLUMN NUMCOB POSITION 72;

ALTER TABLE VDCLIENTE ALTER COLUMN COMPLCOB POSITION 73;

ALTER TABLE VDCLIENTE ALTER COLUMN BAIRCOB POSITION 74;

ALTER TABLE VDCLIENTE ALTER COLUMN CIDCOB POSITION 75;

ALTER TABLE VDCLIENTE ALTER COLUMN UFCOB POSITION 76;

ALTER TABLE VDCLIENTE ALTER COLUMN CEPCOB POSITION 77;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFONECOB POSITION 78;

ALTER TABLE VDCLIENTE ALTER COLUMN FONECOB POSITION 79;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFAXCOB POSITION 80;

ALTER TABLE VDCLIENTE ALTER COLUMN FAXCOB POSITION 81;

ALTER TABLE VDCLIENTE ALTER COLUMN ENDENT POSITION 82;

ALTER TABLE VDCLIENTE ALTER COLUMN NUMENT POSITION 83;

ALTER TABLE VDCLIENTE ALTER COLUMN COMPLENT POSITION 84;

ALTER TABLE VDCLIENTE ALTER COLUMN BAIRENT POSITION 85;

ALTER TABLE VDCLIENTE ALTER COLUMN CIDENT POSITION 86;

ALTER TABLE VDCLIENTE ALTER COLUMN UFENT POSITION 87;

ALTER TABLE VDCLIENTE ALTER COLUMN CEPENT POSITION 88;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFONEENT POSITION 89;

ALTER TABLE VDCLIENTE ALTER COLUMN FONEENT POSITION 90;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFAXENT POSITION 91;

ALTER TABLE VDCLIENTE ALTER COLUMN FAXENT POSITION 92;

ALTER TABLE VDCLIENTE ALTER COLUMN OBSCLI POSITION 93;

ALTER TABLE VDCLIENTE ALTER COLUMN AGENCIACLI POSITION 94;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPPQ POSITION 95;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALPQ POSITION 96;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPESQ POSITION 97;

ALTER TABLE VDCLIENTE ALTER COLUMN INCRACLI POSITION 98;

ALTER TABLE VDCLIENTE ALTER COLUMN DTINITR POSITION 99;

ALTER TABLE VDCLIENTE ALTER COLUMN DTVENCTOTR POSITION 100;

ALTER TABLE VDCLIENTE ALTER COLUMN NIRFCLI POSITION 101;

ALTER TABLE VDCLIENTE ALTER COLUMN SIMPLESCLI POSITION 102;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDCELCLI POSITION 103;

ALTER TABLE VDCLIENTE ALTER COLUMN CELCLI POSITION 104;

ALTER TABLE VDCLIENTE ALTER COLUMN NATCLI POSITION 105;

ALTER TABLE VDCLIENTE ALTER COLUMN UFNATCLI POSITION 106;

ALTER TABLE VDCLIENTE ALTER COLUMN TEMPORESCLI POSITION 107;

ALTER TABLE VDCLIENTE ALTER COLUMN APELIDOCLI POSITION 108;

ALTER TABLE VDCLIENTE ALTER COLUMN SITECLI POSITION 109;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCONTDEB POSITION 110;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCONTCRED POSITION 111;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCLICONTAB POSITION 112;

ALTER TABLE VDCLIENTE ALTER COLUMN FOTOCLI POSITION 113;

ALTER TABLE VDCLIENTE ALTER COLUMN IMGASSCLI POSITION 114;

ALTER TABLE VDCLIENTE ALTER COLUMN CODMUNIC POSITION 115;

ALTER TABLE VDCLIENTE ALTER COLUMN SIGLAUF POSITION 116;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPAIS POSITION 117;

ALTER TABLE VDCLIENTE ALTER COLUMN CODMUNICENT POSITION 118;

ALTER TABLE VDCLIENTE ALTER COLUMN SIGLAUFENT POSITION 119;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPAISENT POSITION 120;

ALTER TABLE VDCLIENTE ALTER COLUMN CODMUNICCOB POSITION 121;

ALTER TABLE VDCLIENTE ALTER COLUMN SIGLAUFCOB POSITION 122;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPAISCOB POSITION 123;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPUC POSITION 124;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALUC POSITION 125;

ALTER TABLE VDCLIENTE ALTER COLUMN CODUNIFCOD POSITION 126;

ALTER TABLE VDCLIENTE ALTER COLUMN SUFRAMACLI POSITION 127;

ALTER TABLE VDCLIENTE ALTER COLUMN PRODRURALCLI POSITION 128;

ALTER TABLE VDCLIENTE ALTER COLUMN CTOCLI POSITION 129;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCNAE POSITION 130;

ALTER TABLE VDCLIENTE ALTER COLUMN INSCMUNCLI POSITION 131;

ALTER TABLE VDCLIENTE ALTER COLUMN DTINS POSITION 132;

ALTER TABLE VDCLIENTE ALTER COLUMN HINS POSITION 133;

ALTER TABLE VDCLIENTE ALTER COLUMN IDUSUINS POSITION 134;

ALTER TABLE VDCLIENTE ALTER COLUMN DTALT POSITION 135;

ALTER TABLE VDCLIENTE ALTER COLUMN HALT POSITION 136;

ALTER TABLE VDCLIENTE ALTER COLUMN IDUSUALT POSITION 137;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODCONTR POSITION 3;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODITCONTR POSITION 4;

ALTER TABLE VDITCONTRATO ALTER COLUMN DESCITCONTR POSITION 5;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODEMPPD POSITION 6;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODFILIALPD POSITION 7;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODPROD POSITION 8;

ALTER TABLE VDITCONTRATO ALTER COLUMN QTDITCONTR POSITION 9;

ALTER TABLE VDITCONTRATO ALTER COLUMN VLRITCONTR POSITION 10;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODEMPPE POSITION 11;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODFILIALPE POSITION 12;

ALTER TABLE VDITCONTRATO ALTER COLUMN CODPRODPE POSITION 13;

ALTER TABLE VDITCONTRATO ALTER COLUMN VLRITCONTREXCED POSITION 14;

ALTER TABLE VDITCONTRATO ALTER COLUMN KEYLIC POSITION 15;

ALTER TABLE VDITCONTRATO ALTER COLUMN DTINS POSITION 16;

ALTER TABLE VDITCONTRATO ALTER COLUMN HINS POSITION 17;

ALTER TABLE VDITCONTRATO ALTER COLUMN IDUSUINS POSITION 18;

ALTER TABLE VDITCONTRATO ALTER COLUMN DTALT POSITION 19;

ALTER TABLE VDITCONTRATO ALTER COLUMN HALT POSITION 20;

ALTER TABLE VDITCONTRATO ALTER COLUMN IDUSUALT POSITION 21;

UPDATE SGPREFERE1 SET CASASDECPRE=CASASDECFIN;

COMMIT;

