UPDATE SGPREFERE1 SET ESTLOTNEG='S', ESTNEG='S';

UPDATE EQPRODUTO P SET P.SLDPROD=
((SELECT SUM(QTDINVP) FROM EQINVPROD IT WHERE IT.CODEMPPD=P.CODEMP AND
IT.CODFILIALPD=P.CODFILIAL AND IT.CODPROD=P.CODPROD  ) +
(SELECT SUM(QTDITCOMPRA) FROM CPITCOMPRA IC, CPCOMPRA C, EQTIPOMOV TM
 WHERE IC.CODEMPPD=P.CODEMP AND IC.CODFILIALPD=P.CODFILIAL AND IC.CODPROD=P.CODPROD AND
 C.CODCOMPRA=IC.CODCOMPRA AND C.CODEMP=IC.CODEMP AND C.CODFILIAL=IC.CODFILIAL AND
 TM.CODTIPOMOV=C.CODTIPOMOV AND TM.CODEMP=C.CODEMPTM AND TM.CODFILIAL=C.CODFILIALTM AND TM.ESTOQTIPOMOV='S'
) -
(SELECT SUM(QTDITVENDA) FROM VDITVENDA IV, VDVENDA V, EQTIPOMOV TM
 WHERE IV.CODEMPPD=P.CODEMP AND IV.CODFILIALPD=P.CODFILIAL AND IV.CODPROD=P.CODPROD AND
 V.CODVENDA=IV.CODVENDA AND V.TIPOVENDA=IV.TIPOVENDA AND V.CODEMP=IV.CODEMP AND
V.CODFILIAL=IV.CODFILIAL AND (NOT SUBSTR(V.STATUSVENDA,1,1)='C') AND
TM.CODTIPOMOV=V.CODTIPOMOV AND TM.CODEMP=V.CODEMPTM AND
TM.CODFILIAL=V.CODFILIALTM AND TM.ESTOQTIPOMOV='S') )
 WHERE P.CODEMP=6 AND P.CODFILIAL=1
AND ( ( NOT P.SLDLIQPROD=( SELECT FIRST 1 M.SLDMOVPROD FROM EQMOVPROD M
 WHERE M.CODEMPPD=P.CODEMP AND M.CODFILIALPD=P.CODFILIAL AND
 M.CODPROD=P.CODPROD ORDER BY M.DTMOVPROD DESC, M.CODMOVPROD DESC ) ) OR
 ( NOT P.SLDLIQPROD=(
( COALESCE((SELECT SUM(QTDINVP) FROM EQINVPROD IT WHERE IT.CODEMPPD=P.CODEMP AND
              IT.CODFILIALPD=P.CODFILIAL AND IT.CODPROD=P.CODPROD),0 )) +
( COALESCE((SELECT SUM(QTDITCOMPRA) FROM CPITCOMPRA IC, CPCOMPRA C, EQTIPOMOV TM
 WHERE IC.CODEMPPD=P.CODEMP AND IC.CODFILIALPD=P.CODFILIAL AND IC.CODPROD=P.CODPROD AND
 C.CODCOMPRA=IC.CODCOMPRA AND C.CODEMP=IC.CODEMP AND C.CODFILIAL=IC.CODFILIAL AND
 TM.CODTIPOMOV=C.CODTIPOMOV AND TM.CODEMP=C.CODEMPTM AND TM.CODFILIAL=C.CODFILIALTM AND TM.ESTOQTIPOMOV='S'),0 )) -
( COALESCE((SELECT SUM(QTDITVENDA) FROM VDITVENDA IV, VDVENDA V, EQTIPOMOV TM
 WHERE IV.CODEMPPD=P.CODEMP AND IV.CODFILIALPD=P.CODFILIAL AND IV.CODPROD=P.CODPROD AND
 V.CODVENDA=IV.CODVENDA AND V.TIPOVENDA=IV.TIPOVENDA AND V.CODEMP=IV.CODEMP AND
V.CODFILIAL=IV.CODFILIAL AND (NOT SUBSTR(V.STATUSVENDA,1,1)='C') AND
TM.CODTIPOMOV=V.CODTIPOMOV AND TM.CODEMP=V.CODEMPTM AND
TM.CODFILIAL=V.CODFILIALTM AND TM.ESTOQTIPOMOV='S'),0))
)) ) ;

UPDATE EQLOTE P SET P.SLDLOTE=
(COALESCE((SELECT SUM(QTDINVP) FROM EQINVPROD IT WHERE IT.CODEMPPD=P.CODEMP AND
IT.CODFILIALPD=P.CODFILIAL AND IT.CODPROD=P.CODPROD AND
 IT.CODEMPLE=P.CODEMP AND IT.CODFILIALLE=P.CODFILIAL AND IT.CODLOTE=P.CODLOTE  ),0) +
COALESCE((SELECT SUM(QTDITCOMPRA) FROM CPITCOMPRA IC, CPCOMPRA C, EQTIPOMOV TM
 WHERE IC.CODEMPPD=P.CODEMP AND IC.CODFILIALPD=P.CODFILIAL AND IC.CODPROD=P.CODPROD AND
 IC.CODEMPLE=P.CODEMP AND IC.CODFILIALLE=P.CODFILIAL AND IC.CODLOTE=P.CODLOTE AND
 C.CODCOMPRA=IC.CODCOMPRA AND C.CODEMP=IC.CODEMP AND C.CODFILIAL=IC.CODFILIAL AND
 TM.CODTIPOMOV=C.CODTIPOMOV AND TM.CODEMP=C.CODEMPTM AND TM.CODFILIAL=C.CODFILIALTM AND
 TM.ESTOQTIPOMOV='S'
),0) -
COALESCE((SELECT SUM(QTDITVENDA) FROM VDITVENDA IV, VDVENDA V, EQTIPOMOV TM
 WHERE IV.CODEMPPD=P.CODEMP AND IV.CODFILIALPD=P.CODFILIAL AND IV.CODPROD=P.CODPROD AND
  IV.CODEMPLE=P.CODEMP AND IV.CODFILIALLE=P.CODFILIAL AND IV.CODLOTE=P.CODLOTE AND
 V.CODVENDA=IV.CODVENDA AND V.TIPOVENDA=IV.TIPOVENDA AND V.CODEMP=IV.CODEMP AND
V.CODFILIAL=IV.CODFILIAL AND (NOT SUBSTR(V.STATUSVENDA,1,1)='C') AND
TM.CODTIPOMOV=V.CODTIPOMOV AND TM.CODEMP=V.CODEMPTM AND
TM.CODFILIAL=V.CODFILIALTM AND TM.ESTOQTIPOMOV='S'),0) )
 WHERE P.CODEMP=4 AND P.CODFILIAL=1
AND  ( NOT P.SLDLIQLOTE=(
( COALESCE((SELECT SUM(QTDINVP) FROM EQINVPROD IT WHERE IT.CODEMPPD=P.CODEMP AND
              IT.CODFILIALPD=P.CODFILIAL AND IT.CODPROD=P.CODPROD AND
               IT.CODEMPLE=P.CODEMP AND IT.CODFILIALLE=P.CODFILIAL AND IT.CODLOTE=P.CODLOTE
              ),0 )) +
( COALESCE((SELECT SUM(QTDITCOMPRA) FROM CPITCOMPRA IC, CPCOMPRA C, EQTIPOMOV TM
 WHERE IC.CODEMPPD=P.CODEMP AND IC.CODFILIALPD=P.CODFILIAL AND IC.CODPROD=P.CODPROD AND
  IC.CODEMPLE=P.CODEMP AND IC.CODFILIALLE=P.CODFILIAL AND IC.CODLOTE=P.CODLOTE AND
 C.CODCOMPRA=IC.CODCOMPRA AND C.CODEMP=IC.CODEMP AND C.CODFILIAL=IC.CODFILIAL AND
 TM.CODTIPOMOV=C.CODTIPOMOV AND TM.CODEMP=C.CODEMPTM AND TM.CODFILIAL=C.CODFILIALTM AND
 TM.ESTOQTIPOMOV='S'),0 )) -
( COALESCE((SELECT SUM(QTDITVENDA) FROM VDITVENDA IV, VDVENDA V, EQTIPOMOV TM
 WHERE IV.CODEMPPD=P.CODEMP AND IV.CODFILIALPD=P.CODFILIAL AND IV.CODPROD=P.CODPROD AND
  IV.CODEMPLE=P.CODEMP AND IV.CODFILIALLE=P.CODFILIAL AND IV.CODLOTE=P.CODLOTE AND
 V.CODVENDA=IV.CODVENDA AND V.TIPOVENDA=IV.TIPOVENDA AND V.CODEMP=IV.CODEMP AND
V.CODFILIAL=IV.CODFILIAL AND (NOT SUBSTR(V.STATUSVENDA,1,1)='C') AND
TM.CODTIPOMOV=V.CODTIPOMOV AND TM.CODEMP=V.CODEMPTM AND
TM.CODFILIAL=V.CODFILIALTM AND TM.ESTOQTIPOMOV='S'),0))
)) ;

UPDATE SGPREFERE1 SET ESTLOTNEG='N', ESTNEG='N';

COMMIT WORK;

