SET TERM ^ ;

CREATE PROCEDURE EQRELDEMANDASP (
    ICODEMP INTEGER,
    SCODFILIAL SMALLINT,
    SCODFILIALPD SMALLINT,
    DDTINI DATE,
    DDTFIM DATE)
RETURNS (
    CODMARCA CHAR(6),
    CODGRUP CHAR(14),
    CODPROD INTEGER,
    REFPROD CHAR(13),
    DESCPROD CHAR(50),
    DESCGRUP CHAR(50),
    SLDINI NUMERIC(15,3),
    VLROUTSAI NUMERIC(15,3),
    VLROUTENT NUMERIC(15,3),
    VLRDEVSAI NUMERIC(15,3),
    VLRCOMPRAS NUMERIC(15,3),
    VLRVENDAS NUMERIC(15,3),
    SLDFIM NUMERIC(15,3))
AS
begin
  /* Stored procedure de relatório de demanda */
  FOR SELECT P.CODMARCA, P.CODGRUP,P.CODPROD,
     P.REFPROD, P.DESCPROD,G.DESCGRUP,
     (SELECT FIRST 1 SLDMOVPROD FROM EQMOVPROD MP
      WHERE MP.CODEMP=:ICODEMP AND MP.CODFILIAL=:SCODFILIAL AND
         MP.CODEMPPD=P.CODEMP AND MP.CODFILIALPD=P.CODFILIAL AND
         MP.CODPROD=P.CODPROD AND MP.DTMOVPROD<:DDTINI
         ORDER BY MP.DTMOVPROD DESC, MP.CODMOVPROD DESC ) SLDINI,
     (SELECT SUM(MP.QTDMOVPROD)
        FROM EQMOVPROD MP, EQTIPOMOV TM
         WHERE TM.CODEMP=MP.CODEMPTM AND TM.CODFILIAL=MP.CODFILIALTM AND
           TM.CODTIPOMOV=MP.CODTIPOMOV AND MP.CODPROD=P.CODPROD AND
           MP.CODEMPPD=P.CODEMP AND MP.CODFILIALPD=P.CODFILIAL AND
           MP.DTMOVPROD BETWEEN :DDTINI AND :DDTFIM AND MP.ESTOQMOVPROD='S' AND
           TM.TIPOMOV NOT IN ('VD','PV','DV') AND TM.ESTIPOMOV = 'S') VLROUTSAI,
     (SELECT SUM(MP.QTDMOVPROD)
         FROM EQMOVPROD MP , EQTIPOMOV TM
         WHERE TM.CODEMP=MP.CODEMPTM AND TM.CODFILIAL=MP.CODFILIALTM AND
           TM.CODTIPOMOV=MP.CODTIPOMOV AND MP.CODPROD=P.CODPROD AND
           MP.CODEMPPD=P.CODEMP AND MP.CODFILIALPD=P.CODFILIAL AND
           MP.DTMOVPROD BETWEEN :DDTINI AND :DDTFIM AND MP.ESTOQMOVPROD='S' AND
           TM.TIPOMOV NOT IN ('CP','PC','DV') AND TM.ESTIPOMOV IN ('E','I')) VLROUTENT,
     (SELECT SUM(MP.QTDMOVPROD)
         FROM EQMOVPROD MP, EQTIPOMOV TM
         WHERE TM.CODEMP=MP.CODEMPTM AND TM.CODFILIAL=MP.CODFILIALTM AND
           TM.CODTIPOMOV=MP.CODTIPOMOV AND MP.CODPROD=P.CODPROD AND
           MP.CODEMPPD=P.CODEMP AND MP.CODFILIALPD=P.CODFILIAL AND
           MP.DTMOVPROD BETWEEN :DDTINI AND :DDTFIM AND MP.ESTOQMOVPROD='S' AND
           TM.TIPOMOV ='DV' AND TM.ESTIPOMOV = 'S') VLRDEVSAI,
     (SELECT SUM(MP.QTDMOVPROD)
         FROM EQMOVPROD MP, EQTIPOMOV TM
         WHERE TM.CODEMP=MP.CODEMPTM AND TM.CODFILIAL=MP.CODFILIALTM AND
           TM.CODTIPOMOV=MP.CODTIPOMOV AND MP.CODPROD=P.CODPROD AND
           MP.CODEMPPD=P.CODEMP AND MP.CODFILIALPD=P.CODFILIAL AND
           MP.DTMOVPROD BETWEEN :DDTINI AND :DDTFIM AND MP.ESTOQMOVPROD='S' AND
           TM.TIPOMOV IN ('CP','PC') AND TM.ESTIPOMOV = 'E') VLRCOMPRAS,
     (SELECT SUM(MP.QTDMOVPROD)
         FROM EQMOVPROD MP, EQTIPOMOV TM
         WHERE TM.CODEMP=MP.CODEMPTM AND TM.CODFILIAL=MP.CODFILIALTM AND
           TM.CODTIPOMOV=MP.CODTIPOMOV AND MP.CODPROD=P.CODPROD AND
           MP.CODEMPPD=P.CODEMP AND MP.CODFILIALPD=P.CODFILIAL AND
           MP.DTMOVPROD BETWEEN :DDTINI AND :DDTFIM AND MP.ESTOQMOVPROD='S' AND
           TM.TIPOMOV IN ('VD','PV') AND TM.ESTIPOMOV = 'S') VLRVENDAS
     FROM EQPRODUTO P, EQGRUPO G
         WHERE G.CODGRUP=P.CODGRUP AND G.CODEMP=P.CODEMPGP AND
           G.CODFILIAL=P.CODFILIALGP AND P.CODEMP=:ICODEMP AND
           P.CODFILIAL=:SCODFILIALPD AND P.ATIVOPROD='S'
     INTO :CODMARCA, :CODGRUP, :CODPROD, :REFPROD, :DESCPROD, :DESCGRUP,
        :SLDINI, :VLROUTSAI, :VLROUTENT, :VLRDEVSAI, :VLRCOMPRAS, :VLRVENDAS DO
     BEGIN
        if (SLDINI IS NULL) then
           SLDINI = 0;
        if (VLROUTSAI IS NULL) then
           VLROUTSAI = 0;
        if (VLROUTENT IS NULL) then
           VLROUTENT = 0;
        if (VLRDEVSAI IS NULL) then
           VLRDEVSAI = 0;
        if (VLRCOMPRAS IS NULL) then
           VLRCOMPRAS = 0;
        if (VLRVENDAS IS NULL) then
           VLRVENDAS = 0;
        SLDFIM = SLDINI - VLROUTSAI + VLROUTENT + VLRDEVSAI + VLRCOMPRAS - VLRVENDAS;
        suspend;
     END
end
^

SET TERM ; ^

COMMIT WORK;

GRANT SELECT ON EQMOVPROD TO PROCEDURE EQRELDEMANDASP;

COMMIT WORK;

GRANT SELECT ON EQTIPOMOV TO PROCEDURE EQRELDEMANDASP;

COMMIT WORK;

GRANT SELECT ON EQPRODUTO TO PROCEDURE EQRELDEMANDASP;

COMMIT WORK;

GRANT SELECT ON EQGRUPO TO PROCEDURE EQRELDEMANDASP;

COMMIT WORK;

GRANT EXECUTE ON PROCEDURE EQRELDEMANDASP TO GROUP secretar, adm;

COMMIT WORK;


