GRANT EXECUTE ON PROCEDURE VDRETLISTAPRODSP TO ROLE "ADM";
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SGPAIS TO ROLE "ADM";
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SGUF TO ROLE "ADM";
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SGMUNICIPIO TO ROLE "ADM";