-- implantação modulo de controle de representaçoes --

-- PARAREMETROS INICIAIS --

INSERT INTO SGESTACAO (CODEMP, CODFILIAL, CODEST, DESCEST, MODODEMOEST) VALUES (#CODEMP#, 1, 1, 'ADIMINISTRAÇÃO', 'N');
INSERT INTO RPMOEDA (CODEMP, CODFILIAL, CODMOEDA, TIPOMOEDA, SINGMOEDA, PLURMOEDA, DECSMOEDA, DECPMOEDA) VALUES (#CODEMP#, 1, 'R$', 'C', 'REAL', 'REAIS', 'CENTAVO', 'CENTAVOS');
INSERT INTO SGPREFERE1 (CODEMP, CODFILIAL, IPICOMIS, IPIPED, CODBARPROD, ENDCLIPED, ORDEMPED, SERVIDORSMTP, USUARIOSMTP, CASASDEC, CASASDECFIN, CODEMPMO, CODFILIALMO, CODMOEDA, LAYOUTPED) VALUES (#CODEMP#, 1, 'S', 'N', 'N', 'N', 'S', NULL, NULL, 5, 2, #CODEMP#, 1, 'R$', NULL);

-- GRANT -- 

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPCLIENTE TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPCONTATO TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPCOTMOEDA TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPFORNECEDOR TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPGRUPO TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPMOEDA TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPPARCPLANOPAG TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPPLANOPAG TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPPRODUTO TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPTRANSP TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPUNIDADE TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RPVENDEDOR TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGACESSOEU TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGACESSOMU TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGAGENTE TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGCONEXAO TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGEMPRESA TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGGRPUSU TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGMENU TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGMODULO TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGOBJETO TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGSISTEMA TO  ADM;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SGUSUARIO TO  ADM;
GRANT EXECUTE ON PROCEDURE SGAGENTEISP TO  ADM;
GRANT EXECUTE ON PROCEDURE SGAGENTEISP TO PROCEDURE SGINICONSP;
GRANT EXECUTE ON PROCEDURE SGAGENTEUSP TO  ADM;
GRANT EXECUTE ON PROCEDURE SGATUALIZABDSP TO  ADM;
GRANT EXECUTE ON PROCEDURE SGDADOSINISP TO  ADM;
GRANT EXECUTE ON PROCEDURE SGDADOSINISP TO PROCEDURE SGAGENTEISP;
GRANT EXECUTE ON PROCEDURE SGGRANTADMSP TO  ADM;
GRANT EXECUTE ON PROCEDURE SGGRANTADMSP TO PROCEDURE SGAGENTEISP;
GRANT EXECUTE ON PROCEDURE SGGRANTUSERSP TO  ADM;
GRANT EXECUTE ON PROCEDURE SGGRANTUSERSP TO PROCEDURE SGAGENTEISP;
GRANT EXECUTE ON PROCEDURE SGOBJETOINSTBSP TO  ADM;
GRANT EXECUTE ON PROCEDURE SGOBJETOINSTBSP TO PROCEDURE SGAGENTEISP;
GRANT DELETE, INSERT, SELECT ON "SGACESSOMU" TO PROCEDURE "SGUPACESSOMUSP"; 
GRANT DELETE, INSERT, SELECT, UPDATE ON "SGCONEXAO" TO PROCEDURE "SGFIMCONSP"; 
GRANT DELETE, INSERT, SELECT, UPDATE ON "SGCONEXAO" TO PROCEDURE "SGINICONSP"; 
GRANT DELETE, SELECT ON "SGAGENTE" TO PROCEDURE "SGAGENTEUIDSP"; 
GRANT EXECUTE ON PROCEDURE "SGAGENTEISP" TO PROCEDURE "SGAGENTEUIDSP";  
GRANT EXECUTE ON PROCEDURE "SGAGENTEUSP" TO PROCEDURE "SGAGENTEUIDSP"; 
GRANT EXECUTE ON PROCEDURE "SGDADOSINISP" TO PROCEDURE "SGATUALIZABDSP"; 
GRANT EXECUTE ON PROCEDURE "SGGRANTADMSP" TO PROCEDURE "SGATUALIZABDSP"; 
GRANT EXECUTE ON PROCEDURE "SGGRANTUSERSP" TO PROCEDURE "SGATUALIZABDSP"; 
GRANT EXECUTE ON PROCEDURE "SGOBJETOINSTBSP" TO PROCEDURE "SGATUALIZABDSP"; 
GRANT EXECUTE ON PROCEDURE "SGRETFILIAL" TO PROCEDURE "SGAGENTEUIDSP"; 
GRANT EXECUTE ON PROCEDURE "SGRETFILIAL" TO PROCEDURE "SGRETMULTIALMOXSP";  
GRANT INSERT ON "SGFILIAL" TO PROCEDURE "SGDADOSINISP"; 
GRANT INSERT, SELECT ON "SGAGENTE" TO PROCEDURE "SGAGENTEISP"; 
GRANT INSERT, SELECT ON "SGEMPRESA" TO PROCEDURE "SGDADOSINISP"; 
GRANT INSERT, SELECT ON "SGGRPUSU" TO PROCEDURE "SGDADOSINISP"; 
GRANT INSERT, SELECT ON "SGMODULO" TO PROCEDURE "SGUPMENUSP01"; 
GRANT INSERT, SELECT ON "SGOBJETO" TO PROCEDURE "SGOBJETOINSTBSP"; 
GRANT INSERT, SELECT ON "SGSISTEMA" TO PROCEDURE "SGUPMENUSP01"; 
GRANT INSERT, SELECT ON "SGUSUARIO" TO PROCEDURE "SGDADOSINISP";  
GRANT INSERT, SELECT, UPDATE ON "SGMENU" TO PROCEDURE "SGUPMENUSP01";  
GRANT SELECT ON "SGCONEXAO" TO PROCEDURE "SGRETFILIAL"; 
GRANT SELECT ON "SGEMPRESA" TO PROCEDURE "SGATUALIZABDSP"; 
GRANT SELECT ON "SGEMPRESA" TO PROCEDURE "SGINICONSP"; 
GRANT SELECT ON "SGFILIAL" TO PROCEDURE "SGRETFILIAL"; 
GRANT SELECT ON "SGOBJETO" TO PROCEDURE "SGGRANTADMSP"; 
GRANT SELECT ON "SGOBJETO" TO PROCEDURE "SGRETFILIAL"; 
GRANT SELECT ON "SGUSUARIO" TO PROCEDURE "SGGRANTUSERSP"; 
GRANT SELECT ON "SGUSUARIO" TO PROCEDURE "SGINICONSP"; 
GRANT SELECT, UPDATE ON "SGAGENTE" TO PROCEDURE "SGAGENTEUSP"; 
 
