JC=javac -g
FLAGS=-classpath /aplic/appjava:/aplic/appjava/jars/jcommon-0.8.7.jar:/aplic/appjava/jars/jfreechart-0.9.12.jar

all: \
DLRLancaExp.class \
FVenda.class \
FCompra.class \
FProduto.class \
FGrupo.class \
DLGrupo.class \
DLRInventario.class \
FCpProd.class \
FPrecoBase.class \
FREstoqueMin.class \
FRListaPreco.class \
FRMediaItem.class \
FRVendasItem.class \
FRVendasGeral.class \
FRVendasFisico.class \
FCliente.class \
FInventario.class \
FLancaExp.class \
FLanca.class \
DLRPedido.class \
DLDataTransf.class \
DLNovoPag.class \
FRComprasFor.class \
FRGraficoCC.class \
FManutRec.class \
FPlanejamento.class \
DLEditaPag.class \
DLEditaRec.class \
DLBaixaRec.class \
FKardex.class \
FRVencLote.class \
FConsulta.class \
DLRCliente.class \
FRegraFiscal.class \
FPrefereGeral.class \
Freedom.class

FRComprasFor.class: FRComprasFor.java
	$(JC) $(FLAGS) $^

DLDataTransf.class: DLDataTransf.java
	$(JC) $(FLAGS) $^

DLRPedido.class: DLRPedido.java
	$(JC) $(FLAGS) $^

FVenda.class: FVenda.java
	$(JC) $(FLAGS) $^

FCompra.class: FCompra.java
	$(JC) $(FLAGS) $^

FProduto.class: FProduto.java
	$(JC) $(FLAGS) $^

FGrupo.class: FGrupo.java
	$(JC) $(FLAGS) $^

DLGrupo.class: DLGrupo.java
	$(JC) $(FLAGS) $^

DLRInventario.class: DLRInventario.java
	$(JC) $(FLAGS) $^

DLNovoPag.class: DLNovoPag.java
	$(JC) $(FLAGS) $^

FCpProd.class: FCpProd.java
	$(JC) $(FLAGS) $^

FRGraficoCC.class: FRGraficoCC.java
	$(JC) $(FLAGS) $^

FPrecoBase.class: FPrecoBase.java
	$(JC) $(FLAGS) $^

FREstoqueMin.class: FREstoqueMin.java
	$(JC) $(FLAGS) $^

FRListaPreco.class: FRListaPreco.java
	$(JC) $(FLAGS) $^

FRMediaItem.class: FRMediaItem.java
	$(JC) $(FLAGS) $^

FRVendasItem.class: FRVendasItem.java
	$(JC) $(FLAGS) $^

FRVendasGeral.class: FRVendasGeral.java
	$(JC) $(FLAGS) $^

FRVendasFisico.class: FRVendasFisico.java
	$(JC) $(FLAGS) $^

FInventario.class: FInventario.java
	$(JC) $(FLAGS) $^

FCliente.class: FCliente.java
	$(JC) $(FLAGS) $^

FLancaExp.class: FLancaExp.java
	$(JC) $(FLAGS) $^

FLanca.class: FLanca.java
	$(JC) $(FLAGS) $^

DLRLancaExp.class: DLRLancaExp.java
	$(JC) $(FLAGS) $^

FManutRec.class: FManutRec.java
	$(JC) $(FLAGS) $^

DLEditaPag.class: DLEditaPag.java
	$(JC) $(FLAGS) $^

DLEditaRec.class: DLEditaRec.java
	$(JC) $(FLAGS) $^

DLBaixaRec.class: DLBaixaRec.java
	$(JC) $(FLAGS) $^

Freedom.class: Freedom.java
	$(JC) $(FLAGS) $^

FKardex.class: FKardex.java
	$(JC) $(FLAGS) $^

FRVencLote.class: FRVencLote.java
	$(JC) $(FLAGS) $^

FConsulta.class: FConsulta.java
	$(JC) $(FLAGS) $^

DLRCliente.class: DLRCliente.java
	$(JC) $(FLAGS) $^

FRegraFiscal.class: FRegraFiscal.java
	$(JC) $(FLAGS) $^

FPrefereGeral.class: FPrefereGeral.java
	$(JC) $(FLAGS) $^

.PHONY: all
