package org.freedom.persist.entity;

// Generated 10/05/2014 10:27:15 by Hibernate Tools 4.0.0

/**
 * Atatendimentovw03 generated by hbm2java
 */
public class Atatendimentovw03 implements java.io.Serializable {

	private Atatendimentovw03Id id;

	public Atatendimentovw03() {
	}

	public Atatendimentovw03(Atatendimentovw03Id id) {
		this.id = id;
	}

	public Atatendimentovw03Id getId() {
		return this.id;
	}

	public void setId(Atatendimentovw03Id id) {
		this.id = id;
	}

}
