package org.freedom.persist.entity;

// Generated 14/04/2014 10:17:08 by Hibernate Tools 4.0.0

/**
 * Atatendimentovw08 generated by hbm2java
 */
public class Atatendimentovw08 implements java.io.Serializable {

	private Atatendimentovw08Id id;

	public Atatendimentovw08() {
	}

	public Atatendimentovw08(Atatendimentovw08Id id) {
		this.id = id;
	}

	public Atatendimentovw08Id getId() {
		return this.id;
	}

	public void setId(Atatendimentovw08Id id) {
		this.id = id;
	}

}
