package org.freedom.persist.entity;

// Generated 18/02/2014 15:53:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cpdevolucao generated by hbm2java
 */
public class Cpdevolucao implements java.io.Serializable {

	private CpdevolucaoId id;
	private Vditvenda vditvenda;
	private Cpitcompra cpitcompra;
	private BigDecimal qtddev;
	private String idusualt;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;

	public Cpdevolucao() {
	}

	public Cpdevolucao(CpdevolucaoId id, Vditvenda vditvenda,
			Cpitcompra cpitcompra, BigDecimal qtddev, Date dtins, Date hins,
			String idusuins) {
		this.id = id;
		this.vditvenda = vditvenda;
		this.cpitcompra = cpitcompra;
		this.qtddev = qtddev;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Cpdevolucao(CpdevolucaoId id, Vditvenda vditvenda,
			Cpitcompra cpitcompra, BigDecimal qtddev, String idusualt,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt) {
		this.id = id;
		this.vditvenda = vditvenda;
		this.cpitcompra = cpitcompra;
		this.qtddev = qtddev;
		this.idusualt = idusualt;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
	}

	public CpdevolucaoId getId() {
		return this.id;
	}

	public void setId(CpdevolucaoId id) {
		this.id = id;
	}

	public Vditvenda getVditvenda() {
		return this.vditvenda;
	}

	public void setVditvenda(Vditvenda vditvenda) {
		this.vditvenda = vditvenda;
	}

	public Cpitcompra getCpitcompra() {
		return this.cpitcompra;
	}

	public void setCpitcompra(Cpitcompra cpitcompra) {
		this.cpitcompra = cpitcompra;
	}

	public BigDecimal getQtddev() {
		return this.qtddev;
	}

	public void setQtddev(BigDecimal qtddev) {
		this.qtddev = qtddev;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

}
