package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cpitsolitsol generated by hbm2java
 */
@Entity
@Table(name = "CPITSOLITSOL")
public class Cpitsolitsol implements java.io.Serializable {

	private CpitsolitsolId id;
	private Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoln;
	private Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoli;
	private Date dtitsolis;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Cpitsolitsol() {
	}

	public Cpitsolitsol(CpitsolitsolId id,
			Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoln,
			Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoli, Date dtitsolis,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.cpitsolicitacaoByCpitsolfkcpitsoln = cpitsolicitacaoByCpitsolfkcpitsoln;
		this.cpitsolicitacaoByCpitsolfkcpitsoli = cpitsolicitacaoByCpitsolfkcpitsoli;
		this.dtitsolis = dtitsolis;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Cpitsolitsol(CpitsolitsolId id,
			Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoln,
			Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoli, Date dtitsolis,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt) {
		this.id = id;
		this.cpitsolicitacaoByCpitsolfkcpitsoln = cpitsolicitacaoByCpitsolfkcpitsoln;
		this.cpitsolicitacaoByCpitsolfkcpitsoli = cpitsolicitacaoByCpitsolfkcpitsoli;
		this.dtitsolis = dtitsolis;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codsol", column = @Column(name = "CODSOL", nullable = false)),
			@AttributeOverride(name = "coditsol", column = @Column(name = "CODITSOL", nullable = false)),
			@AttributeOverride(name = "codsoln", column = @Column(name = "CODSOLN", nullable = false)),
			@AttributeOverride(name = "coditsoln", column = @Column(name = "CODITSOLN", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)),
			@AttributeOverride(name = "codfilialsn", column = @Column(name = "CODFILIALSN", nullable = false)),
			@AttributeOverride(name = "codempsn", column = @Column(name = "CODEMPSN", nullable = false)) })
	public CpitsolitsolId getId() {
		return this.id;
	}

	public void setId(CpitsolitsolId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODSOLN", referencedColumnName = "CODSOL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODITSOLN", referencedColumnName = "CODITSOL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIALSN", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMPSN", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Cpitsolicitacao getCpitsolicitacaoByCpitsolfkcpitsoln() {
		return this.cpitsolicitacaoByCpitsolfkcpitsoln;
	}

	public void setCpitsolicitacaoByCpitsolfkcpitsoln(
			Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoln) {
		this.cpitsolicitacaoByCpitsolfkcpitsoln = cpitsolicitacaoByCpitsolfkcpitsoln;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODSOL", referencedColumnName = "CODSOL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODITSOL", referencedColumnName = "CODITSOL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Cpitsolicitacao getCpitsolicitacaoByCpitsolfkcpitsoli() {
		return this.cpitsolicitacaoByCpitsolfkcpitsoli;
	}

	public void setCpitsolicitacaoByCpitsolfkcpitsoli(
			Cpitsolicitacao cpitsolicitacaoByCpitsolfkcpitsoli) {
		this.cpitsolicitacaoByCpitsolfkcpitsoli = cpitsolicitacaoByCpitsolfkcpitsoli;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTITSOLIS", nullable = false, length = 10)
	public Date getDtitsolis() {
		return this.dtitsolis;
	}

	public void setDtitsolis(Date dtitsolis) {
		this.dtitsolis = dtitsolis;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 128)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 128)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
