package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cpitordcomprape generated by hbm2java
 */
@Entity
@Table(name = "CPITORDCOMPRAPE")
public class Cpitordcomprape implements java.io.Serializable {

	private CpitordcomprapeId id;
	private Cpitordcompra cpitordcompra;
	private Date dtitpe;
	private BigDecimal qtditpe;
	private BigDecimal qtditentpe;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Cpitordcomprape() {
	}

	public Cpitordcomprape(CpitordcomprapeId id, Cpitordcompra cpitordcompra,
			Date dtitpe, BigDecimal qtditpe, BigDecimal qtditentpe, Date dtins,
			Date hins, String idusuins) {
		this.id = id;
		this.cpitordcompra = cpitordcompra;
		this.dtitpe = dtitpe;
		this.qtditpe = qtditpe;
		this.qtditentpe = qtditentpe;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Cpitordcomprape(CpitordcomprapeId id, Cpitordcompra cpitordcompra,
			Date dtitpe, BigDecimal qtditpe, BigDecimal qtditentpe, Date dtins,
			Date hins, String idusuins, Date dtalt, Date halt, String idusualt) {
		this.id = id;
		this.cpitordcompra = cpitordcompra;
		this.dtitpe = dtitpe;
		this.qtditpe = qtditpe;
		this.qtditentpe = qtditentpe;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codordcp", column = @Column(name = "CODORDCP", nullable = false)),
			@AttributeOverride(name = "coditordcp", column = @Column(name = "CODITORDCP", nullable = false)),
			@AttributeOverride(name = "seqitordcppe", column = @Column(name = "SEQITORDCPPE", nullable = false)) })
	public CpitordcomprapeId getId() {
		return this.id;
	}

	public void setId(CpitordcomprapeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODORDCP", referencedColumnName = "CODORDCP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODITORDCP", referencedColumnName = "CODITORDCP", nullable = false, insertable = false, updatable = false) })
	public Cpitordcompra getCpitordcompra() {
		return this.cpitordcompra;
	}

	public void setCpitordcompra(Cpitordcompra cpitordcompra) {
		this.cpitordcompra = cpitordcompra;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTITPE", nullable = false, length = 10)
	public Date getDtitpe() {
		return this.dtitpe;
	}

	public void setDtitpe(Date dtitpe) {
		this.dtitpe = dtitpe;
	}

	@Column(name = "QTDITPE", nullable = false, precision = 15, scale = 5)
	public BigDecimal getQtditpe() {
		return this.qtditpe;
	}

	public void setQtditpe(BigDecimal qtditpe) {
		this.qtditpe = qtditpe;
	}

	@Column(name = "QTDITENTPE", nullable = false, precision = 15, scale = 5)
	public BigDecimal getQtditentpe() {
		return this.qtditentpe;
	}

	public void setQtditentpe(BigDecimal qtditentpe) {
		this.qtditentpe = qtditentpe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
