package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
//import java.util.HashSet;
//import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
//import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eqinvprod generated by hbm2java
 */
@Entity
@Table(name = "EQINVPROD")
public class Eqinvprod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private EqinvprodId id;
	private Eqproduto eqproduto;
	private Sgfilial sgfilial;
	private Eqtipomov eqtipomov;
	private Eqalmox eqalmox;
	private Eqlote eqlote;
	private Date datainvp;
	private BigDecimal qtdinvp;
	private BigDecimal precoinvp;
	private String refprod;
	private BigDecimal sldatualinvp;
	private BigDecimal slddiginvp;
	private Character flag;
	private String obsinvp;
	private char emmanut;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
//	private Set eqmovseries = new HashSet(0);
//	private Set eqmovprods = new HashSet(0);

	public Eqinvprod() {
	}

	public Eqinvprod(EqinvprodId id, Eqproduto eqproduto, Sgfilial sgfilial,
			Eqtipomov eqtipomov, Eqalmox eqalmox, Eqlote eqlote, Date datainvp,
			BigDecimal qtdinvp, BigDecimal precoinvp, char emmanut, Date dtins,
			Date hins, String idusuins) {
		this.id = id;
		this.eqproduto = eqproduto;
		this.sgfilial = sgfilial;
		this.eqtipomov = eqtipomov;
		this.eqalmox = eqalmox;
		this.eqlote = eqlote;
		this.datainvp = datainvp;
		this.qtdinvp = qtdinvp;
		this.precoinvp = precoinvp;
		this.emmanut = emmanut;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Eqinvprod(EqinvprodId id, Eqproduto eqproduto, Sgfilial sgfilial,
			Eqtipomov eqtipomov, Eqalmox eqalmox, Eqlote eqlote, Date datainvp,
			BigDecimal qtdinvp, BigDecimal precoinvp, String refprod,
			BigDecimal sldatualinvp, BigDecimal slddiginvp, Character flag,
			String obsinvp, char emmanut, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt
			//,
			//Set eqmovseries, Set eqmovprods
			) {
		this.id = id;
		this.eqproduto = eqproduto;
		this.sgfilial = sgfilial;
		this.eqtipomov = eqtipomov;
		this.eqalmox = eqalmox;
		this.eqlote = eqlote;
		this.datainvp = datainvp;
		this.qtdinvp = qtdinvp;
		this.precoinvp = precoinvp;
		this.refprod = refprod;
		this.sldatualinvp = sldatualinvp;
		this.slddiginvp = slddiginvp;
		this.flag = flag;
		this.obsinvp = obsinvp;
		this.emmanut = emmanut;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		//this.eqmovseries = eqmovseries;
		//this.eqmovprods = eqmovprods;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codinvprod", column = @Column(name = "CODINVPROD", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public EqinvprodId getId() {
		return this.id;
	}

	public void setId(EqinvprodId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODPROD", referencedColumnName = "CODPROD", nullable = false),
			@JoinColumn(name = "CODFILIALPD", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPPD", referencedColumnName = "CODEMP", nullable = false) })
	public Eqproduto getEqproduto() {
		return this.eqproduto;
	}

	public void setEqproduto(Eqproduto eqproduto) {
		this.eqproduto = eqproduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Sgfilial getSgfilial() {
		return this.sgfilial;
	}

	public void setSgfilial(Sgfilial sgfilial) {
		this.sgfilial = sgfilial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODTIPOMOV", referencedColumnName = "CODTIPOMOV", nullable = false),
			@JoinColumn(name = "CODFILIALTM", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPTM", referencedColumnName = "CODEMP", nullable = false) })
	public Eqtipomov getEqtipomov() {
		return this.eqtipomov;
	}

	public void setEqtipomov(Eqtipomov eqtipomov) {
		this.eqtipomov = eqtipomov;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODALMOX", referencedColumnName = "CODALMOX", nullable = false),
			@JoinColumn(name = "CODFILIALAX", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPAX", referencedColumnName = "CODEMP", nullable = false) })
	public Eqalmox getEqalmox() {
		return this.eqalmox;
	}

	public void setEqalmox(Eqalmox eqalmox) {
		this.eqalmox = eqalmox;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODLOTE", referencedColumnName = "CODLOTE", insertable = false, updatable = false),
			@JoinColumn(name = "CODPROD", referencedColumnName = "CODPROD", insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIALLE", referencedColumnName = "CODFILIAL", insertable = false, updatable = false),
			@JoinColumn(name = "CODEMPLE", referencedColumnName = "CODEMP", insertable = false, updatable = false) })
	public Eqlote getEqlote() {
		return this.eqlote;
	}

	public void setEqlote(Eqlote eqlote) {
		this.eqlote = eqlote;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATAINVP", nullable = false, length = 10)
	public Date getDatainvp() {
		return this.datainvp;
	}

	public void setDatainvp(Date datainvp) {
		this.datainvp = datainvp;
	}

	@Column(name = "QTDINVP", nullable = false, precision = 15, scale = 5)
	public BigDecimal getQtdinvp() {
		return this.qtdinvp;
	}

	public void setQtdinvp(BigDecimal qtdinvp) {
		this.qtdinvp = qtdinvp;
	}

	@Column(name = "PRECOINVP", nullable = false, precision = 15, scale = 5)
	public BigDecimal getPrecoinvp() {
		return this.precoinvp;
	}

	public void setPrecoinvp(BigDecimal precoinvp) {
		this.precoinvp = precoinvp;
	}

	@Column(name = "REFPROD", length = 20)
	public String getRefprod() {
		return this.refprod;
	}

	public void setRefprod(String refprod) {
		this.refprod = refprod;
	}

	@Column(name = "SLDATUALINVP", precision = 15, scale = 5)
	public BigDecimal getSldatualinvp() {
		return this.sldatualinvp;
	}

	public void setSldatualinvp(BigDecimal sldatualinvp) {
		this.sldatualinvp = sldatualinvp;
	}

	@Column(name = "SLDDIGINVP", precision = 15, scale = 5)
	public BigDecimal getSlddiginvp() {
		return this.slddiginvp;
	}

	public void setSlddiginvp(BigDecimal slddiginvp) {
		this.slddiginvp = slddiginvp;
	}

	@Column(name = "FLAG", length = 1)
	public Character getFlag() {
		return this.flag;
	}

	public void setFlag(Character flag) {
		this.flag = flag;
	}

	@Column(name = "OBSINVP", length = 500)
	public String getObsinvp() {
		return this.obsinvp;
	}

	public void setObsinvp(String obsinvp) {
		this.obsinvp = obsinvp;
	}

	@Column(name = "EMMANUT", nullable = false, length = 1)
	public char getEmmanut() {
		return this.emmanut;
	}

	public void setEmmanut(char emmanut) {
		this.emmanut = emmanut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqinvprod")
	public Set getEqmovseries() {
		return this.eqmovseries;
	}

	public void setEqmovseries(Set eqmovseries) {
		this.eqmovseries = eqmovseries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqinvprod")
	public Set getEqmovprods() {
		return this.eqmovprods;
	}
*/
	/*public void setEqmovprods(Set eqmovprods) {
		this.eqmovprods = eqmovprods;
	}*/

}
