package org.freedom.persist.entity;

// Generated 20/11/2013 10:59:59 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * EqprodutologId generated by hbm2java
 */
public class EqprodutologId implements java.io.Serializable {

	private int codemp;
	private short codfilial;
	private int codprod;
	private BigDecimal precobaseprodant;
	private BigDecimal precobaseprodnovo;
	private int seqlog;
	private char precoproc;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public EqprodutologId() {
	}

	public EqprodutologId(int codemp, short codfilial, int codprod,
			BigDecimal precobaseprodant, BigDecimal precobaseprodnovo,
			int seqlog, char precoproc, Date dtins, Date hins, String idusuins) {
		this.codemp = codemp;
		this.codfilial = codfilial;
		this.codprod = codprod;
		this.precobaseprodant = precobaseprodant;
		this.precobaseprodnovo = precobaseprodnovo;
		this.seqlog = seqlog;
		this.precoproc = precoproc;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public EqprodutologId(int codemp, short codfilial, int codprod,
			BigDecimal precobaseprodant, BigDecimal precobaseprodnovo,
			int seqlog, char precoproc, Date dtins, Date hins, String idusuins,
			Date dtalt, Date halt, String idusualt) {
		this.codemp = codemp;
		this.codfilial = codfilial;
		this.codprod = codprod;
		this.precobaseprodant = precobaseprodant;
		this.precobaseprodnovo = precobaseprodnovo;
		this.seqlog = seqlog;
		this.precoproc = precoproc;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	public int getCodemp() {
		return this.codemp;
	}

	public void setCodemp(int codemp) {
		this.codemp = codemp;
	}

	public short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(short codfilial) {
		this.codfilial = codfilial;
	}

	public int getCodprod() {
		return this.codprod;
	}

	public void setCodprod(int codprod) {
		this.codprod = codprod;
	}

	public BigDecimal getPrecobaseprodant() {
		return this.precobaseprodant;
	}

	public void setPrecobaseprodant(BigDecimal precobaseprodant) {
		this.precobaseprodant = precobaseprodant;
	}

	public BigDecimal getPrecobaseprodnovo() {
		return this.precobaseprodnovo;
	}

	public void setPrecobaseprodnovo(BigDecimal precobaseprodnovo) {
		this.precobaseprodnovo = precobaseprodnovo;
	}

	public int getSeqlog() {
		return this.seqlog;
	}

	public void setSeqlog(int seqlog) {
		this.seqlog = seqlog;
	}

	public char getPrecoproc() {
		return this.precoproc;
	}

	public void setPrecoproc(char precoproc) {
		this.precoproc = precoproc;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EqprodutologId))
			return false;
		EqprodutologId castOther = (EqprodutologId) other;

		return (this.getCodemp() == castOther.getCodemp())
				&& (this.getCodfilial() == castOther.getCodfilial())
				&& (this.getCodprod() == castOther.getCodprod())
				&& ((this.getPrecobaseprodant() == castOther
						.getPrecobaseprodant()) || (this.getPrecobaseprodant() != null
						&& castOther.getPrecobaseprodant() != null && this
						.getPrecobaseprodant().equals(
								castOther.getPrecobaseprodant())))
				&& ((this.getPrecobaseprodnovo() == castOther
						.getPrecobaseprodnovo()) || (this
						.getPrecobaseprodnovo() != null
						&& castOther.getPrecobaseprodnovo() != null && this
						.getPrecobaseprodnovo().equals(
								castOther.getPrecobaseprodnovo())))
				&& (this.getSeqlog() == castOther.getSeqlog())
				&& (this.getPrecoproc() == castOther.getPrecoproc())
				&& ((this.getDtins() == castOther.getDtins()) || (this
						.getDtins() != null && castOther.getDtins() != null && this
						.getDtins().equals(castOther.getDtins())))
				&& ((this.getHins() == castOther.getHins()) || (this.getHins() != null
						&& castOther.getHins() != null && this.getHins()
						.equals(castOther.getHins())))
				&& ((this.getIdusuins() == castOther.getIdusuins()) || (this
						.getIdusuins() != null
						&& castOther.getIdusuins() != null && this
						.getIdusuins().equals(castOther.getIdusuins())))
				&& ((this.getDtalt() == castOther.getDtalt()) || (this
						.getDtalt() != null && castOther.getDtalt() != null && this
						.getDtalt().equals(castOther.getDtalt())))
				&& ((this.getHalt() == castOther.getHalt()) || (this.getHalt() != null
						&& castOther.getHalt() != null && this.getHalt()
						.equals(castOther.getHalt())))
				&& ((this.getIdusualt() == castOther.getIdusualt()) || (this
						.getIdusualt() != null
						&& castOther.getIdusualt() != null && this
						.getIdusualt().equals(castOther.getIdusualt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodemp();
		result = 37 * result + this.getCodfilial();
		result = 37 * result + this.getCodprod();
		result = 37
				* result
				+ (getPrecobaseprodant() == null ? 0 : this
						.getPrecobaseprodant().hashCode());
		result = 37
				* result
				+ (getPrecobaseprodnovo() == null ? 0 : this
						.getPrecobaseprodnovo().hashCode());
		result = 37 * result + this.getSeqlog();
		result = 37 * result + this.getPrecoproc();
		result = 37 * result
				+ (getDtins() == null ? 0 : this.getDtins().hashCode());
		result = 37 * result
				+ (getHins() == null ? 0 : this.getHins().hashCode());
		result = 37 * result
				+ (getIdusuins() == null ? 0 : this.getIdusuins().hashCode());
		result = 37 * result
				+ (getDtalt() == null ? 0 : this.getDtalt().hashCode());
		result = 37 * result
				+ (getHalt() == null ? 0 : this.getHalt().hashCode());
		result = 37 * result
				+ (getIdusualt() == null ? 0 : this.getIdusualt().hashCode());
		return result;
	}

}
