package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eqrmaal generated by hbm2java
 */
@Entity
@Table(name = "EQRMAAL")
public class Eqrmaal implements java.io.Serializable {

	private EqrmaalId id;
	private Sgusuario sgusuario;
	private Eqrma eqrma;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Eqrmaal() {
	}

	public Eqrmaal(EqrmaalId id, Sgusuario sgusuario, Eqrma eqrma) {
		this.id = id;
		this.sgusuario = sgusuario;
		this.eqrma = eqrma;
	}

	public Eqrmaal(EqrmaalId id, Sgusuario sgusuario, Eqrma eqrma, Date dtins,
			Date hins, String idusuins, Date dtalt, Date halt, String idusualt) {
		this.id = id;
		this.sgusuario = sgusuario;
		this.eqrma = eqrma;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codrma", column = @Column(name = "CODRMA", nullable = false)),
			@AttributeOverride(name = "tipormaal", column = @Column(name = "TIPORMAAL", nullable = false, length = 1)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)),
			@AttributeOverride(name = "idusu", column = @Column(name = "IDUSU", nullable = false, length = 8)),
			@AttributeOverride(name = "codfilialuu", column = @Column(name = "CODFILIALUU", nullable = false)),
			@AttributeOverride(name = "codempuu", column = @Column(name = "CODEMPUU", nullable = false)) })
	public EqrmaalId getId() {
		return this.id;
	}

	public void setId(EqrmaalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "IDUSU", referencedColumnName = "IDUSU", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIALUU", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMPUU", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Sgusuario getSgusuario() {
		return this.sgusuario;
	}

	public void setSgusuario(Sgusuario sgusuario) {
		this.sgusuario = sgusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODRMA", referencedColumnName = "CODRMA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Eqrma getEqrma() {
		return this.eqrma;
	}

	public void setEqrma(Eqrma eqrma) {
		this.eqrma = eqrma;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
