package org.freedom.persist.entity;

// Generated 31/05/2013 12:00:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eqsecao generated by hbm2java
 */
@Entity
@Table(name = "EQSECAO")
public class Eqsecao implements java.io.Serializable {

	private EqsecaoId id;
	private String descsecao;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set<Vdvendedor> vdvendedors = new HashSet<Vdvendedor>(0);
	private Set<Eqproduto> eqprodutos = new HashSet<Eqproduto>(0);
	private Set<Vdregracomis> vdregracomises = new HashSet<Vdregracomis>(0);

	public Eqsecao() {
	}

	public Eqsecao(EqsecaoId id, String descsecao, Date dtins, Date hins,
			String idusuins) {
		this.id = id;
		this.descsecao = descsecao;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Eqsecao(EqsecaoId id, String descsecao, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt,
			Set<Vdvendedor> vdvendedors, Set<Eqproduto> eqprodutos,
			Set<Vdregracomis> vdregracomises) {
		this.id = id;
		this.descsecao = descsecao;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.vdvendedors = vdvendedors;
		this.eqprodutos = eqprodutos;
		this.vdregracomises = vdregracomises;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codsecao", column = @Column(name = "CODSECAO", nullable = false, length = 13)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public EqsecaoId getId() {
		return this.id;
	}

	public void setId(EqsecaoId id) {
		this.id = id;
	}

	@Column(name = "DESCSECAO", nullable = false, length = 50)
	public String getDescsecao() {
		return this.descsecao;
	}

	public void setDescsecao(String descsecao) {
		this.descsecao = descsecao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqsecao")
	public Set<Vdvendedor> getVdvendedors() {
		return this.vdvendedors;
	}

	public void setVdvendedors(Set<Vdvendedor> vdvendedors) {
		this.vdvendedors = vdvendedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqsecao")
	public Set<Eqproduto> getEqprodutos() {
		return this.eqprodutos;
	}

	public void setEqprodutos(Set<Eqproduto> eqprodutos) {
		this.eqprodutos = eqprodutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqsecao")
	public Set<Vdregracomis> getVdregracomises() {
		return this.vdregracomises;
	}

	public void setVdregracomises(Set<Vdregracomis> vdregracomises) {
		this.vdregracomises = vdregracomises;
	}

}
