package org.freedom.persist.entity;

// Generated 20/11/2013 10:59:59 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Eqsecao generated by hbm2java
 */
public class Eqsecao implements java.io.Serializable {

	private EqsecaoId id;
	private String descsecao;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set vdvendedors = new HashSet(0);
	private Set eqprodutos = new HashSet(0);
	private Set vdregracomises = new HashSet(0);

	public Eqsecao() {
	}

	public Eqsecao(EqsecaoId id, String descsecao, Date dtins, Date hins,
			String idusuins) {
		this.id = id;
		this.descsecao = descsecao;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Eqsecao(EqsecaoId id, String descsecao, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt,
			Set vdvendedors, Set eqprodutos, Set vdregracomises) {
		this.id = id;
		this.descsecao = descsecao;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.vdvendedors = vdvendedors;
		this.eqprodutos = eqprodutos;
		this.vdregracomises = vdregracomises;
	}

	public EqsecaoId getId() {
		return this.id;
	}

	public void setId(EqsecaoId id) {
		this.id = id;
	}

	public String getDescsecao() {
		return this.descsecao;
	}

	public void setDescsecao(String descsecao) {
		this.descsecao = descsecao;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	public Set getVdvendedors() {
		return this.vdvendedors;
	}

	public void setVdvendedors(Set vdvendedors) {
		this.vdvendedors = vdvendedors;
	}

	public Set getEqprodutos() {
		return this.eqprodutos;
	}

	public void setEqprodutos(Set eqprodutos) {
		this.eqprodutos = eqprodutos;
	}

	public Set getVdregracomises() {
		return this.vdregracomises;
	}

	public void setVdregracomises(Set vdregracomises) {
		this.vdregracomises = vdregracomises;
	}

}
