package org.freedom.persist.entity;

// Generated 14/04/2014 10:17:08 by Hibernate Tools 4.0.0

/**
 * FnittbjurosId generated by hbm2java
 */
public class FnittbjurosId implements java.io.Serializable {

	private int codtbj;
	private short mesittbj;
	private short anoittbj;
	private short codfilial;
	private int codemp;

	public FnittbjurosId() {
	}

	public FnittbjurosId(int codtbj, short mesittbj, short anoittbj,
			short codfilial, int codemp) {
		this.codtbj = codtbj;
		this.mesittbj = mesittbj;
		this.anoittbj = anoittbj;
		this.codfilial = codfilial;
		this.codemp = codemp;
	}

	public int getCodtbj() {
		return this.codtbj;
	}

	public void setCodtbj(int codtbj) {
		this.codtbj = codtbj;
	}

	public short getMesittbj() {
		return this.mesittbj;
	}

	public void setMesittbj(short mesittbj) {
		this.mesittbj = mesittbj;
	}

	public short getAnoittbj() {
		return this.anoittbj;
	}

	public void setAnoittbj(short anoittbj) {
		this.anoittbj = anoittbj;
	}

	public short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(short codfilial) {
		this.codfilial = codfilial;
	}

	public int getCodemp() {
		return this.codemp;
	}

	public void setCodemp(int codemp) {
		this.codemp = codemp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FnittbjurosId))
			return false;
		FnittbjurosId castOther = (FnittbjurosId) other;

		return (this.getCodtbj() == castOther.getCodtbj())
				&& (this.getMesittbj() == castOther.getMesittbj())
				&& (this.getAnoittbj() == castOther.getAnoittbj())
				&& (this.getCodfilial() == castOther.getCodfilial())
				&& (this.getCodemp() == castOther.getCodemp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodtbj();
		result = 37 * result + this.getMesittbj();
		result = 37 * result + this.getAnoittbj();
		result = 37 * result + this.getCodfilial();
		result = 37 * result + this.getCodemp();
		return result;
	}

}
