package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fnitpagar generated by hbm2java
 */
@Entity
@Table(name = "FNITPAGAR")
public class Fnitpagar implements java.io.Serializable {

	private FnitpagarId id;
	private Fnconta fnconta;
	private Rhempregado rhempregado;
	private Fntipocob fntipocob;
	private Fnsinal fnsinal;
	private Fnplanejamento fnplanejamento;
	private Vditcontrato vditcontrato;
	private Fnpagar fnpagar;
	private BigDecimal vlritpag;
	private BigDecimal vlrdescitpag;
	private BigDecimal vlrmultaitpag;
	private BigDecimal vlrjurositpag;
	private BigDecimal vlrdevitpag;
	private BigDecimal vlrparcitpag;
	private BigDecimal vlrpagoitpag;
	private BigDecimal vlrapagitpag;
	private BigDecimal vlradicitpag;
	private BigDecimal vlrcancitpag;
	private Date dtitpag;
	private Date dtcompitpag;
	private Date dtvencitpag;
	private Date dtpagoitpag;
	private String statusitpag;
	private String doclancaitpag;
	private String obsitpag;
	private Character flag;
	private Integer codempcc;
	private Short codfilialcc;
	private Short anocc;
	private String codcc;
	private char emmanut;
	private Character multibaixa;
	private Character edititpag;
	private Date dtins;
	private String idusuins;
	private Date dtalt;
	private String idusualt;
	private Date hins;
	private Date halt;
	private Set fnlancas = new HashSet(0);
	private Set fnsublancas = new HashSet(0);
	private Set fnmovimentos = new HashSet(0);
	private Set fnpagcheqs = new HashSet(0);

	public Fnitpagar() {
	}

	public Fnitpagar(FnitpagarId id, Fnpagar fnpagar, BigDecimal vlritpag,
			BigDecimal vlrdevitpag, BigDecimal vlrparcitpag, Date dtitpag,
			Date dtcompitpag, Date dtvencitpag, String statusitpag,
			char emmanut, Date dtins, String idusuins, Date hins) {
		this.id = id;
		this.fnpagar = fnpagar;
		this.vlritpag = vlritpag;
		this.vlrdevitpag = vlrdevitpag;
		this.vlrparcitpag = vlrparcitpag;
		this.dtitpag = dtitpag;
		this.dtcompitpag = dtcompitpag;
		this.dtvencitpag = dtvencitpag;
		this.statusitpag = statusitpag;
		this.emmanut = emmanut;
		this.dtins = dtins;
		this.idusuins = idusuins;
		this.hins = hins;
	}

	public Fnitpagar(FnitpagarId id, Fnconta fnconta, Rhempregado rhempregado,
			Fntipocob fntipocob, Fnsinal fnsinal,
			Fnplanejamento fnplanejamento, Vditcontrato vditcontrato,
			Fnpagar fnpagar, BigDecimal vlritpag, BigDecimal vlrdescitpag,
			BigDecimal vlrmultaitpag, BigDecimal vlrjurositpag,
			BigDecimal vlrdevitpag, BigDecimal vlrparcitpag,
			BigDecimal vlrpagoitpag, BigDecimal vlrapagitpag,
			BigDecimal vlradicitpag, BigDecimal vlrcancitpag, Date dtitpag,
			Date dtcompitpag, Date dtvencitpag, Date dtpagoitpag,
			String statusitpag, String doclancaitpag, String obsitpag,
			Character flag, Integer codempcc, Short codfilialcc, Short anocc,
			String codcc, char emmanut, Character multibaixa,
			Character edititpag, Date dtins, String idusuins, Date dtalt,
			String idusualt, Date hins, Date halt, Set fnlancas,
			Set fnsublancas, Set fnmovimentos, Set fnpagcheqs) {
		this.id = id;
		this.fnconta = fnconta;
		this.rhempregado = rhempregado;
		this.fntipocob = fntipocob;
		this.fnsinal = fnsinal;
		this.fnplanejamento = fnplanejamento;
		this.vditcontrato = vditcontrato;
		this.fnpagar = fnpagar;
		this.vlritpag = vlritpag;
		this.vlrdescitpag = vlrdescitpag;
		this.vlrmultaitpag = vlrmultaitpag;
		this.vlrjurositpag = vlrjurositpag;
		this.vlrdevitpag = vlrdevitpag;
		this.vlrparcitpag = vlrparcitpag;
		this.vlrpagoitpag = vlrpagoitpag;
		this.vlrapagitpag = vlrapagitpag;
		this.vlradicitpag = vlradicitpag;
		this.vlrcancitpag = vlrcancitpag;
		this.dtitpag = dtitpag;
		this.dtcompitpag = dtcompitpag;
		this.dtvencitpag = dtvencitpag;
		this.dtpagoitpag = dtpagoitpag;
		this.statusitpag = statusitpag;
		this.doclancaitpag = doclancaitpag;
		this.obsitpag = obsitpag;
		this.flag = flag;
		this.codempcc = codempcc;
		this.codfilialcc = codfilialcc;
		this.anocc = anocc;
		this.codcc = codcc;
		this.emmanut = emmanut;
		this.multibaixa = multibaixa;
		this.edititpag = edititpag;
		this.dtins = dtins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.idusualt = idusualt;
		this.hins = hins;
		this.halt = halt;
		this.fnlancas = fnlancas;
		this.fnsublancas = fnsublancas;
		this.fnmovimentos = fnmovimentos;
		this.fnpagcheqs = fnpagcheqs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codpag", column = @Column(name = "CODPAG", nullable = false)),
			@AttributeOverride(name = "nparcpag", column = @Column(name = "NPARCPAG", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public FnitpagarId getId() {
		return this.id;
	}

	public void setId(FnitpagarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NUMCONTA", referencedColumnName = "NUMCONTA"),
			@JoinColumn(name = "CODFILIALCA", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPCA", referencedColumnName = "CODEMP") })
	public Fnconta getFnconta() {
		return this.fnconta;
	}

	public void setFnconta(Fnconta fnconta) {
		this.fnconta = fnconta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MATEMPR", referencedColumnName = "MATEMPR"),
			@JoinColumn(name = "CODFILIALEM", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPEM", referencedColumnName = "CODEMP") })
	public Rhempregado getRhempregado() {
		return this.rhempregado;
	}

	public void setRhempregado(Rhempregado rhempregado) {
		this.rhempregado = rhempregado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODTIPOCOB", referencedColumnName = "CODTIPOCOB"),
			@JoinColumn(name = "CODFILIALTC", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPTC", referencedColumnName = "CODEMP") })
	public Fntipocob getFntipocob() {
		return this.fntipocob;
	}

	public void setFntipocob(Fntipocob fntipocob) {
		this.fntipocob = fntipocob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODSINAL", referencedColumnName = "CODSINAL"),
			@JoinColumn(name = "CODEMPSN", referencedColumnName = "CODEMP"),
			@JoinColumn(name = "CODFILIALSN", referencedColumnName = "CODFILIAL") })
	public Fnsinal getFnsinal() {
		return this.fnsinal;
	}

	public void setFnsinal(Fnsinal fnsinal) {
		this.fnsinal = fnsinal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODPLAN", referencedColumnName = "CODPLAN"),
			@JoinColumn(name = "CODFILIALPN", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPPN", referencedColumnName = "CODEMP") })
	public Fnplanejamento getFnplanejamento() {
		return this.fnplanejamento;
	}

	public void setFnplanejamento(Fnplanejamento fnplanejamento) {
		this.fnplanejamento = fnplanejamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODCONTR", referencedColumnName = "CODCONTR"),
			@JoinColumn(name = "CODITCONTR", referencedColumnName = "CODITCONTR"),
			@JoinColumn(name = "CODFILIALCT", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPCT", referencedColumnName = "CODEMP") })
	public Vditcontrato getVditcontrato() {
		return this.vditcontrato;
	}

	public void setVditcontrato(Vditcontrato vditcontrato) {
		this.vditcontrato = vditcontrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODPAG", referencedColumnName = "CODPAG", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Fnpagar getFnpagar() {
		return this.fnpagar;
	}

	public void setFnpagar(Fnpagar fnpagar) {
		this.fnpagar = fnpagar;
	}

	@Column(name = "VLRITPAG", nullable = false, precision = 15, scale = 5)
	public BigDecimal getVlritpag() {
		return this.vlritpag;
	}

	public void setVlritpag(BigDecimal vlritpag) {
		this.vlritpag = vlritpag;
	}

	@Column(name = "VLRDESCITPAG", precision = 15, scale = 5)
	public BigDecimal getVlrdescitpag() {
		return this.vlrdescitpag;
	}

	public void setVlrdescitpag(BigDecimal vlrdescitpag) {
		this.vlrdescitpag = vlrdescitpag;
	}

	@Column(name = "VLRMULTAITPAG", precision = 15, scale = 5)
	public BigDecimal getVlrmultaitpag() {
		return this.vlrmultaitpag;
	}

	public void setVlrmultaitpag(BigDecimal vlrmultaitpag) {
		this.vlrmultaitpag = vlrmultaitpag;
	}

	@Column(name = "VLRJUROSITPAG", precision = 15, scale = 5)
	public BigDecimal getVlrjurositpag() {
		return this.vlrjurositpag;
	}

	public void setVlrjurositpag(BigDecimal vlrjurositpag) {
		this.vlrjurositpag = vlrjurositpag;
	}

	@Column(name = "VLRDEVITPAG", nullable = false, precision = 15, scale = 5)
	public BigDecimal getVlrdevitpag() {
		return this.vlrdevitpag;
	}

	public void setVlrdevitpag(BigDecimal vlrdevitpag) {
		this.vlrdevitpag = vlrdevitpag;
	}

	@Column(name = "VLRPARCITPAG", nullable = false, precision = 15, scale = 5)
	public BigDecimal getVlrparcitpag() {
		return this.vlrparcitpag;
	}

	public void setVlrparcitpag(BigDecimal vlrparcitpag) {
		this.vlrparcitpag = vlrparcitpag;
	}

	@Column(name = "VLRPAGOITPAG", precision = 15, scale = 5)
	public BigDecimal getVlrpagoitpag() {
		return this.vlrpagoitpag;
	}

	public void setVlrpagoitpag(BigDecimal vlrpagoitpag) {
		this.vlrpagoitpag = vlrpagoitpag;
	}

	@Column(name = "VLRAPAGITPAG", precision = 15, scale = 5)
	public BigDecimal getVlrapagitpag() {
		return this.vlrapagitpag;
	}

	public void setVlrapagitpag(BigDecimal vlrapagitpag) {
		this.vlrapagitpag = vlrapagitpag;
	}

	@Column(name = "VLRADICITPAG", precision = 15, scale = 5)
	public BigDecimal getVlradicitpag() {
		return this.vlradicitpag;
	}

	public void setVlradicitpag(BigDecimal vlradicitpag) {
		this.vlradicitpag = vlradicitpag;
	}

	@Column(name = "VLRCANCITPAG", precision = 15, scale = 5)
	public BigDecimal getVlrcancitpag() {
		return this.vlrcancitpag;
	}

	public void setVlrcancitpag(BigDecimal vlrcancitpag) {
		this.vlrcancitpag = vlrcancitpag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTITPAG", nullable = false, length = 10)
	public Date getDtitpag() {
		return this.dtitpag;
	}

	public void setDtitpag(Date dtitpag) {
		this.dtitpag = dtitpag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTCOMPITPAG", nullable = false, length = 10)
	public Date getDtcompitpag() {
		return this.dtcompitpag;
	}

	public void setDtcompitpag(Date dtcompitpag) {
		this.dtcompitpag = dtcompitpag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTVENCITPAG", nullable = false, length = 10)
	public Date getDtvencitpag() {
		return this.dtvencitpag;
	}

	public void setDtvencitpag(Date dtvencitpag) {
		this.dtvencitpag = dtvencitpag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPAGOITPAG", length = 10)
	public Date getDtpagoitpag() {
		return this.dtpagoitpag;
	}

	public void setDtpagoitpag(Date dtpagoitpag) {
		this.dtpagoitpag = dtpagoitpag;
	}

	@Column(name = "STATUSITPAG", nullable = false, length = 2)
	public String getStatusitpag() {
		return this.statusitpag;
	}

	public void setStatusitpag(String statusitpag) {
		this.statusitpag = statusitpag;
	}

	@Column(name = "DOCLANCAITPAG", length = 15)
	public String getDoclancaitpag() {
		return this.doclancaitpag;
	}

	public void setDoclancaitpag(String doclancaitpag) {
		this.doclancaitpag = doclancaitpag;
	}

	@Column(name = "OBSITPAG", length = 250)
	public String getObsitpag() {
		return this.obsitpag;
	}

	public void setObsitpag(String obsitpag) {
		this.obsitpag = obsitpag;
	}

	@Column(name = "FLAG", length = 1)
	public Character getFlag() {
		return this.flag;
	}

	public void setFlag(Character flag) {
		this.flag = flag;
	}

	@Column(name = "CODEMPCC")
	public Integer getCodempcc() {
		return this.codempcc;
	}

	public void setCodempcc(Integer codempcc) {
		this.codempcc = codempcc;
	}

	@Column(name = "CODFILIALCC")
	public Short getCodfilialcc() {
		return this.codfilialcc;
	}

	public void setCodfilialcc(Short codfilialcc) {
		this.codfilialcc = codfilialcc;
	}

	@Column(name = "ANOCC")
	public Short getAnocc() {
		return this.anocc;
	}

	public void setAnocc(Short anocc) {
		this.anocc = anocc;
	}

	@Column(name = "CODCC", length = 19)
	public String getCodcc() {
		return this.codcc;
	}

	public void setCodcc(String codcc) {
		this.codcc = codcc;
	}

	@Column(name = "EMMANUT", nullable = false, length = 1)
	public char getEmmanut() {
		return this.emmanut;
	}

	public void setEmmanut(char emmanut) {
		this.emmanut = emmanut;
	}

	@Column(name = "MULTIBAIXA", length = 1)
	public Character getMultibaixa() {
		return this.multibaixa;
	}

	public void setMultibaixa(Character multibaixa) {
		this.multibaixa = multibaixa;
	}

	@Column(name = "EDITITPAG", length = 1)
	public Character getEdititpag() {
		return this.edititpag;
	}

	public void setEdititpag(Character edititpag) {
		this.edititpag = edititpag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "fnitpagar")
	public Set getFnlancas() {
		return this.fnlancas;
	}

	public void setFnlancas(Set fnlancas) {
		this.fnlancas = fnlancas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fnitpagar")
	public Set getFnsublancas() {
		return this.fnsublancas;
	}

	public void setFnsublancas(Set fnsublancas) {
		this.fnsublancas = fnsublancas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fnitpagar")
	public Set getFnmovimentos() {
		return this.fnmovimentos;
	}

	public void setFnmovimentos(Set fnmovimentos) {
		this.fnmovimentos = fnmovimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fnitpagar")
	public Set getFnpagcheqs() {
		return this.fnpagcheqs;
	}

	public void setFnpagcheqs(Set fnpagcheqs) {
		this.fnpagcheqs = fnpagcheqs;
	}
*/
}
