package org.freedom.persist.entity;

// Generated 20/11/2013 10:59:59 by Hibernate Tools 4.0.0

/**
 * FnrestricaoId generated by hbm2java
 */
public class FnrestricaoId implements java.io.Serializable {

	private int codcli;
	private short seqrestr;
	private short codfilial;
	private int codemp;

	public FnrestricaoId() {
	}

	public FnrestricaoId(int codcli, short seqrestr, short codfilial, int codemp) {
		this.codcli = codcli;
		this.seqrestr = seqrestr;
		this.codfilial = codfilial;
		this.codemp = codemp;
	}

	public int getCodcli() {
		return this.codcli;
	}

	public void setCodcli(int codcli) {
		this.codcli = codcli;
	}

	public short getSeqrestr() {
		return this.seqrestr;
	}

	public void setSeqrestr(short seqrestr) {
		this.seqrestr = seqrestr;
	}

	public short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(short codfilial) {
		this.codfilial = codfilial;
	}

	public int getCodemp() {
		return this.codemp;
	}

	public void setCodemp(int codemp) {
		this.codemp = codemp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FnrestricaoId))
			return false;
		FnrestricaoId castOther = (FnrestricaoId) other;

		return (this.getCodcli() == castOther.getCodcli())
				&& (this.getSeqrestr() == castOther.getSeqrestr())
				&& (this.getCodfilial() == castOther.getCodfilial())
				&& (this.getCodemp() == castOther.getCodemp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodcli();
		result = 37 * result + this.getSeqrestr();
		result = 37 * result + this.getCodfilial();
		result = 37 * result + this.getCodemp();
		return result;
	}

}
