package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fntipocred generated by hbm2java
 */
@Entity
@Table(name = "FNTIPOCRED")
public class Fntipocred implements java.io.Serializable {

	private FntipocredId id;
	private String desctpcred;
	private BigDecimal vlrtpcred;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set vdclientes = new HashSet(0);

	public Fntipocred() {
	}

	public Fntipocred(FntipocredId id, String desctpcred, BigDecimal vlrtpcred,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.desctpcred = desctpcred;
		this.vlrtpcred = vlrtpcred;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Fntipocred(FntipocredId id, String desctpcred, BigDecimal vlrtpcred,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt, Set vdclientes) {
		this.id = id;
		this.desctpcred = desctpcred;
		this.vlrtpcred = vlrtpcred;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.vdclientes = vdclientes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codtpcred", column = @Column(name = "CODTPCRED", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public FntipocredId getId() {
		return this.id;
	}

	public void setId(FntipocredId id) {
		this.id = id;
	}

	@Column(name = "DESCTPCRED", nullable = false, length = 50)
	public String getDesctpcred() {
		return this.desctpcred;
	}

	public void setDesctpcred(String desctpcred) {
		this.desctpcred = desctpcred;
	}

	@Column(name = "VLRTPCRED", nullable = false, precision = 15, scale = 5)
	public BigDecimal getVlrtpcred() {
		return this.vlrtpcred;
	}

	public void setVlrtpcred(BigDecimal vlrtpcred) {
		this.vlrtpcred = vlrtpcred;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "fntipocred")
	public Set getVdclientes() {
		return this.vdclientes;
	}

	public void setVdclientes(Set vdclientes) {
		this.vdclientes = vdclientes;
	}
*/
}
