package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pptipoanalise generated by hbm2java
 */
@Entity
@Table(name = "PPTIPOANALISE")
public class Pptipoanalise implements java.io.Serializable {

	private PptipoanaliseId id;
	private Equnidade equnidade;
	private Ppmetodoanalise ppmetodoanalise;
	private String desctpanalise;
	private String obstpanalise;
	private String tipoexpec;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set ppestruanalises = new HashSet(0);

	public Pptipoanalise() {
	}

	public Pptipoanalise(PptipoanaliseId id, Ppmetodoanalise ppmetodoanalise,
			String tipoexpec, Date dtins, Date hins, String idusuins,
			Date dtalt, Date halt, String idusualt) {
		this.id = id;
		this.ppmetodoanalise = ppmetodoanalise;
		this.tipoexpec = tipoexpec;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	public Pptipoanalise(PptipoanaliseId id, Equnidade equnidade,
			Ppmetodoanalise ppmetodoanalise, String desctpanalise,
			String obstpanalise, String tipoexpec, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt,
			Set ppestruanalises) {
		this.id = id;
		this.equnidade = equnidade;
		this.ppmetodoanalise = ppmetodoanalise;
		this.desctpanalise = desctpanalise;
		this.obstpanalise = obstpanalise;
		this.tipoexpec = tipoexpec;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.ppestruanalises = ppestruanalises;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codtpanalise", column = @Column(name = "CODTPANALISE", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public PptipoanaliseId getId() {
		return this.id;
	}

	public void setId(PptipoanaliseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODUNID", referencedColumnName = "CODUNID"),
			@JoinColumn(name = "CODFILIALUD", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPUD", referencedColumnName = "CODEMP") })
	public Equnidade getEqunidade() {
		return this.equnidade;
	}

	public void setEqunidade(Equnidade equnidade) {
		this.equnidade = equnidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODMTANALISE", referencedColumnName = "CODMTANALISE", nullable = false),
			@JoinColumn(name = "CODFILIALMA", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPMA", referencedColumnName = "CODEMP", nullable = false) })
	public Ppmetodoanalise getPpmetodoanalise() {
		return this.ppmetodoanalise;
	}

	public void setPpmetodoanalise(Ppmetodoanalise ppmetodoanalise) {
		this.ppmetodoanalise = ppmetodoanalise;
	}

	@Column(name = "DESCTPANALISE", length = 80)
	public String getDesctpanalise() {
		return this.desctpanalise;
	}

	public void setDesctpanalise(String desctpanalise) {
		this.desctpanalise = desctpanalise;
	}

	@Column(name = "OBSTPANALISE", length = 500)
	public String getObstpanalise() {
		return this.obstpanalise;
	}

	public void setObstpanalise(String obstpanalise) {
		this.obstpanalise = obstpanalise;
	}

	@Column(name = "TIPOEXPEC", nullable = false, length = 2)
	public String getTipoexpec() {
		return this.tipoexpec;
	}

	public void setTipoexpec(String tipoexpec) {
		this.tipoexpec = tipoexpec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 128)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", nullable = false, length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", nullable = false, length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", nullable = false, length = 128)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "pptipoanalise")
	public Set getPpestruanalises() {
		return this.ppestruanalises;
	}

	public void setPpestruanalises(Set ppestruanalises) {
		this.ppestruanalises = ppestruanalises;
	}
*/
}
