package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pptiporec generated by hbm2java
 */
@Entity
@Table(name = "PPTIPOREC")
public class Pptiporec implements java.io.Serializable {

	private PptiporecId id;
	private Sgfilial sgfilial;
	private String desctprec;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set ppopfases = new HashSet(0);
	private Set pprecursos = new HashSet(0);
	private Set ppestrufases = new HashSet(0);

	public Pptiporec() {
	}

	public Pptiporec(PptiporecId id, Sgfilial sgfilial, String desctprec,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.desctprec = desctprec;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Pptiporec(PptiporecId id, Sgfilial sgfilial, String desctprec,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt, Set ppopfases, Set pprecursos, Set ppestrufases) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.desctprec = desctprec;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.ppopfases = ppopfases;
		this.pprecursos = pprecursos;
		this.ppestrufases = ppestrufases;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codtprec", column = @Column(name = "CODTPREC", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public PptiporecId getId() {
		return this.id;
	}

	public void setId(PptiporecId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Sgfilial getSgfilial() {
		return this.sgfilial;
	}

	public void setSgfilial(Sgfilial sgfilial) {
		this.sgfilial = sgfilial;
	}

	@Column(name = "DESCTPREC", nullable = false, length = 50)
	public String getDesctprec() {
		return this.desctprec;
	}

	public void setDesctprec(String desctprec) {
		this.desctprec = desctprec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "pptiporec")
	public Set getPpopfases() {
		return this.ppopfases;
	}

	public void setPpopfases(Set ppopfases) {
		this.ppopfases = ppopfases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pptiporec")
	public Set getPprecursos() {
		return this.pprecursos;
	}

	public void setPprecursos(Set pprecursos) {
		this.pprecursos = pprecursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pptiporec")
	public Set getPpestrufases() {
		return this.ppestrufases;
	}

	public void setPpestrufases(Set ppestrufases) {
		this.ppestrufases = ppestrufases;
	}
*/
}
