package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rhcandidatostatus generated by hbm2java
 */
@Entity
@Table(name = "RHCANDIDATOSTATUS")
public class Rhcandidatostatus implements java.io.Serializable {

	private RhcandidatostatusId id;
	private Rhcandidato rhcandidato;
	private Rhvaga rhvaga;
	private Integer codempvg;
	private Short codfilialvg;
	private String stcand;
	private Date dtstatus;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Rhcandidatostatus() {
	}

	public Rhcandidatostatus(RhcandidatostatusId id, Rhcandidato rhcandidato,
			Rhvaga rhvaga, Date dtstatus, Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.rhcandidato = rhcandidato;
		this.rhvaga = rhvaga;
		this.dtstatus = dtstatus;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Rhcandidatostatus(RhcandidatostatusId id, Rhcandidato rhcandidato,
			Rhvaga rhvaga, Integer codempvg, Short codfilialvg, String stcand,
			Date dtstatus, Date dtins, Date hins, String idusuins, Date dtalt,
			Date halt, String idusualt) {
		this.id = id;
		this.rhcandidato = rhcandidato;
		this.rhvaga = rhvaga;
		this.codempvg = codempvg;
		this.codfilialvg = codfilialvg;
		this.stcand = stcand;
		this.dtstatus = dtstatus;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codcand", column = @Column(name = "CODCAND", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)),
			@AttributeOverride(name = "sqstcand", column = @Column(name = "SQSTCAND", nullable = false)) })
	public RhcandidatostatusId getId() {
		return this.id;
	}

	public void setId(RhcandidatostatusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODCAND", referencedColumnName = "CODCAND", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Rhcandidato getRhcandidato() {
		return this.rhcandidato;
	}

	public void setRhcandidato(Rhcandidato rhcandidato) {
		this.rhcandidato = rhcandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODVAGA", referencedColumnName = "CODVAGA", insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", insertable = false, updatable = false) })
	public Rhvaga getRhvaga() {
		return this.rhvaga;
	}

	public void setRhvaga(Rhvaga rhvaga) {
		this.rhvaga = rhvaga;
	}

	@Column(name = "CODEMPVG")
	public Integer getCodempvg() {
		return this.codempvg;
	}

	public void setCodempvg(Integer codempvg) {
		this.codempvg = codempvg;
	}

	@Column(name = "CODFILIALVG")
	public Short getCodfilialvg() {
		return this.codfilialvg;
	}

	public void setCodfilialvg(Short codfilialvg) {
		this.codfilialvg = codfilialvg;
	}

	@Column(name = "STCAND", length = 2)
	public String getStcand() {
		return this.stcand;
	}

	public void setStcand(String stcand) {
		this.stcand = stcand;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTSTATUS", nullable = false, length = 10)
	public Date getDtstatus() {
		return this.dtstatus;
	}

	public void setDtstatus(Date dtstatus) {
		this.dtstatus = dtstatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
