package org.freedom.persist.entity;

// Generated 31/05/2013 12:00:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rhempregado generated by hbm2java
 */
@Entity
@Table(name = "RHEMPREGADO")
public class Rhempregado implements java.io.Serializable {

	private RhempregadoId id;
	private Rhdepto rhdepto;
	private Rhempregado rhempregado;
	private Rhfuncao rhfuncao;
	private Rhturno rhturno;
	private String nomeempr;
	private String apelidoempr;
	private String endempr;
	private Integer numempr;
	private String cidempr;
	private String bairempr;
	private String cepempr;
	private String foneempr;
	private Date dtadmissao;
	private byte[] fotoempr;
	private String statusempr;
	private char sexoempr;
	private Date dtnascempr;
	private String ctpsempr;
	private String seriectpsempr;
	private String ufctpsempr;
	private String certreservempr;
	private String pispasepempr;
	private String rgempr;
	private String orgexprhempr;
	private String cpfempr;
	private String ufrgempr;
	private Date dtexprgempr;
	private String titeleitempr;
	private Integer zonaeleitempr;
	private Integer secaoeleitempr;
	private String cnhempr;
	private String maeempr;
	private String paiempr;
	private String complendempr;
	private String ufempr;
	private Date dtdemissaoempr;
	private String dddempr;
	private String fone2empr;
	private String celempr;
	private String emailempr;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set<Pebatida> pebatidas = new HashSet<Pebatida>(0);
	private Set<Rhponto> rhpontos = new HashSet<Rhponto>(0);
	private Set<Atatendente> atatendentes = new HashSet<Atatendente>(0);
	private Set<Rhempregadobenef> rhempregadobenefs = new HashSet<Rhempregadobenef>(
			0);
	private Set<Rhempregado> rhempregados = new HashSet<Rhempregado>(0);
	private Set<Pefalta> pefaltas = new HashSet<Pefalta>(0);
	private Set<Rhempregadosal> rhempregadosals = new HashSet<Rhempregadosal>(0);

	public Rhempregado() {
	}

	public Rhempregado(RhempregadoId id, Rhdepto rhdepto,
			Rhempregado rhempregado, Rhfuncao rhfuncao, Rhturno rhturno,
			String nomeempr, String apelidoempr, Date dtadmissao,
			String statusempr, char sexoempr, Date dtins, Date hins,
			String idusuins) {
		this.id = id;
		this.rhdepto = rhdepto;
		this.rhempregado = rhempregado;
		this.rhfuncao = rhfuncao;
		this.rhturno = rhturno;
		this.nomeempr = nomeempr;
		this.apelidoempr = apelidoempr;
		this.dtadmissao = dtadmissao;
		this.statusempr = statusempr;
		this.sexoempr = sexoempr;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Rhempregado(RhempregadoId id, Rhdepto rhdepto,
			Rhempregado rhempregado, Rhfuncao rhfuncao, Rhturno rhturno,
			String nomeempr, String apelidoempr, String endempr,
			Integer numempr, String cidempr, String bairempr, String cepempr,
			String foneempr, Date dtadmissao, byte[] fotoempr,
			String statusempr, char sexoempr, Date dtnascempr, String ctpsempr,
			String seriectpsempr, String ufctpsempr, String certreservempr,
			String pispasepempr, String rgempr, String orgexprhempr,
			String cpfempr, String ufrgempr, Date dtexprgempr,
			String titeleitempr, Integer zonaeleitempr, Integer secaoeleitempr,
			String cnhempr, String maeempr, String paiempr,
			String complendempr, String ufempr, Date dtdemissaoempr,
			String dddempr, String fone2empr, String celempr, String emailempr,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt, Set<Pebatida> pebatidas, Set<Rhponto> rhpontos,
			Set<Atatendente> atatendentes,
			Set<Rhempregadobenef> rhempregadobenefs,
			Set<Rhempregado> rhempregados, Set<Pefalta> pefaltas,
			Set<Rhempregadosal> rhempregadosals) {
		this.id = id;
		this.rhdepto = rhdepto;
		this.rhempregado = rhempregado;
		this.rhfuncao = rhfuncao;
		this.rhturno = rhturno;
		this.nomeempr = nomeempr;
		this.apelidoempr = apelidoempr;
		this.endempr = endempr;
		this.numempr = numempr;
		this.cidempr = cidempr;
		this.bairempr = bairempr;
		this.cepempr = cepempr;
		this.foneempr = foneempr;
		this.dtadmissao = dtadmissao;
		this.fotoempr = fotoempr;
		this.statusempr = statusempr;
		this.sexoempr = sexoempr;
		this.dtnascempr = dtnascempr;
		this.ctpsempr = ctpsempr;
		this.seriectpsempr = seriectpsempr;
		this.ufctpsempr = ufctpsempr;
		this.certreservempr = certreservempr;
		this.pispasepempr = pispasepempr;
		this.rgempr = rgempr;
		this.orgexprhempr = orgexprhempr;
		this.cpfempr = cpfempr;
		this.ufrgempr = ufrgempr;
		this.dtexprgempr = dtexprgempr;
		this.titeleitempr = titeleitempr;
		this.zonaeleitempr = zonaeleitempr;
		this.secaoeleitempr = secaoeleitempr;
		this.cnhempr = cnhempr;
		this.maeempr = maeempr;
		this.paiempr = paiempr;
		this.complendempr = complendempr;
		this.ufempr = ufempr;
		this.dtdemissaoempr = dtdemissaoempr;
		this.dddempr = dddempr;
		this.fone2empr = fone2empr;
		this.celempr = celempr;
		this.emailempr = emailempr;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.pebatidas = pebatidas;
		this.rhpontos = rhpontos;
		this.atatendentes = atatendentes;
		this.rhempregadobenefs = rhempregadobenefs;
		this.rhempregados = rhempregados;
		this.pefaltas = pefaltas;
		this.rhempregadosals = rhempregadosals;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "matempr", column = @Column(name = "MATEMPR", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public RhempregadoId getId() {
		return this.id;
	}

	public void setId(RhempregadoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODDEP", referencedColumnName = "CODDEP", nullable = false),
			@JoinColumn(name = "CODFILIALDP", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPDP", referencedColumnName = "CODEMP", nullable = false) })
	public Rhdepto getRhdepto() {
		return this.rhdepto;
	}

	public void setRhdepto(Rhdepto rhdepto) {
		this.rhdepto = rhdepto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MATEMPR", referencedColumnName = "MATEMPR", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMPDP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Rhempregado getRhempregado() {
		return this.rhempregado;
	}

	public void setRhempregado(Rhempregado rhempregado) {
		this.rhempregado = rhempregado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODFUNC", referencedColumnName = "CODFUNC", nullable = false),
			@JoinColumn(name = "CODFILIALFO", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPFO", referencedColumnName = "CODEMP", nullable = false) })
	public Rhfuncao getRhfuncao() {
		return this.rhfuncao;
	}

	public void setRhfuncao(Rhfuncao rhfuncao) {
		this.rhfuncao = rhfuncao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODTURNO", referencedColumnName = "CODTURNO"),
			@JoinColumn(name = "CODFILIALTO", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPTO", referencedColumnName = "CODEMP", nullable = false) })
	public Rhturno getRhturno() {
		return this.rhturno;
	}

	public void setRhturno(Rhturno rhturno) {
		this.rhturno = rhturno;
	}

	@Column(name = "NOMEEMPR", nullable = false, length = 50)
	public String getNomeempr() {
		return this.nomeempr;
	}

	public void setNomeempr(String nomeempr) {
		this.nomeempr = nomeempr;
	}

	@Column(name = "APELIDOEMPR", nullable = false, length = 30)
	public String getApelidoempr() {
		return this.apelidoempr;
	}

	public void setApelidoempr(String apelidoempr) {
		this.apelidoempr = apelidoempr;
	}

	@Column(name = "ENDEMPR", length = 50)
	public String getEndempr() {
		return this.endempr;
	}

	public void setEndempr(String endempr) {
		this.endempr = endempr;
	}

	@Column(name = "NUMEMPR")
	public Integer getNumempr() {
		return this.numempr;
	}

	public void setNumempr(Integer numempr) {
		this.numempr = numempr;
	}

	@Column(name = "CIDEMPR", length = 30)
	public String getCidempr() {
		return this.cidempr;
	}

	public void setCidempr(String cidempr) {
		this.cidempr = cidempr;
	}

	@Column(name = "BAIREMPR", length = 30)
	public String getBairempr() {
		return this.bairempr;
	}

	public void setBairempr(String bairempr) {
		this.bairempr = bairempr;
	}

	@Column(name = "CEPEMPR", length = 8)
	public String getCepempr() {
		return this.cepempr;
	}

	public void setCepempr(String cepempr) {
		this.cepempr = cepempr;
	}

	@Column(name = "FONEEMPR", length = 12)
	public String getFoneempr() {
		return this.foneempr;
	}

	public void setFoneempr(String foneempr) {
		this.foneempr = foneempr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTADMISSAO", nullable = false, length = 10)
	public Date getDtadmissao() {
		return this.dtadmissao;
	}

	public void setDtadmissao(Date dtadmissao) {
		this.dtadmissao = dtadmissao;
	}

	@Column(name = "FOTOEMPR")
	public byte[] getFotoempr() {
		return this.fotoempr;
	}

	public void setFotoempr(byte[] fotoempr) {
		this.fotoempr = fotoempr;
	}

	@Column(name = "STATUSEMPR", nullable = false, length = 2)
	public String getStatusempr() {
		return this.statusempr;
	}

	public void setStatusempr(String statusempr) {
		this.statusempr = statusempr;
	}

	@Column(name = "SEXOEMPR", nullable = false, length = 1)
	public char getSexoempr() {
		return this.sexoempr;
	}

	public void setSexoempr(char sexoempr) {
		this.sexoempr = sexoempr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTNASCEMPR", length = 10)
	public Date getDtnascempr() {
		return this.dtnascempr;
	}

	public void setDtnascempr(Date dtnascempr) {
		this.dtnascempr = dtnascempr;
	}

	@Column(name = "CTPSEMPR", length = 20)
	public String getCtpsempr() {
		return this.ctpsempr;
	}

	public void setCtpsempr(String ctpsempr) {
		this.ctpsempr = ctpsempr;
	}

	@Column(name = "SERIECTPSEMPR", length = 6)
	public String getSeriectpsempr() {
		return this.seriectpsempr;
	}

	public void setSeriectpsempr(String seriectpsempr) {
		this.seriectpsempr = seriectpsempr;
	}

	@Column(name = "UFCTPSEMPR", length = 2)
	public String getUfctpsempr() {
		return this.ufctpsempr;
	}

	public void setUfctpsempr(String ufctpsempr) {
		this.ufctpsempr = ufctpsempr;
	}

	@Column(name = "CERTRESERVEMPR", length = 20)
	public String getCertreservempr() {
		return this.certreservempr;
	}

	public void setCertreservempr(String certreservempr) {
		this.certreservempr = certreservempr;
	}

	@Column(name = "PISPASEPEMPR", length = 20)
	public String getPispasepempr() {
		return this.pispasepempr;
	}

	public void setPispasepempr(String pispasepempr) {
		this.pispasepempr = pispasepempr;
	}

	@Column(name = "RGEMPR", length = 13)
	public String getRgempr() {
		return this.rgempr;
	}

	public void setRgempr(String rgempr) {
		this.rgempr = rgempr;
	}

	@Column(name = "ORGEXPRHEMPR", length = 10)
	public String getOrgexprhempr() {
		return this.orgexprhempr;
	}

	public void setOrgexprhempr(String orgexprhempr) {
		this.orgexprhempr = orgexprhempr;
	}

	@Column(name = "CPFEMPR", length = 11)
	public String getCpfempr() {
		return this.cpfempr;
	}

	public void setCpfempr(String cpfempr) {
		this.cpfempr = cpfempr;
	}

	@Column(name = "UFRGEMPR", length = 2)
	public String getUfrgempr() {
		return this.ufrgempr;
	}

	public void setUfrgempr(String ufrgempr) {
		this.ufrgempr = ufrgempr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTEXPRGEMPR", length = 10)
	public Date getDtexprgempr() {
		return this.dtexprgempr;
	}

	public void setDtexprgempr(Date dtexprgempr) {
		this.dtexprgempr = dtexprgempr;
	}

	@Column(name = "TITELEITEMPR", length = 15)
	public String getTiteleitempr() {
		return this.titeleitempr;
	}

	public void setTiteleitempr(String titeleitempr) {
		this.titeleitempr = titeleitempr;
	}

	@Column(name = "ZONAELEITEMPR")
	public Integer getZonaeleitempr() {
		return this.zonaeleitempr;
	}

	public void setZonaeleitempr(Integer zonaeleitempr) {
		this.zonaeleitempr = zonaeleitempr;
	}

	@Column(name = "SECAOELEITEMPR")
	public Integer getSecaoeleitempr() {
		return this.secaoeleitempr;
	}

	public void setSecaoeleitempr(Integer secaoeleitempr) {
		this.secaoeleitempr = secaoeleitempr;
	}

	@Column(name = "CNHEMPR", length = 20)
	public String getCnhempr() {
		return this.cnhempr;
	}

	public void setCnhempr(String cnhempr) {
		this.cnhempr = cnhempr;
	}

	@Column(name = "MAEEMPR", length = 80)
	public String getMaeempr() {
		return this.maeempr;
	}

	public void setMaeempr(String maeempr) {
		this.maeempr = maeempr;
	}

	@Column(name = "PAIEMPR", length = 80)
	public String getPaiempr() {
		return this.paiempr;
	}

	public void setPaiempr(String paiempr) {
		this.paiempr = paiempr;
	}

	@Column(name = "COMPLENDEMPR", length = 40)
	public String getComplendempr() {
		return this.complendempr;
	}

	public void setComplendempr(String complendempr) {
		this.complendempr = complendempr;
	}

	@Column(name = "UFEMPR", length = 2)
	public String getUfempr() {
		return this.ufempr;
	}

	public void setUfempr(String ufempr) {
		this.ufempr = ufempr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTDEMISSAOEMPR", length = 10)
	public Date getDtdemissaoempr() {
		return this.dtdemissaoempr;
	}

	public void setDtdemissaoempr(Date dtdemissaoempr) {
		this.dtdemissaoempr = dtdemissaoempr;
	}

	@Column(name = "DDDEMPR", length = 4)
	public String getDddempr() {
		return this.dddempr;
	}

	public void setDddempr(String dddempr) {
		this.dddempr = dddempr;
	}

	@Column(name = "FONE2EMPR", length = 12)
	public String getFone2empr() {
		return this.fone2empr;
	}

	public void setFone2empr(String fone2empr) {
		this.fone2empr = fone2empr;
	}

	@Column(name = "CELEMPR", length = 12)
	public String getCelempr() {
		return this.celempr;
	}

	public void setCelempr(String celempr) {
		this.celempr = celempr;
	}

	@Column(name = "EMAILEMPR", length = 40)
	public String getEmailempr() {
		return this.emailempr;
	}

	public void setEmailempr(String emailempr) {
		this.emailempr = emailempr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rhempregado")
	public Set<Pebatida> getPebatidas() {
		return this.pebatidas;
	}

	public void setPebatidas(Set<Pebatida> pebatidas) {
		this.pebatidas = pebatidas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rhempregado")
	public Set<Rhponto> getRhpontos() {
		return this.rhpontos;
	}

	public void setRhpontos(Set<Rhponto> rhpontos) {
		this.rhpontos = rhpontos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rhempregado")
	public Set<Atatendente> getAtatendentes() {
		return this.atatendentes;
	}

	public void setAtatendentes(Set<Atatendente> atatendentes) {
		this.atatendentes = atatendentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rhempregado")
	public Set<Rhempregadobenef> getRhempregadobenefs() {
		return this.rhempregadobenefs;
	}

	public void setRhempregadobenefs(Set<Rhempregadobenef> rhempregadobenefs) {
		this.rhempregadobenefs = rhempregadobenefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rhempregado")
	public Set<Rhempregado> getRhempregados() {
		return this.rhempregados;
	}

	public void setRhempregados(Set<Rhempregado> rhempregados) {
		this.rhempregados = rhempregados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rhempregado")
	public Set<Pefalta> getPefaltas() {
		return this.pefaltas;
	}

	public void setPefaltas(Set<Pefalta> pefaltas) {
		this.pefaltas = pefaltas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rhempregado")
	public Set<Rhempregadosal> getRhempregadosals() {
		return this.rhempregadosals;
	}

	public void setRhempregadosals(Set<Rhempregadosal> rhempregadosals) {
		this.rhempregadosals = rhempregadosals;
	}

}
