package org.freedom.persist.entity;

// Generated 18/02/2014 15:53:28 by Hibernate Tools 4.0.0

/**
 * SgestcivilId generated by hbm2java
 */
public class SgestcivilId implements java.io.Serializable {

	private String codestcivil;
	private short codfilial;
	private int codemp;

	public SgestcivilId() {
	}

	public SgestcivilId(String codestcivil, short codfilial, int codemp) {
		this.codestcivil = codestcivil;
		this.codfilial = codfilial;
		this.codemp = codemp;
	}

	public String getCodestcivil() {
		return this.codestcivil;
	}

	public void setCodestcivil(String codestcivil) {
		this.codestcivil = codestcivil;
	}

	public short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(short codfilial) {
		this.codfilial = codfilial;
	}

	public int getCodemp() {
		return this.codemp;
	}

	public void setCodemp(int codemp) {
		this.codemp = codemp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SgestcivilId))
			return false;
		SgestcivilId castOther = (SgestcivilId) other;

		return ((this.getCodestcivil() == castOther.getCodestcivil()) || (this
				.getCodestcivil() != null && castOther.getCodestcivil() != null && this
				.getCodestcivil().equals(castOther.getCodestcivil())))
				&& (this.getCodfilial() == castOther.getCodfilial())
				&& (this.getCodemp() == castOther.getCodemp());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodestcivil() == null ? 0 : this.getCodestcivil()
						.hashCode());
		result = 37 * result + this.getCodfilial();
		result = 37 * result + this.getCodemp();
		return result;
	}

}
