package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tktipoimp generated by hbm2java
 */
@Entity
@Table(name = "TKTIPOIMP")
public class Tktipoimp implements java.io.Serializable {

	private TktipoimpId id;
	private String desctpimp;
	private char transbintpimp;
	private char cseptpimp;
	private char enterlntpimp;
	private String septpimp;
	private String layouttpimp;
	private Short delcrttpimp;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set tkcontatos = new HashSet(0);

	public Tktipoimp() {
	}

	public Tktipoimp(TktipoimpId id, String desctpimp, char transbintpimp,
			char cseptpimp, char enterlntpimp, Date dtins, Date hins,
			String idusuins) {
		this.id = id;
		this.desctpimp = desctpimp;
		this.transbintpimp = transbintpimp;
		this.cseptpimp = cseptpimp;
		this.enterlntpimp = enterlntpimp;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Tktipoimp(TktipoimpId id, String desctpimp, char transbintpimp,
			char cseptpimp, char enterlntpimp, String septpimp,
			String layouttpimp, Short delcrttpimp, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt,
			Set tkcontatos) {
		this.id = id;
		this.desctpimp = desctpimp;
		this.transbintpimp = transbintpimp;
		this.cseptpimp = cseptpimp;
		this.enterlntpimp = enterlntpimp;
		this.septpimp = septpimp;
		this.layouttpimp = layouttpimp;
		this.delcrttpimp = delcrttpimp;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.tkcontatos = tkcontatos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codtpimp", column = @Column(name = "CODTPIMP", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public TktipoimpId getId() {
		return this.id;
	}

	public void setId(TktipoimpId id) {
		this.id = id;
	}

	@Column(name = "DESCTPIMP", nullable = false, length = 50)
	public String getDesctpimp() {
		return this.desctpimp;
	}

	public void setDesctpimp(String desctpimp) {
		this.desctpimp = desctpimp;
	}

	@Column(name = "TRANSBINTPIMP", nullable = false, length = 1)
	public char getTransbintpimp() {
		return this.transbintpimp;
	}

	public void setTransbintpimp(char transbintpimp) {
		this.transbintpimp = transbintpimp;
	}

	@Column(name = "CSEPTPIMP", nullable = false, length = 1)
	public char getCseptpimp() {
		return this.cseptpimp;
	}

	public void setCseptpimp(char cseptpimp) {
		this.cseptpimp = cseptpimp;
	}

	@Column(name = "ENTERLNTPIMP", nullable = false, length = 1)
	public char getEnterlntpimp() {
		return this.enterlntpimp;
	}

	public void setEnterlntpimp(char enterlntpimp) {
		this.enterlntpimp = enterlntpimp;
	}

	@Column(name = "SEPTPIMP", length = 10)
	public String getSeptpimp() {
		return this.septpimp;
	}

	public void setSeptpimp(String septpimp) {
		this.septpimp = septpimp;
	}

	@Column(name = "LAYOUTTPIMP", length = 256)
	public String getLayouttpimp() {
		return this.layouttpimp;
	}

	public void setLayouttpimp(String layouttpimp) {
		this.layouttpimp = layouttpimp;
	}

	@Column(name = "DELCRTTPIMP")
	public Short getDelcrttpimp() {
		return this.delcrttpimp;
	}

	public void setDelcrttpimp(Short delcrttpimp) {
		this.delcrttpimp = delcrttpimp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tktipoimp")
	public Set getTkcontatos() {
		return this.tkcontatos;
	}

	public void setTkcontatos(Set tkcontatos) {
		this.tkcontatos = tkcontatos;
	}
*/
}
