package org.freedom.persist.entity;

// Generated 14/04/2014 10:17:08 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vdgruporc generated by hbm2java
 */
public class Vdgruporc implements java.io.Serializable {

	private VdgruporcId id;
	private Sgfilial sgfilial;
	private String descgo;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set vditgruporcs = new HashSet(0);

	public Vdgruporc() {
	}

	public Vdgruporc(VdgruporcId id, Sgfilial sgfilial, String descgo,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.descgo = descgo;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Vdgruporc(VdgruporcId id, Sgfilial sgfilial, String descgo,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt, Set vditgruporcs) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.descgo = descgo;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.vditgruporcs = vditgruporcs;
	}

	public VdgruporcId getId() {
		return this.id;
	}

	public void setId(VdgruporcId id) {
		this.id = id;
	}

	public Sgfilial getSgfilial() {
		return this.sgfilial;
	}

	public void setSgfilial(Sgfilial sgfilial) {
		this.sgfilial = sgfilial;
	}

	public String getDescgo() {
		return this.descgo;
	}

	public void setDescgo(String descgo) {
		this.descgo = descgo;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	public Set getVditgruporcs() {
		return this.vditgruporcs;
	}

	public void setVditgruporcs(Set vditgruporcs) {
		this.vditgruporcs = vditgruporcs;
	}

}
