package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vditvendavditcontr generated by hbm2java
 */
@Entity
@Table(name = "VDITVENDAVDITCONTR")
public class Vditvendavditcontr implements java.io.Serializable {

	private VditvendavditcontrId id;
	private Vditvenda vditvenda;
	private Vdcontrato vdcontrato;
	private short coditcontr;
	private Date dtiniapura;
	private Date dtfinapura;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Vditvendavditcontr() {
	}

	public Vditvendavditcontr(Vditvenda vditvenda, Vdcontrato vdcontrato,
			short coditcontr, Date dtiniapura, Date dtfinapura, Date dtins,
			Date hins, String idusuins) {
		this.vditvenda = vditvenda;
		this.vdcontrato = vdcontrato;
		this.coditcontr = coditcontr;
		this.dtiniapura = dtiniapura;
		this.dtfinapura = dtfinapura;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Vditvendavditcontr(Vditvenda vditvenda, Vdcontrato vdcontrato,
			short coditcontr, Date dtiniapura, Date dtfinapura, Date dtins,
			Date hins, String idusuins, Date dtalt, Date halt, String idusualt) {
		this.vditvenda = vditvenda;
		this.vdcontrato = vdcontrato;
		this.coditcontr = coditcontr;
		this.dtiniapura = dtiniapura;
		this.dtfinapura = dtfinapura;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codvenda", column = @Column(name = "CODVENDA", nullable = false)),
			@AttributeOverride(name = "coditvenda", column = @Column(name = "CODITVENDA", nullable = false)),
			@AttributeOverride(name = "tipovenda", column = @Column(name = "TIPOVENDA", nullable = false, length = 1)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public VditvendavditcontrId getId() {
		return this.id;
	}

	public void setId(VditvendavditcontrId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Vditvenda getVditvenda() {
		return this.vditvenda;
	}

	public void setVditvenda(Vditvenda vditvenda) {
		this.vditvenda = vditvenda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODCONTR", referencedColumnName = "CODCONTR", nullable = false),
			@JoinColumn(name = "CODFILIALCT", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPCT", referencedColumnName = "CODEMP", nullable = false) })
	public Vdcontrato getVdcontrato() {
		return this.vdcontrato;
	}

	public void setVdcontrato(Vdcontrato vdcontrato) {
		this.vdcontrato = vdcontrato;
	}

	@Column(name = "CODITCONTR", nullable = false)
	public short getCoditcontr() {
		return this.coditcontr;
	}

	public void setCoditcontr(short coditcontr) {
		this.coditcontr = coditcontr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINIAPURA", nullable = false, length = 10)
	public Date getDtiniapura() {
		return this.dtiniapura;
	}

	public void setDtiniapura(Date dtiniapura) {
		this.dtiniapura = dtiniapura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTFINAPURA", nullable = false, length = 10)
	public Date getDtfinapura() {
		return this.dtfinapura;
	}

	public void setDtfinapura(Date dtfinapura) {
		this.dtfinapura = dtfinapura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 128)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 128)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
