package org.freedom.persist.entity;

// Generated 14/04/2014 10:17:08 by Hibernate Tools 4.0.0

/**
 * VdmotoristaId generated by hbm2java
 */
public class VdmotoristaId implements java.io.Serializable {

	private int codmot;
	private short codfilial;
	private int codemp;

	public VdmotoristaId() {
	}

	public VdmotoristaId(int codmot, short codfilial, int codemp) {
		this.codmot = codmot;
		this.codfilial = codfilial;
		this.codemp = codemp;
	}

	public int getCodmot() {
		return this.codmot;
	}

	public void setCodmot(int codmot) {
		this.codmot = codmot;
	}

	public short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(short codfilial) {
		this.codfilial = codfilial;
	}

	public int getCodemp() {
		return this.codemp;
	}

	public void setCodemp(int codemp) {
		this.codemp = codemp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdmotoristaId))
			return false;
		VdmotoristaId castOther = (VdmotoristaId) other;

		return (this.getCodmot() == castOther.getCodmot())
				&& (this.getCodfilial() == castOther.getCodfilial())
				&& (this.getCodemp() == castOther.getCodemp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodmot();
		result = 37 * result + this.getCodfilial();
		result = 37 * result + this.getCodemp();
		return result;
	}

}
