package org.freedom.persist.entity;

// Generated 10/05/2014 10:27:15 by Hibernate Tools 4.0.0

/**
 * Vwcustoproj01 generated by hbm2java
 */
public class Vwcustoproj01 implements java.io.Serializable {

	private Vwcustoproj01Id id;

	public Vwcustoproj01() {
	}

	public Vwcustoproj01(Vwcustoproj01Id id) {
		this.id = id;
	}

	public Vwcustoproj01Id getId() {
		return this.id;
	}

	public void setId(Vwcustoproj01Id id) {
		this.id = id;
	}

}
