package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwprodPrecoCusto generated by hbm2java
 */
@Entity
@Table(name = "VWPROD_PRECO_CUSTO")
public class VwprodPrecoCusto implements java.io.Serializable {

	private VwprodPrecoCustoId id;

	public VwprodPrecoCusto() {
	}

	public VwprodPrecoCusto(VwprodPrecoCustoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "refprod", column = @Column(name = "REFPROD", length = 20)),
			@AttributeOverride(name = "codsecao", column = @Column(name = "CODSECAO", length = 13)),
			@AttributeOverride(name = "descprod", column = @Column(name = "DESCPROD", length = 100)),
			@AttributeOverride(name = "precobaseprod", column = @Column(name = "PRECOBASEPROD", precision = 15, scale = 5)),
			@AttributeOverride(name = "custo", column = @Column(name = "CUSTO", precision = 0, scale = 5)) })
	public VwprodPrecoCustoId getId() {
		return this.id;
	}

	public void setId(VwprodPrecoCustoId id) {
		this.id = id;
	}

}
