SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'localhost:c:/opt/firebird/dados/desenv/freedom.fdb' PAGE_SIZE 16384 DEFAULT CHARACTER SET WIN1252 COLLATION WIN_PTBR;

/*  Character sets */
ALTER CHARACTER SET WIN1252 SET DEFAULT COLLATION WIN_PTBR;
