/* Server version: LI-V6.3.3.4870 Firebird 1.5 
   SQLDialect: 3. ODS: 10.1. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 75 (300 Kb). Read-only: False. */
SET SQL DIALECT 3;

SET AUTODDL ON;

ALTER TABLE ATATENDIMENTO ADD CONCLUICHAMADO CHAR DEFAULT 'N' NOT NULL;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se o atendimento deve concluir o chamado'
WHERE RDB$RELATION_NAME = 'ATATENDIMENTO' AND RDB$FIELD_NAME = 'CONCLUICHAMADO';

ALTER TABLE CRCHAMADO ADD EMATENDIMENTO CHAR DEFAULT 'N' NOT NULL;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se o chamado está sendo atendido neste momento.'
WHERE RDB$RELATION_NAME = 'CRCHAMADO' AND RDB$FIELD_NAME = 'EMATENDIMENTO';

ALTER TABLE FNITPAGAR ADD EMMANUT CHAR DEFAULT 'N' NOT NULL;

ALTER TABLE FNPAGAR ADD EMMANUT CHAR DEFAULT 'N' NOT NULL;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'P1 - Pendente
PL - Pagamento parcial
PP - Pagamento total
CP - Cancelado'
WHERE RDB$RELATION_NAME = 'FNITPAGAR' AND RDB$FIELD_NAME = 'STATUSITPAG';

/* Alter Procedure... */
/* Alter (ATADICATENDIMENTOCLISP) */
SET TERM ^ ;

ALTER PROCEDURE ATADICATENDIMENTOCLISP(ICODTIPOATENDO INTEGER,
ICODATEND INTEGER,
ICODSETOR INTEGER,
ICODEMP INTEGER,
ICODFILIAL INTEGER,
IDOC INTEGER,
DATAATENDO DATE,
DATAATENDOFIN DATE,
HORAATENDO TIME,
HORAATENDOFIN TIME,
OBSATENDO VARCHAR(10000),
CODEMPCL INTEGER,
CODFILIALCL SMALLINT,
CODCLI INTEGER,
CODEMPCT INTEGER,
CODFILIALCT INTEGER,
CODCONTR INTEGER,
CODITCONTR INTEGER,
CODREC INTEGER,
NPARCITREC INTEGER,
CODEMPCH INTEGER,
CODFILIALCH SMALLINT,
CODCHAMADO INTEGER,
OBSINTERNO VARCHAR(10000),
CONCLUICHAMADO CHAR)
 AS
declare variable icodatendo integer;
declare variable ifilialatendo integer;
declare variable ifilialtipoatendo integer;
declare variable ifilialatend integer;
declare variable ifilialsetor integer;
BEGIN
  SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'ATATENDIMENTO') INTO IFILIALATENDO;
  SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'ATTIPOATENDO') INTO IFILIALTIPOATENDO;
  SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'ATATENDENTE') INTO IFILIALATEND;
  SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'ATSETOR') INTO IFILIALSETOR;
  SELECT ISEQ FROM SPGERANUM(:ICODEMP,:IFILIALATENDO,'AT') INTO ICODATENDO;

  INSERT INTO ATATENDIMENTO (
    CODEMP,CODFILIAL,CODATENDO,CODEMPTO,
    CODFILIALTO,CODTPATENDO,CODEMPAE,
    CODFILIALAE,CODATEND,CODEMPSA,CODFILIALSA,
    CODSETAT,STATUSATENDO,IDUSU,CODEMPUS,CODFILIALUS,DOCATENDO, DATAATENDO,
    DATAATENDOFIN, HORAATENDO, HORAATENDOFIN, OBSATENDO, CODEMPCL, CODFILIALCL, CODCLI, CODEMPCT, CODFILIALCT,
    CODCONTR, CODITCONTR, CODEMPCH, CODFILIALCH, CODCHAMADO, obsinterno, CONCLUICHAMADO )

  VALUES
  (
    :ICODEMP,:IFILIALATENDO,:ICODATENDO,:ICODEMP,
    :IFILIALTIPOATENDO,:ICODTIPOATENDO,:ICODEMP,
    :IFILIALATEND,:ICODATEND,:ICODEMP,:IFILIALSETOR,
    :ICODSETOR,'AA',lower(USER),:ICODEMP,:ICODFILIAL,:IDOC,
    :DATAATENDO,:DATAATENDOFIN,:HORAATENDO,:HORAATENDOFIN,:OBSATENDO,:CODEMPCL,
    :CODFILIALCL,:CODCLI, :CODEMPCT, :CODFILIALCT, :CODCONTR, :CODITCONTR, :codempch, :codfilialch, :codchamado, :obsinterno, :CONCLUICHAMADO
  );

  -- Caso o atendimento tenha vinculo com o contas a receber
  IF(CODREC IS NOT NULL AND NPARCITREC IS NOT NULL) THEN
  BEGIN
    INSERT INTO ATATENDIMENTOITREC (CODEMP,CODFILIAL,CODATENDO,CODEMPIR,CODFILIALIR,CODREC,NPARCITREC) VALUES
        (:ICODEMP,:ICODFILIAL,:ICODATENDO,:ICODEMP,:ICODFILIAL,:CODREC,:NPARCITREC);
  END



END
^

/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.2.6 (28/06/2010)';
    suspend;
end
^

/* Create trigger... */
CREATE TRIGGER ATATENDIMENTOTGAU FOR ATATENDIMENTO
ACTIVE AFTER UPDATE POSITION 0 
AS
declare variable statuschamado char(2);
declare variable novostatuschamado char(2);
begin
   -- Buscando status do chamado;
   select status from crchamado where codemp=new.codempch and codfilial=new.codfilialch and codchamado=new.codchamado
   into :statuschamado;

    -- Atualiza status do chamado
    -- Outros status devem ser implementados futuramente.
    if(:statuschamado is not null) then
        begin
            novostatuschamado = 'EA';

            if(new.concluichamado='S') then
            begin
                novostatuschamado = 'CO';
            end

            update crchamado set status=:novostatuschamado, ematendimento='S'
            where codemp=new.codempch and codfilial=new.codfilialch and codchamado=new.codchamado;

        end
end
^


/* Alter exist trigger... */
ALTER TRIGGER ATATENDIMENTOTGAI
AS
declare variable statuschamado char(2);
declare variable novostatuschamado char(2);
begin
    -- Verifica se o atendimento é para um chamado
    if (new.codchamado is not null) then
    begin
        -- Buscando status do chamado;
        select status from crchamado where codemp=new.codempch and codfilial=new.codfilialch and codchamado=new.codchamado
        into :statuschamado;

        -- Atualiza o status do chamado...
        -- Outros status devem ser implementados futuramente.
        if(:statuschamado is not null) then
        begin
            novostatuschamado = 'EA';

            if(new.concluichamado='S') then
            begin
                novostatuschamado = 'CO';
            end

            update crchamado set status=:novostatuschamado, ematendimento='S'
            where codemp=new.codempch and codfilial=new.codfilialch and codchamado=new.codchamado;

        end

    end
end
^

/* Alter exist trigger... */
ALTER TRIGGER FNITPAGARTGAU
AS

BEGIN
  IF ( not ( (new.EMMANUT='S') or ( (old.EMMANUT='S') and (old.EMMANUT is not null)) ) ) THEN
  BEGIN

     UPDATE FNPAGAR SET VLRPAG = VLRPAG - old.VLRITPAG + new.VLRITPAG,
         VLRDESCPAG = VLRDESCPAG - old.VLRDESCITPAG + new.VLRDESCITPAG,
         VLRMULTAPAG = VLRMULTAPAG - old.VLRMULTAITPAG + new.VLRMULTAITPAG,
         VLRJUROSPAG = VLRJUROSPAG - old.VLRJUROSITPAG + new.VLRJUROSITPAG,
         VLRDEVPAG = VLRDEVPAG - old.VLRDEVITPAG + new.VLRDEVITPAG,
         VLRADICPAG = VLRADICPAG - old.VLRADICITPAG + new.VLRADICITPAG,
         VLRPARCPAG = VLRPARCPAG - old.VLRPARCITPAG + new.VLRPARCITPAG,
         VLRPAGOPAG = VLRPAGOPAG - old.VLRPAGOITPAG + new.VLRPAGOITPAG,
         VLRAPAGPAG = VLRAPAGPAG - old.VLRAPAGITPAG + new.VLRAPAGITPAG
         WHERE CODPAG=new.CODPAG
              AND CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL;
   END
END
^

/* Alter exist trigger... */
ALTER TRIGGER FNITPAGARTGBU
AS
  DECLARE VARIABLE IFILIALPAG INTEGER;
  DECLARE VARIABLE ICODFOR INTEGER;
  DECLARE VARIABLE ICODEMPFR INTEGER;
  DECLARE VARIABLE ICODFILIALFR INTEGER;
BEGIN
  new.DTALT=cast('now' AS DATE);
  new.IDUSUALT=USER;
  new.HALT = cast('now' AS TIME);
  IF ( new.EMMANUT IS NULL ) THEN
  BEGIN
      new.EMMANUT = 'S';
  END

  IF ( not ( (new.EMMANUT='S') or ( (old.EMMANUT='S') and (old.EMMANUT is not null)) ) ) THEN
  BEGIN

     SELECT ICODFILIAL FROM SGRETFILIAL(new.CODEMP,'FNPAGAR') INTO IFILIALPAG;
     IF ((old.STATUSITPAG IN ('PP','PL') )  AND (new.STATUSITPAG='P1') ) THEN
     BEGIN
       DELETE FROM FNLANCA WHERE CODPAG=new.CODPAG AND NPARCPAG=new.NPARCPAG
              AND CODEMPPG=new.CODEMP AND CODFILIALPG = new.CODFILIAL
              AND CODEMP=new.CODEMP AND CODFILIAL=:IFILIALPAG;
       new.VLRPAGOITPAG = 0;
       new.DTPAGOITPAG = NULL;
     END
     ELSE IF ( (old.STATUSITPAG='P1') AND ( new.STATUSITPAG='CP' ) ) THEN
     BEGIN
        IF ( (new.OBSITPAG IS NULL) OR (rtrim(new.OBSITPAG)='') ) THEN
        BEGIN
           EXCEPTION FNITPAGAREX01;
        END
        new.VLRCANCITPAG = new.VLRAPAGITPAG;
        new.VLRPARCITPAG = 0;
        new.VLRDESCITPAG = 0;
        new.VLRJUROSITPAG = 0;
        new.VLRDEVITPAG = 0;
        new.VLRITPAG = 0;
     END

     new.VLRITPAG = new.VLRPARCITPAG - new.VLRDESCITPAG - new.VLRDEVITPAG + new.VLRJUROSITPAG +
     new.VLRMULTAITPAG + new.VLRADICITPAG;
     new.VLRAPAGITPAG = new.VLRITPAG - new.VLRPAGOITPAG;
  
     if (new.VLRAPAGITPAG < 0) then /* se o valor a pagar for menor que zero */
       new.VLRAPAGITPAG = 0;  /* então valor a pagar será zero */
     if ( (new.VLRAPAGITPAG=0) AND (new.VLRITPAG>0) ) then /* se o valor a pagar for igual a zero e existir valor na parcela*/
       new.STATUSITPAG = 'PP';  /* então o status será PP(pagamento completo) */
     else if ( (new.VLRPAGOITPAG>0) AND (new.VLRITPAG>0) ) then /* caso contrário e o valor pago maior que zero e existir valor na parcela*/
       new.STATUSITPAG = 'PL'; /*  então o status será PL(pagamento parcial) */

     /* faz o lançamento */
     SELECT CODFOR,CODEMPFR,CODFILIALFR FROM FNPAGAR WHERE CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL AND CODPAG=new.CODPAG
       INTO ICODFOR,ICODEMPFR,ICODFILIALFR;
     IF ((old.STATUSITPAG='P1' AND new.STATUSITPAG in ('PP','PL'))
           OR (old.STATUSITPAG in ('PP','PL') AND new.STATUSITPAG in ('PP','PL') AND
           new.VLRPAGOITPAG > 0))THEN
     BEGIN
       EXECUTE PROCEDURE FNADICLANCASP02(new.CodPag,new.NParcPag,new.NumConta,new.CODEMPCA,new.CODFILIALCA,:ICODFOR,:ICODEMPFR,:ICODFILIALFR,
                              new.CodPlan,new.CODEMPPN,new.CODFILIALPN,new.AnoCC,new.CodCC,new.CODEMPCC,new.CODFILIALCC,
                              new.DtPagoItPag,new.DocLancaItPag,new.ObsItPag,new.VlrPagoItPag,new.CODEMP,new.CODFILIAL,new.vlrjurositpag,new.vlrdescitpag);

       /* Altera o valor pago e o valor a pagar */
       new.VLRPAGOITPAG = new.VLRPAGOITPAG + old.VLRPAGOITPAG;
       new.VLRAPAGITPAG = new.VLRITPAG - new.VLRPAGOITPAG;

       if (new.VLRAPAGITPAG < 0) then /* se o valor a pagar for menor que zero */
         new.VLRAPAGITPAG = 0;  /* então valor a pagar será zero */

       if (new.VLRAPAGITPAG=0) then /* se o valor a pagar for igual a zero */
         new.STATUSITPAG = 'PP';  /* então o status será PP(pagamento completo) */
       else if (new.VLRPAGOITPAG>0) then /* caso contrário e o valor pago maior que zero */
         new.STATUSITPAG = 'PL'; /*  então o status será PL(pagamento parcial) */

     END
     ELSE IF ((old.STATUSITPAG='PP') AND (new.STATUSITPAG='PP')) THEN
     BEGIN
        EXCEPTION FNPAGAREX01;
     END

   END

END
^

/* Alter exist trigger... */
ALTER TRIGGER FNPAGARTGBU
as
begin
  new.DTALT=cast('now' AS DATE);
  new.IDUSUALT=USER;
  new.HALT = cast('now' AS TIME);
  IF (new.EMMANUT IS NULL) THEN
     new.EMMANUT='N';
  /* Trigger Text */
end
^

SET TERM ; ^

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODATENDO POSITION 3;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODCONV POSITION 4;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPCV POSITION 5;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALCV POSITION 6;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPTO POSITION 7;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALTO POSITION 8;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODTPATENDO POSITION 9;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPAE POSITION 10;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALAE POSITION 11;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODATEND POSITION 12;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPSA POSITION 13;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALSA POSITION 14;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODSETAT POSITION 15;

ALTER TABLE ATATENDIMENTO ALTER COLUMN DATAATENDO POSITION 16;

ALTER TABLE ATATENDIMENTO ALTER COLUMN HORAATENDO POSITION 17;

ALTER TABLE ATATENDIMENTO ALTER COLUMN DATAATENDOFIN POSITION 18;

ALTER TABLE ATATENDIMENTO ALTER COLUMN HORAATENDOFIN POSITION 19;

ALTER TABLE ATATENDIMENTO ALTER COLUMN OBSATENDO POSITION 20;

ALTER TABLE ATATENDIMENTO ALTER COLUMN OBSINTERNO POSITION 21;

ALTER TABLE ATATENDIMENTO ALTER COLUMN STATUSATENDO POSITION 22;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPCL POSITION 23;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALCL POSITION 24;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODCLI POSITION 25;

ALTER TABLE ATATENDIMENTO ALTER COLUMN IDUSU POSITION 26;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPUS POSITION 27;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALUS POSITION 28;

ALTER TABLE ATATENDIMENTO ALTER COLUMN DOCATENDO POSITION 29;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPCT POSITION 30;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALCT POSITION 31;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODCONTR POSITION 32;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODITCONTR POSITION 33;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPCA POSITION 34;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALCA POSITION 35;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODCLASATENDO POSITION 36;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODEMPCH POSITION 37;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODFILIALCH POSITION 38;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CODCHAMADO POSITION 39;

ALTER TABLE ATATENDIMENTO ALTER COLUMN CONCLUICHAMADO POSITION 40;

ALTER TABLE ATATENDIMENTO ALTER COLUMN DTINS POSITION 41;

ALTER TABLE ATATENDIMENTO ALTER COLUMN HINS POSITION 42;

ALTER TABLE ATATENDIMENTO ALTER COLUMN IDUSUINS POSITION 43;

ALTER TABLE ATATENDIMENTO ALTER COLUMN DTALT POSITION 44;

ALTER TABLE ATATENDIMENTO ALTER COLUMN HALT POSITION 45;

ALTER TABLE ATATENDIMENTO ALTER COLUMN IDUSUALT POSITION 46;

ALTER TABLE CRCHAMADO ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE CRCHAMADO ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE CRCHAMADO ALTER COLUMN CODCHAMADO POSITION 3;

ALTER TABLE CRCHAMADO ALTER COLUMN DESCCHAMADO POSITION 4;

ALTER TABLE CRCHAMADO ALTER COLUMN DETCHAMADO POSITION 5;

ALTER TABLE CRCHAMADO ALTER COLUMN OBSCHAMADO POSITION 6;

ALTER TABLE CRCHAMADO ALTER COLUMN CODEMPCL POSITION 7;

ALTER TABLE CRCHAMADO ALTER COLUMN CODFILIALCL POSITION 8;

ALTER TABLE CRCHAMADO ALTER COLUMN CODCLI POSITION 9;

ALTER TABLE CRCHAMADO ALTER COLUMN SOLICITANTE POSITION 10;

ALTER TABLE CRCHAMADO ALTER COLUMN PRIORIDADE POSITION 11;

ALTER TABLE CRCHAMADO ALTER COLUMN CODEMPTC POSITION 12;

ALTER TABLE CRCHAMADO ALTER COLUMN CODFILIALTC POSITION 13;

ALTER TABLE CRCHAMADO ALTER COLUMN CODTPCHAMADO POSITION 14;

ALTER TABLE CRCHAMADO ALTER COLUMN STATUS POSITION 15;

ALTER TABLE CRCHAMADO ALTER COLUMN DTCHAMADO POSITION 16;

ALTER TABLE CRCHAMADO ALTER COLUMN DTPREVISAO POSITION 17;

ALTER TABLE CRCHAMADO ALTER COLUMN QTDHORASPREVISAO POSITION 18;

ALTER TABLE CRCHAMADO ALTER COLUMN DTCONCLUSAO POSITION 19;

ALTER TABLE CRCHAMADO ALTER COLUMN CODEMPAE POSITION 20;

ALTER TABLE CRCHAMADO ALTER COLUMN CODFILIALAE POSITION 21;

ALTER TABLE CRCHAMADO ALTER COLUMN CODATEND POSITION 22;

ALTER TABLE CRCHAMADO ALTER COLUMN EMATENDIMENTO POSITION 23;

ALTER TABLE CRCHAMADO ALTER COLUMN DTINS POSITION 24;

ALTER TABLE CRCHAMADO ALTER COLUMN HINS POSITION 25;

ALTER TABLE CRCHAMADO ALTER COLUMN IDUSUINS POSITION 26;

ALTER TABLE CRCHAMADO ALTER COLUMN DTALT POSITION 27;

ALTER TABLE CRCHAMADO ALTER COLUMN HALT POSITION 28;

ALTER TABLE CRCHAMADO ALTER COLUMN IDUSUALT POSITION 29;

ALTER TABLE FNITPAGAR ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE FNITPAGAR ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE FNITPAGAR ALTER COLUMN CODPAG POSITION 3;

ALTER TABLE FNITPAGAR ALTER COLUMN NPARCPAG POSITION 4;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRITPAG POSITION 5;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRDESCITPAG POSITION 6;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRMULTAITPAG POSITION 7;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRJUROSITPAG POSITION 8;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRDEVITPAG POSITION 9;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRPARCITPAG POSITION 10;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRPAGOITPAG POSITION 11;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRAPAGITPAG POSITION 12;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRADICITPAG POSITION 13;

ALTER TABLE FNITPAGAR ALTER COLUMN VLRCANCITPAG POSITION 14;

ALTER TABLE FNITPAGAR ALTER COLUMN DTITPAG POSITION 15;

ALTER TABLE FNITPAGAR ALTER COLUMN DTVENCITPAG POSITION 16;

ALTER TABLE FNITPAGAR ALTER COLUMN DTPAGOITPAG POSITION 17;

ALTER TABLE FNITPAGAR ALTER COLUMN STATUSITPAG POSITION 18;

ALTER TABLE FNITPAGAR ALTER COLUMN CODEMPCA POSITION 19;

ALTER TABLE FNITPAGAR ALTER COLUMN CODFILIALCA POSITION 20;

ALTER TABLE FNITPAGAR ALTER COLUMN NUMCONTA POSITION 21;

ALTER TABLE FNITPAGAR ALTER COLUMN CODEMPPN POSITION 22;

ALTER TABLE FNITPAGAR ALTER COLUMN CODFILIALPN POSITION 23;

ALTER TABLE FNITPAGAR ALTER COLUMN CODPLAN POSITION 24;

ALTER TABLE FNITPAGAR ALTER COLUMN DOCLANCAITPAG POSITION 25;

ALTER TABLE FNITPAGAR ALTER COLUMN OBSITPAG POSITION 26;

ALTER TABLE FNITPAGAR ALTER COLUMN FLAG POSITION 27;

ALTER TABLE FNITPAGAR ALTER COLUMN CODEMPCC POSITION 28;

ALTER TABLE FNITPAGAR ALTER COLUMN CODFILIALCC POSITION 29;

ALTER TABLE FNITPAGAR ALTER COLUMN ANOCC POSITION 30;

ALTER TABLE FNITPAGAR ALTER COLUMN CODCC POSITION 31;

ALTER TABLE FNITPAGAR ALTER COLUMN CODEMPTC POSITION 32;

ALTER TABLE FNITPAGAR ALTER COLUMN CODFILIALTC POSITION 33;

ALTER TABLE FNITPAGAR ALTER COLUMN CODTIPOCOB POSITION 34;

ALTER TABLE FNITPAGAR ALTER COLUMN EMMANUT POSITION 35;

ALTER TABLE FNITPAGAR ALTER COLUMN DTINS POSITION 36;

ALTER TABLE FNITPAGAR ALTER COLUMN IDUSUINS POSITION 37;

ALTER TABLE FNITPAGAR ALTER COLUMN DTALT POSITION 38;

ALTER TABLE FNITPAGAR ALTER COLUMN IDUSUALT POSITION 39;

ALTER TABLE FNITPAGAR ALTER COLUMN HINS POSITION 40;

ALTER TABLE FNITPAGAR ALTER COLUMN HALT POSITION 41;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE FNPAGAR ALTER COLUMN CODPAG POSITION 3;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPCP POSITION 4;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALCP POSITION 5;

ALTER TABLE FNPAGAR ALTER COLUMN CODCOMPRA POSITION 6;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPPG POSITION 7;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALPG POSITION 8;

ALTER TABLE FNPAGAR ALTER COLUMN CODPLANOPAG POSITION 9;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPFR POSITION 10;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALFR POSITION 11;

ALTER TABLE FNPAGAR ALTER COLUMN CODFOR POSITION 12;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPBO POSITION 13;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALBO POSITION 14;

ALTER TABLE FNPAGAR ALTER COLUMN CODBANCO POSITION 15;

ALTER TABLE FNPAGAR ALTER COLUMN VLRDESCPAG POSITION 16;

ALTER TABLE FNPAGAR ALTER COLUMN VLRMULTAPAG POSITION 17;

ALTER TABLE FNPAGAR ALTER COLUMN VLRJUROSPAG POSITION 18;

ALTER TABLE FNPAGAR ALTER COLUMN VLRDEVPAG POSITION 19;

ALTER TABLE FNPAGAR ALTER COLUMN VLRPARCPAG POSITION 20;

ALTER TABLE FNPAGAR ALTER COLUMN VLRPAGOPAG POSITION 21;

ALTER TABLE FNPAGAR ALTER COLUMN VLRAPAGPAG POSITION 22;

ALTER TABLE FNPAGAR ALTER COLUMN DATAPAG POSITION 23;

ALTER TABLE FNPAGAR ALTER COLUMN STATUSPAG POSITION 24;

ALTER TABLE FNPAGAR ALTER COLUMN DTQUITPAG POSITION 25;

ALTER TABLE FNPAGAR ALTER COLUMN DOCPAG POSITION 26;

ALTER TABLE FNPAGAR ALTER COLUMN VLRPAG POSITION 27;

ALTER TABLE FNPAGAR ALTER COLUMN NROPARCPAG POSITION 28;

ALTER TABLE FNPAGAR ALTER COLUMN OBSPAG POSITION 29;

ALTER TABLE FNPAGAR ALTER COLUMN VLRADICPAG POSITION 30;

ALTER TABLE FNPAGAR ALTER COLUMN FLAG POSITION 31;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPTC POSITION 32;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALTC POSITION 33;

ALTER TABLE FNPAGAR ALTER COLUMN CODTIPOCOB POSITION 34;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPCA POSITION 35;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALCA POSITION 36;

ALTER TABLE FNPAGAR ALTER COLUMN NUMCONTA POSITION 37;

ALTER TABLE FNPAGAR ALTER COLUMN EMMANUT POSITION 38;

ALTER TABLE FNPAGAR ALTER COLUMN DTINS POSITION 39;

ALTER TABLE FNPAGAR ALTER COLUMN HINS POSITION 40;

ALTER TABLE FNPAGAR ALTER COLUMN IDUSUINS POSITION 41;

ALTER TABLE FNPAGAR ALTER COLUMN DTALT POSITION 42;

ALTER TABLE FNPAGAR ALTER COLUMN HALT POSITION 43;

ALTER TABLE FNPAGAR ALTER COLUMN IDUSUALT POSITION 44;

/* Create(Add) Crant */
GRANT DELETE, INSERT, SELECT, UPDATE ON SGCNAE TO ADM;


