package org.freedom.modulos.crm.business.object;


public class ContratoVW {
	
	public enum EColContr { 
		INDICE, DESCRICAO, PREVGERAL, TOTALGERAL, TOTALCOBCLIGERAL, TOTALANT, TOTALCOBCLIANT, TOTALPER, TOTALCOBCLIPER , TIPO, IDX, CODCONTR, CODCONTRSC, CODITCONTR, CODTAREFA, CODTAREFAST,
		 
	}

}
