/* Server version: LI-V6.3.3.4870 Firebird 1.5 
   SQLDialect: 3. ODS: 10.1. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 75 (300 Kb). Read-only: False. */
SET SQL DIALECT 3;

SET AUTODDL ON;

/* Create Table... */
CREATE TABLE FNCHEQUE(CODEMP INTEGER NOT NULL,
CODFILIAL SMALLINT NOT NULL,
CODEMPBO INTEGER NOT NULL,
SEQCHEQ INTEGER NOT NULL,
CODFILIALBO SMALLINT NOT NULL,
CODBANC CHAR(3) NOT NULL,
AGENCIACHEQ VARCHAR(7) NOT NULL,
CONTACHEQ VARCHAR(10) NOT NULL,
NUMCHEQ INTEGER NOT NULL,
NOMEEMITCHEQ VARCHAR(1) NOT NULL,
NOMEFAVCHEQ VARCHAR(50) NOT NULL,
DTEMITCHEQ DATE DEFAULT 'today' NOT NULL,
DTVENCTOCHEQ DATE DEFAULT 'today' NOT NULL,
DTCOMPCHEQ DATE DEFAULT 'today' NOT NULL,
TIPOCHEQ CHAR(2) DEFAULT 'PF' NOT NULL,
PREDATCHEQ CHAR DEFAULT 'N',
SITCHEQ CHAR(2) DEFAULT 'CA' NOT NULL,
VLRCHEQ NUMERIC(15,5) DEFAULT 0 NOT NULL,
HISTCHEQ VARCHAR(500) NOT NULL,
CNPJEMITCHEQ VARCHAR(14),
CPFEMITCHEQ VARCHAR(11),
CNPJFAVCHEQ VARCHAR(14),
CPFFAVCHEQ VARCHAR(11),
DDDEMITCHEQ VARCHAR(4),
FONEEMITCHEQ VARCHAR(8),
DTINS DATE DEFAULT 'today' NOT NULL,
HINS TIME DEFAULT 'now' NOT NULL,
IDUSUINS VARCHAR(128) NOT NULL,
DTALT DATE DEFAULT 'today' NOT NULL,
HALT TIME DEFAULT 'now' NOT NULL,
IDUSUALT VARCHAR(128) DEFAULT 'user' NOT NULL);


UPDATE RDB$RELATIONS SET RDB$DESCRIPTION = 
'Tabela de cheques.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'CODEMP';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'CODFILIAL';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código empresa na tabela banco.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'CODEMPBO';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Sequencia.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'SEQCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial na tabela banco.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'CODFILIALBO';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código do banco.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'CODBANC';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Agência.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'AGENCIACHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Número da conta
'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'CONTACHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Número do cheque.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'NUMCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Nome do emitente.
'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'NOMEEMITCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Nome do favorecido.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'NOMEFAVCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Emissão'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'DTEMITCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Data de vencimento.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'DTVENCTOCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Data de compensação'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'DTCOMPCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Tipo de cheque.
PF - Pagamento de fornecedor;
RC - Recebimento de cliente.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'TIPOCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Cheque pré-datado (S/N)
'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'PREDATCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Situação do cheque.
CA - Cadastrado;
ED - Emitido;
CD - Compensado;
DV - Devolvido.
'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'SITCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Valor do cheque'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'VLRCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Histórico.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'HISTCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'DDD Tel. emitente.
'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'DDDEMITCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Telefone emitente.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'FONEEMITCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Data de inserção.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'DTINS';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Hora de inserção.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'HINS';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Ident. do usuário que inseriu.
'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'IDUSUINS';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Data de alteração.
'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'DTALT';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Hora de alteração.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'HALT';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Ident. usuário que alterou.'
WHERE RDB$RELATION_NAME = 'FNCHEQUE' AND RDB$FIELD_NAME = 'IDUSUALT';

CREATE TABLE FNTALAOCHEQ(CODEMP INTEGER NOT NULL,
CODFILIAL SMALLINT NOT NULL,
NUMCONTA CHAR(10) NOT NULL,
SEQTALAO SMALLINT NOT NULL,
DTTALAO DATE DEFAULT 'today' NOT NULL,
CHEQINITALAO INTEGER DEFAULT 0 NOT NULL,
CHEQFIMTALAO INTEGER DEFAULT 1 NOT NULL,
CHEQATUALTALAO INTEGER DEFAULT 1 NOT NULL,
ATIVOTALAO CHAR DEFAULT 'S' NOT NULL,
DTINS DATE DEFAULT 'today' NOT NULL,
HINS TIME DEFAULT 'now' NOT NULL,
IDUSUINS VARCHAR(128) DEFAULT 'USER' NOT NULL,
DTALT DATE DEFAULT 'today' NOT NULL,
HALT TIME DEFAULT 'now' NOT NULL,
IDUSUALT VARCHAR(128) DEFAULT 'USER' NOT NULL);


UPDATE RDB$RELATIONS SET RDB$DESCRIPTION = 
'Tabela de talonário de cheques.'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'CODEMP';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial.'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'CODFILIAL';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Número da conta'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'NUMCONTA';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Sequencia do talão.'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'SEQTALAO';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Data do talão.'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'DTTALAO';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Número do cheque inicial.'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'CHEQINITALAO';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Número final do cheque.'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'CHEQFIMTALAO';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Último cheque impresso.'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'CHEQATUALTALAO';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Talonário ativo (S/N).'
WHERE RDB$RELATION_NAME = 'FNTALAOCHEQ' AND RDB$FIELD_NAME = 'ATIVOTALAO';

CREATE TABLE RHTABELAINSS(CODTABINSS INTEGER NOT NULL,
TETO NUMERICDN NOT NULL,
ALIQUOTA NUMERICDN NOT NULL,
DTINS DATE DEFAULT 'now' NOT NULL,
HINS TIME DEFAULT 'now' NOT NULL,
IDUSUINS CHAR(8) DEFAULT USER NOT NULL,
DTALT DATE DEFAULT 'now',
HALT TIME DEFAULT 'now',
IDUSUALT CHAR(8) DEFAULT USER);


CREATE TABLE RHTABELAIRRF(CODTABIRRF INTEGER NOT NULL,
TETO NUMERICDN NOT NULL,
ALIQUOTA NUMERICDN NOT NULL,
REDUCAODEPENDENTE NUMERICDN NOT NULL,
DEDUCAO NUMERICDN NOT NULL,
DTINS DATE DEFAULT 'now' NOT NULL,
HINS TIME DEFAULT 'now' NOT NULL,
IDUSUINS CHAR(8) DEFAULT USER NOT NULL,
DTALT DATE DEFAULT 'now',
HALT TIME DEFAULT 'now',
IDUSUALT CHAR(8) DEFAULT USER);


UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Dedução'
WHERE RDB$RELATION_NAME = 'RHTABELAIRRF' AND RDB$FIELD_NAME = 'DEDUCAO';


ALTER TABLE CPCOMPRA ADD CODEMPTC INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa na tabela tipo de cobrança.
'
WHERE RDB$RELATION_NAME = 'CPCOMPRA' AND RDB$FIELD_NAME = 'CODEMPTC';

ALTER TABLE CPCOMPRA ADD CODFILIALTC SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial na tabela tipo de cobrança.
'
WHERE RDB$RELATION_NAME = 'CPCOMPRA' AND RDB$FIELD_NAME = 'CODFILIALTC';

ALTER TABLE CPCOMPRA ADD CODTIPOCOB INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código do tipo de cobrança.
'
WHERE RDB$RELATION_NAME = 'CPCOMPRA' AND RDB$FIELD_NAME = 'CODTIPOCOB';

ALTER TABLE CPCOMPRA ADD CODEMPRM INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa do recebimento de mercadoria vinculado.'
WHERE RDB$RELATION_NAME = 'CPCOMPRA' AND RDB$FIELD_NAME = 'CODEMPRM';

ALTER TABLE CPCOMPRA ADD CODFILIALRM SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial do recebimento de mercadoria vinculado.'
WHERE RDB$RELATION_NAME = 'CPCOMPRA' AND RDB$FIELD_NAME = 'CODFILIALRM';

ALTER TABLE CPCOMPRA ADD TICKET INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Ticket do recebimento de mercadoria vinculado.'
WHERE RDB$RELATION_NAME = 'CPCOMPRA' AND RDB$FIELD_NAME = 'TICKET';

ALTER TABLE CPFORNECED ADD NRODEPENDFOR SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Número de dependes do fornecedor (pessoa física) (calculo de irrf)'
WHERE RDB$RELATION_NAME = 'CPFORNECED' AND RDB$FIELD_NAME = 'NRODEPENDFOR';

ALTER TABLE CPTIPOFOR ADD RETENCAOINSS CHAR;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se deve realizar a retenção do inss nos pagamentos (autonomo).'
WHERE RDB$RELATION_NAME = 'CPTIPOFOR' AND RDB$FIELD_NAME = 'RETENCAOINSS';

ALTER TABLE CPTIPOFOR ADD PERCBASEINSS NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Percentual de base de calculo do INSS.'
WHERE RDB$RELATION_NAME = 'CPTIPOFOR' AND RDB$FIELD_NAME = 'PERCBASEINSS';

ALTER TABLE CPTIPOFOR ADD RETENCAOOUTROS CHAR;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se deve calcular outras retenções agregadas ao INSS ex.: SEST/SENAT'
WHERE RDB$RELATION_NAME = 'CPTIPOFOR' AND RDB$FIELD_NAME = 'RETENCAOOUTROS';

ALTER TABLE CPTIPOFOR ADD PERCRETOUTROS NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Percentual de retenção de outros tributos agregados ao inss (SEST/SENAT)'
WHERE RDB$RELATION_NAME = 'CPTIPOFOR' AND RDB$FIELD_NAME = 'PERCRETOUTROS';

ALTER TABLE CPTIPOFOR ADD RETENCAOIRRF CHAR;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Indica se deve realizar a retenção do imposto de renda nos pagamentos (autonomo).'
WHERE RDB$RELATION_NAME = 'CPTIPOFOR' AND RDB$FIELD_NAME = 'RETENCAOIRRF';

ALTER TABLE CPTIPOFOR ADD PERCBASEIRRF NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Percentual de base de calculo do IRRF.'
WHERE RDB$RELATION_NAME = 'CPTIPOFOR' AND RDB$FIELD_NAME = 'PERCBASEIRRF';

ALTER TABLE EQRECMERC ADD MEDIAAMOSTRAGEM NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Media geral da amostragem.'
WHERE RDB$RELATION_NAME = 'EQRECMERC' AND RDB$FIELD_NAME = 'MEDIAAMOSTRAGEM';

ALTER TABLE EQRECMERC ADD RENDAAMOSTRAGEM SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Renda media geral da amostragem'
WHERE RDB$RELATION_NAME = 'EQRECMERC' AND RDB$FIELD_NAME = 'RENDAAMOSTRAGEM';

ALTER TABLE EQRECMERC ADD CODEMPAX INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa do almoxarifado de descarregamento da mercadoria.'
WHERE RDB$RELATION_NAME = 'EQRECMERC' AND RDB$FIELD_NAME = 'CODEMPAX';

ALTER TABLE EQRECMERC ADD CODFILIALAX SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial do almoxarifado de descarregamento da mercadoria.'
WHERE RDB$RELATION_NAME = 'EQRECMERC' AND RDB$FIELD_NAME = 'CODFILIALAX';

ALTER TABLE EQRECMERC ADD CODALMOX INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código do almoxarifado de descarregamento da mercadoria.'
WHERE RDB$RELATION_NAME = 'EQRECMERC' AND RDB$FIELD_NAME = 'CODALMOX';

ALTER TABLE FNBANCO ADD LAYOUTCHEQBANCO VARCHAR(1000);

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Layout de impressão de cheques.'
WHERE RDB$RELATION_NAME = 'FNBANCO' AND RDB$FIELD_NAME = 'LAYOUTCHEQBANCO';

ALTER TABLE FNPAGAR ADD VLRBASEIRRF NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Valor da base de calculo do IRRF (Pagamento de autonomos)'
WHERE RDB$RELATION_NAME = 'FNPAGAR' AND RDB$FIELD_NAME = 'VLRBASEIRRF';

ALTER TABLE FNPAGAR ADD VLRBASEINSS NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Valor da base de calculo do INSS (Pagamento de autonomos)'
WHERE RDB$RELATION_NAME = 'FNPAGAR' AND RDB$FIELD_NAME = 'VLRBASEINSS';

ALTER TABLE FNPAGAR ADD VLRRETIRRF NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Valor de desconto/retenção do IRRF (Pagamento de autonomos)'
WHERE RDB$RELATION_NAME = 'FNPAGAR' AND RDB$FIELD_NAME = 'VLRRETIRRF';

ALTER TABLE FNPAGAR ADD VLRRETINSS NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Valor do desconto/retenção do INSS (Pagamento de autonomos)'
WHERE RDB$RELATION_NAME = 'FNPAGAR' AND RDB$FIELD_NAME = 'VLRRETINSS';

ALTER TABLE FNTIPOCOB ADD CODEMPCT INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa na tabela de contas.
'
WHERE RDB$RELATION_NAME = 'FNTIPOCOB' AND RDB$FIELD_NAME = 'CODEMPCT';

ALTER TABLE FNTIPOCOB ADD CODFILIALCT SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial na tabela de contas.'
WHERE RDB$RELATION_NAME = 'FNTIPOCOB' AND RDB$FIELD_NAME = 'CODFILIALCT';

ALTER TABLE FNTIPOCOB ADD NUMCONTA VARCHAR(10);

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Número da conta para impressão de cheques.
'
WHERE RDB$RELATION_NAME = 'FNTIPOCOB' AND RDB$FIELD_NAME = 'NUMCONTA';

ALTER TABLE FNTIPOCOB ADD SEQTALAO SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Sequencia do talonário.'
WHERE RDB$RELATION_NAME = 'FNTIPOCOB' AND RDB$FIELD_NAME = 'SEQTALAO';

ALTER TABLE LFFRETE ADD CODEMPRM INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa do recebimento de mercadorias.'
WHERE RDB$RELATION_NAME = 'LFFRETE' AND RDB$FIELD_NAME = 'CODEMPRM';

ALTER TABLE LFFRETE ADD CODFILIALRM SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial do recebimento de mercadorias.'
WHERE RDB$RELATION_NAME = 'LFFRETE' AND RDB$FIELD_NAME = 'CODFILIALRM';

ALTER TABLE LFFRETE ADD TICKET INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Ticket do recebimento de mercadoria.'
WHERE RDB$RELATION_NAME = 'LFFRETE' AND RDB$FIELD_NAME = 'TICKET';

ALTER TABLE SGBAIRRO ADD VLRFRETE NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Valor de frete estimado para carga vinda deste bairro.'
WHERE RDB$RELATION_NAME = 'SGBAIRRO' AND RDB$FIELD_NAME = 'VLRFRETE';

ALTER TABLE SGBAIRRO ADD QTDFRETE NUMERICDN;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Quantidade referente ao valor de frete.'
WHERE RDB$RELATION_NAME = 'SGBAIRRO' AND RDB$FIELD_NAME = 'QTDFRETE';

ALTER TABLE SGPREFERE1 ADD CODEMPFT INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da empresa do tipo de fornecedor para transportadoras.'
WHERE RDB$RELATION_NAME = 'SGPREFERE1' AND RDB$FIELD_NAME = 'CODEMPFT';

ALTER TABLE SGPREFERE1 ADD CODFILIALFT SMALLINT;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da filial do tipo de fornecedor para transportadoras.'
WHERE RDB$RELATION_NAME = 'SGPREFERE1' AND RDB$FIELD_NAME = 'CODFILIALFT';

ALTER TABLE SGPREFERE1 ADD CODTIPOFORFT INTEGER;

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código do tipo de fornecedor para transportadoras.'
WHERE RDB$RELATION_NAME = 'SGPREFERE1' AND RDB$FIELD_NAME = 'CODTIPOFORFT';

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Valor dos descontos. (Deve ser incluidos as retenções se houverem)'
WHERE RDB$RELATION_NAME = 'FNPAGAR' AND RDB$FIELD_NAME = 'VLRDESCPAG';

/* Alter Field (Null / Not Null)... */
UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = NULL WHERE RDB$FIELD_NAME='CODEMPNT' AND RDB$RELATION_NAME='LFFRETE';

/* Alter Field (Null / Not Null)... */
UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = NULL WHERE RDB$FIELD_NAME='CODFILIALNT' AND RDB$RELATION_NAME='LFFRETE';

/* Alter Field (Null / Not Null)... */
UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = NULL WHERE RDB$FIELD_NAME='CODNAT' AND RDB$RELATION_NAME='LFFRETE';

CREATE DOMAIN IBCXXX NUMERIC(15,5) DEFAULT 0;

UPDATE RDB$RELATION_FIELDS SET RDB$DEFAULT_SOURCE=
(SELECT RDB$DEFAULT_SOURCE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX'),
RDB$DEFAULT_VALUE=
(SELECT RDB$DEFAULT_VALUE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX')
WHERE RDB$FIELD_NAME='ALIQICMSFRETE' AND RDB$RELATION_NAME='LFFRETE';

DROP DOMAIN IBCXXX;

CREATE DOMAIN IBCXXX NUMERIC(15,5) DEFAULT 0;

UPDATE RDB$RELATION_FIELDS SET RDB$DEFAULT_SOURCE=
(SELECT RDB$DEFAULT_SOURCE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX'),
RDB$DEFAULT_VALUE=
(SELECT RDB$DEFAULT_VALUE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX')
WHERE RDB$FIELD_NAME='VLRICMSFRETE' AND RDB$RELATION_NAME='LFFRETE';

DROP DOMAIN IBCXXX;

CREATE DOMAIN IBCXXX NUMERIC(15,5) DEFAULT 0;

UPDATE RDB$RELATION_FIELDS SET RDB$DEFAULT_SOURCE=
(SELECT RDB$DEFAULT_SOURCE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX'),
RDB$DEFAULT_VALUE=
(SELECT RDB$DEFAULT_VALUE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX')
WHERE RDB$FIELD_NAME='VLRBASEICMSFRETE' AND RDB$RELATION_NAME='LFFRETE';

DROP DOMAIN IBCXXX;


/* Create Primary Key... */
ALTER TABLE FNCHEQUE ADD CONSTRAINT FNCHEQUEPK PRIMARY KEY (SEQCHEQ, CODFILIAL, CODEMP);

ALTER TABLE FNTALAOCHEQ ADD CONSTRAINT FNTALAOCHEQPK PRIMARY KEY (NUMCONTA, SEQTALAO, CODFILIAL, CODEMP);

ALTER TABLE RHTABELAINSS ADD CONSTRAINT RHTABELAINSSPK PRIMARY KEY (CODTABINSS);

ALTER TABLE RHTABELAIRRF ADD CONSTRAINT RHTABELAIRRFPK PRIMARY KEY (CODTABIRRF);

/* Create Foreign Key... */
RECONNECT;

ALTER TABLE CPCOMPRA ADD CONSTRAINT CPCOMPRAFKEQRECMERC FOREIGN KEY (TICKET, CODFILIALRM, CODEMPRM) REFERENCES EQRECMERC (TICKET, CODFILIAL, CODEMP);

ALTER TABLE CPCOMPRA ADD CONSTRAINT CPCOMPRAFKFNTIPOCOB FOREIGN KEY (CODTIPOCOB, CODFILIALTC, CODEMPTC) REFERENCES FNTIPOCOB (CODTIPOCOB, CODFILIAL, CODEMP);

ALTER TABLE EQRECMERC ADD CONSTRAINT EQRECMERCFKEQALMOX FOREIGN KEY (CODALMOX, CODFILIALAX, CODEMPAX) REFERENCES EQALMOX (CODALMOX, CODFILIAL, CODEMP);

ALTER TABLE FNTIPOCOB ADD CONSTRAINT FNTIPOCOBFKFNTALON FOREIGN KEY (NUMCONTA, SEQTALAO, CODFILIAL, CODEMP) REFERENCES FNTALAOCHEQ (NUMCONTA, SEQTALAO, CODFILIAL, CODEMP);

ALTER TABLE LFFRETE ADD CONSTRAINT LFFRETEFKEQRECMERC FOREIGN KEY (TICKET, CODFILIALRM, CODEMPRM) REFERENCES EQRECMERC (TICKET, CODFILIAL, CODEMP);

/* Alter Procedure... */
/* Alter (FNADICLANCASP02) */
SET TERM ^ ;

ALTER PROCEDURE FNADICLANCASP02(ICODPAG INTEGER,
INPARCPAG INTEGER,
SNUMCONTA CHAR(10),
ICODEMPCA INTEGER,
ICODFILIALCA INTEGER,
ICODFOR INTEGER,
ICODEMPFR INTEGER,
ICODFILIALFR INTEGER,
SCODPLAN CHAR(13),
ICODEMPPN INTEGER,
ICODFILIALPN INTEGER,
IANOCC INTEGER,
SCODCC CHAR(19),
ICODEMPCC INTEGER,
ICODFILIALCC INTEGER,
DDTPAGOITPAG DATE,
SDOCLANCAITPAG CHAR(10),
SOBSITPAG CHAR(100),
DVLRPAGOITPAG NUMERIC(15,5),
ICODEMP INTEGER,
ICODFILIAL SMALLINT,
DVLRJUROSPAG NUMERIC(15,5),
DVLRDESC NUMERIC(15,5))
 AS
declare variable icodlanca integer;
declare variable scodplanconta char(13);
declare variable icodemppconta integer;
declare variable icodfilialpconta integer;
declare variable cflag char(1);
declare variable ifiliallanca integer;
declare variable tipolanca char(1);
declare variable codempjp integer;
declare variable codfilialjp smallint;
declare variable codplanjp char(13);
declare variable codempdr integer;
declare variable codfilialdr smallint;
declare variable codplandr char(13);
declare variable codsublanca smallint = 1;
BEGIN

    SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'FNLANCA')
    INTO IFILIALLANCA;

    SELECT CODPLAN,CODEMP,CODFILIAL FROM FNCONTA
    WHERE NUMCONTA=:sNumConta AND CODEMP=:ICODEMPCA AND CODFILIAL=:ICODFILIALCA
    INTO :sCodPlanConta,:iCodEmpPConta,:iCodFilialPConta;

    SELECT ISEQ FROM SPGERANUM(:iCODEMP,:IFILIALLANCA,'LA')
    INTO :iCodLanca;

    SELECT FLAG FROM FNPAGAR
    WHERE CODPAG=:iCodPag AND CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
    INTO :cFlag;

    SELECT CODEMPJP,CODFILIALJP,CODPLANJP,CODEMPDR,CODFILIALDR,CODPLANDR
    FROM SGPREFERE1
    WHERE CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
    INTO :CODEMPJP,:CODFILIALJP,:CODPLANJP,:CODEMPDR,:CODFILIALDR,:CODPLANDR;

    IF (ICODFOR IS NULL) THEN
        TIPOLANCA = 'A';
      ELSE
        TIPOLANCA = 'F';

    if ( (DVLRJUROSPAG IS NULL) OR (:CODPLANJP IS NULL)  ) then
        DVLRJUROSPAG = 0;
    else
        DVLRPAGOITPAG = DVLRPAGOITPAG - DVLRJUROSPAG;

    if (DVLRDESC IS NULL  OR (:CODPLANDR IS NULL) ) then
        DVLRDESC = 0;
    else
        DVLRPAGOITPAG = DVLRPAGOITPAG + DVLRDESC;


    INSERT INTO FNLANCA (TIPOLANCA,CODEMP,CODFILIAL,CODLANCA,CODEMPPG,CODFILIALPG,CODPAG,
                         NPARCPAG,CODEMPPN,CODFILIALPN,CODPLAN,DATALANCA,DOCLANCA,
                         HISTBLANCA,DTPREVLANCA,VLRLANCA,FLAG, CODEMPFR, CODFILIALFR, CODFOR)
         VALUES (:TIPOLANCA,:ICODEMP,:IFILIALLANCA,:iCodLanca,:ICODEMP,:ICODFILIAL,:iCodPag,
                 :iNParcPag,:iCodEmpPConta,:iCodFilialPConta,:sCodPlanConta,:dDtPagoItPag,:sDocLancaItPag,
                 :sObsItPag,:dDtPagoItPag,0,:cFlag, :ICODEMPFR, :ICODFILIALFR, :ICODFOR
         );

    INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:ICODEMPPN,:ICODFILIALPN,:sCodplan,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:dVlrPagoItPag,:cFlag);

    -- Lançamento dos juros em conta distinta.

    IF(DVLRJUROSPAG >0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
            VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:CODEMPJP,:CODFILIALJP,:CODPLANJP,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:DVLRJUROSPAG,:cFlag);

    END

    -- Lançamento de desconto em conta distinta.

    IF(DVLRDESC >0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
            VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:CODEMPDR,:CODFILIALDR,:CODPLANDR,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:DVLRDESC*-1,:cFlag);

    END

END
^

/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.3.3 (03/08/2010)';
    suspend;
end
^

/* Create trigger... */
CREATE TRIGGER FNTALAOCHEQTGBU FOR FNTALAOCHEQ
ACTIVE BEFORE UPDATE POSITION 0 
AS
begin
  new.DTALT=cast('now' AS DATE);
  new.IDUSUALT=USER;
  new.HALT = cast('now' AS TIME);
end
^

CREATE TRIGGER RHTABELAINSSTGBU FOR RHTABELAINSS
ACTIVE BEFORE UPDATE POSITION 0 
as
begin
  new.dtalt=cast('now' as date);
  new.idusualt=user;
  new.halt = cast('now' as time);
end
^

CREATE TRIGGER RHTABELAIRRFTGBU FOR RHTABELAIRRF
ACTIVE BEFORE UPDATE POSITION 0 
as
begin
  new.dtalt=cast('now' as date);
  new.idusualt=user;
  new.halt = cast('now' as time);
end
^


/* Alter exist trigger... */
ALTER TRIGGER CPITCOMPRATGBI
as

declare variable srefprod char(13);
declare variable habCustoCompra char(1);
declare variable calctrib char(1);

begin

    -- Buscando preferências
    select p.custocompra from sgprefere1 p
    where p.codemp=new.codemp and p.codfilial=new.codfilial
    into habCustoCompra;

    --Buscando informações da compra
    select cp.calctrib from cpcompra cp
    where cp.codemp=new.codemp and cp.codfilial=new.codfilial and cp.codcompra=new.codcompra
    into :calctrib;

    -- Buscando referência do produto
    select refprod from eqproduto
    where codprod=new.codprod and codemp=new.codemppd and codfilial=new.codfilialpd
    into srefprod;

    -- Carregando valores padrão
    if (new.refprod is null) then new.refprod = srefprod;
    if (new.vlrdescitcompra is null) then new.vlrdescitcompra = 0;
    if (new.vlrbaseicmsitcompra is null) then new.vlrbaseicmsitcompra = 0;
    if (new.vlricmsitcompra is null) then new.vlricmsitcompra = 0;
    if (new.vlrbaseipiitcompra is null) then new.vlrbaseipiitcompra = 0;
    if (new.vlripiitcompra is null) then new.vlripiitcompra = 0;
    if (new.vlrliqitcompra is null) then new.vlrliqitcompra = 0;
    if (new.vlradicitcompra is null) then new.vlradicitcompra = 0;
    if (new.vlrfreteitcompra is null) then new.vlrfreteitcompra = 0;

    if(new.vlrliqitcompra=0) then
    begin
       new.vlrliqitcompra = (new.qtditcompra * new.precoitcompra) - new.vlrdescitcompra + new.vlradicitcompra;
    end

    -- Buscando e carregando almoxarifado do produto
    if (new.codalmox is null) then
    begin
        select codempax, codfilialax, codalmox from eqproduto
        where codemp=new.codemppd and codfilial=new.codfilialpd and codprod=new.codprod
        into new.codempax, new.codfilialax, new.codalmox;
    end

    -- Buscando e carregando custo do produto
    if (('N' = habCustoCompra) or (new.custoitcompra is null)) then
    begin
        select nvlrcusto from cpcomprasp01(new.codemp, new.codfilial, new.qtditcompra, new.vlrliqitcompra, new.vlricmsitcompra)
        into new.custoitcompra;
    end

    -- Buscando e carregando retenção de tributos
    if(calctrib='S') then
    begin
        select coalesce(bc.vlrbasefunrural,0), coalesce(bc.aliqfunrural,0), coalesce(bc.vlrfunrural,0), bc.codempif, bc.codfilialif, bc.codfisc, bc.coditfisc
        from lfbuscatribcompra(new.codemp, new.codfilial, new.codcompra, new.codemppd, new.codfilialpd, new.codprod, new.vlrliqitcompra) bc
        into new.vlrbasefunruralitcompra, new.aliqfunruralitcompra, new.vlrfunruralitcompra,
        new.codempif, new.codfilialif, new.codfisc, new.coditfisc;
    end

    -- Descontando o valor do funrual do valor liquido do ítem
    if( new.vlrfunruralitcompra > 0 ) then
    begin
        new.vlrliqitcompra = new.vlrliqitcompra - new.vlrfunruralitcompra;
    end

    --Atualizando totais da compra
    update cpcompra cp set cp.vlrdescitcompra=cp.vlrdescitcompra + new.vlrdescitcompra,
    cp.vlrprodcompra = cp.vlrprodcompra + new.vlrproditcompra,
    cp.vlrbaseicmscompra = cp.vlrbaseicmscompra + new.vlrbaseicmsitcompra,
    cp.vlricmscompra = cp.vlricmscompra + new.vlricmsitcompra,
    cp.vlrisentascompra = cp.vlrisentascompra + new.vlrisentasitcompra,
    cp.vlroutrascompra = cp.vlroutrascompra + new.vlroutrasitcompra,
    cp.vlrbaseipicompra = cp.vlrbaseipicompra + new.vlrbaseipiitcompra,
    cp.vlripicompra = cp.vlripicompra + new.vlripiitcompra,
    cp.vlrliqcompra = cp.vlrliqcompra + new.vlrliqitcompra,
    cp.vlrfunruralcompra = coalesce(cp.vlrfunruralcompra,0) + coalesce(new.vlrfunruralitcompra,0)
    where cp.codcompra=new.codcompra and cp.codemp=new.codemp and cp.codfilial=new.codfilial;

end
^

/* Alter exist trigger... */
ALTER TRIGGER EQITRECMERCTGAU
as
    declare variable tipoprocrecmerc char(2);

begin

  -- buscando tipo de amostragem

    select pr.tipoprocrecmerc
    from eqprocrecmerc pr, eqitrecmerc ir
    where ir.codemp=new.codemp and ir.codfilial=new.codfilial and ir.ticket=new.ticket and ir.coditrecmerc=new.coditrecmerc
    and pr.codemp=ir.codemptp and pr.codfilial=ir.codfilialtp and pr.codtiporecmerc=ir.codtiporecmerc and pr.codprocrecmerc=ir.codprocrecmerc
    into :tipoprocrecmerc;

    if( ( coalesce(new.mediaamostragem,0) > 0 )  and ( coalesce(new.rendaamostragem,0) > 0 ) ) then
    begin

        update eqrecmerc rm set
        rm.mediaamostragem = ( coalesce(rm.mediaamostragem,new.mediaamostragem) + new.mediaamostragem ) / 2,
        rm.rendaamostragem = ( coalesce(rm.rendaamostragem,new.rendaamostragem) + new.rendaamostragem ) / 2
        where
        rm.codemp=new.codemp and rm.codfilial=new.codfilial and rm.ticket=new.ticket;

    end

    if(new.statusitrecmerc='FN') then
    begin

        if (tipoprocrecmerc='PI') then
        begin
            update eqrecmerc rm set rm.status='E1'
            where rm.codemp=new.codemp and rm.codfilial=new.codfilial and rm.ticket=new.ticket;
        end
        else if (tipoprocrecmerc='TR') then
        begin
            update eqrecmerc rm set rm.status='E2'
            where rm.codemp=new.codemp and rm.codfilial=new.codfilial and rm.ticket=new.ticket;
        end
        else if (tipoprocrecmerc='PF') then
        begin
            update eqrecmerc rm set rm.status='FN'
            where rm.codemp=new.codemp and rm.codfilial=new.codfilial and rm.ticket=new.ticket;
        end
    end

end
^

/* Alter exist trigger... */
ALTER TRIGGER FNITPAGARTGBU
AS
  DECLARE VARIABLE IFILIALPAG INTEGER;
  DECLARE VARIABLE ICODFOR INTEGER;
  DECLARE VARIABLE ICODEMPFR INTEGER;
  DECLARE VARIABLE ICODFILIALFR INTEGER;
BEGIN

  new.DTALT=cast('now' AS DATE);
  new.IDUSUALT=USER;
  new.HALT = cast('now' AS TIME);

  IF ( new.EMMANUT IS NULL ) THEN
  BEGIN
      new.EMMANUT = 'S';
  END

  IF ( not ( (new.EMMANUT='S') or ( (old.EMMANUT='S') and (old.EMMANUT is not null)) ) ) THEN
  BEGIN

     SELECT ICODFILIAL FROM SGRETFILIAL(new.CODEMP,'FNPAGAR') INTO IFILIALPAG;
     IF ((old.STATUSITPAG IN ('PP','PL') )  AND (new.STATUSITPAG='P1') ) THEN
     BEGIN
       DELETE FROM FNLANCA WHERE CODPAG=new.CODPAG AND NPARCPAG=new.NPARCPAG
              AND CODEMPPG=new.CODEMP AND CODFILIALPG = new.CODFILIAL
              AND CODEMP=new.CODEMP AND CODFILIAL=:IFILIALPAG;

       new.VLRPAGOITPAG = 0;
       new.DTPAGOITPAG = NULL;

     END
     ELSE IF ( (old.STATUSITPAG='P1') AND ( new.STATUSITPAG='CP' ) ) THEN
     BEGIN
        IF ( (new.OBSITPAG IS NULL) OR (rtrim(new.OBSITPAG)='') ) THEN
        BEGIN
           EXCEPTION FNITPAGAREX01;
        END
        new.VLRCANCITPAG = new.VLRAPAGITPAG;
        new.VLRPARCITPAG = 0;
        new.VLRDESCITPAG = 0;
        new.VLRJUROSITPAG = 0;
        new.VLRDEVITPAG = 0;
        new.VLRITPAG = 0;
     END

     new.VLRITPAG = new.VLRPARCITPAG - new.VLRDESCITPAG - new.VLRDEVITPAG + new.VLRJUROSITPAG +
     new.VLRMULTAITPAG + new.VLRADICITPAG;
     new.VLRAPAGITPAG = new.VLRITPAG - new.VLRPAGOITPAG;
  
     if (new.VLRAPAGITPAG < 0) then /* se o valor a pagar for menor que zero */
       new.VLRAPAGITPAG = 0;  /* então valor a pagar será zero */
     if ( (new.VLRAPAGITPAG=0) AND (new.VLRITPAG>0) ) then /* se o valor a pagar for igual a zero e existir valor na parcela*/
       new.STATUSITPAG = 'PP';  /* então o status será PP(pagamento completo) */
     else if ( (new.VLRPAGOITPAG>0) AND (new.VLRITPAG>0) ) then /* caso contrário e o valor pago maior que zero e existir valor na parcela*/
       new.STATUSITPAG = 'PL'; /*  então o status será PL(pagamento parcial) */

     /* faz o lançamento */
     SELECT CODFOR,CODEMPFR,CODFILIALFR FROM FNPAGAR WHERE CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL AND CODPAG=new.CODPAG
        INTO ICODFOR,ICODEMPFR,ICODFILIALFR;

     IF ((old.STATUSITPAG='P1' AND new.STATUSITPAG in ('PP','PL')) OR (old.STATUSITPAG in ('PP','PL') AND new.STATUSITPAG in ('PP','PL') AND new.VLRPAGOITPAG > 0)) THEN
     BEGIN

       EXECUTE PROCEDURE FNADICLANCASP02(new.CodPag,new.NParcPag,new.NumConta,new.CODEMPCA,new.CODFILIALCA,:ICODFOR,:ICODEMPFR,:ICODFILIALFR,
                              new.CodPlan,new.CODEMPPN,new.CODFILIALPN,new.AnoCC,new.CodCC,new.CODEMPCC,new.CODFILIALCC,
                              new.DtPagoItPag,new.DocLancaItPag,new.ObsItPag,new.VlrPagoItPag,new.CODEMP,new.CODFILIAL,new.vlrjurositpag,new.vlrdescitpag);

       /* Altera o valor pago e o valor a pagar */
       new.VLRPAGOITPAG = new.VLRPAGOITPAG + old.VLRPAGOITPAG;
       new.VLRAPAGITPAG = new.VLRITPAG - new.VLRPAGOITPAG;

       if (new.VLRAPAGITPAG < 0) then /* se o valor a pagar for menor que zero */
         new.VLRAPAGITPAG = 0;  /* então valor a pagar será zero */

       if (new.VLRAPAGITPAG=0) then /* se o valor a pagar for igual a zero */
         new.STATUSITPAG = 'PP';  /* então o status será PP(pagamento completo) */
       else if (new.VLRPAGOITPAG>0) then /* caso contrário e o valor pago maior que zero */
         new.STATUSITPAG = 'PL'; /*  então o status será PL(pagamento parcial) */

     END
     ELSE IF ((old.STATUSITPAG='PP') AND (new.STATUSITPAG='PP')) THEN
     BEGIN
        EXCEPTION FNPAGAREX01;
     END

   END

END
^

/* Alter exist trigger... */
ALTER TRIGGER FNSUBLANCATGAI
AS
DECLARE VARIABLE dDataSl DATE;
DECLARE VARIABLE dSaldoSl NUMERIC(15, 5);
DECLARE VARIABLE sCodplan CHAR(13);
DECLARE VARIABLE dSaldoAnt NUMERIC(15, 5);
DECLARE VARIABLE IFILIALSALDO INTEGER;
declare variable codemppn integer;
declare variable codfilialpn smallint;
BEGIN

  SELECT ICODFILIAL FROM SGRETFILIAL(new.CODEMP,'FNSALDOLANCA') INTO IFILIALSALDO;

  SELECT CODPLAN,CODEMPPN,CODFILIALPN, DATASL,SALDOSL FROM FNSALDOLANCA
  WHERE CODPLAN=new.CODPLAN AND DATASL=new.DATASUBLANCA AND CODEMP=new.CODEMP AND CODFILIAL = :IFILIALSALDO
  INTO :sCodplan,:codemppn,:codfilialpn,:dDataSl,:dSaldoSl;


   IF (:sCodplan IS NULL ) THEN
   BEGIN

      SELECT SALDOSL FROM FNSALDOLANCA SL1 WHERE SL1.CODPLAN=new.CODPLAN and sl1.codemppn=:codemppn and sl1.codfilialpn=:codfilialpn
             AND SL1.DATASL=(
                            SELECT MAX(SL2.DATASL) FROM FNSALDOLANCA SL2 WHERE
                                   SL2.CODPLAN=SL1.CODPLAN AND SL2.DATASL<new.DATASUBLANCA
                                   AND SL2.CODEMP=new.CODEMP AND SL2.CODFILIAL=:IFILIALSALDO
                            )
              AND SL1.CODEMP=new.CODEMP AND SL1.CODFILIAL = :IFILIALSALDO INTO :dSaldoAnt;



      IF (:dSaldoAnt IS NULL) THEN
         dSaldoAnt = 0;

      INSERT INTO FNSALDOLANCA (CODEMP,CODFILIAL,CODPLAN,CODEMPPN,CODFILIALPN,DATASL,SALDOSL)
             VALUES (new.CODEMPPN,:IFILIALSALDO,new.CODPLAN,new.CODEMPPN,new.CODFILIALPN,new.DATASUBLANCA,:dSaldoAnt+new.VLRSUBLANCA);

      UPDATE FNSALDOLANCA SET SALDOSL = SALDOSL + new.VLRSUBLANCA
             WHERE CODPLAN=new.CODPLAN AND DATASL>new.DATASUBLANCA
             AND CODEMP=new.CODEMP AND CODFILIAL=:IFILIALSALDO;



   END
   ELSE
   BEGIN

      UPDATE FNSALDOLANCA SET SALDOSL = SALDOSL + new.VLRSUBLANCA
             WHERE CODPLAN=new.CODPLAN AND DATASL>=new.DATASUBLANCA
             AND CODEMP=new.CODEMP AND CODFILIAL=:IFILIALSALDO;

   END
END
^

/* Alter exist trigger... */
ALTER TRIGGER FNSUBLANCATGBI
AS
  DECLARE VARIABLE sEhTransf CHAR(1);
  DECLARE VARIABLE sTipoPlan CHAR(1);
  DECLARE VARIABLE dDataLanca DATE;
  DECLARE VARIABLE dDtPrevLanca DATE;
  DECLARE VARIABLE sHistSubLanc VARCHAR(100);
BEGIN
  /*IF ( new.VLRSUBLANCA = 0 ) THEN
     EXCEPTION FNSUBLANCAEX04;         */
  SELECT HISTBLANCA FROM FNLANCA WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL = new.CODFILIAL
  INTO sHistSubLanc;

  IF (new.HISTSUBLANCA IS NULL) THEN
      new.HISTSUBLANCA = sHistSubLanc;

  IF (new.CODSUBLANCA IS NULL) THEN
    SELECT MAX(CODSUBLANCA) FROM FNSUBLANCA
    WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL = new.CODFILIAL
    INTO new.CODSUBLANCA;

  new.STATUSSUBLANCA = 'S1';

  SELECT TRANSFLANCA,DATALANCA,DTPREVLANCA FROM FNLANCA
  WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL = new.CODFILIAL
  INTO sEhTransf,dDataLanca,dDtPrevLanca;

  SELECT TIPOPLAN FROM FNPLANEJAMENTO WHERE CODPLAN = new.CODPLAN AND CODEMP=new.CODEMPPN AND CODFILIAL = new.CODFILIALPN
  INTO sTipoPlan;

  new.DATASUBLANCA = dDataLanca;

  IF (new.CODSUBLANCA > 0) THEN
  BEGIN
    new.ORIGSUBLANCA = 'N';
  END

  new.STATUSSUBLANCA = 'S1';
  new.DTPREVSUBLANCA = dDtPrevLanca;

  IF (sEhTransf = 'S') THEN
  BEGIN
   IF (new.CODSUBLANCA = 2) THEN
     EXCEPTION FNSUBLANCAEX01;
   ELSE IF (sTipoPlan IN ('D','R')) THEN
     EXCEPTION FNSUBLANCAEX02;
  END
  ELSE
    IF ((new.CODSUBLANCA != 0) AND (sTipoPlan IN ('C','B'))) THEN
      EXCEPTION FNSUBLANCAEX03;
  UPDATE FNLANCA SET STATUSLANCA = 'L2', VLRLANCA=(VLRLANCA-new.VLRSUBLANCA)
         WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL;
END
^

SET TERM ; ^

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE CPCOMPRA ALTER COLUMN CODCOMPRA POSITION 3;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPPG POSITION 4;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALPG POSITION 5;

ALTER TABLE CPCOMPRA ALTER COLUMN CODPLANOPAG POSITION 6;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPFR POSITION 7;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALFR POSITION 8;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFOR POSITION 9;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPSE POSITION 10;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALSE POSITION 11;

ALTER TABLE CPCOMPRA ALTER COLUMN SERIE POSITION 12;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPTM POSITION 13;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALTM POSITION 14;

ALTER TABLE CPCOMPRA ALTER COLUMN CODTIPOMOV POSITION 15;

ALTER TABLE CPCOMPRA ALTER COLUMN DOCCOMPRA POSITION 16;

ALTER TABLE CPCOMPRA ALTER COLUMN DTENTCOMPRA POSITION 17;

ALTER TABLE CPCOMPRA ALTER COLUMN DTEMITCOMPRA POSITION 18;

ALTER TABLE CPCOMPRA ALTER COLUMN PERCDESCCOMPRA POSITION 19;

ALTER TABLE CPCOMPRA ALTER COLUMN PERCIPICOMPRA POSITION 20;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRPRODCOMPRA POSITION 21;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRLIQCOMPRA POSITION 22;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRCOMPRA POSITION 23;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRDESCCOMPRA POSITION 24;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRDESCITCOMPRA POSITION 25;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRADICCOMPRA POSITION 26;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRBASEICMSCOMPRA POSITION 27;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRBASEICMSSTCOMPRA POSITION 28;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRBASEIPICOMPRA POSITION 29;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRBASEPISCOMPRA POSITION 30;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRBASECOFINSCOMPRA POSITION 31;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRICMSCOMPRA POSITION 32;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRICMSSTCOMPRA POSITION 33;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRIPICOMPRA POSITION 34;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRPISCOMPRA POSITION 35;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRCOFINSCOMPRA POSITION 36;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRFUNRURALCOMPRA POSITION 37;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRFRETECOMPRA POSITION 38;

ALTER TABLE CPCOMPRA ALTER COLUMN VLROUTRASCOMPRA POSITION 39;

ALTER TABLE CPCOMPRA ALTER COLUMN VLRISENTASCOMPRA POSITION 40;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPTC POSITION 41;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALTC POSITION 42;

ALTER TABLE CPCOMPRA ALTER COLUMN CODTIPOCOB POSITION 43;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPBO POSITION 44;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALBO POSITION 45;

ALTER TABLE CPCOMPRA ALTER COLUMN CODBANCO POSITION 46;

ALTER TABLE CPCOMPRA ALTER COLUMN IMPNOTACOMPRA POSITION 47;

ALTER TABLE CPCOMPRA ALTER COLUMN BLOQCOMPRA POSITION 48;

ALTER TABLE CPCOMPRA ALTER COLUMN EMMANUT POSITION 49;

ALTER TABLE CPCOMPRA ALTER COLUMN FLAG POSITION 50;

ALTER TABLE CPCOMPRA ALTER COLUMN ADICFRETECOMPRA POSITION 51;

ALTER TABLE CPCOMPRA ALTER COLUMN TIPOFRETECOMPRA POSITION 52;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPSOL POSITION 53;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALSOL POSITION 54;

ALTER TABLE CPCOMPRA ALTER COLUMN CODSOL POSITION 55;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPTN POSITION 56;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALTN POSITION 57;

ALTER TABLE CPCOMPRA ALTER COLUMN CODTRAN POSITION 58;

ALTER TABLE CPCOMPRA ALTER COLUMN OBSERVACAO POSITION 59;

ALTER TABLE CPCOMPRA ALTER COLUMN OBS01 POSITION 60;

ALTER TABLE CPCOMPRA ALTER COLUMN OBS02 POSITION 61;

ALTER TABLE CPCOMPRA ALTER COLUMN OBS03 POSITION 62;

ALTER TABLE CPCOMPRA ALTER COLUMN OBS04 POSITION 63;

ALTER TABLE CPCOMPRA ALTER COLUMN ADICADICCOMPRA POSITION 64;

ALTER TABLE CPCOMPRA ALTER COLUMN QTDFRETECOMPRA POSITION 65;

ALTER TABLE CPCOMPRA ALTER COLUMN ADICFRETEBASEICMS POSITION 66;

ALTER TABLE CPCOMPRA ALTER COLUMN ADICADICBASEICMS POSITION 67;

ALTER TABLE CPCOMPRA ALTER COLUMN ADICIPIBASEICMS POSITION 68;

ALTER TABLE CPCOMPRA ALTER COLUMN CHAVENFECOMPRA POSITION 69;

ALTER TABLE CPCOMPRA ALTER COLUMN STATUSCOMPRA POSITION 70;

ALTER TABLE CPCOMPRA ALTER COLUMN NRODI POSITION 71;

ALTER TABLE CPCOMPRA ALTER COLUMN DTREGDI POSITION 72;

ALTER TABLE CPCOMPRA ALTER COLUMN LOCDESEMBDI POSITION 73;

ALTER TABLE CPCOMPRA ALTER COLUMN SIGLAUFDESEMBDI POSITION 74;

ALTER TABLE CPCOMPRA ALTER COLUMN CODPAISDESEMBDI POSITION 75;

ALTER TABLE CPCOMPRA ALTER COLUMN DTDESEMBDI POSITION 76;

ALTER TABLE CPCOMPRA ALTER COLUMN IDENTCONTAINER POSITION 77;

ALTER TABLE CPCOMPRA ALTER COLUMN CALCTRIB POSITION 78;

ALTER TABLE CPCOMPRA ALTER COLUMN CODEMPRM POSITION 79;

ALTER TABLE CPCOMPRA ALTER COLUMN CODFILIALRM POSITION 80;

ALTER TABLE CPCOMPRA ALTER COLUMN TICKET POSITION 81;

ALTER TABLE CPCOMPRA ALTER COLUMN DTINS POSITION 82;

ALTER TABLE CPCOMPRA ALTER COLUMN HINS POSITION 83;

ALTER TABLE CPCOMPRA ALTER COLUMN IDUSUINS POSITION 84;

ALTER TABLE CPCOMPRA ALTER COLUMN DTALT POSITION 85;

ALTER TABLE CPCOMPRA ALTER COLUMN HALT POSITION 86;

ALTER TABLE CPCOMPRA ALTER COLUMN IDUSUALT POSITION 87;

ALTER TABLE CPFORNECED ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE CPFORNECED ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE CPFORNECED ALTER COLUMN CODFOR POSITION 3;

ALTER TABLE CPFORNECED ALTER COLUMN RAZFOR POSITION 4;

ALTER TABLE CPFORNECED ALTER COLUMN CODEMPTF POSITION 5;

ALTER TABLE CPFORNECED ALTER COLUMN CODFILIALTF POSITION 6;

ALTER TABLE CPFORNECED ALTER COLUMN CODTIPOFOR POSITION 7;

ALTER TABLE CPFORNECED ALTER COLUMN CODEMPBO POSITION 8;

ALTER TABLE CPFORNECED ALTER COLUMN CODFILIALBO POSITION 9;

ALTER TABLE CPFORNECED ALTER COLUMN CODBANCO POSITION 10;

ALTER TABLE CPFORNECED ALTER COLUMN CODEMPHP POSITION 11;

ALTER TABLE CPFORNECED ALTER COLUMN CODFILIALHP POSITION 12;

ALTER TABLE CPFORNECED ALTER COLUMN CODHIST POSITION 13;

ALTER TABLE CPFORNECED ALTER COLUMN NOMEFOR POSITION 14;

ALTER TABLE CPFORNECED ALTER COLUMN DATAFOR POSITION 15;

ALTER TABLE CPFORNECED ALTER COLUMN ATIVOFOR POSITION 16;

ALTER TABLE CPFORNECED ALTER COLUMN PESSOAFOR POSITION 17;

ALTER TABLE CPFORNECED ALTER COLUMN CNPJFOR POSITION 18;

ALTER TABLE CPFORNECED ALTER COLUMN CPFFOR POSITION 19;

ALTER TABLE CPFORNECED ALTER COLUMN INSCFOR POSITION 20;

ALTER TABLE CPFORNECED ALTER COLUMN RGFOR POSITION 21;

ALTER TABLE CPFORNECED ALTER COLUMN ENDFOR POSITION 22;

ALTER TABLE CPFORNECED ALTER COLUMN NUMFOR POSITION 23;

ALTER TABLE CPFORNECED ALTER COLUMN COMPLFOR POSITION 24;

ALTER TABLE CPFORNECED ALTER COLUMN BAIRFOR POSITION 25;

ALTER TABLE CPFORNECED ALTER COLUMN CEPFOR POSITION 26;

ALTER TABLE CPFORNECED ALTER COLUMN CIDFOR POSITION 27;

ALTER TABLE CPFORNECED ALTER COLUMN UFFOR POSITION 28;

ALTER TABLE CPFORNECED ALTER COLUMN CONTFOR POSITION 29;

ALTER TABLE CPFORNECED ALTER COLUMN FONEFOR POSITION 30;

ALTER TABLE CPFORNECED ALTER COLUMN FAXFOR POSITION 31;

ALTER TABLE CPFORNECED ALTER COLUMN AGENCIAFOR POSITION 32;

ALTER TABLE CPFORNECED ALTER COLUMN CONTAFOR POSITION 33;

ALTER TABLE CPFORNECED ALTER COLUMN EMAILFOR POSITION 34;

ALTER TABLE CPFORNECED ALTER COLUMN OBSFOR POSITION 35;

ALTER TABLE CPFORNECED ALTER COLUMN CELFOR POSITION 36;

ALTER TABLE CPFORNECED ALTER COLUMN CLIFOR POSITION 37;

ALTER TABLE CPFORNECED ALTER COLUMN SSPFOR POSITION 38;

ALTER TABLE CPFORNECED ALTER COLUMN DDDFONEFOR POSITION 39;

ALTER TABLE CPFORNECED ALTER COLUMN DDDFAXFOR POSITION 40;

ALTER TABLE CPFORNECED ALTER COLUMN DDDCELFOR POSITION 41;

ALTER TABLE CPFORNECED ALTER COLUMN SITEFOR POSITION 42;

ALTER TABLE CPFORNECED ALTER COLUMN CODCONTDEB POSITION 43;

ALTER TABLE CPFORNECED ALTER COLUMN CODCONTCRED POSITION 44;

ALTER TABLE CPFORNECED ALTER COLUMN CODFORCONTAB POSITION 45;

ALTER TABLE CPFORNECED ALTER COLUMN CODMUNIC POSITION 46;

ALTER TABLE CPFORNECED ALTER COLUMN SIGLAUF POSITION 47;

ALTER TABLE CPFORNECED ALTER COLUMN CODPAIS POSITION 48;

ALTER TABLE CPFORNECED ALTER COLUMN CODEMPUC POSITION 49;

ALTER TABLE CPFORNECED ALTER COLUMN CODFILIALUC POSITION 50;

ALTER TABLE CPFORNECED ALTER COLUMN CODUNIFCOD POSITION 51;

ALTER TABLE CPFORNECED ALTER COLUMN CODEMPFF POSITION 52;

ALTER TABLE CPFORNECED ALTER COLUMN CODFILIALFF POSITION 53;

ALTER TABLE CPFORNECED ALTER COLUMN CODFISCFOR POSITION 54;

ALTER TABLE CPFORNECED ALTER COLUMN SUFRAMAFOR POSITION 55;

ALTER TABLE CPFORNECED ALTER COLUMN NRODEPENDFOR POSITION 56;

ALTER TABLE CPFORNECED ALTER COLUMN DTINS POSITION 57;

ALTER TABLE CPFORNECED ALTER COLUMN HINS POSITION 58;

ALTER TABLE CPFORNECED ALTER COLUMN IDUSUINS POSITION 59;

ALTER TABLE CPFORNECED ALTER COLUMN DTALT POSITION 60;

ALTER TABLE CPFORNECED ALTER COLUMN HALT POSITION 61;

ALTER TABLE CPFORNECED ALTER COLUMN IDUSUALT POSITION 62;

ALTER TABLE CPTIPOFOR ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE CPTIPOFOR ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE CPTIPOFOR ALTER COLUMN CODTIPOFOR POSITION 3;

ALTER TABLE CPTIPOFOR ALTER COLUMN DESCTIPOFOR POSITION 4;

ALTER TABLE CPTIPOFOR ALTER COLUMN RETENCAOINSS POSITION 5;

ALTER TABLE CPTIPOFOR ALTER COLUMN PERCBASEINSS POSITION 6;

ALTER TABLE CPTIPOFOR ALTER COLUMN RETENCAOOUTROS POSITION 7;

ALTER TABLE CPTIPOFOR ALTER COLUMN PERCRETOUTROS POSITION 8;

ALTER TABLE CPTIPOFOR ALTER COLUMN RETENCAOIRRF POSITION 9;

ALTER TABLE CPTIPOFOR ALTER COLUMN PERCBASEIRRF POSITION 10;

ALTER TABLE CPTIPOFOR ALTER COLUMN DTINS POSITION 11;

ALTER TABLE CPTIPOFOR ALTER COLUMN HINS POSITION 12;

ALTER TABLE CPTIPOFOR ALTER COLUMN IDUSUINS POSITION 13;

ALTER TABLE CPTIPOFOR ALTER COLUMN DTALT POSITION 14;

ALTER TABLE CPTIPOFOR ALTER COLUMN HALT POSITION 15;

ALTER TABLE CPTIPOFOR ALTER COLUMN IDUSUALT POSITION 16;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE EQRECMERC ALTER COLUMN TICKET POSITION 3;

ALTER TABLE EQRECMERC ALTER COLUMN PLACAVEICULO POSITION 4;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPPD POSITION 5;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALPD POSITION 6;

ALTER TABLE EQRECMERC ALTER COLUMN CODPROD POSITION 7;

ALTER TABLE EQRECMERC ALTER COLUMN REFPROD POSITION 8;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPFR POSITION 9;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALFR POSITION 10;

ALTER TABLE EQRECMERC ALTER COLUMN CODFOR POSITION 11;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPTR POSITION 12;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALTR POSITION 13;

ALTER TABLE EQRECMERC ALTER COLUMN CODTIPORECMERC POSITION 14;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPTN POSITION 15;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALTN POSITION 16;

ALTER TABLE EQRECMERC ALTER COLUMN CODTRAN POSITION 17;

ALTER TABLE EQRECMERC ALTER COLUMN IDUSUALT POSITION 18;

ALTER TABLE EQRECMERC ALTER COLUMN CODBAIRRO POSITION 19;

ALTER TABLE EQRECMERC ALTER COLUMN CODMUNIC POSITION 20;

ALTER TABLE EQRECMERC ALTER COLUMN SIGLAUF POSITION 21;

ALTER TABLE EQRECMERC ALTER COLUMN CODPAIS POSITION 22;

ALTER TABLE EQRECMERC ALTER COLUMN STATUS POSITION 23;

ALTER TABLE EQRECMERC ALTER COLUMN TIPOFRETE POSITION 24;

ALTER TABLE EQRECMERC ALTER COLUMN DTENT POSITION 25;

ALTER TABLE EQRECMERC ALTER COLUMN DTPREVRET POSITION 26;

ALTER TABLE EQRECMERC ALTER COLUMN DOCRECMERC POSITION 27;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPVD POSITION 28;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALVD POSITION 29;

ALTER TABLE EQRECMERC ALTER COLUMN CODVEND POSITION 30;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPCL POSITION 31;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALCL POSITION 32;

ALTER TABLE EQRECMERC ALTER COLUMN CODCLI POSITION 33;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPAR POSITION 34;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALAR POSITION 35;

ALTER TABLE EQRECMERC ALTER COLUMN CODATENDREC POSITION 36;

ALTER TABLE EQRECMERC ALTER COLUMN SOLICITANTE POSITION 37;

ALTER TABLE EQRECMERC ALTER COLUMN MEDIAAMOSTRAGEM POSITION 38;

ALTER TABLE EQRECMERC ALTER COLUMN RENDAAMOSTRAGEM POSITION 39;

ALTER TABLE EQRECMERC ALTER COLUMN CODEMPAX POSITION 40;

ALTER TABLE EQRECMERC ALTER COLUMN CODFILIALAX POSITION 41;

ALTER TABLE EQRECMERC ALTER COLUMN CODALMOX POSITION 42;

ALTER TABLE EQRECMERC ALTER COLUMN DTINS POSITION 43;

ALTER TABLE EQRECMERC ALTER COLUMN HINS POSITION 44;

ALTER TABLE EQRECMERC ALTER COLUMN IDUSUINS POSITION 45;

ALTER TABLE EQRECMERC ALTER COLUMN DTALT POSITION 46;

ALTER TABLE EQRECMERC ALTER COLUMN HALT POSITION 47;

ALTER TABLE FNBANCO ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE FNBANCO ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE FNBANCO ALTER COLUMN CODBANCO POSITION 3;

ALTER TABLE FNBANCO ALTER COLUMN NOMEBANCO POSITION 4;

ALTER TABLE FNBANCO ALTER COLUMN DVBANCO POSITION 5;

ALTER TABLE FNBANCO ALTER COLUMN SITEBANCO POSITION 6;

ALTER TABLE FNBANCO ALTER COLUMN CODEMPMB POSITION 7;

ALTER TABLE FNBANCO ALTER COLUMN CODFILIALMB POSITION 8;

ALTER TABLE FNBANCO ALTER COLUMN CODMODBOL POSITION 9;

ALTER TABLE FNBANCO ALTER COLUMN IMGBOLBANCO POSITION 10;

ALTER TABLE FNBANCO ALTER COLUMN IMGBOLBANCO2 POSITION 11;

ALTER TABLE FNBANCO ALTER COLUMN LAYOUTCHEQBANCO POSITION 12;

ALTER TABLE FNBANCO ALTER COLUMN DTINS POSITION 13;

ALTER TABLE FNBANCO ALTER COLUMN HINS POSITION 14;

ALTER TABLE FNBANCO ALTER COLUMN IDUSUINS POSITION 15;

ALTER TABLE FNBANCO ALTER COLUMN DTALT POSITION 16;

ALTER TABLE FNBANCO ALTER COLUMN HALT POSITION 17;

ALTER TABLE FNBANCO ALTER COLUMN IDUSUALT POSITION 18;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE FNPAGAR ALTER COLUMN CODPAG POSITION 3;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPCP POSITION 4;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALCP POSITION 5;

ALTER TABLE FNPAGAR ALTER COLUMN CODCOMPRA POSITION 6;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPPG POSITION 7;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALPG POSITION 8;

ALTER TABLE FNPAGAR ALTER COLUMN CODPLANOPAG POSITION 9;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPFR POSITION 10;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALFR POSITION 11;

ALTER TABLE FNPAGAR ALTER COLUMN CODFOR POSITION 12;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPBO POSITION 13;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALBO POSITION 14;

ALTER TABLE FNPAGAR ALTER COLUMN CODBANCO POSITION 15;

ALTER TABLE FNPAGAR ALTER COLUMN VLRDESCPAG POSITION 16;

ALTER TABLE FNPAGAR ALTER COLUMN VLRMULTAPAG POSITION 17;

ALTER TABLE FNPAGAR ALTER COLUMN VLRJUROSPAG POSITION 18;

ALTER TABLE FNPAGAR ALTER COLUMN VLRDEVPAG POSITION 19;

ALTER TABLE FNPAGAR ALTER COLUMN VLRPARCPAG POSITION 20;

ALTER TABLE FNPAGAR ALTER COLUMN VLRPAGOPAG POSITION 21;

ALTER TABLE FNPAGAR ALTER COLUMN VLRAPAGPAG POSITION 22;

ALTER TABLE FNPAGAR ALTER COLUMN DATAPAG POSITION 23;

ALTER TABLE FNPAGAR ALTER COLUMN STATUSPAG POSITION 24;

ALTER TABLE FNPAGAR ALTER COLUMN DTQUITPAG POSITION 25;

ALTER TABLE FNPAGAR ALTER COLUMN DOCPAG POSITION 26;

ALTER TABLE FNPAGAR ALTER COLUMN VLRPAG POSITION 27;

ALTER TABLE FNPAGAR ALTER COLUMN NROPARCPAG POSITION 28;

ALTER TABLE FNPAGAR ALTER COLUMN OBSPAG POSITION 29;

ALTER TABLE FNPAGAR ALTER COLUMN VLRADICPAG POSITION 30;

ALTER TABLE FNPAGAR ALTER COLUMN FLAG POSITION 31;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPTC POSITION 32;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALTC POSITION 33;

ALTER TABLE FNPAGAR ALTER COLUMN CODTIPOCOB POSITION 34;

ALTER TABLE FNPAGAR ALTER COLUMN CODEMPCA POSITION 35;

ALTER TABLE FNPAGAR ALTER COLUMN CODFILIALCA POSITION 36;

ALTER TABLE FNPAGAR ALTER COLUMN NUMCONTA POSITION 37;

ALTER TABLE FNPAGAR ALTER COLUMN EMMANUT POSITION 38;

ALTER TABLE FNPAGAR ALTER COLUMN VLRBASEIRRF POSITION 39;

ALTER TABLE FNPAGAR ALTER COLUMN VLRBASEINSS POSITION 40;

ALTER TABLE FNPAGAR ALTER COLUMN VLRRETIRRF POSITION 41;

ALTER TABLE FNPAGAR ALTER COLUMN VLRRETINSS POSITION 42;

ALTER TABLE FNPAGAR ALTER COLUMN DTINS POSITION 43;

ALTER TABLE FNPAGAR ALTER COLUMN HINS POSITION 44;

ALTER TABLE FNPAGAR ALTER COLUMN IDUSUINS POSITION 45;

ALTER TABLE FNPAGAR ALTER COLUMN DTALT POSITION 46;

ALTER TABLE FNPAGAR ALTER COLUMN HALT POSITION 47;

ALTER TABLE FNPAGAR ALTER COLUMN IDUSUALT POSITION 48;

ALTER TABLE FNTIPOCOB ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE FNTIPOCOB ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE FNTIPOCOB ALTER COLUMN CODTIPOCOB POSITION 3;

ALTER TABLE FNTIPOCOB ALTER COLUMN DESCTIPOCOB POSITION 4;

ALTER TABLE FNTIPOCOB ALTER COLUMN TIPOFEBRABAN POSITION 5;

ALTER TABLE FNTIPOCOB ALTER COLUMN DUPLCOB POSITION 6;

ALTER TABLE FNTIPOCOB ALTER COLUMN OBRIGCARTCOB POSITION 7;

ALTER TABLE FNTIPOCOB ALTER COLUMN DTINS POSITION 8;

ALTER TABLE FNTIPOCOB ALTER COLUMN HINS POSITION 9;

ALTER TABLE FNTIPOCOB ALTER COLUMN IDUSUINS POSITION 10;

ALTER TABLE FNTIPOCOB ALTER COLUMN DTALT POSITION 11;

ALTER TABLE FNTIPOCOB ALTER COLUMN HALT POSITION 12;

ALTER TABLE FNTIPOCOB ALTER COLUMN IDUSUALT POSITION 13;

ALTER TABLE FNTIPOCOB ALTER COLUMN CODEMPCT POSITION 14;

ALTER TABLE FNTIPOCOB ALTER COLUMN CODFILIALCT POSITION 15;

ALTER TABLE FNTIPOCOB ALTER COLUMN NUMCONTA POSITION 16;

ALTER TABLE FNTIPOCOB ALTER COLUMN SEQTALAO POSITION 17;

ALTER TABLE LFFRETE ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE LFFRETE ALTER COLUMN CODFRETE POSITION 3;

ALTER TABLE LFFRETE ALTER COLUMN DOCFRETE POSITION 4;

ALTER TABLE LFFRETE ALTER COLUMN CODEMPTN POSITION 5;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIALTN POSITION 6;

ALTER TABLE LFFRETE ALTER COLUMN CODTRAN POSITION 7;

ALTER TABLE LFFRETE ALTER COLUMN CODEMPTM POSITION 8;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIALTM POSITION 9;

ALTER TABLE LFFRETE ALTER COLUMN CODTIPOMOV POSITION 10;

ALTER TABLE LFFRETE ALTER COLUMN CODEMPNT POSITION 11;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIALNT POSITION 12;

ALTER TABLE LFFRETE ALTER COLUMN CODNAT POSITION 13;

ALTER TABLE LFFRETE ALTER COLUMN TIPOFRETE POSITION 14;

ALTER TABLE LFFRETE ALTER COLUMN TIPOPGTO POSITION 15;

ALTER TABLE LFFRETE ALTER COLUMN CODEMPRE POSITION 16;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIALRE POSITION 17;

ALTER TABLE LFFRETE ALTER COLUMN CODREMET POSITION 18;

ALTER TABLE LFFRETE ALTER COLUMN CODEMPDE POSITION 19;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIALDE POSITION 20;

ALTER TABLE LFFRETE ALTER COLUMN CODDESTINAT POSITION 21;

ALTER TABLE LFFRETE ALTER COLUMN DTEMITFRETE POSITION 22;

ALTER TABLE LFFRETE ALTER COLUMN QTDFRETE POSITION 23;

ALTER TABLE LFFRETE ALTER COLUMN VLRMERCADORIA POSITION 24;

ALTER TABLE LFFRETE ALTER COLUMN VLRFRETE POSITION 25;

ALTER TABLE LFFRETE ALTER COLUMN VLRFRETENOTA POSITION 26;

ALTER TABLE LFFRETE ALTER COLUMN PESOBRUTO POSITION 27;

ALTER TABLE LFFRETE ALTER COLUMN PESOLIQUIDO POSITION 28;

ALTER TABLE LFFRETE ALTER COLUMN ALIQICMSFRETE POSITION 29;

ALTER TABLE LFFRETE ALTER COLUMN VLRICMSFRETE POSITION 30;

ALTER TABLE LFFRETE ALTER COLUMN VLRBASEICMSFRETE POSITION 31;

ALTER TABLE LFFRETE ALTER COLUMN CODEMPPA POSITION 32;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIALPA POSITION 33;

ALTER TABLE LFFRETE ALTER COLUMN CODPAG POSITION 34;

ALTER TABLE LFFRETE ALTER COLUMN SERIE POSITION 35;

ALTER TABLE LFFRETE ALTER COLUMN CODEMPRM POSITION 36;

ALTER TABLE LFFRETE ALTER COLUMN CODFILIALRM POSITION 37;

ALTER TABLE LFFRETE ALTER COLUMN TICKET POSITION 38;

ALTER TABLE LFFRETE ALTER COLUMN DTINS POSITION 39;

ALTER TABLE LFFRETE ALTER COLUMN HINS POSITION 40;

ALTER TABLE LFFRETE ALTER COLUMN IDUSUINS POSITION 41;

ALTER TABLE LFFRETE ALTER COLUMN DTALT POSITION 42;

ALTER TABLE LFFRETE ALTER COLUMN HALT POSITION 43;

ALTER TABLE LFFRETE ALTER COLUMN IDUSUALT POSITION 44;

ALTER TABLE SGBAIRRO ALTER COLUMN CODBAIRRO POSITION 1;

ALTER TABLE SGBAIRRO ALTER COLUMN CODMUNIC POSITION 2;

ALTER TABLE SGBAIRRO ALTER COLUMN SIGLAUF POSITION 3;

ALTER TABLE SGBAIRRO ALTER COLUMN CODPAIS POSITION 4;

ALTER TABLE SGBAIRRO ALTER COLUMN NOMEBAIRRO POSITION 5;

ALTER TABLE SGBAIRRO ALTER COLUMN VLRFRETE POSITION 6;

ALTER TABLE SGBAIRRO ALTER COLUMN QTDFRETE POSITION 7;

ALTER TABLE SGBAIRRO ALTER COLUMN DTINS POSITION 8;

ALTER TABLE SGBAIRRO ALTER COLUMN HINS POSITION 9;

ALTER TABLE SGBAIRRO ALTER COLUMN IDUSUINS POSITION 10;

ALTER TABLE SGBAIRRO ALTER COLUMN DTALT POSITION 11;

ALTER TABLE SGBAIRRO ALTER COLUMN HALT POSITION 12;

ALTER TABLE SGBAIRRO ALTER COLUMN IDUSUALT POSITION 13;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAREFPROD POSITION 3;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV POSITION 4;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTM POSITION 5;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTM POSITION 6;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPEDSEQ POSITION 7;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAORCSEQ POSITION 8;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILTRO POSITION 9;

ALTER TABLE SGPREFERE1 ALTER COLUMN USALIQREL POSITION 10;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOPRECOCUSTO POSITION 11;

ALTER TABLE SGPREFERE1 ALTER COLUMN ANOCENTROCUSTO POSITION 12;

ALTER TABLE SGPREFERE1 ALTER COLUMN OBSORCPAD POSITION 13;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV2 POSITION 14;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT2 POSITION 15;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT2 POSITION 16;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSORC POSITION 17;

ALTER TABLE SGPREFERE1 ALTER COLUMN TITORCTXT01 POSITION 18;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV3 POSITION 19;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT3 POSITION 20;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT3 POSITION 21;

ALTER TABLE SGPREFERE1 ALTER COLUMN ORDNOTA POSITION 22;

ALTER TABLE SGPREFERE1 ALTER COLUMN SETORVENDA POSITION 23;

ALTER TABLE SGPREFERE1 ALTER COLUMN PREFCRED POSITION 24;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOPREFCRED POSITION 25;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMO POSITION 26;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMO POSITION 27;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMOEDA POSITION 28;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV4 POSITION 29;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT4 POSITION 30;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT4 POSITION 31;

ALTER TABLE SGPREFERE1 ALTER COLUMN USACLASCOMIS POSITION 32;

ALTER TABLE SGPREFERE1 ALTER COLUMN PERCPRECOCUSTO POSITION 33;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODGRUP POSITION 34;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALGP POSITION 35;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPGP POSITION 36;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMARCA POSITION 37;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMC POSITION 38;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMC POSITION 39;

ALTER TABLE SGPREFERE1 ALTER COLUMN RGCLIOBRIG POSITION 40;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABFRETEVD POSITION 41;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABADICVD POSITION 42;

ALTER TABLE SGPREFERE1 ALTER COLUMN TRAVATMNFVD POSITION 43;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOVALIDORC POSITION 44;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLIMESMOCNPJ POSITION 45;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTBJ POSITION 46;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTJ POSITION 47;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTJ POSITION 48;

ALTER TABLE SGPREFERE1 ALTER COLUMN CNPJOBRIGCLI POSITION 49;

ALTER TABLE SGPREFERE1 ALTER COLUMN JUROSPOSCALC POSITION 50;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPFR POSITION 51;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALFR POSITION 52;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFOR POSITION 53;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTN POSITION 54;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTN POSITION 55;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTRAN POSITION 56;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTF POSITION 57;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTF POSITION 58;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOFOR POSITION 59;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT5 POSITION 60;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT5 POSITION 61;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV5 POSITION 62;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTLOTNEG POSITION 63;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTNEG POSITION 64;

ALTER TABLE SGPREFERE1 ALTER COLUMN NATVENDA POSITION 65;

ALTER TABLE SGPREFERE1 ALTER COLUMN IPIVENDA POSITION 66;

ALTER TABLE SGPREFERE1 ALTER COLUMN CUSTOSICMS POSITION 67;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPPG POSITION 68;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALPG POSITION 69;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANOPAG POSITION 70;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTB POSITION 71;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTB POSITION 72;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTAB POSITION 73;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPCE POSITION 74;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALCE POSITION 75;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODCLASCLI POSITION 76;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDEC POSITION 77;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDECFIN POSITION 78;

ALTER TABLE SGPREFERE1 ALTER COLUMN COMISPDUPL POSITION 79;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT6 POSITION 80;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT6 POSITION 81;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV6 POSITION 82;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQVENDA POSITION 83;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQCOMPRA POSITION 84;

ALTER TABLE SGPREFERE1 ALTER COLUMN VENDAMATPRIM POSITION 85;

ALTER TABLE SGPREFERE1 ALTER COLUMN VENDAPATRIM POSITION 86;

ALTER TABLE SGPREFERE1 ALTER COLUMN PEPSPROD POSITION 87;

ALTER TABLE SGPREFERE1 ALTER COLUMN CNPJFOROBRIG POSITION 88;

ALTER TABLE SGPREFERE1 ALTER COLUMN INSCESTFOROBRIG POSITION 89;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCAPRODSIMILAR POSITION 90;

ALTER TABLE SGPREFERE1 ALTER COLUMN MULTIALMOX POSITION 91;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT8 POSITION 92;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT8 POSITION 93;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV8 POSITION 94;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTNEGGRUP POSITION 95;

ALTER TABLE SGPREFERE1 ALTER COLUMN USATABPE POSITION 96;

ALTER TABLE SGPREFERE1 ALTER COLUMN TAMDESCPROD POSITION 97;

ALTER TABLE SGPREFERE1 ALTER COLUMN DESCCOMPPED POSITION 98;

ALTER TABLE SGPREFERE1 ALTER COLUMN OBSCLIVEND POSITION 99;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONTESTOQ POSITION 100;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIASPEDT POSITION 101;

ALTER TABLE SGPREFERE1 ALTER COLUMN RECALCPCVENDA POSITION 102;

ALTER TABLE SGPREFERE1 ALTER COLUMN RECALCPCORC POSITION 103;

ALTER TABLE SGPREFERE1 ALTER COLUMN USALAYOUTPED POSITION 104;

ALTER TABLE SGPREFERE1 ALTER COLUMN VERIFALTPARCVENDA POSITION 105;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCACODPRODGEN POSITION 106;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENPROD POSITION 107;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENREF POSITION 108;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODBAR POSITION 109;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODFAB POSITION 110;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODFOR POSITION 111;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCAVLRULTCOMPRA POSITION 112;

ALTER TABLE SGPREFERE1 ALTER COLUMN ICMSVENDA POSITION 113;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPRECOZERO POSITION 114;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIMGASSORC POSITION 115;

ALTER TABLE SGPREFERE1 ALTER COLUMN IMGASSORC POSITION 116;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTCPFCLI POSITION 117;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIECLI POSITION 118;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIEFOR POSITION 119;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTECPFFOR POSITION 120;

ALTER TABLE SGPREFERE1 ALTER COLUMN USANOMEVENDORC POSITION 121;

ALTER TABLE SGPREFERE1 ALTER COLUMN SISCONTABIL POSITION 122;

ALTER TABLE SGPREFERE1 ALTER COLUMN ATBANCOIMPBOL POSITION 123;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCODBAR POSITION 124;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICORCOBSPED POSITION 125;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMENSORC POSITION 126;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMENSORC POSITION 127;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMENSORC POSITION 128;

ALTER TABLE SGPREFERE1 ALTER COLUMN CUSTOCOMPRA POSITION 129;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABTRANSPCP POSITION 130;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABTRANSPORC POSITION 131;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABSOLCP POSITION 132;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICFRETEBASEICM POSITION 133;

ALTER TABLE SGPREFERE1 ALTER COLUMN PRECOCPREL POSITION 134;

ALTER TABLE SGPREFERE1 ALTER COLUMN DESCORC POSITION 135;

ALTER TABLE SGPREFERE1 ALTER COLUMN MULTICOMIS POSITION 136;

ALTER TABLE SGPREFERE1 ALTER COLUMN USUATIVCLI POSITION 137;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPHISTREC POSITION 138;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALHISTREC POSITION 139;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODHISTREC POSITION 140;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPHISTPAG POSITION 141;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALHISTPAG POSITION 142;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODHISTPAG POSITION 143;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTC POSITION 144;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTC POSITION 145;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOCLI POSITION 146;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTITRECALTDTVENC POSITION 147;

ALTER TABLE SGPREFERE1 ALTER COLUMN LCREDGLOBAL POSITION 148;

ALTER TABLE SGPREFERE1 ALTER COLUMN VDMANUTCOMOBRIG POSITION 149;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSPED POSITION 150;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCLASSPED POSITION 151;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGECLI POSITION 152;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGEFOR POSITION 153;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGETRANSP POSITION 154;

ALTER TABLE SGPREFERE1 ALTER COLUMN SOMAVOLUMES POSITION 155;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCACEP POSITION 156;

ALTER TABLE SGPREFERE1 ALTER COLUMN URLWSCEP POSITION 157;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSCP POSITION 158;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS01CP POSITION 159;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS02CP POSITION 160;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS03CP POSITION 161;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS04CP POSITION 162;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIEPF POSITION 163;

ALTER TABLE SGPREFERE1 ALTER COLUMN CREDICMSSIMPLES POSITION 164;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMS POSITION 165;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMS POSITION 166;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMENSICMSSIMPLES POSITION 167;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERACOMISVENDAORC POSITION 168;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERACODUNIF POSITION 169;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV9 POSITION 170;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT9 POSITION 171;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT9 POSITION 172;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPJP POSITION 173;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALJP POSITION 174;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANJP POSITION 175;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPJR POSITION 176;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALJR POSITION 177;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANJR POSITION 178;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPDR POSITION 179;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALDR POSITION 180;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANDR POSITION 181;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPDC POSITION 182;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALDC POSITION 183;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANDC POSITION 184;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERAPAGEMIS POSITION 185;

ALTER TABLE SGPREFERE1 ALTER COLUMN LANCAFINCONTR POSITION 186;

ALTER TABLE SGPREFERE1 ALTER COLUMN LANCARMACONTR POSITION 187;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDECPRE POSITION 188;

ALTER TABLE SGPREFERE1 ALTER COLUMN VISUALIZALUCR POSITION 189;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSNFE POSITION 190;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIRNFE POSITION 191;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIRNFELIN POSITION 192;

ALTER TABLE SGPREFERE1 ALTER COLUMN FORMATODANFE POSITION 193;

ALTER TABLE SGPREFERE1 ALTER COLUMN AMBIENTENFE POSITION 194;

ALTER TABLE SGPREFERE1 ALTER COLUMN PROCEMINFE POSITION 195;

ALTER TABLE SGPREFERE1 ALTER COLUMN VERPROCNFE POSITION 196;

ALTER TABLE SGPREFERE1 ALTER COLUMN KEYLICNFE POSITION 197;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTVENCTONFE POSITION 198;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFADPRODNFE POSITION 199;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPNF POSITION 200;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALNF POSITION 201;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMAILNF POSITION 202;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFCPDEVOLUCAO POSITION 203;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFVDREMESSA POSITION 204;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERARECEMIS POSITION 205;

ALTER TABLE SGPREFERE1 ALTER COLUMN RETENSAOIMP POSITION 206;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCUSTOLUC POSITION 207;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABIMPORTCP POSITION 208;

ALTER TABLE SGPREFERE1 ALTER COLUMN HABVLRTOTITORC POSITION 209;

ALTER TABLE SGPREFERE1 ALTER COLUMN USABUSCAGENPRODCP POSITION 210;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICOBSORCPED POSITION 211;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPRECOCOT POSITION 212;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQPRECOAPROV POSITION 213;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPFT POSITION 214;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALFT POSITION 215;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOFORFT POSITION 216;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTINS POSITION 217;

ALTER TABLE SGPREFERE1 ALTER COLUMN HINS POSITION 218;

ALTER TABLE SGPREFERE1 ALTER COLUMN IDUSUINS POSITION 219;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTALT POSITION 220;

ALTER TABLE SGPREFERE1 ALTER COLUMN HALT POSITION 221;

ALTER TABLE SGPREFERE1 ALTER COLUMN IDUSUALT POSITION 222;

/* Create(Add) Crant */
GRANT DELETE, INSERT, SELECT, UPDATE ON EQITRECMERCITCP TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNTALAOCHEQ TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON RHTABELAINSS TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON RHTABELAIRRF TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGBAIRRO TO ADM;


