INSERT INTO CRMOTIVOFB (ID, CODEMP, CODFILIAL, DESCRICAO, TIPO)
                VALUES (1, #CODEMP#, 1, 'Sugestão', '00');
INSERT INTO CRMOTIVOFB (ID, CODEMP, CODFILIAL, DESCRICAO, TIPO)
                VALUES (2, #CODEMP#, 1, 'Crítica', '00');
INSERT INTO CRMOTIVOFB (ID, CODEMP, CODFILIAL, DESCRICAO, TIPO)
                VALUES (3, #CODEMP#, 1, 'Dúvida', '00');
INSERT INTO CRMOTIVOFB (ID, CODEMP, CODFILIAL, DESCRICAO, TIPO)
                VALUES (4, #CODEMP#, 1, 'Avaliação do website', '00');

INSERT INTO  SGSEQUENCE_ID (table_name, seq_id)
values ('CRMOTIVOFB', 4);

COMMIT WORK;
