/* Server Version: LI-V6.3.3.4870 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

SET AUTODDL ON;

Update Rdb$Relation_Fields set Rdb$Description =
'Preço base do produto (primeiro preço de venda) base para geração de outras tabelas de preço.'
where Rdb$Relation_Name='EQPRODUTO' and Rdb$Field_Name='PRECOBASEPROD';

/* Alter Field (Length): from 1 to 2... */
UPDATE RDB$FIELDS SET RDB$FIELD_LENGTH=2, RDB$CHARACTER_LENGTH=2
  WHERE RDB$FIELD_NAME=(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
  WHERE RDB$RELATION_NAME='FNCARTCOB' AND  RDB$FIELD_NAME='CARTCOBCNAB');

/* Alter Field (Length): from 100 to 250... */
UPDATE RDB$FIELDS SET RDB$FIELD_LENGTH=250, RDB$CHARACTER_LENGTH=250
  WHERE RDB$FIELD_NAME=(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
  WHERE RDB$RELATION_NAME='FNLANCA' AND  RDB$FIELD_NAME='HISTBLANCA');

/* Alter Field (Length): from 100 to 250... */
UPDATE RDB$FIELDS SET RDB$FIELD_LENGTH=250, RDB$CHARACTER_LENGTH=250
  WHERE RDB$FIELD_NAME=(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
  WHERE RDB$RELATION_NAME='FNSUBLANCA' AND  RDB$FIELD_NAME='HISTSUBLANCA');


ALTER TABLE EQPRODUTO ADD PRECOCOMISPROD NUMERICDN;

Update Rdb$Relation_Fields set Rdb$Description =
'Preço base do produto para cálculo de comissões especiais.'
where Rdb$Relation_Name='EQPRODUTO' and Rdb$Field_Name='PRECOCOMISPROD';

ALTER TABLE FNCHEQUE ADD DDDFAVCHEQ VARCHAR(4);

Update Rdb$Relation_Fields set Rdb$Description =
'DDD do favorecido do cheque'
where Rdb$Relation_Name='FNCHEQUE' and Rdb$Field_Name='DDDFAVCHEQ';

ALTER TABLE FNCHEQUE ADD FONEFAVCHEQ VARCHAR(8);

Update Rdb$Relation_Fields set Rdb$Description =
'Telefone do favorecido'
where Rdb$Relation_Name='FNCHEQUE' and Rdb$Field_Name='FONEFAVCHEQ';

ALTER TABLE SGPREFERE1 ADD USAPRECOCOMIS CHAR(1) DEFAULT 'N' NOT NULL;

Update Rdb$Relation_Fields set Rdb$Description =
'Indica se deve utilizar o preço para comissionamento do cadastro de produtos, para calculo de comissioament especial por seção de produção.'
where Rdb$Relation_Name='SGPREFERE1' and Rdb$Field_Name='USAPRECOCOMIS';

ALTER TABLE VDITREGRACOMIS ADD CODEMPVD INTEGER;

Update Rdb$Relation_Fields set Rdb$Description =
'Código da empresa do vendedor.'
where Rdb$Relation_Name='VDITREGRACOMIS' and Rdb$Field_Name='CODEMPVD';

ALTER TABLE VDITREGRACOMIS ADD CODFILIALVD SMALLINT;

Update Rdb$Relation_Fields set Rdb$Description =
'Código da filial do vendedor '
where Rdb$Relation_Name='VDITREGRACOMIS' and Rdb$Field_Name='CODFILIALVD';

ALTER TABLE VDITREGRACOMIS ADD CODVEND INTEGER;

Update Rdb$Relation_Fields set Rdb$Description =
'Código do vendedor.'
where Rdb$Relation_Name='VDITREGRACOMIS' and Rdb$Field_Name='CODVEND';

ALTER TABLE VDREGRACOMIS ADD CODEMPSC INTEGER;

ALTER TABLE VDREGRACOMIS ADD CODFILIALSC SMALLINT;

ALTER TABLE VDREGRACOMIS ADD CODSECAO VARCHAR(13);

ALTER TABLE VDVENDEDOR ADD CODEMPSC INTEGER;

ALTER TABLE VDVENDEDOR ADD CODFILIALSC SMALLINT;

ALTER TABLE VDVENDEDOR ADD CODSECAO VARCHAR(13);

DROP VIEW VWCUSTOPROJ01;

/* Create view: VWCUSTOPROJ01 (ViwData.CreateDependDef) */
CREATE VIEW VWCUSTOPROJ01(
CODEMP,
CODFILIAL,
CODCLI,
DATA,
DESCCUSTO,
CODCONTR,
CODITCONTR,
TPCONTR,
VLRPREVREC,
QTDCUSTO,
VLRCUSTO,
TIPOCUSTO)
 AS 
select ad.codemp, ad.codfilial, ad.codcli, ad.dataatendo ,cast('Hora trabalhada - ' || rtrim(ae.nomeatend)  as varchar(200)) as desccusto, ad.codcontr,ad.coditcontr, co.tpcontr ,ic.vlritcontr * ic.qtditcontr as vlrreceitaprev,
 ( ad.horaatendofin  - ad.horaatendo ) / 3600 as qtd , sa.custohoratrab as custo, 'M' as tipo
from
vditcontrato ic, atatendimento ad, atatendente ae, rhempregado em, rhempregadosal sa, vdcontrato co
where
ic.codemp=ad.codempct and ic.codfilial=ad.codfilialct and ic.codcontr=ad.codcontr and ic.coditcontr=ad.coditcontr and
co.codemp=ic.codemp and co.codfilial=ic.codfilial and co.codcontr=ic.codcontr and
ae.codemp=ad.codempae and ae.codfilial=ad.codfilialae and ae.codatend=ad.codatend and
em.codemp=ae.codempep and em.codfilial=ae.codfilialep and em.matempr=ae.matempr and
sa.codemp=em.codemp and sa.codfilial=em.codfilial and sa.matempr=em.matempr and sa.seqsal=
(
    select first 1 seqsal from rhempregadosal s1 where s1.codemp=em.codemp and
    s1.codfilial=em.codfilial and s1.matempr=em.matempr and
    s1.dtvigor < cast('today' as date) order by s1.dtvigor desc
)
-- Custos de outras despesas financeiras;
union
select sl.codemp, sl.codfilial, co.codcli, sl.datasublanca, cast(sl.histsublanca as varchar(200)) as desccusto, ic.codcontr, ic.coditcontr, co.tpcontr ,ic.vlritcontr * ic.qtditcontr as vlrreceitaprev,
1.00 as qtd, sl.vlrsublanca  as custo, 'F' as tipo
from
vditcontrato ic, vdcontrato co, fnsublanca sl, fnplanejamento pl
where
ic.codemp=sl.codempct and ic.codfilial=sl.codfilialct and ic.codcontr=sl.codcontr and ic.coditcontr=sl.coditcontr and
co.codemp=ic.codemp and co.codfilial=ic.codfilial and co.codcontr=ic.codcontr
and pl.codemp=sl.codemppn and pl.codfilial=sl.codfilialpn and pl.codplan=sl.codplan and pl.tipoplan='D'
union
--Custos de estoque
select ir.codemp, ir.codfilial, co.codcli, rma.dtaexprma, cast(pd.descprod as varchar(200)) as desccusto ,ic.codcontr, ic.coditcontr, co.tpcontr, ic.vlritcontr * ic.qtditcontr as vlrreceitaprev,
ir.qtdexpitrma as qtd, ir.precoitrma as custo, 'E' as tipo
from
vditcontrato ic, vdcontrato co, eqrma rma, eqitrma ir, eqproduto pd
where ic.codemp=rma.codempct and ic.codfilial=rma.codfilialct and ic.codcontr=rma.codcontr and ic.coditcontr=rma.coditcontr and
co.codemp=ic.codemp and co.codfilial=ic.codfilial and co.codcontr=ic.codcontr
and ir.codemp=rma.codemp and ir.codfilial=rma.codfilial and ir.codrma=rma.codrma and
pd.codemp=ir.codemppd and pd.codfilial=ir.codfilialpd and pd.codprod=ir.codprod and
ir.sitexpitrma='ET'
;

/* Create Foreign Key... */
--CONNECT 'localhost:/opt/firebird/dados/desenv/1.2.3.4/freedom.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

ALTER TABLE FNCHEQUE ADD CONSTRAINT FNCHEQUEFKFNBANCO FOREIGN KEY (CODBANC,CODFILIALBO,CODEMPBO) REFERENCES FNBANCO(CODBANCO,CODFILIAL,CODEMP);

ALTER TABLE VDITREGRACOMIS ADD CONSTRAINT VDITREGRACOMISFKVENDEDOR FOREIGN KEY (CODVEND,CODFILIALVD,CODEMPVD) REFERENCES VDVENDEDOR(CODVEND,CODFILIAL,CODEMP);

ALTER TABLE VDREGRACOMIS ADD CONSTRAINT VDREGRACOMISFKEQSECAO FOREIGN KEY (CODSECAO,CODFILIALSC,CODEMPSC) REFERENCES EQSECAO(CODSECAO,CODFILIAL,CODEMP);

ALTER TABLE VDVENDEDOR ADD CONSTRAINT VDVENDEDORFKEQSETOR FOREIGN KEY (CODSECAO,CODFILIALSC,CODEMPSC) REFERENCES EQSECAO(CODSECAO,CODFILIAL,CODEMP);

SET TERM ^ ;

ALTER TRIGGER FNITRECEBERTGAU
 AS Declare variable I integer;
BEGIN I = 0; END
^

ALTER TRIGGER FNITPAGARTGBU
 AS Declare variable I integer;
BEGIN I = 0; END
^

/* Alter Procedure... */
/* Alter (FNADICLANCASP01) */
ALTER PROCEDURE FNADICLANCASP01(ICODREC INTEGER,
INPARCITREC INTEGER,
PDVITREC CHAR(1),
SNUMCONTA CHAR(10),
ICODEMPCA INTEGER,
ICODFILIALCA INTEGER,
ICODCLI INTEGER,
ICODEMPCL INTEGER,
ICODFILIALCL INTEGER,
SCODPLAN CHAR(13),
ICODEMPPN INTEGER,
ICODFILIALPN INTEGER,
IANOCC INTEGER,
SCODCC CHAR(19),
ICODEMPCC INTEGER,
ICODFILIALCC INTEGER,
DDTPAGOITREC DATE,
SDOCLANCAITREC CHAR(10),
SOBSITREC CHAR(250),
DVLRPAGOITREC NUMERIC(15,5),
ICODEMP INTEGER,
ICODFILIAL SMALLINT,
DVLRPAGOJUROS NUMERIC(15,5),
DVLRDESC NUMERIC(15,5))
 AS
declare variable icodlanca integer;
declare variable scodplanconta char(13);
declare variable icodemppconta integer;
declare variable icodfilialpconta integer;
declare variable cflag char(1);
declare variable ifiliallanca integer;
declare variable tipolanca char(1);
declare variable codempjr integer;
declare variable codfilialjr smallint;
declare variable codplanjr char(13);
declare variable codempdc integer;
declare variable codfilialdc smallint;
declare variable codplandc char(13);
declare variable codsublanca smallint = 1;
BEGIN
    SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'FNLANCA') INTO IFILIALLANCA;

    SELECT CODPLAN,CODEMPPN,CODFILIALPN FROM FNCONTA WHERE NUMCONTA = :SNUMCONTA
        AND CODEMP=:ICODEMPCA AND CODFILIAL=:ICODFILIALCA INTO :sCodPlanConta,:iCodEmpPConta,:iCodFilialPConta;

    SELECT ISEQ FROM SPGERANUM(:ICODEMP,:IFILIALLANCA,'LA') INTO ICODLANCA;

    SELECT FLAG FROM FNRECEBER WHERE CODREC=:ICODREC
        AND CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL INTO :cFlag;

    SELECT CODEMPJR,CODFILIALJR,CODPLANJR,CODEMPDC,CODFILIALDC,CODPLANDC FROM SGPREFERE1
        WHERE CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
        INTO :CODEMPJR,:CODFILIALJR,:CODPLANJR,:CODEMPDC,:CODFILIALDC,:CODPLANDC;


    IF (ICODCLI IS NULL) THEN
        TIPOLANCA = 'A';
    ELSE
        TIPOLANCA = 'C';

    if ( (DVLRPAGOJUROS IS NULL) OR (:CODPLANJR IS NULL)  ) then
        DVLRPAGOJUROS = 0;
    else
        DVLRPAGOITREC = DVLRPAGOITREC - DVLRPAGOJUROS;

    if (DVLRDESC IS NULL  OR (:CODPLANDC IS NULL) ) then
        DVLRDESC = 0;
    else
        DVLRPAGOITREC = DVLRPAGOITREC + DVLRDESC;


    INSERT INTO FNLANCA (TIPOLANCA,CODEMP,CODFILIAL,CODLANCA,CODEMPRC,CODFILIALRC,CODREC,NPARCITREC,CODEMPPN,CODFILIALPN,
                         CODPLAN,DATALANCA,DOCLANCA,HISTBLANCA,DTPREVLANCA,VLRLANCA,FLAG,CODEMPCL,CODFILIALCL,CODCLI,PDVITREC)
        VALUES (:TIPOLANCA,:ICODEMP,:IFILIALLANCA,:iCodLanca,:ICODEMP,:ICODFILIAL,:ICODREC,:iNParcItRec,:iCodEmpPConta,:iCodFilialPConta,
                :sCodPlanConta,:dDtPagoItRec,:sDocLancaItRec,:sObsItRec,:dDtPagoItRec,0,:cFlag,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:PDVITREC
        );

    INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPCL,CODFILIALCL,CODCLI,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,
                            CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:ICODEMPPN,:ICODFILIALPN,:SCODPLAN,:ICODEMPCC,
                :ICODFILIALCC,:IANOCC,:SCODCC,'S',:dDtPagoItRec,:dDtPagoItRec,:dVlrPagoItRec*-1,:cFlag
        );

    -- Lançamento dos juros em conta distinta.

    IF(DVLRPAGOJUROS > 0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPCL,CODFILIALCL,CODCLI,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,
                            CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:CODEMPJR,:CODFILIALJR,:CODPLANJR,:ICODEMPCC,
                :ICODFILIALCC,:IANOCC,:SCODCC,'S',:dDtPagoItRec,:dDtPagoItRec,:DVLRPAGOJUROS*-1,:cFlag
        );

    END

    -- Lançamento do desconto em conta distinta.

    IF(DVLRDESC > 0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPCL,CODFILIALCL,CODCLI,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,
                            CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:CODEMPDC,:CODFILIALDC,:CODPLANDC,:ICODEMPCC,
                :ICODFILIALCC,:IANOCC,:SCODCC,'S',:dDtPagoItRec,:dDtPagoItRec,:DVLRDESC,:cFlag
        );

    END


END
^

/* Alter (FNADICLANCASP02) */
ALTER PROCEDURE FNADICLANCASP02(ICODPAG INTEGER,
INPARCPAG INTEGER,
SNUMCONTA CHAR(10),
ICODEMPCA INTEGER,
ICODFILIALCA INTEGER,
ICODFOR INTEGER,
ICODEMPFR INTEGER,
ICODFILIALFR INTEGER,
SCODPLAN CHAR(13),
ICODEMPPN INTEGER,
ICODFILIALPN INTEGER,
IANOCC INTEGER,
SCODCC CHAR(19),
ICODEMPCC INTEGER,
ICODFILIALCC INTEGER,
DDTPAGOITPAG DATE,
SDOCLANCAITPAG CHAR(10),
SOBSITPAG CHAR(250),
DVLRPAGOITPAG NUMERIC(15,5),
ICODEMP INTEGER,
ICODFILIAL SMALLINT,
DVLRJUROSPAG NUMERIC(15,5),
DVLRDESC NUMERIC(15,5))
 AS
declare variable icodlanca integer;
declare variable scodplanconta char(13);
declare variable icodemppconta integer;
declare variable icodfilialpconta integer;
declare variable cflag char(1);
declare variable ifiliallanca integer;
declare variable tipolanca char(1);
declare variable codempjp integer;
declare variable codfilialjp smallint;
declare variable codplanjp char(13);
declare variable codempdr integer;
declare variable codfilialdr smallint;
declare variable codplandr char(13);
declare variable codsublanca smallint = 1;
BEGIN

    SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'FNLANCA')
    INTO IFILIALLANCA;

    SELECT CODPLAN,CODEMP,CODFILIAL FROM FNCONTA
    WHERE NUMCONTA=:sNumConta AND CODEMP=:ICODEMPCA AND CODFILIAL=:ICODFILIALCA
    INTO :sCodPlanConta,:iCodEmpPConta,:iCodFilialPConta;

    SELECT ISEQ FROM SPGERANUM(:iCODEMP,:IFILIALLANCA,'LA')
    INTO :iCodLanca;

    SELECT FLAG FROM FNPAGAR
    WHERE CODPAG=:iCodPag AND CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
    INTO :cFlag;

    SELECT CODEMPJP,CODFILIALJP,CODPLANJP,CODEMPDR,CODFILIALDR,CODPLANDR
    FROM SGPREFERE1
    WHERE CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
    INTO :CODEMPJP,:CODFILIALJP,:CODPLANJP,:CODEMPDR,:CODFILIALDR,:CODPLANDR;

    IF (ICODFOR IS NULL) THEN
        TIPOLANCA = 'A';
      ELSE
        TIPOLANCA = 'F';

    if ( (DVLRJUROSPAG IS NULL) OR (:CODPLANJP IS NULL)  ) then
        DVLRJUROSPAG = 0;
    else
        DVLRPAGOITPAG = DVLRPAGOITPAG - DVLRJUROSPAG;

    if (DVLRDESC IS NULL  OR (:CODPLANDR IS NULL) ) then
        DVLRDESC = 0;
    else
        DVLRPAGOITPAG = DVLRPAGOITPAG + DVLRDESC;


    INSERT INTO FNLANCA (TIPOLANCA,CODEMP,CODFILIAL,CODLANCA,CODEMPPG,CODFILIALPG,CODPAG,
                         NPARCPAG,CODEMPPN,CODFILIALPN,CODPLAN,DATALANCA,DOCLANCA,
                         HISTBLANCA,DTPREVLANCA,VLRLANCA,FLAG, CODEMPFR, CODFILIALFR, CODFOR)
         VALUES (:TIPOLANCA,:ICODEMP,:IFILIALLANCA,:iCodLanca,:ICODEMP,:ICODFILIAL,:iCodPag,
                 :iNParcPag,:iCodEmpPConta,:iCodFilialPConta,:sCodPlanConta,:dDtPagoItPag,:sDocLancaItPag,
                 :sObsItPag,:dDtPagoItPag,0,:cFlag, :ICODEMPFR, :ICODFILIALFR, :ICODFOR
         );

    INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:ICODEMPPN,:ICODFILIALPN,:sCodplan,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:dVlrPagoItPag,:cFlag);

    -- Lançamento dos juros em conta distinta.

    IF(DVLRJUROSPAG >0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
            VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:CODEMPJP,:CODFILIALJP,:CODPLANJP,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:DVLRJUROSPAG,:cFlag);

    END

    -- Lançamento de desconto em conta distinta.

    IF(DVLRDESC >0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
            VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:CODEMPDR,:CODFILIALDR,:CODPLANDR,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:DVLRDESC*-1,:cFlag);

    END

END
^

/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.3.5 (28/08/2010)';
    suspend;
end
^

/* Alter exist trigger... */
ALTER TRIGGER FNITPAGARTGBU
AS
  DECLARE VARIABLE IFILIALPAG INTEGER;
  DECLARE VARIABLE ICODFOR INTEGER;
  DECLARE VARIABLE ICODEMPFR INTEGER;
  DECLARE VARIABLE ICODFILIALFR INTEGER;
BEGIN

  new.DTALT=cast('now' AS DATE);
  new.IDUSUALT=USER;
  new.HALT = cast('now' AS TIME);

  IF ( new.EMMANUT IS NULL ) THEN
  BEGIN
      new.EMMANUT = 'S';
  END

  IF ( not ( (new.EMMANUT='S') or ( (old.EMMANUT='S') and (old.EMMANUT is not null)) ) ) THEN
  BEGIN

     SELECT ICODFILIAL FROM SGRETFILIAL(new.CODEMP,'FNPAGAR') INTO IFILIALPAG;
     IF ((old.STATUSITPAG IN ('PP','PL') )  AND (new.STATUSITPAG='P1') ) THEN
     BEGIN
       DELETE FROM FNLANCA WHERE CODPAG=new.CODPAG AND NPARCPAG=new.NPARCPAG
              AND CODEMPPG=new.CODEMP AND CODFILIALPG = new.CODFILIAL
              AND CODEMP=new.CODEMP AND CODFILIAL=:IFILIALPAG;

       new.VLRPAGOITPAG = 0;
       new.DTPAGOITPAG = NULL;

     END
     ELSE IF ( (old.STATUSITPAG='P1') AND ( new.STATUSITPAG='CP' ) ) THEN
     BEGIN
        IF ( (new.OBSITPAG IS NULL) OR (rtrim(new.OBSITPAG)='') ) THEN
        BEGIN
           EXCEPTION FNITPAGAREX01;
        END
        new.VLRCANCITPAG = new.VLRAPAGITPAG;
        new.VLRPARCITPAG = 0;
        new.VLRDESCITPAG = 0;
        new.VLRJUROSITPAG = 0;
        new.VLRDEVITPAG = 0;
        new.VLRITPAG = 0;
     END

     new.VLRITPAG = new.VLRPARCITPAG - new.VLRDESCITPAG - new.VLRDEVITPAG + new.VLRJUROSITPAG +
     new.VLRMULTAITPAG + new.VLRADICITPAG;
     new.VLRAPAGITPAG = new.VLRITPAG - new.VLRPAGOITPAG;
  
     if (new.VLRAPAGITPAG < 0) then /* se o valor a pagar for menor que zero */
       new.VLRAPAGITPAG = 0;  /* então valor a pagar será zero */
     if ( (new.VLRAPAGITPAG=0) AND (new.VLRITPAG>0) ) then /* se o valor a pagar for igual a zero e existir valor na parcela*/
       new.STATUSITPAG = 'PP';  /* então o status será PP(pagamento completo) */
     else if ( (new.VLRPAGOITPAG>0) AND (new.VLRITPAG>0) ) then /* caso contrário e o valor pago maior que zero e existir valor na parcela*/
       new.STATUSITPAG = 'PL'; /*  então o status será PL(pagamento parcial) */

     /* faz o lançamento */
     SELECT CODFOR,CODEMPFR,CODFILIALFR FROM FNPAGAR WHERE CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL AND CODPAG=new.CODPAG
        INTO ICODFOR,ICODEMPFR,ICODFILIALFR;

     IF ((old.STATUSITPAG='P1' AND new.STATUSITPAG in ('PP','PL')) OR (old.STATUSITPAG in ('PP','PL') AND new.STATUSITPAG in ('PP','PL') AND new.VLRPAGOITPAG > 0)) THEN
     BEGIN

       EXECUTE PROCEDURE FNADICLANCASP02(new.CodPag,new.NParcPag,new.NumConta,new.CODEMPCA,new.CODFILIALCA,:ICODFOR,:ICODEMPFR,:ICODFILIALFR,
                              new.CodPlan,new.CODEMPPN,new.CODFILIALPN,new.AnoCC,new.CodCC,new.CODEMPCC,new.CODFILIALCC,
                              new.DtPagoItPag,new.DocLancaItPag,new.ObsItPag,new.VlrPagoItPag,new.CODEMP,new.CODFILIAL,new.vlrjurositpag,new.vlrdescitpag);

       /* Altera o valor pago e o valor a pagar */
       new.VLRPAGOITPAG = new.VLRPAGOITPAG + old.VLRPAGOITPAG;
       new.VLRAPAGITPAG = new.VLRITPAG - new.VLRPAGOITPAG;

       if (new.VLRAPAGITPAG < 0) then /* se o valor a pagar for menor que zero */
         new.VLRAPAGITPAG = 0;  /* então valor a pagar será zero */

       if (new.VLRAPAGITPAG=0) then /* se o valor a pagar for igual a zero */
         new.STATUSITPAG = 'PP';  /* então o status será PP(pagamento completo) */
       else if (new.VLRPAGOITPAG>0) then /* caso contrário e o valor pago maior que zero */
         new.STATUSITPAG = 'PL'; /*  então o status será PL(pagamento parcial) */

     END
     ELSE IF ((old.STATUSITPAG='PP') AND (new.STATUSITPAG='PP')) THEN
     BEGIN
        EXCEPTION FNPAGAREX01;
     END

   END

END
^

/* Alter exist trigger... */
ALTER TRIGGER FNITRECEBERTGAU
AS
  DECLARE VARIABLE ICODCLI INTEGER;
  DECLARE VARIABLE ICODEMPCL INTEGER;
  DECLARE VARIABLE ICODFILIALCL INTEGER;
  DECLARE VARIABLE SCODFILIALCI SMALLINT;
  DECLARE VARIABLE SCODFILIALLC SMALLINT;
  DECLARE VARIABLE ESTITRECALTDTVENC CHAR(1);
  DECLARE VARIABLE AUTOBAIXAPARC CHAR(1);
BEGIN
  SELECT ESTITRECALTDTVENC FROM SGPREFERE1 WHERE CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL INTO :ESTITRECALTDTVENC;
  SELECT ITPP.AUTOBAIXAPARC FROM FNPARCPAG ITPP, FNRECEBER R
    WHERE ITPP.CODEMP=R.CODFILIALPG AND ITPP.CODFILIAL=R.CODFILIALPG AND ITPP.CODPLANOPAG=R.CODPLANOPAG AND
      ITPP.NROPARCPAG=new.NPARCITREC AND
       R.CODEMP=new.CODEMP AND R.CODFILIAL=new.CODFILIAL AND R.CODREC=new.CODREC
    INTO :AUTOBAIXAPARC;
  IF  ( ( (old.STATUSITREC IN ('RP','RL') )  AND (new.STATUSITREC='R1') ) OR
        ( (ESTITRECALTDTVENC='S') AND (AUTOBAIXAPARC='S') AND
          (old.DTVENCITREC<>new.DTVENCITREC) ) ) THEN
  BEGIN
    SELECT ICODFILIAL FROM SGRETFILIAL(new.CODEMP,'FNCOMISSAO') INTO :SCODFILIALCI;
    SELECT ICODFILIAL FROM SGRETFILIAL(new.CODEMP,'FNLANCA') INTO :SCODFILIALLC;
    UPDATE VDCOMISSAO SET STATUSCOMI='C1'
           WHERE CODREC=new.CODREC AND NPARCITREC=new.NPARCITREC
           AND CODEMPRC = new.CODEMP AND CODFILIALRC=new.CODFILIAL
           AND CODEMP=new.CODEMP AND CODFILIAL=:SCODFILIALCI
           AND STATUSCOMI NOT IN ('CE') AND TIPOCOMI='R';
    DELETE FROM FNLANCA WHERE CODREC=new.CODREC AND NPARCITREC=new.NPARCITREC
           AND CODEMPRC= new.CODEMP AND CODFILIALRC=new.CODFILIAL
           AND CODEMP=new.CODEMP AND CODFILIAL = :SCODFILIALLC;
  END
  ELSE IF ((old.STATUSITREC='R1' AND new.STATUSITREC in ('RP','RL')) OR
           (old.STATUSITREC in ('RP','RL') AND new.STATUSITREC in ('RP','RL') AND new.VLRPAGOITREC > 0) OR
           (old.STATUSITREC = 'RB' AND new.STATUSITREC = 'RP')) THEN
  BEGIN
     SELECT CODCLI,CODEMPCL,CODFILIALCL FROM FNRECEBER WHERE CODEMP=new.CODEMP AND
        CODFILIAL=new.CODFILIAL AND CODREC=new.CODREC
        INTO ICODCLI,ICODEMPCL,ICODFILIALCL;
     IF ((new.VLRPAGOITREC-old.VLRPAGOITREC) > 0) THEN
     BEGIN
        EXECUTE PROCEDURE FNADICLANCASP01(new.CodRec,new.NParcItRec,new.PDVITREC,new.NumConta,new.CODEMPCA,new.CODFILIALCA,:ICODCLI,:ICODEMPCL,:ICODFILIALCL,
                           new.CodPlan,new.CODEMPPN,new.CODFILIALPN,new.ANOCC,new.CODCC,new.CODEMPCC,new.CODFILIALCC,new.DtPagoItRec,new.DocLancaItRec,
                           SUBSTRING(new.ObsItRec FROM 1 FOR 50),new.VlrPagoItRec-old.VlrPagoItRec,new.CODEMP,new.CODFILIAL,new.vlrjurositrec,new.vlrdescitrec);
     END
     IF (new.STATUSITREC = 'RP') THEN
     BEGIN
         UPDATE VDCOMISSAO SET STATUSCOMI='C2'
            WHERE CODREC=old.CODREC
            AND CODEMPRC=old.CODEMP
            AND CODFILIALRC=old.CODFILIAL
            AND NPARCITREC=old.NPARCITREC
            AND NOT STATUSCOMI IN ('CP','C2')
            AND CODEMP=old.CODEMP;
     END
  END
  ELSE IF (old.VLRCOMIITREC != new.VLRCOMIITREC) THEN
  BEGIN
     EXECUTE PROCEDURE vdgeracomissaosp(new.CODEMP, new.CODFILIAL, new.CODREC,
        new.NPARCITREC, new.VLRCOMIITREC, new.DTVENCITREC);
  END





  IF ( (new.ALTUSUITREC='S') AND ( (old.VLRITREC!=new.VLRITREC) OR
       (old.VLRDESCITREC!=new.VLRDESCITREC) OR (old.VLRMULTAITREC!=new.VLRMULTAITREC) OR
       (old.VLRJUROSITREC!=new.VLRJUROSITREC) OR (old.VLRPARCITREC!=new.VLRPARCITREC) OR
       (old.VLRPAGOITREC!=new.VLRPAGOITREC) OR (old.VLRAPAGITREC!=new.VLRAPAGITREC) ) ) THEN
     UPDATE FNRECEBER SET VLRREC = VLRREC - old.VLRITREC + new.VLRITREC,
         VLRDESCREC = VLRDESCREC - old.VLRDESCITREC + new.VLRDESCITREC,
         VLRMULTAREC = VLRMULTAREC - old.VLRMULTAITREC + new.VLRMULTAITREC,
         VLRJUROSREC = VLRJUROSREC - old.VLRJUROSITREC + new.VLRJUROSITREC,
         VLRDEVREC = VLRDEVREC - old.VLRDEVITREC + new.VLRDEVITREC,
         VLRPARCREC = VLRPARCREC - old.VLRPARCITREC + new.VLRPARCITREC,
         VLRPAGOREC = VLRPAGOREC - old.VLRPAGOITREC + new.VLRPAGOITREC,
         VLRAPAGREC = VLRAPAGREC - old.VLRAPAGITREC + new.VLRAPAGITREC,
         ALTUSUREC = 'S' WHERE CODREC=new.CODREC
        AND CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL;
END
^

/* Alter exist trigger... */
ALTER TRIGGER FNSUBLANCATGBI
AS
  DECLARE VARIABLE sEhTransf CHAR(1);
  DECLARE VARIABLE sTipoPlan CHAR(1);
  DECLARE VARIABLE dDataLanca DATE;
  DECLARE VARIABLE dDtPrevLanca DATE;
  DECLARE VARIABLE sHistSubLanc VARCHAR(250);
BEGIN
  /*IF ( new.VLRSUBLANCA = 0 ) THEN
     EXCEPTION FNSUBLANCAEX04;         */
  SELECT HISTBLANCA FROM FNLANCA WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL = new.CODFILIAL
  INTO sHistSubLanc;

  IF (new.HISTSUBLANCA IS NULL) THEN
      new.HISTSUBLANCA = sHistSubLanc;

  IF (new.CODSUBLANCA IS NULL) THEN
    SELECT MAX(CODSUBLANCA) FROM FNSUBLANCA
    WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL = new.CODFILIAL
    INTO new.CODSUBLANCA;

  new.STATUSSUBLANCA = 'S1';

  SELECT TRANSFLANCA,DATALANCA,DTPREVLANCA FROM FNLANCA
  WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL = new.CODFILIAL
  INTO sEhTransf,dDataLanca,dDtPrevLanca;

  SELECT TIPOPLAN FROM FNPLANEJAMENTO WHERE CODPLAN = new.CODPLAN AND CODEMP=new.CODEMPPN AND CODFILIAL = new.CODFILIALPN
  INTO sTipoPlan;

  new.DATASUBLANCA = dDataLanca;

  IF (new.CODSUBLANCA > 0) THEN
  BEGIN
    new.ORIGSUBLANCA = 'N';
  END

  new.STATUSSUBLANCA = 'S1';
  new.DTPREVSUBLANCA = dDtPrevLanca;

  IF (sEhTransf = 'S') THEN
  BEGIN
   IF (new.CODSUBLANCA = 2) THEN
     EXCEPTION FNSUBLANCAEX01;
   ELSE IF (sTipoPlan IN ('D','R')) THEN
     EXCEPTION FNSUBLANCAEX02;
  END
  ELSE
    IF ((new.CODSUBLANCA != 0) AND (sTipoPlan IN ('C','B'))) THEN
      EXCEPTION FNSUBLANCAEX03;
  UPDATE FNLANCA SET STATUSLANCA = 'L2', VLRLANCA=(VLRLANCA-new.VLRSUBLANCA)
         WHERE CODLANCA = new.CODLANCA AND CODEMP=new.CODEMP AND CODFILIAL=new.CODFILIAL;
END
^

/* Alter Procedure... */
/* Alter (FNADICLANCASP01) */
ALTER PROCEDURE FNADICLANCASP01(ICODREC INTEGER,
INPARCITREC INTEGER,
PDVITREC CHAR(1),
SNUMCONTA CHAR(10),
ICODEMPCA INTEGER,
ICODFILIALCA INTEGER,
ICODCLI INTEGER,
ICODEMPCL INTEGER,
ICODFILIALCL INTEGER,
SCODPLAN CHAR(13),
ICODEMPPN INTEGER,
ICODFILIALPN INTEGER,
IANOCC INTEGER,
SCODCC CHAR(19),
ICODEMPCC INTEGER,
ICODFILIALCC INTEGER,
DDTPAGOITREC DATE,
SDOCLANCAITREC CHAR(10),
SOBSITREC CHAR(250),
DVLRPAGOITREC NUMERIC(15,5),
ICODEMP INTEGER,
ICODFILIAL SMALLINT,
DVLRPAGOJUROS NUMERIC(15,5),
DVLRDESC NUMERIC(15,5))
 AS
declare variable icodlanca integer;
declare variable scodplanconta char(13);
declare variable icodemppconta integer;
declare variable icodfilialpconta integer;
declare variable cflag char(1);
declare variable ifiliallanca integer;
declare variable tipolanca char(1);
declare variable codempjr integer;
declare variable codfilialjr smallint;
declare variable codplanjr char(13);
declare variable codempdc integer;
declare variable codfilialdc smallint;
declare variable codplandc char(13);
declare variable codsublanca smallint = 1;
BEGIN
    SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'FNLANCA') INTO IFILIALLANCA;

    SELECT CODPLAN,CODEMPPN,CODFILIALPN FROM FNCONTA WHERE NUMCONTA = :SNUMCONTA
        AND CODEMP=:ICODEMPCA AND CODFILIAL=:ICODFILIALCA INTO :sCodPlanConta,:iCodEmpPConta,:iCodFilialPConta;

    SELECT ISEQ FROM SPGERANUM(:ICODEMP,:IFILIALLANCA,'LA') INTO ICODLANCA;

    SELECT FLAG FROM FNRECEBER WHERE CODREC=:ICODREC
        AND CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL INTO :cFlag;

    SELECT CODEMPJR,CODFILIALJR,CODPLANJR,CODEMPDC,CODFILIALDC,CODPLANDC FROM SGPREFERE1
        WHERE CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
        INTO :CODEMPJR,:CODFILIALJR,:CODPLANJR,:CODEMPDC,:CODFILIALDC,:CODPLANDC;


    IF (ICODCLI IS NULL) THEN
        TIPOLANCA = 'A';
    ELSE
        TIPOLANCA = 'C';

    if ( (DVLRPAGOJUROS IS NULL) OR (:CODPLANJR IS NULL)  ) then
        DVLRPAGOJUROS = 0;
    else
        DVLRPAGOITREC = DVLRPAGOITREC - DVLRPAGOJUROS;

    if (DVLRDESC IS NULL  OR (:CODPLANDC IS NULL) ) then
        DVLRDESC = 0;
    else
        DVLRPAGOITREC = DVLRPAGOITREC + DVLRDESC;


    INSERT INTO FNLANCA (TIPOLANCA,CODEMP,CODFILIAL,CODLANCA,CODEMPRC,CODFILIALRC,CODREC,NPARCITREC,CODEMPPN,CODFILIALPN,
                         CODPLAN,DATALANCA,DOCLANCA,HISTBLANCA,DTPREVLANCA,VLRLANCA,FLAG,CODEMPCL,CODFILIALCL,CODCLI,PDVITREC)
        VALUES (:TIPOLANCA,:ICODEMP,:IFILIALLANCA,:iCodLanca,:ICODEMP,:ICODFILIAL,:ICODREC,:iNParcItRec,:iCodEmpPConta,:iCodFilialPConta,
                :sCodPlanConta,:dDtPagoItRec,:sDocLancaItRec,:sObsItRec,:dDtPagoItRec,0,:cFlag,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:PDVITREC
        );

    INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPCL,CODFILIALCL,CODCLI,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,
                            CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:ICODEMPPN,:ICODFILIALPN,:SCODPLAN,:ICODEMPCC,
                :ICODFILIALCC,:IANOCC,:SCODCC,'S',:dDtPagoItRec,:dDtPagoItRec,:dVlrPagoItRec*-1,:cFlag
        );

    -- Lançamento dos juros em conta distinta.

    IF(DVLRPAGOJUROS > 0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPCL,CODFILIALCL,CODCLI,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,
                            CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:CODEMPJR,:CODFILIALJR,:CODPLANJR,:ICODEMPCC,
                :ICODFILIALCC,:IANOCC,:SCODCC,'S',:dDtPagoItRec,:dDtPagoItRec,:DVLRPAGOJUROS*-1,:cFlag
        );

    END

    -- Lançamento do desconto em conta distinta.

    IF(DVLRDESC > 0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPCL,CODFILIALCL,CODCLI,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,
                            CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPCL,:ICODFILIALCL,:ICODCLI,:CODEMPDC,:CODFILIALDC,:CODPLANDC,:ICODEMPCC,
                :ICODFILIALCC,:IANOCC,:SCODCC,'S',:dDtPagoItRec,:dDtPagoItRec,:DVLRDESC,:cFlag
        );

    END


END
^

/* Alter (FNADICLANCASP02) */
ALTER PROCEDURE FNADICLANCASP02(ICODPAG INTEGER,
INPARCPAG INTEGER,
SNUMCONTA CHAR(10),
ICODEMPCA INTEGER,
ICODFILIALCA INTEGER,
ICODFOR INTEGER,
ICODEMPFR INTEGER,
ICODFILIALFR INTEGER,
SCODPLAN CHAR(13),
ICODEMPPN INTEGER,
ICODFILIALPN INTEGER,
IANOCC INTEGER,
SCODCC CHAR(19),
ICODEMPCC INTEGER,
ICODFILIALCC INTEGER,
DDTPAGOITPAG DATE,
SDOCLANCAITPAG CHAR(10),
SOBSITPAG CHAR(250),
DVLRPAGOITPAG NUMERIC(15,5),
ICODEMP INTEGER,
ICODFILIAL SMALLINT,
DVLRJUROSPAG NUMERIC(15,5),
DVLRDESC NUMERIC(15,5))
 AS
declare variable icodlanca integer;
declare variable scodplanconta char(13);
declare variable icodemppconta integer;
declare variable icodfilialpconta integer;
declare variable cflag char(1);
declare variable ifiliallanca integer;
declare variable tipolanca char(1);
declare variable codempjp integer;
declare variable codfilialjp smallint;
declare variable codplanjp char(13);
declare variable codempdr integer;
declare variable codfilialdr smallint;
declare variable codplandr char(13);
declare variable codsublanca smallint = 1;
BEGIN

    SELECT ICODFILIAL FROM SGRETFILIAL(:ICODEMP,'FNLANCA')
    INTO IFILIALLANCA;

    SELECT CODPLAN,CODEMP,CODFILIAL FROM FNCONTA
    WHERE NUMCONTA=:sNumConta AND CODEMP=:ICODEMPCA AND CODFILIAL=:ICODFILIALCA
    INTO :sCodPlanConta,:iCodEmpPConta,:iCodFilialPConta;

    SELECT ISEQ FROM SPGERANUM(:iCODEMP,:IFILIALLANCA,'LA')
    INTO :iCodLanca;

    SELECT FLAG FROM FNPAGAR
    WHERE CODPAG=:iCodPag AND CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
    INTO :cFlag;

    SELECT CODEMPJP,CODFILIALJP,CODPLANJP,CODEMPDR,CODFILIALDR,CODPLANDR
    FROM SGPREFERE1
    WHERE CODEMP=:ICODEMP AND CODFILIAL=:ICODFILIAL
    INTO :CODEMPJP,:CODFILIALJP,:CODPLANJP,:CODEMPDR,:CODFILIALDR,:CODPLANDR;

    IF (ICODFOR IS NULL) THEN
        TIPOLANCA = 'A';
      ELSE
        TIPOLANCA = 'F';

    if ( (DVLRJUROSPAG IS NULL) OR (:CODPLANJP IS NULL)  ) then
        DVLRJUROSPAG = 0;
    else
        DVLRPAGOITPAG = DVLRPAGOITPAG - DVLRJUROSPAG;

    if (DVLRDESC IS NULL  OR (:CODPLANDR IS NULL) ) then
        DVLRDESC = 0;
    else
        DVLRPAGOITPAG = DVLRPAGOITPAG + DVLRDESC;


    INSERT INTO FNLANCA (TIPOLANCA,CODEMP,CODFILIAL,CODLANCA,CODEMPPG,CODFILIALPG,CODPAG,
                         NPARCPAG,CODEMPPN,CODFILIALPN,CODPLAN,DATALANCA,DOCLANCA,
                         HISTBLANCA,DTPREVLANCA,VLRLANCA,FLAG, CODEMPFR, CODFILIALFR, CODFOR)
         VALUES (:TIPOLANCA,:ICODEMP,:IFILIALLANCA,:iCodLanca,:ICODEMP,:ICODFILIAL,:iCodPag,
                 :iNParcPag,:iCodEmpPConta,:iCodFilialPConta,:sCodPlanConta,:dDtPagoItPag,:sDocLancaItPag,
                 :sObsItPag,:dDtPagoItPag,0,:cFlag, :ICODEMPFR, :ICODFILIALFR, :ICODFOR
         );

    INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
        VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:ICODEMPPN,:ICODFILIALPN,:sCodplan,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:dVlrPagoItPag,:cFlag);

    -- Lançamento dos juros em conta distinta.

    IF(DVLRJUROSPAG >0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
            VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:CODEMPJP,:CODFILIALJP,:CODPLANJP,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:DVLRJUROSPAG,:cFlag);

    END

    -- Lançamento de desconto em conta distinta.

    IF(DVLRDESC >0) THEN
    BEGIN

        CODSUBLANCA = CODSUBLANCA + 1;

        INSERT INTO FNSUBLANCA (CODEMP,CODFILIAL,CODLANCA,CODSUBLANCA,CODEMPFR,CODFILIALFR,CODFOR,CODEMPPN,CODFILIALPN,CODPLAN,CODEMPCC,CODFILIALCC,ANOCC,CODCC,ORIGSUBLANCA,DATASUBLANCA,DTPREVSUBLANCA,VLRSUBLANCA,FLAG)
            VALUES (:ICODEMP,:IFILIALLANCA,:iCodLanca,:CODSUBLANCA,:ICODEMPFR,:ICODFILIALFR,:ICODFOR,:CODEMPDR,:CODFILIALDR,:CODPLANDR,:ICODEMPCC,:ICODFILIALCC,:IANOCC,:SCODCC,'E',:dDtPagoItPag,:dDtPagoItPag,:DVLRDESC*-1,:cFlag);

    END

END
^

/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.3.5 (28/08/2010)';
    suspend;
end
^

SET TERM ; ^

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE EQPRODUTO ALTER COLUMN CODPROD POSITION 3;

ALTER TABLE EQPRODUTO ALTER COLUMN DESCPROD POSITION 4;

ALTER TABLE EQPRODUTO ALTER COLUMN REFPROD POSITION 5;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPAX POSITION 6;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALAX POSITION 7;

ALTER TABLE EQPRODUTO ALTER COLUMN CODALMOX POSITION 8;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPMA POSITION 9;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALMA POSITION 10;

ALTER TABLE EQPRODUTO ALTER COLUMN CODMOEDA POSITION 11;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPUD POSITION 12;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALUD POSITION 13;

ALTER TABLE EQPRODUTO ALTER COLUMN CODUNID POSITION 14;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPFC POSITION 15;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALFC POSITION 16;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFISC POSITION 17;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPMC POSITION 18;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALMC POSITION 19;

ALTER TABLE EQPRODUTO ALTER COLUMN CODMARCA POSITION 20;

ALTER TABLE EQPRODUTO ALTER COLUMN DESCAUXPROD POSITION 21;

ALTER TABLE EQPRODUTO ALTER COLUMN TIPOPROD POSITION 22;

ALTER TABLE EQPRODUTO ALTER COLUMN CVPROD POSITION 23;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPGP POSITION 24;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALGP POSITION 25;

ALTER TABLE EQPRODUTO ALTER COLUMN CODGRUP POSITION 26;

ALTER TABLE EQPRODUTO ALTER COLUMN CODBARPROD POSITION 27;

ALTER TABLE EQPRODUTO ALTER COLUMN CLOTEPROD POSITION 28;

ALTER TABLE EQPRODUTO ALTER COLUMN SERIEPROD POSITION 29;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFABPROD POSITION 30;

ALTER TABLE EQPRODUTO ALTER COLUMN COMISPROD POSITION 31;

ALTER TABLE EQPRODUTO ALTER COLUMN PESOLIQPROD POSITION 32;

ALTER TABLE EQPRODUTO ALTER COLUMN PESOBRUTPROD POSITION 33;

ALTER TABLE EQPRODUTO ALTER COLUMN QTDMINPROD POSITION 34;

ALTER TABLE EQPRODUTO ALTER COLUMN QTDMAXPROD POSITION 35;

ALTER TABLE EQPRODUTO ALTER COLUMN DTMPMPROD POSITION 36;

ALTER TABLE EQPRODUTO ALTER COLUMN CUSTOMPMPROD POSITION 37;

ALTER TABLE EQPRODUTO ALTER COLUMN CUSTOPEPSPROD POSITION 38;

ALTER TABLE EQPRODUTO ALTER COLUMN CUSTOINFOPROD POSITION 39;

ALTER TABLE EQPRODUTO ALTER COLUMN PRECOBASEPROD POSITION 40;

ALTER TABLE EQPRODUTO ALTER COLUMN PRECOCOMISPROD POSITION 41;

ALTER TABLE EQPRODUTO ALTER COLUMN SLDPROD POSITION 42;

ALTER TABLE EQPRODUTO ALTER COLUMN SLDRESPROD POSITION 43;

ALTER TABLE EQPRODUTO ALTER COLUMN SLDCONSIGPROD POSITION 44;

ALTER TABLE EQPRODUTO ALTER COLUMN SLDLIQPROD POSITION 45;

ALTER TABLE EQPRODUTO ALTER COLUMN ATIVOPROD POSITION 46;

ALTER TABLE EQPRODUTO ALTER COLUMN DTULTCPPROD POSITION 47;

ALTER TABLE EQPRODUTO ALTER COLUMN QTDULTCPPROD POSITION 48;

ALTER TABLE EQPRODUTO ALTER COLUMN DESCCOMPPROD POSITION 49;

ALTER TABLE EQPRODUTO ALTER COLUMN VERIFPROD POSITION 50;

ALTER TABLE EQPRODUTO ALTER COLUMN LOCALPROD POSITION 51;

ALTER TABLE EQPRODUTO ALTER COLUMN RMAPROD POSITION 52;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPPE POSITION 53;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALPE POSITION 54;

ALTER TABLE EQPRODUTO ALTER COLUMN CODPE POSITION 55;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPCC POSITION 56;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALCC POSITION 57;

ALTER TABLE EQPRODUTO ALTER COLUMN ANOCC POSITION 58;

ALTER TABLE EQPRODUTO ALTER COLUMN CODCC POSITION 59;

ALTER TABLE EQPRODUTO ALTER COLUMN USARECEITAPROD POSITION 60;

ALTER TABLE EQPRODUTO ALTER COLUMN USATELAADICPDV POSITION 61;

ALTER TABLE EQPRODUTO ALTER COLUMN VLRDENSIDADE POSITION 62;

ALTER TABLE EQPRODUTO ALTER COLUMN VLRCONCENT POSITION 63;

ALTER TABLE EQPRODUTO ALTER COLUMN COMPRIMENTO POSITION 64;

ALTER TABLE EQPRODUTO ALTER COLUMN LARGURA POSITION 65;

ALTER TABLE EQPRODUTO ALTER COLUMN ESPESSURA POSITION 66;

ALTER TABLE EQPRODUTO ALTER COLUMN GUIATRAFPROD POSITION 67;

ALTER TABLE EQPRODUTO ALTER COLUMN QTDEMBALAGEM POSITION 68;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEANPROD POSITION 69;

ALTER TABLE EQPRODUTO ALTER COLUMN CUBAGEM POSITION 70;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPSC POSITION 71;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALSC POSITION 72;

ALTER TABLE EQPRODUTO ALTER COLUMN CODSECAO POSITION 73;

ALTER TABLE EQPRODUTO ALTER COLUMN CODEMPTC POSITION 74;

ALTER TABLE EQPRODUTO ALTER COLUMN CODFILIALTC POSITION 75;

ALTER TABLE EQPRODUTO ALTER COLUMN CODTPCHAMADO POSITION 76;

ALTER TABLE EQPRODUTO ALTER COLUMN QTDHORASSERV POSITION 77;

ALTER TABLE EQPRODUTO ALTER COLUMN DTINS POSITION 78;

ALTER TABLE EQPRODUTO ALTER COLUMN HINS POSITION 79;

ALTER TABLE EQPRODUTO ALTER COLUMN IDUSUINS POSITION 80;

ALTER TABLE EQPRODUTO ALTER COLUMN DTALT POSITION 81;

ALTER TABLE EQPRODUTO ALTER COLUMN HALT POSITION 82;

ALTER TABLE EQPRODUTO ALTER COLUMN IDUSUALT POSITION 83;

ALTER TABLE FNCHEQUE ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE FNCHEQUE ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE FNCHEQUE ALTER COLUMN CODEMPBO POSITION 3;

ALTER TABLE FNCHEQUE ALTER COLUMN SEQCHEQ POSITION 4;

ALTER TABLE FNCHEQUE ALTER COLUMN CODFILIALBO POSITION 5;

ALTER TABLE FNCHEQUE ALTER COLUMN CODBANC POSITION 6;

ALTER TABLE FNCHEQUE ALTER COLUMN AGENCIACHEQ POSITION 7;

ALTER TABLE FNCHEQUE ALTER COLUMN CONTACHEQ POSITION 8;

ALTER TABLE FNCHEQUE ALTER COLUMN NUMCHEQ POSITION 9;

ALTER TABLE FNCHEQUE ALTER COLUMN NOMEEMITCHEQ POSITION 10;

ALTER TABLE FNCHEQUE ALTER COLUMN NOMEFAVCHEQ POSITION 11;

ALTER TABLE FNCHEQUE ALTER COLUMN DTEMITCHEQ POSITION 12;

ALTER TABLE FNCHEQUE ALTER COLUMN DTVENCTOCHEQ POSITION 13;

ALTER TABLE FNCHEQUE ALTER COLUMN DTCOMPCHEQ POSITION 14;

ALTER TABLE FNCHEQUE ALTER COLUMN TIPOCHEQ POSITION 15;

ALTER TABLE FNCHEQUE ALTER COLUMN PREDATCHEQ POSITION 16;

ALTER TABLE FNCHEQUE ALTER COLUMN SITCHEQ POSITION 17;

ALTER TABLE FNCHEQUE ALTER COLUMN VLRCHEQ POSITION 18;

ALTER TABLE FNCHEQUE ALTER COLUMN HISTCHEQ POSITION 19;

ALTER TABLE FNCHEQUE ALTER COLUMN CNPJEMITCHEQ POSITION 20;

ALTER TABLE FNCHEQUE ALTER COLUMN CPFEMITCHEQ POSITION 21;

ALTER TABLE FNCHEQUE ALTER COLUMN CNPJFAVCHEQ POSITION 22;

ALTER TABLE FNCHEQUE ALTER COLUMN CPFFAVCHEQ POSITION 23;

ALTER TABLE FNCHEQUE ALTER COLUMN DDDFAVCHEQ POSITION 24;

ALTER TABLE FNCHEQUE ALTER COLUMN DDDEMITCHEQ POSITION 25;

ALTER TABLE FNCHEQUE ALTER COLUMN FONEEMITCHEQ POSITION 26;

ALTER TABLE FNCHEQUE ALTER COLUMN DTINS POSITION 27;

ALTER TABLE FNCHEQUE ALTER COLUMN HINS POSITION 28;

ALTER TABLE FNCHEQUE ALTER COLUMN IDUSUINS POSITION 29;

ALTER TABLE FNCHEQUE ALTER COLUMN DTALT POSITION 30;

ALTER TABLE FNCHEQUE ALTER COLUMN HALT POSITION 31;

ALTER TABLE FNCHEQUE ALTER COLUMN IDUSUALT POSITION 32;

ALTER TABLE FNCHEQUE ALTER COLUMN FONEFAVCHEQ POSITION 33;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAREFPROD POSITION 3;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV POSITION 4;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTM POSITION 5;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTM POSITION 6;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPEDSEQ POSITION 7;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAORCSEQ POSITION 8;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILTRO POSITION 9;

ALTER TABLE SGPREFERE1 ALTER COLUMN USALIQREL POSITION 10;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOPRECOCUSTO POSITION 11;

ALTER TABLE SGPREFERE1 ALTER COLUMN ANOCENTROCUSTO POSITION 12;

ALTER TABLE SGPREFERE1 ALTER COLUMN OBSORCPAD POSITION 13;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV2 POSITION 14;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT2 POSITION 15;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT2 POSITION 16;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSORC POSITION 17;

ALTER TABLE SGPREFERE1 ALTER COLUMN TITORCTXT01 POSITION 18;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV3 POSITION 19;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT3 POSITION 20;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT3 POSITION 21;

ALTER TABLE SGPREFERE1 ALTER COLUMN ORDNOTA POSITION 22;

ALTER TABLE SGPREFERE1 ALTER COLUMN SETORVENDA POSITION 23;

ALTER TABLE SGPREFERE1 ALTER COLUMN PREFCRED POSITION 24;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOPREFCRED POSITION 25;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMO POSITION 26;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMO POSITION 27;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMOEDA POSITION 28;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV4 POSITION 29;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT4 POSITION 30;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT4 POSITION 31;

ALTER TABLE SGPREFERE1 ALTER COLUMN USACLASCOMIS POSITION 32;

ALTER TABLE SGPREFERE1 ALTER COLUMN PERCPRECOCUSTO POSITION 33;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODGRUP POSITION 34;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALGP POSITION 35;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPGP POSITION 36;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMARCA POSITION 37;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMC POSITION 38;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMC POSITION 39;

ALTER TABLE SGPREFERE1 ALTER COLUMN RGCLIOBRIG POSITION 40;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABFRETEVD POSITION 41;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABADICVD POSITION 42;

ALTER TABLE SGPREFERE1 ALTER COLUMN TRAVATMNFVD POSITION 43;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOVALIDORC POSITION 44;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLIMESMOCNPJ POSITION 45;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTBJ POSITION 46;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTJ POSITION 47;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTJ POSITION 48;

ALTER TABLE SGPREFERE1 ALTER COLUMN CNPJOBRIGCLI POSITION 49;

ALTER TABLE SGPREFERE1 ALTER COLUMN JUROSPOSCALC POSITION 50;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPFR POSITION 51;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALFR POSITION 52;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFOR POSITION 53;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTN POSITION 54;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTN POSITION 55;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTRAN POSITION 56;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTF POSITION 57;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTF POSITION 58;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOFOR POSITION 59;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT5 POSITION 60;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT5 POSITION 61;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV5 POSITION 62;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTLOTNEG POSITION 63;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTNEG POSITION 64;

ALTER TABLE SGPREFERE1 ALTER COLUMN NATVENDA POSITION 65;

ALTER TABLE SGPREFERE1 ALTER COLUMN IPIVENDA POSITION 66;

ALTER TABLE SGPREFERE1 ALTER COLUMN CUSTOSICMS POSITION 67;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPPG POSITION 68;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALPG POSITION 69;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANOPAG POSITION 70;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTB POSITION 71;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTB POSITION 72;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTAB POSITION 73;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPCE POSITION 74;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALCE POSITION 75;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODCLASCLI POSITION 76;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDEC POSITION 77;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDECFIN POSITION 78;

ALTER TABLE SGPREFERE1 ALTER COLUMN COMISPDUPL POSITION 79;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT6 POSITION 80;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT6 POSITION 81;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV6 POSITION 82;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQVENDA POSITION 83;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQCOMPRA POSITION 84;

ALTER TABLE SGPREFERE1 ALTER COLUMN VENDAMATPRIM POSITION 85;

ALTER TABLE SGPREFERE1 ALTER COLUMN VENDAPATRIM POSITION 86;

ALTER TABLE SGPREFERE1 ALTER COLUMN PEPSPROD POSITION 87;

ALTER TABLE SGPREFERE1 ALTER COLUMN CNPJFOROBRIG POSITION 88;

ALTER TABLE SGPREFERE1 ALTER COLUMN INSCESTFOROBRIG POSITION 89;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCAPRODSIMILAR POSITION 90;

ALTER TABLE SGPREFERE1 ALTER COLUMN MULTIALMOX POSITION 91;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT8 POSITION 92;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT8 POSITION 93;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV8 POSITION 94;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTNEGGRUP POSITION 95;

ALTER TABLE SGPREFERE1 ALTER COLUMN USATABPE POSITION 96;

ALTER TABLE SGPREFERE1 ALTER COLUMN TAMDESCPROD POSITION 97;

ALTER TABLE SGPREFERE1 ALTER COLUMN DESCCOMPPED POSITION 98;

ALTER TABLE SGPREFERE1 ALTER COLUMN OBSCLIVEND POSITION 99;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONTESTOQ POSITION 100;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIASPEDT POSITION 101;

ALTER TABLE SGPREFERE1 ALTER COLUMN RECALCPCVENDA POSITION 102;

ALTER TABLE SGPREFERE1 ALTER COLUMN RECALCPCORC POSITION 103;

ALTER TABLE SGPREFERE1 ALTER COLUMN USALAYOUTPED POSITION 104;

ALTER TABLE SGPREFERE1 ALTER COLUMN VERIFALTPARCVENDA POSITION 105;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCACODPRODGEN POSITION 106;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENPROD POSITION 107;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENREF POSITION 108;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODBAR POSITION 109;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODFAB POSITION 110;

ALTER TABLE SGPREFERE1 ALTER COLUMN FILBUSCGENCODFOR POSITION 111;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCAVLRULTCOMPRA POSITION 112;

ALTER TABLE SGPREFERE1 ALTER COLUMN ICMSVENDA POSITION 113;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPRECOZERO POSITION 114;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIMGASSORC POSITION 115;

ALTER TABLE SGPREFERE1 ALTER COLUMN IMGASSORC POSITION 116;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTCPFCLI POSITION 117;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIECLI POSITION 118;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIEFOR POSITION 119;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTECPFFOR POSITION 120;

ALTER TABLE SGPREFERE1 ALTER COLUMN USANOMEVENDORC POSITION 121;

ALTER TABLE SGPREFERE1 ALTER COLUMN SISCONTABIL POSITION 122;

ALTER TABLE SGPREFERE1 ALTER COLUMN ATBANCOIMPBOL POSITION 123;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCODBAR POSITION 124;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICORCOBSPED POSITION 125;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMENSORC POSITION 126;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMENSORC POSITION 127;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMENSORC POSITION 128;

ALTER TABLE SGPREFERE1 ALTER COLUMN CUSTOCOMPRA POSITION 129;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABTRANSPCP POSITION 130;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABTRANSPORC POSITION 131;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABSOLCP POSITION 132;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICFRETEBASEICM POSITION 133;

ALTER TABLE SGPREFERE1 ALTER COLUMN PRECOCPREL POSITION 134;

ALTER TABLE SGPREFERE1 ALTER COLUMN DESCORC POSITION 135;

ALTER TABLE SGPREFERE1 ALTER COLUMN MULTICOMIS POSITION 136;

ALTER TABLE SGPREFERE1 ALTER COLUMN USUATIVCLI POSITION 137;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPHISTREC POSITION 138;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALHISTREC POSITION 139;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODHISTREC POSITION 140;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPHISTPAG POSITION 141;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALHISTPAG POSITION 142;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODHISTPAG POSITION 143;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPTC POSITION 144;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALTC POSITION 145;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOCLI POSITION 146;

ALTER TABLE SGPREFERE1 ALTER COLUMN ESTITRECALTDTVENC POSITION 147;

ALTER TABLE SGPREFERE1 ALTER COLUMN LCREDGLOBAL POSITION 148;

ALTER TABLE SGPREFERE1 ALTER COLUMN VDMANUTCOMOBRIG POSITION 149;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSPED POSITION 150;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCLASSPED POSITION 151;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGECLI POSITION 152;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGEFOR POSITION 153;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAIBGETRANSP POSITION 154;

ALTER TABLE SGPREFERE1 ALTER COLUMN SOMAVOLUMES POSITION 155;

ALTER TABLE SGPREFERE1 ALTER COLUMN BUSCACEP POSITION 156;

ALTER TABLE SGPREFERE1 ALTER COLUMN URLWSCEP POSITION 157;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSCP POSITION 158;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS01CP POSITION 159;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS02CP POSITION 160;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS03CP POSITION 161;

ALTER TABLE SGPREFERE1 ALTER COLUMN LABELOBS04CP POSITION 162;

ALTER TABLE SGPREFERE1 ALTER COLUMN CONSISTEIEPF POSITION 163;

ALTER TABLE SGPREFERE1 ALTER COLUMN CREDICMSSIMPLES POSITION 164;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPMS POSITION 165;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALMS POSITION 166;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODMENSICMSSIMPLES POSITION 167;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERACOMISVENDAORC POSITION 168;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERACODUNIF POSITION 169;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOMOV9 POSITION 170;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALT9 POSITION 171;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPT9 POSITION 172;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPJP POSITION 173;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALJP POSITION 174;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANJP POSITION 175;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPJR POSITION 176;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALJR POSITION 177;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANJR POSITION 178;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPDR POSITION 179;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALDR POSITION 180;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANDR POSITION 181;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPDC POSITION 182;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALDC POSITION 183;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODPLANDC POSITION 184;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERAPAGEMIS POSITION 185;

ALTER TABLE SGPREFERE1 ALTER COLUMN LANCAFINCONTR POSITION 186;

ALTER TABLE SGPREFERE1 ALTER COLUMN LANCARMACONTR POSITION 187;

ALTER TABLE SGPREFERE1 ALTER COLUMN CASASDECPRE POSITION 188;

ALTER TABLE SGPREFERE1 ALTER COLUMN VISUALIZALUCR POSITION 189;

ALTER TABLE SGPREFERE1 ALTER COLUMN CLASSNFE POSITION 190;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIRNFE POSITION 191;

ALTER TABLE SGPREFERE1 ALTER COLUMN DIRNFELIN POSITION 192;

ALTER TABLE SGPREFERE1 ALTER COLUMN FORMATODANFE POSITION 193;

ALTER TABLE SGPREFERE1 ALTER COLUMN AMBIENTENFE POSITION 194;

ALTER TABLE SGPREFERE1 ALTER COLUMN PROCEMINFE POSITION 195;

ALTER TABLE SGPREFERE1 ALTER COLUMN VERPROCNFE POSITION 196;

ALTER TABLE SGPREFERE1 ALTER COLUMN KEYLICNFE POSITION 197;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTVENCTONFE POSITION 198;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFADPRODNFE POSITION 199;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPNF POSITION 200;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALNF POSITION 201;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMAILNF POSITION 202;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFCPDEVOLUCAO POSITION 203;

ALTER TABLE SGPREFERE1 ALTER COLUMN INFVDREMESSA POSITION 204;

ALTER TABLE SGPREFERE1 ALTER COLUMN GERARECEMIS POSITION 205;

ALTER TABLE SGPREFERE1 ALTER COLUMN RETENSAOIMP POSITION 206;

ALTER TABLE SGPREFERE1 ALTER COLUMN TIPOCUSTOLUC POSITION 207;

ALTER TABLE SGPREFERE1 ALTER COLUMN TABIMPORTCP POSITION 208;

ALTER TABLE SGPREFERE1 ALTER COLUMN HABVLRTOTITORC POSITION 209;

ALTER TABLE SGPREFERE1 ALTER COLUMN USABUSCAGENPRODCP POSITION 210;

ALTER TABLE SGPREFERE1 ALTER COLUMN ADICOBSORCPED POSITION 211;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPRECOCOT POSITION 212;

ALTER TABLE SGPREFERE1 ALTER COLUMN BLOQPRECOAPROV POSITION 213;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODEMPFT POSITION 214;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODFILIALFT POSITION 215;

ALTER TABLE SGPREFERE1 ALTER COLUMN CODTIPOFORFT POSITION 216;

ALTER TABLE SGPREFERE1 ALTER COLUMN USAPRECOCOMIS POSITION 217;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTINS POSITION 218;

ALTER TABLE SGPREFERE1 ALTER COLUMN HINS POSITION 219;

ALTER TABLE SGPREFERE1 ALTER COLUMN IDUSUINS POSITION 220;

ALTER TABLE SGPREFERE1 ALTER COLUMN DTALT POSITION 221;

ALTER TABLE SGPREFERE1 ALTER COLUMN HALT POSITION 222;

ALTER TABLE SGPREFERE1 ALTER COLUMN IDUSUALT POSITION 223;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODREGRCOMIS POSITION 3;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN SEQITRC POSITION 4;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODEMPTV POSITION 5;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODFILIALTV POSITION 6;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODTIPOVEND POSITION 7;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN OBRIGITRC POSITION 8;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN PERCCOMISITRC POSITION 9;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN IDUSUALT POSITION 10;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODEMPVD POSITION 11;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODFILIALVD POSITION 12;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN CODVEND POSITION 13;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN DTINS POSITION 14;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN HINS POSITION 15;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN IDUSUINS POSITION 16;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN DTALT POSITION 17;

ALTER TABLE VDITREGRACOMIS ALTER COLUMN HALT POSITION 18;

ALTER TABLE VDREGRACOMIS ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE VDREGRACOMIS ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE VDREGRACOMIS ALTER COLUMN CODREGRCOMIS POSITION 3;

ALTER TABLE VDREGRACOMIS ALTER COLUMN DESCREGRCOMIS POSITION 4;

ALTER TABLE VDREGRACOMIS ALTER COLUMN IDUSUALT POSITION 5;

ALTER TABLE VDREGRACOMIS ALTER COLUMN CODEMPSC POSITION 6;

ALTER TABLE VDREGRACOMIS ALTER COLUMN CODFILIALSC POSITION 7;

ALTER TABLE VDREGRACOMIS ALTER COLUMN CODSECAO POSITION 8;

ALTER TABLE VDREGRACOMIS ALTER COLUMN DTINS POSITION 9;

ALTER TABLE VDREGRACOMIS ALTER COLUMN HINS POSITION 10;

ALTER TABLE VDREGRACOMIS ALTER COLUMN IDUSUINS POSITION 11;

ALTER TABLE VDREGRACOMIS ALTER COLUMN DTALT POSITION 12;

ALTER TABLE VDREGRACOMIS ALTER COLUMN HALT POSITION 13;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODVEND POSITION 3;

ALTER TABLE VDVENDEDOR ALTER COLUMN NOMEVEND POSITION 4;

ALTER TABLE VDVENDEDOR ALTER COLUMN ENDVEND POSITION 5;

ALTER TABLE VDVENDEDOR ALTER COLUMN NUMVEND POSITION 6;

ALTER TABLE VDVENDEDOR ALTER COLUMN COMPLVEND POSITION 7;

ALTER TABLE VDVENDEDOR ALTER COLUMN BAIRVEND POSITION 8;

ALTER TABLE VDVENDEDOR ALTER COLUMN CIDVEND POSITION 9;

ALTER TABLE VDVENDEDOR ALTER COLUMN CEPVEND POSITION 10;

ALTER TABLE VDVENDEDOR ALTER COLUMN UFVEND POSITION 11;

ALTER TABLE VDVENDEDOR ALTER COLUMN FONEVEND POSITION 12;

ALTER TABLE VDVENDEDOR ALTER COLUMN FAXVEND POSITION 13;

ALTER TABLE VDVENDEDOR ALTER COLUMN EMAILVEND POSITION 14;

ALTER TABLE VDVENDEDOR ALTER COLUMN PERCCOMVEND POSITION 15;

ALTER TABLE VDVENDEDOR ALTER COLUMN COMIPIVEND POSITION 16;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMPPN POSITION 17;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIALPN POSITION 18;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODPLAN POSITION 19;

ALTER TABLE VDVENDEDOR ALTER COLUMN CPFVEND POSITION 20;

ALTER TABLE VDVENDEDOR ALTER COLUMN RGVEND POSITION 21;

ALTER TABLE VDVENDEDOR ALTER COLUMN CNPJVEND POSITION 22;

ALTER TABLE VDVENDEDOR ALTER COLUMN INSCVEND POSITION 23;

ALTER TABLE VDVENDEDOR ALTER COLUMN CELVEND POSITION 24;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMPSE POSITION 25;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIALSE POSITION 26;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODSETOR POSITION 27;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMPCM POSITION 28;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIALCM POSITION 29;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODCLCOMIS POSITION 30;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFORNVEND POSITION 31;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFUNC POSITION 32;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMPFU POSITION 33;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIALFU POSITION 34;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMPTV POSITION 35;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIALTV POSITION 36;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODTIPOVEND POSITION 37;

ALTER TABLE VDVENDEDOR ALTER COLUMN DDDFONEVEND POSITION 38;

ALTER TABLE VDVENDEDOR ALTER COLUMN DDDFAXVEND POSITION 39;

ALTER TABLE VDVENDEDOR ALTER COLUMN DDDCELVEND POSITION 40;

ALTER TABLE VDVENDEDOR ALTER COLUMN SSPVEND POSITION 41;

ALTER TABLE VDVENDEDOR ALTER COLUMN OBSVEND POSITION 42;

ALTER TABLE VDVENDEDOR ALTER COLUMN ATIVOCOMIS POSITION 43;

ALTER TABLE VDVENDEDOR ALTER COLUMN IMGASSVEND POSITION 44;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMPCA POSITION 45;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIALCA POSITION 46;

ALTER TABLE VDVENDEDOR ALTER COLUMN NUMCONTA POSITION 47;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODEMPSC POSITION 48;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODFILIALSC POSITION 49;

ALTER TABLE VDVENDEDOR ALTER COLUMN CODSECAO POSITION 50;

ALTER TABLE VDVENDEDOR ALTER COLUMN DTINS POSITION 51;

ALTER TABLE VDVENDEDOR ALTER COLUMN HINS POSITION 52;

ALTER TABLE VDVENDEDOR ALTER COLUMN IDUSUINS POSITION 53;

ALTER TABLE VDVENDEDOR ALTER COLUMN DTALT POSITION 54;

ALTER TABLE VDVENDEDOR ALTER COLUMN HALT POSITION 55;

ALTER TABLE VDVENDEDOR ALTER COLUMN IDUSUALT POSITION 56;

/* Create(Add) Crant */
GRANT SELECT ON VWCUSTOPROJ01 TO ADM;

COMMIT;

