JC=javac -g
FLAGS=-classpath ../../:../../jars/jfreechart-0.9.12.jar:../../jars/jcommon-0.8.7.jar

all: \
FPrefereGeral.class \
FreedomCFG.class

FPrefereGeral.class: FPrefereGeral.java
	$(JC) $(FLAGS) $^

FreedomFNC.class: FreedomFNC.java
	$(JC) $(FLAGS) $^

.PHONY: all
