UPDATE VDITVENDA V SET
EMMANUT='S', 
CODEMPIF=(SELECT F.CODEMP FROM LFITCLFISCAL F, EQPRODUTO P
 WHERE P.CODEMP=V.CODEMPPD AND P.CODFILIAL=V.CODFILIALPD AND P.CODPROD=V.CODPROD AND  
   F.CODEMP=P.CODEMPFC AND F.CODFILIAL=P.CODFILIALFC AND F.CODFISC=P.CODFISC AND F.GERALFISC='S'),
CODFILIALIF=(SELECT F.CODFILIAL FROM LFITCLFISCAL F, EQPRODUTO P
 WHERE P.CODEMP=V.CODEMPPD AND P.CODFILIAL=V.CODFILIALPD AND P.CODPROD=V.CODPROD AND  
   F.CODEMP=P.CODEMPFC AND F.CODFILIAL=P.CODFILIALFC AND F.CODFISC=P.CODFISC AND F.GERALFISC='S'), 
CODFISC=(SELECT F.CODFISC FROM LFITCLFISCAL F, EQPRODUTO P
 WHERE P.CODEMP=V.CODEMPPD AND P.CODFILIAL=V.CODFILIALPD AND P.CODPROD=V.CODPROD AND  
   F.CODEMP=P.CODEMPFC AND F.CODFILIAL=P.CODFILIALFC AND F.CODFISC=P.CODFISC AND F.GERALFISC='S'),
 CODITFISC=(SELECT F.CODITFISC FROM LFITCLFISCAL F, EQPRODUTO P
 WHERE P.CODEMP=V.CODEMPPD AND P.CODFILIAL=V.CODFILIALPD AND P.CODPROD=V.CODPROD AND  
   F.CODEMP=P.CODEMPFC AND F.CODFILIAL=P.CODFILIALFC AND F.CODFISC=P.CODFISC AND F.GERALFISC='S') 
WHERE CODFISC IS NULL;
UPDATE VDITVENDA V SET EMMANUT='N' WHERE EMMANUT='S'; 
COMMIT WORK;

