/* Server Version: LI-V6.3.4.4910 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.5.0.fdb' USER 'SYSDBA' PASSWORD '123654';

SET AUTODDL ON;

ALTER TABLE EQTIPOMOV ADD OPERTIPOMOV CHAR(1) DEFAULT 'C' NOT NULL;

Update Rdb$Relation_Fields set Rdb$Description =
'Operação:
"C" - Conjugada;
"P" - Produto;
"S" - Serviço;
'
where Rdb$Relation_Name='EQTIPOMOV' and Rdb$Field_Name='OPERTIPOMOV';

ALTER TABLE SGITPREFERE6 ADD PADRAOSIACC CHAR(4) DEFAULT '150' NOT NULL;

Update Rdb$Relation_Fields set Rdb$Description =
'Indica o padrão SIACC, pode ser: 150 ou 240
'
where Rdb$Relation_Name='SGITPREFERE6' and Rdb$Field_Name='PADRAOSIACC';

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
SET TERM ^ ;

ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.5.1 (13/06/2012)';
    suspend;
end
^

/* Alter exist trigger... */
ALTER TRIGGER CPITIMPORTACAOTGBU
as
    declare variable cotacao        decimal(15,5);

begin

    -- Atualizando log
    new.DTALT=cast('now' AS DATE);
    new.IDUSUALT=USER;
    new.HALT = cast('now' AS TIME);

    -- Buscando informações do cabeçalho
    select imp.cotacaomoeda
    from cpimportacao imp where imp.codemp=new.codemp and imp.codfilial=new.codfilial and imp.codimp=new.codimp
    into :cotacao;

    -- Calculando VMLE e VMLD

    new.vmlemi      =  ( new.qtd         *       new.precomi ) + new.vlrthcmi ;
    new.vmldmi      =   new.vmlemi       +       new.vlrfretemi;
    new.vlradmi     =   new.vmldmi       ;
    new.vlrvmcv     =  ( new.qtd         *       new.precomi ) + new.vlrfretemi ;

    -- Calculando valores em moeda corrente
    new.preco       =   new.precomi     *       :cotacao;
    new.vmle        =   new.vmlemi      *       :cotacao;
    new.vmld        =   new.vmldmi      *       :cotacao;
    new.vlrfrete    =   new.vlrfretemi  *       :cotacao;
    new.vlrseguro   =   new.vlrseguromi *       :cotacao;
    new.vlrthc      =   new.vlrthcmi    *       :cotacao;
    new.vlrad       =   new.vlradmi     *       :cotacao;

    -- Calculando II

    new.vlrii       =   new.vlrad       *       new.aliqii  /   100.00;

    -- Calculando IPI

    new.vlripi      = ( new.vlrad       +       new.vlrii ) *  ( new.aliqipi /   100.00);

    -- Calculando o ICMS

    new.vlrbaseicms         =  ( new.vlrad      +       new.vlrcofins      +   new.vlrpis   +     new.vlripi   + new.vlrii + new.vlrtxsiscomex ) / (  cast(1.00 as decimal(15,5)) - (new.aliqicmsuf / 100.00) ) ;

    new.vlricms             =   new.vlrbaseicms *      ( new.aliqicmsuf     / cast(100.00 as decimal(15,5)) );

    if(new.percdifericms > 0) then
        new.vlricmsdiferido     =   new.vlricms     *      ( new.percdifericms  / cast(100.00 as decimal(15,5)) );
    else
        new.vlricmsdiferido     =   0.00;

    new.vlricmsdevido       =   new.vlricms     -       new.vlricmsdiferido;

    new.vlricmscredpresum   =   new.vlrbaseicms *      ( new.aliqicmsuf  / cast(100.00 as numeric(15,5) ) )  ;
    
    new.vlricmscredpresum   =   new.vlricmscredpresum - new.vlricmsdiferido;

    if (new.perccredpresimp<100) then
    begin
       new.vlricmscredpresum = new.vlricmscredpresum * ( new.perccredpresimp / cast(100.00 as numeric(15,5) ) ) ; 
    end

    new.vlricmsrecolhimento =   new.vlricmsdevido   -   new.vlricmscredpresum;

    -- Gerando o número do sequencial de adição.
    if(old.codncm <> new.codncm) then
    begin
        select coalesce(count(*),0) + 1
        from cpitimportacao
        where codemp=new.codemp and codfilial=new.codfilial and codimp=new.codimp and codncm=new.codncm
        into new.seqadic;
    end


end
^

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.5.1 (13/06/2012)';
    suspend;
end
^

SET TERM ; ^

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODTIPOMOV POSITION 3;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPMN POSITION 4;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALMN POSITION 5;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODMODNOTA POSITION 6;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPSE POSITION 7;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALSE POSITION 8;

ALTER TABLE EQTIPOMOV ALTER COLUMN SERIE POSITION 9;

ALTER TABLE EQTIPOMOV ALTER COLUMN DESCTIPOMOV POSITION 10;

ALTER TABLE EQTIPOMOV ALTER COLUMN ESTIPOMOV POSITION 11;

ALTER TABLE EQTIPOMOV ALTER COLUMN FISCALTIPOMOV POSITION 12;

ALTER TABLE EQTIPOMOV ALTER COLUMN ESTOQTIPOMOV POSITION 13;

ALTER TABLE EQTIPOMOV ALTER COLUMN TIPOMOV POSITION 14;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPTB POSITION 15;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALTB POSITION 16;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODTAB POSITION 17;

ALTER TABLE EQTIPOMOV ALTER COLUMN ESPECIETIPOMOV POSITION 18;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPTM POSITION 19;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALTM POSITION 20;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODTIPOMOVTM POSITION 21;

ALTER TABLE EQTIPOMOV ALTER COLUMN IMPPEDTIPOMOV POSITION 22;

ALTER TABLE EQTIPOMOV ALTER COLUMN IMPNFTIPOMOV POSITION 23;

ALTER TABLE EQTIPOMOV ALTER COLUMN IMPBOLTIPOMOV POSITION 24;

ALTER TABLE EQTIPOMOV ALTER COLUMN IMPRECTIPOMOV POSITION 25;

ALTER TABLE EQTIPOMOV ALTER COLUMN REIMPNFTIPOMOV POSITION 26;

ALTER TABLE EQTIPOMOV ALTER COLUMN TUSUTIPOMOV POSITION 27;

ALTER TABLE EQTIPOMOV ALTER COLUMN SOMAVDTIPOMOV POSITION 28;

ALTER TABLE EQTIPOMOV ALTER COLUMN SEQNFTIPOMOV POSITION 29;

ALTER TABLE EQTIPOMOV ALTER COLUMN VLRMFINTIPOMOV POSITION 30;

ALTER TABLE EQTIPOMOV ALTER COLUMN MCOMISTIPOMOV POSITION 31;

ALTER TABLE EQTIPOMOV ALTER COLUMN OPERTIPOMOV POSITION 32;

ALTER TABLE EQTIPOMOV ALTER COLUMN CTIPOFRETE POSITION 33;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPRC POSITION 34;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALRC POSITION 35;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODREGRCOMIS POSITION 36;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPTN POSITION 37;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALTN POSITION 38;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODTRAN POSITION 39;

ALTER TABLE EQTIPOMOV ALTER COLUMN EMITNFCPMOV POSITION 40;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPDF POSITION 41;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALDF POSITION 42;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODMODDOCFISC POSITION 43;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODEMPPP POSITION 44;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODFILIALPP POSITION 45;

ALTER TABLE EQTIPOMOV ALTER COLUMN CODPLANOPAG POSITION 46;

ALTER TABLE EQTIPOMOV ALTER COLUMN DTINS POSITION 47;

ALTER TABLE EQTIPOMOV ALTER COLUMN HINS POSITION 48;

ALTER TABLE EQTIPOMOV ALTER COLUMN IDUSUINS POSITION 49;

ALTER TABLE EQTIPOMOV ALTER COLUMN DTALT POSITION 50;

ALTER TABLE EQTIPOMOV ALTER COLUMN HALT POSITION 51;

ALTER TABLE EQTIPOMOV ALTER COLUMN IDUSUALT POSITION 52;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODEMPBO POSITION 3;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODFILIALBO POSITION 4;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODBANCO POSITION 5;

ALTER TABLE SGITPREFERE6 ALTER COLUMN TIPOFEBRABAN POSITION 6;

ALTER TABLE SGITPREFERE6 ALTER COLUMN MDECOB POSITION 7;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODCONV POSITION 8;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CONVCOB POSITION 9;

ALTER TABLE SGITPREFERE6 ALTER COLUMN VERLAYOUT POSITION 10;

ALTER TABLE SGITPREFERE6 ALTER COLUMN IDENTSERV POSITION 11;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CONTACOMPR POSITION 12;

ALTER TABLE SGITPREFERE6 ALTER COLUMN IDENTAMBCLI POSITION 13;

ALTER TABLE SGITPREFERE6 ALTER COLUMN IDENTAMBBCO POSITION 14;

ALTER TABLE SGITPREFERE6 ALTER COLUMN NROSEQ POSITION 15;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODEMPCA POSITION 16;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODFILIALCA POSITION 17;

ALTER TABLE SGITPREFERE6 ALTER COLUMN NUMCONTA POSITION 18;

ALTER TABLE SGITPREFERE6 ALTER COLUMN FORCADTIT POSITION 19;

ALTER TABLE SGITPREFERE6 ALTER COLUMN TIPODOC POSITION 20;

ALTER TABLE SGITPREFERE6 ALTER COLUMN IDENTEMITBOL POSITION 21;

ALTER TABLE SGITPREFERE6 ALTER COLUMN IDENTDISTBOL POSITION 22;

ALTER TABLE SGITPREFERE6 ALTER COLUMN ESPECTIT POSITION 23;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODJUROS POSITION 24;

ALTER TABLE SGITPREFERE6 ALTER COLUMN VLRPERCJUROS POSITION 25;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODDESC POSITION 26;

ALTER TABLE SGITPREFERE6 ALTER COLUMN VLRPERCDESC POSITION 27;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODPROT POSITION 28;

ALTER TABLE SGITPREFERE6 ALTER COLUMN DIASPROT POSITION 29;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODBAIXADEV POSITION 30;

ALTER TABLE SGITPREFERE6 ALTER COLUMN DIASBAIXADEV POSITION 31;

ALTER TABLE SGITPREFERE6 ALTER COLUMN ACEITE POSITION 32;

ALTER TABLE SGITPREFERE6 ALTER COLUMN PADRAOCNAB POSITION 33;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CAMINHOREMESSA POSITION 34;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CAMINHORETORNO POSITION 35;

ALTER TABLE SGITPREFERE6 ALTER COLUMN BACKUPREMESSA POSITION 36;

ALTER TABLE SGITPREFERE6 ALTER COLUMN BACKUPRETORNO POSITION 37;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODINSTR POSITION 38;

ALTER TABLE SGITPREFERE6 ALTER COLUMN CODOUTINSTR POSITION 39;

ALTER TABLE SGITPREFERE6 ALTER COLUMN PADRAOSIACC POSITION 40;

ALTER TABLE SGITPREFERE6 ALTER COLUMN DTINS POSITION 41;

ALTER TABLE SGITPREFERE6 ALTER COLUMN HINS POSITION 42;

ALTER TABLE SGITPREFERE6 ALTER COLUMN IDUSUINS POSITION 43;

ALTER TABLE SGITPREFERE6 ALTER COLUMN DTALT POSITION 44;

ALTER TABLE SGITPREFERE6 ALTER COLUMN HALT POSITION 45;

ALTER TABLE SGITPREFERE6 ALTER COLUMN IDUSUALT POSITION 46;


COMMIT WORK;
