copy \\servidor\dados\freedom\lib\freedomstd.jar \opt\freedom\lib\freedomstd.jar
copy \\servidor\dados\freedom\lib\freedomatd.jar \opt\freedom\lib\freedomatd.jar
copy \\servidor\dados\freedom\lib\freedomgms.jar \opt\freedom\lib\freedomgms.jar
copy \\servidor\dados\freedom\lib\freedomtmk.jar \opt\freedom\lib\freedomtmk.jar
copy \\servidor\dados\freedom\lib\freedomfnc.jar \opt\freedom\lib\freedomfnc.jar
copy \\servidor\dados\freedom\lib\freedompcp.jar \opt\freedom\lib\freedompcp.jar
copy \\servidor\dados\freedom\lib\freedomcfg.jar \opt\freedom\lib\freedomcfg.jar
copy \\servidor\dados\freedom\lib\freedompdv.jar \opt\freedom\lib\freedompdv.jar
copy \\servidor\dados\freedom\lib\firebirdsql-full.jar \opt\freedom\lib\firebirdsql-full.jar
copy \\servidor\dados\freedom\lib\mail.jar \opt\freedom\lib\mail.jar
copy \\servidor\dados\freedom\lib\itext-1.02b.jar \opt\freedom\lib\itext-1.02b.jar
copy \\servidor\dados\freedom\lib\jcommon-0.8.7.jar \opt\freedom\lib\jcommon-0.8.7.jar
copy \\servidor\dados\freedom\lib\jfreechart-0.9.12.jar \opt\freedom\lib\jfreechart-0.9.12.jar
copy \\servidor\dados\freedom\lib\activation.jar \opt\freedom\lib\activation.jar
copy \\servidor\dados\freedom\lib\nachocalendar-0.21.jar \opt\freedom\lib\nachocalendar-0.21.jar
copy \\servidor\dados\freedom\lib\commons-logging.jar \opt\freedom\lib\commons-logging.jar
copy \\servidor\dados\freedom\lib\jasperreports-0.6.7.jar \opt\freedom\lib\jasperreports-0.6.7.jar
copy \\servidor\dados\freedom\exec\*.bat \opt\freedom

