INSERT INTO SGESTACAO (CODEMP, CODFILIAL, CODEST, DESCEST, MODODEMOEST)
SELECT CODEMP, CODFILIAL, CODCAIXA, DESCCAIXA, MODODEMO FROM PVCAIXA;

COMMIT WORK;

INSERT INTO SGESTACAOIMP (CODEMP, CODFILIAL, CODEST, NROIMP, IMPPAD, CODEMPIP, CODFILIALIP, CODIMP,
 CODEMPPP, CODFILIALPP, CODPAPEL, TIPOUSOIMP, PORTAWIN, PORTALIN)
SELECT CI.CODEMP, CI.CODFILIAL, CI.CODCAIXA, CI.CODIMP, CI.IMPPAD, CI.CODEMP, CI.CODFILIAL, CI.CODIMP,
 I.CODEMPPL, I.CODFILIALPL, I.CODPAPEL, I.DESTIMP, I.PORTAWINIMP, I.PORTALINIMP
FROM PVCAIXAIMP CI, SGIMPRESSORA I 
WHERE CI.CODEMP=I.CODEMP AND CI.CODFILIAL=I.CODFILIAL AND 
CI.CODIMP=I.CODIMP;

COMMIT WORK;

GRANT SELECT ON VDCLIENTE TO PROCEDURE VDCLIENTEATIVOSP;

COMMIT WORK;
GRANT EXECUTE ON PROCEDURE VDCLIENTEATIVOSP TO TRIGGER VDVENDATGBI;
COMMIT WORK;
GRANT EXECUTE ON PROCEDURE VDCLIENTEATIVOSP TO TRIGGER VDVENDATGBU;
COMMIT WORK;
GRANT EXECUTE ON PROCEDURE VDCLIENTEATIVOSP TO TRIGGER VDORCAMENTOTGBU;
COMMIT WORK;
GRANT EXECUTE ON PROCEDURE VDCLIENTEATIVOSP TO TRIGGER VDORCAMENTOTGBI;
COMMIT WORK;
