INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1', 'VENDA PARA PF');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO ESTADO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1100', 'COMPRAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO OU PRESTAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1101', 'Compra para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1102', 'Compra para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1111', 'Compra para industrialização de mercadoria recebida anterior');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1113', 'Compra para comercialização- de mercadoria recebida anterior');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1116', 'Compra para industrialização originada de encomenda para rec');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1117', 'Compra para comercialização originada de encomenda para rece');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1118', 'Compra de mercadoria para comercialização pelo adquirente or');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1120', 'Compra para industrialização- em venda à ordem- já recebida');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1121', 'Compra para comercialização- em venda à ordem- já recebida d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1122', 'Compra para industrialização em que a mercadoria foi remetid');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1124', 'Industrialização efetuada por outra empresa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1125', 'Industrialização efetuada por outra empresa quando a mercado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1126', 'Compra para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1150', 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO OU PRE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1151', 'Transferência para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1152', 'Transferência para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1153', 'Transferência de energia elétrica para distribuição');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1154', 'Transferência para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA- DE TERCEIROS OU AN');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1202', 'Devolução de venda de mercadoria adquirida ou recebida de te');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1203', 'Devolução de venda de produção do estabelecimento- destinada');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1204', 'Devolução de venda de mercadoria adquirida ou recebida de te');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1205', 'Anulação de valor relativo à prestação de serviço de comunic');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1206', 'Anulação de valor relativo à prestação de serviço de transpo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1208', 'Devolução de produção do estabelecimento- remetida em transf');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1209', 'Devolução de mercadoria adquirida ou recebida de terceiros-');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1251', 'Compra de energia elétrica para distribuição ou comercializa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1252', 'Compra de energia elétrica por estabelecimento industrial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1253', 'Compra de energia elétrica por estabelecimento comercial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1254', 'Compra de energia elétrica por estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1255', 'Compra de energia elétrica por estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1256', 'Compra de energia elétrica por estabelecimento de produtor r');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1257', 'Compra de energia elétrica para consumo por demanda contrata');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1301', 'Aquisição de serviço de comunicação para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1302', 'Aquisição de serviço de comunicação por estabelecimento indu');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1303', 'Aquisição de serviço de comunicação por estabelecimento come');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1304', 'Aquisição de serviço de comunicação por estabelecimento de p');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1305', 'Aquisição de serviço de comunicação por estabelecimento de g');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1306', 'Aquisição de serviço de comunicação por estabelecimento de p');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1351', 'Aquisição de serviço de transporte para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1352', 'Aquisição de serviço de transporte por estabelecimento indus');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1353', 'Aquisição de serviço de transporte por estabelecimento comer');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1354', 'Aquisição de serviço de transporte por estabelecimento de pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1355', 'Aquisição de serviço de transporte por estabelecimento de ge');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1356', 'Aquisição de serviço de transporte por estabelecimento de pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1400', 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO T');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1401', 'Compra para industrialização em operação com mercadoria suje');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1403', 'Compra para comercialização em operação com mercadoria sujei');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1406', 'Compra de bem para o ativo imobilizado cuja mercadoria está');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1407', 'Compra de mercadoria para uso ou consumo cuja mercadoria est');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1408', 'Transferência para industrialização em operação com mercador');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1409', 'Transferência para comercialização em operação com mercadori');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1410', 'Devolução de venda de produção do estabelecimento em operaçã');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1411', 'Devolução de venda de mercadoria adquirida ou recebida de te');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1414', 'Retorno de produção do estabelecimento- remetida para venda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1415', 'Retorno de mercadoria adquirida ou recebida de terceiros- re');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1450', 'SISTEMAS DE INTEGRAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1451', 'Retorno de animal do estabelecimento produtor');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1452', 'Retorno de insumo não utilizado na produção');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1500', 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1501', 'Entrada de mercadoria recebida com fim específico de exporta');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1503', 'Entrada decorrente de devolução de produto remetido com fim');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1504', 'Entrada decorrente de devolução de mercadoria remetida com f');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1551', 'Compra de bem para o ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1552', 'Transferência de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1554', 'Retorno de bem do ativo imobilizado remetido para uso fora d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1555', 'Entrada de bem do ativo imobilizado de terceiro- remetido pa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1556', 'Compra de material para uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1557', 'Transferência de material para uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1601', 'Recebimento- por transferência- de crédito de ICMS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1602', 'Recebimento- por transferência- de saldo credor de ICMS de o');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1604', 'Lançamento do crédito relativo à compra de bem para o ativo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1605', 'Recebimento- por transferência- de saldo devedor de ICMS de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1650', 'ENTRADAS DE COMBUSTÍVEIS- DERIVADOS OU NÃO DE PETRÓLEO E LUB');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1651', 'Compra de combustível ou lubrificante para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1652', 'Compra de combustível ou lubrificante para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1653', 'Compra de combustível ou lubrificante por consumidor ou usuá');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1658', 'Transferência de combustível e lubrificante para industriali');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1659', 'Transferência de combustível e lubrificante para comercializ');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1660', 'Devolução de venda de combustível ou lubrificante destinado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1661', 'Devolução de venda de combustível ou lubrificante destinado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1662', 'Devolução de venda de combustível ou lubrificante destinado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1663', 'Entrada de combustível ou lubrificante para armazenagem');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1664', 'Retorno de combustível ou lubrificante remetido para armazen');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1901', 'Entrada para industrialização por encomenda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1902', 'Retorno de mercadoria remetida para industrialização por enc');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1903', 'Entrada de mercadoria remetida para industrialização e não a');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1904', 'Retorno de remessa para venda fora do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1905', 'Entrada de mercadoria recebida para depósito em depósito fec');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1906', 'Retorno de mercadoria remetida para depósito fechado ou arma');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1907', 'Retorno simbólico de mercadoria remetida para depósito fecha');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1908', 'Entrada de bem por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1909', 'Retorno de bem remetido por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1910', 'Entrada de bonificação- doação ou brinde');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1911', 'Entrada de amostra grátis');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1912', 'Entrada de mercadoria ou bem recebido para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1913', 'Retorno de mercadoria ou bem remetido para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1914', 'Retorno de mercadoria ou bem remetido para exposição ou feir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1915', 'Entrada de mercadoria ou bem recebido para conserto ou repar');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1916', 'Retorno de mercadoria ou bem remetido para conserto ou repar');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1917', 'Entrada de mercadoria recebida em consignação mercantil ou i');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1918', 'Devolução de mercadoria remetida em consignação mercantil ou');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1919', 'Devolução simbólica de mercadoria vendida ou utilizada em pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1920', 'Entrada de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1921', 'Retorno de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1922', 'Lançamento efetuado a título de simples faturamento decorren');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1923', 'Entrada de mercadoria recebida do vendedor remetente- em ven');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1924', 'Entrada para industrialização por conta e ordem do adquirent');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1925', 'Retorno de mercadoria remetida para industrialização por con');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1926', 'Lançamento efetuado a título de reclassificação de mercadori');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1931', 'ançamento efetuado pelo tomador do serviço de transporte qua');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1932', 'quisição de serviço de transporte iniciado em unidade da Fed');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1933', 'Aquisição de serviço tributado pelo ISSQN');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('1949', 'Outra entrada de mercadoria ou prestação de serviço não espe');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DE OUTROS ESTADOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2100', 'COMPRAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO OU PRESTAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2101', 'Compra para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2102', 'Compra para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2111', 'Compra para industrialização de mercadoria recebida anterior');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2113', 'Compra para comercialização- de mercadoria recebida anterior');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2116', 'Compra para industrialização originada de encomenda para rec');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2117', 'Compra para comercialização originada de encomenda para rece');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2118', 'Compra de mercadoria para comercialização pelo adquirente or');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2120', 'Compra para industrialização- em venda à ordem- já recebida');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2121', 'Compra para comercialização- em venda à ordem- já recebida d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2122', 'Compra para industrialização em que a mercadoria foi remetid');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2124', 'Industrialização efetuada por outra empresa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2125', 'Industrialização efetuada por outra empresa quando a mercado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2126', 'Compra para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2150', 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO OU PRE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2151', 'Transferência para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2152', 'Transferência para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2153', 'Transferência de energia elétrica para distribuição');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2154', 'Transferência para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA- DE TERCEIROS OU AN');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2202', 'Devolução de venda de mercadoria adquirida ou recebida de te');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2203', 'Devolução de venda de produção do estabelecimento- destinada');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2204', 'Devolução de venda de mercadoria adquirida ou recebida de te');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2205', 'Anulação de valor relativo à prestação de serviço de comunic');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2206', 'Anulação de valor relativo à prestação de serviço de transpo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2208', 'Devolução de produção do estabelecimento- remetida em transf');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2209', 'Devolução de mercadoria adquirida ou recebida de terceiros-');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2251', 'Compra de energia elétrica para distribuição ou comercializa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2252', 'Compra de energia elétrica por estabelecimento industrial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2253', 'Compra de energia elétrica por estabelecimento comercial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2254', 'Compra de energia elétrica por estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2255', 'Compra de energia elétrica por estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2256', 'Compra de energia elétrica por estabelecimento de produtor r');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2257', 'Compra de energia elétrica para consumo por demanda contrata');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2301', 'Aquisição de serviço de comunicação para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2302', 'Aquisição de serviço de comunicação por estabelecimento indu');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2303', 'Aquisição de serviço de comunicação por estabelecimento come');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2304', 'Aquisição de serviço de comunicação por estabelecimento de p');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2305', 'Aquisição de serviço de comunicação por estabelecimento de g');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2306', 'Aquisição de serviço de comunicação por estabelecimento de p');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2351', 'Aquisição de serviço de transporte para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2352', 'Aquisição de serviço de transporte por estabelecimento indus');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2353', 'Aquisição de serviço de transporte por estabelecimento comer');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2354', 'Aquisição de serviço de transporte por estabelecimento de pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2355', 'Aquisição de serviço de transporte por estabelecimento de ge');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2356', 'Aquisição de serviço de transporte por estabelecimento de pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2400', 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO T');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2401', 'Compra para industrialização em operação com mercadoria suje');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2403', 'Compra para comercialização em operação com mercadoria sujei');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2406', 'Compra de bem para o ativo imobilizado cuja mercadoria está');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2407', 'Compra de mercadoria para uso ou consumo cuja mercadoria est');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2408', 'Transferência para industrialização em operação com mercador');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2409', 'Transferência para comercialização em operação com mercadori');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2410', 'Devolução de venda de produção do estabelecimento em operaçã');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2411', 'Devolução de venda de mercadoria adquirida ou recebida de te');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2414', 'Retorno de produção do estabelecimento- remetida para venda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2415', 'Retorno de mercadoria adquirida ou recebida de terceiros- re');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2500', 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2501', 'Entrada de mercadoria recebida com fim específico de exporta');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2503', 'Entrada decorrente de devolução de produto remetido com fim');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2504', 'Entrada decorrente de devolução de mercadoria remetida com f');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2551', 'Compra de bem para o ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2552', 'Transferência de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2554', 'Retorno de bem do ativo imobilizado remetido para uso fora d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2555', 'Entrada de bem do ativo imobilizado de terceiro- remetido pa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2556', 'Compra de material para uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2557', 'Transferência de material para uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2650', 'ENTRADAS DE COMBUSTÍVEIS- DERIVADOS OU NÃO DE PETRÓLEO E LUB');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2651', 'Compra de combustível ou lubrificante para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2652', 'Compra de combustível ou lubrificante para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2653', 'Compra de combustível ou lubrificante por consumidor ou usuá');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2658', 'Transferência de combustível e lubrificante para industriali');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2659', 'Transferência de combustível e lubrificante para comercializ');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2660', 'Devolução de venda de combustível ou lubrificante destinado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2661', 'Devolução de venda de combustível ou lubrificante destinado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2662', 'Devolução de venda de combustível ou lubrificante destinado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2663', 'Entrada de combustível ou lubrificante para armazenagem');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2664', 'Retorno de combustível ou lubrificante remetido para armazen');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2901', 'Entrada para industrialização por encomenda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2902', 'Retorno de mercadoria remetida para industrialização por enc');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2903', 'Entrada de mercadoria remetida para industrialização e não a');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2904', 'Retorno de remessa para venda fora do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2905', 'Entrada de mercadoria recebida para depósito em depósito fec');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2906', 'Retorno de mercadoria remetida para depósito fechado ou arma');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2907', 'Retorno simbólico de mercadoria remetida para depósito fecha');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2908', 'Entrada de bem por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2909', 'Retorno de bem remetido por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2910', 'Entrada de bonificação- doação ou brinde');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2911', 'Entrada de amostra grátis');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2912', 'Entrada de mercadoria ou bem recebido para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2913', 'Retorno de mercadoria ou bem remetido para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2914', 'Retorno de mercadoria ou bem remetido para exposição ou feir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2915', 'Entrada de mercadoria ou bem recebido para conserto ou repar');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2916', 'Retorno de mercadoria ou bem remetido para conserto ou repar');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2917', 'Entrada de mercadoria recebida em consignação mercantil ou i');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2918', 'Devolução de mercadoria remetida em consignação mercantil ou');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2919', 'Devolução simbólica de mercadoria vendida ou utilizada em pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2920', 'Entrada de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2921', 'Retorno de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2922', 'Lançamento efetuado a título de simples faturamento decorren');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2923', 'Entrada de mercadoria recebida do vendedor remetente- em ven');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2924', 'Entrada para industrialização por conta e ordem do adquirent');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2925', 'Retorno de mercadoria remetida para industrialização por con');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2931', 'ançamento efetuado pelo tomador do serviço de transporte qua');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2932', 'quisição de serviço de transporte iniciado em unidade da Fed');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2933', 'Aquisição de serviço tributado pelo ISSQN');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('2949', 'Outra entrada de mercadoria ou prestação de serviço não espe');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO EXTERIOR');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3100', 'COMPRAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO OU PRESTAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3101', 'Compra para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3102', 'Compra para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3126', 'Compra para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3127', 'Compra para industrialização sob o regime de "drawback"');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA- DE TERCEIROS OU AN');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3202', 'Devolução de venda de mercadoria adquirida ou recebida de te');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3205', 'Anulação de valor relativo à prestação de serviço de comunic');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3206', 'Anulação de valor relativo à prestação de serviço de transpo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3211', 'Devolução de venda de produção do estabelecimento sob o regi');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3251', 'Compra de energia elétrica para distribuição ou comercializa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3301', 'Aquisição de serviço de comunicação para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3351', 'Aquisição de serviço de transporte para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3352', 'Aquisição de serviço de transporte por estabelecimento indus');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3353', 'Aquisição de serviço de transporte por estabelecimento comer');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3354', 'Aquisição de serviço de transporte por estabelecimento de pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3355', 'Aquisição de serviço de transporte por estabelecimento de ge');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3356', 'Aquisição de serviço de transporte por estabelecimento de pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3500', 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3503', 'Devolução de mercadoria exportada que tenha sido recebida co');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3551', 'Compra de bem para o ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3556', 'Compra de material para uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3650', 'ENTRADAS DE COMBUSTÍVEIS- DERIVADOS OU NÃO DE PETRÓLEO E LUB');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3651', 'Compra de combustível ou lubrificante para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3652', 'Compra de combustível ou lubrificante para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3653', 'Compra de combustível ou lubrificante por consumidor ou usuá');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3930', 'Lançamento efetuado a título de entrada de bem sob amparo de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('3949', 'Outra entrada de mercadoria ou prestação de serviço não espe');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O ESTADO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5101', 'Venda de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5102', 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5103', 'Venda de produção do estabelecimento- efetuada fora do estab');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5104', 'Venda de mercadoria adquirida ou recebida de terceiros- efet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5105', 'Venda de produção do estabelecimento que não deva por ele tr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5106', 'Venda de mercadoria adquirida ou recebida de terceiros- que');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5109', 'Venda de produção do estabelecimento- destinada à Zona Franc');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5110', 'Venda de mercadoria adquirida ou recebida de terceiros- dest');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5111', 'Venda de produção do estabelecimento remetida anteriormente');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5112', 'Venda de mercadoria adquirida ou recebida de terceiros remet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5113', 'Venda de produção do estabelecimento remetida anteriormente');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5114', 'Venda de mercadoria adquirida ou recebida de terceiros remet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5115', 'Venda de mercadoria adquirida ou recebida de terceiros- rece');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5116', 'Venda de produção do estabelecimento originada de encomenda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5117', 'Venda de mercadoria adquirida ou recebida de terceiros- orig');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5118', 'Venda de produção do estabelecimento entregue ao destinatári');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5119', 'Venda de mercadoria adquirida ou recebida de terceiros entre');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5120', 'Venda de mercadoria adquirida ou recebida de terceiros entre');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5122', 'Venda de produção do estabelecimento remetida para industria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5123', 'Venda de mercadoria adquirida ou recebida de terceiros remet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5124', 'Industrialização efetuada para outra empresa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5125', 'Industrialização efetuada para outra empresa quando a mercad');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5150', 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5151', 'Transferência de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5152', 'Transferência de mercadoria adquirida ou recebida de terceir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5153', 'Transferência de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5155', 'Transferência de produção do estabelecimento- que não deva p');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5156', 'Transferência de mercadoria adquirida ou recebida de terceir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5201', 'Devolução de compra para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5202', 'Devolução de compra para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5205', 'Anulação de valor relativo a aquisição de serviço de comunic');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5206', 'Anulação de valor relativo a aquisição de serviço de transpo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5208', 'Devolução de mercadoria recebida em transferência para indus');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5209', 'Devolução de mercadoria recebida em transferência para comer');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5251', 'Venda de energia elétrica para distribuição ou comercializaç');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5252', 'Venda de energia elétrica para estabelecimento industrial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5253', 'Venda de energia elétrica para estabelecimento comercial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5254', 'Venda de energia elétrica para estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5255', 'Venda de energia elétrica para estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5256', 'Venda de energia elétrica para estabelecimento de produtor r');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5257', 'Venda de energia elétrica para consumo por demanda contratad');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5258', 'Venda de energia elétrica a não contribuinte');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5301', 'Prestação de serviço de comunicação para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5302', 'Prestação de serviço de comunicação a estabelecimento indust');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5303', 'Prestação de serviço de comunicação a estabelecimento comerc');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5304', 'Prestação de serviço de comunicação a estabelecimento de pre');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5305', 'Prestação de serviço de comunicação a estabelecimento de ger');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5306', 'Prestação de serviço de comunicação a estabelecimento de pro');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5307', 'Prestação de serviço de comunicação a não contribuinte');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5350', 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5351', 'Prestação de serviço de transporte para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5352', 'Prestação de serviço de transporte a estabelecimento industr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5353', 'Prestação de serviço de transporte a estabelecimento comerci');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5354', 'Prestação de serviço de transporte a estabelecimento de pres');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5355', 'Prestação de serviço de transporte a estabelecimento de gera');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5356', 'Prestação de serviço de transporte a estabelecimento de prod');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5357', 'Prestação de serviço de transporte a não contribuinte');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5359', 'Prestação de serviço de transporte a contribuinte ou a não c');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5400', 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRI');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5401', 'Venda de produção do estabelecimento em operação com produto');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5402', 'Venda de produção do estabelecimento de produto sujeito ao r');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5403', 'Venda de mercadoria adquirida ou recebida de terceiros em op');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5405', 'Venda de mercadoria adquirida ou recebida de terceiros em op');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5408', 'Transferência de produção do estabelecimento em operação com');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5409', 'Transferência de mercadoria adquirida ou recebida de terceir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5410', 'Devolução de compra para industrialização em operação com me');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5411', 'Devolução de compra para comercialização em operação com mer');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5412', 'Devolução de bem do ativo imobilizado- em operação com merca');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5413', 'Devolução de mercadoria destinada ao uso ou consumo- em oper');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5414', 'Remessa de produção do estabelecimento para venda fora do es');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5415', 'Remessa de mercadoria adquirida ou recebida de terceiros par');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5450', 'SISTEMAS DE INTEGRAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5451', 'Remessa de animal e de insumo para estabelecimento produtor');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5500', 'REMESSAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLU');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5501', 'Remessa de produção do estabelecimento- com fim específico d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5502', 'Remessa de mercadoria adquirida ou recebida de terceiros- co');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5503', 'Devolução de mercadoria recebida com fim específico de expor');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5551', 'Venda de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5552', 'Transferência de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5554', 'Remessa de bem do ativo imobilizado para uso fora do estabel');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5555', 'Devolução de bem do ativo imobilizado de terceiro- recebido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5557', 'Transferência de material de uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5601', 'Transferência de crédito de ICMS acumulado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5602', 'Transferência de saldo credor de ICMS para outro estabelecim');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5605', 'Transferência de saldo devedor de ICMS de outro estabelecime');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5650', 'SAÍDAS DE COMBUSTÍVEIS- DERIVADOS OU NÃO DE PETRÓLEO E LUBRI');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5651', 'Venda de combustível ou lubrificante de produção do estabele');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5652', 'Venda de combustível ou lubrificante de produção do estabele');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5653', 'Venda de combustível ou lubrificante de produção do estabele');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5654', 'Venda de combustível ou lubrificante adquirido ou recebido d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5655', 'Venda de combustível ou lubrificante adquirido ou recebido d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5656', 'Venda de combustível ou lubrificante adquirido ou recebido d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5657', 'Remessa de combustível ou lubrificante adquirido ou recebido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5658', 'Transferência de combustível ou lubrificante de produção do');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5659', 'Transferência de combustível ou lubrificante adquirido ou re');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5660', 'Devolução de compra de combustível ou lubrificante adquirido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5661', 'Devolução de compra de combustível ou lubrificante adquirido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5662', 'Devolução de compra de combustível ou lubrificante adquirido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5663', 'Remessa para armazenagem de combustível ou lubrificante');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5664', 'Retorno de combustível ou lubrificante recebido para armazen');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5665', 'Retorno simbólico de combustível ou lubrificante recebido pa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5666', 'Remessa por conta e ordem de terceiros de combustível ou lub');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5901', 'Remessa para industrialização por encomenda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5902', 'Retorno de mercadoria utilizada na industrialização por enco');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5903', 'Retorno de mercadoria recebida para industrialização e não a');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5904', 'Remessa para venda fora do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5905', 'Remessa para depósito fechado ou armazém geral');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5906', 'Retorno de mercadoria depositada em depósito fechado ou arma');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5907', 'Retorno simbólico de mercadoria depositada em depósito fecha');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5908', 'Remessa de bem por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5909', 'Retorno de bem recebido por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5910', 'Remessa em bonificação- doação ou brinde');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5911', 'Remessa de amostra grátis');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5912', 'Remessa de mercadoria ou bem para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5913', 'Retorno de mercadoria ou bem recebido para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5914', 'Remessa de mercadoria ou bem para exposição ou feira');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5915', 'Remessa de mercadoria ou bem para conserto ou reparo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5916', 'Retorno de mercadoria ou bem recebido para conserto ou repar');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5917', 'Remessa de mercadoria em consignação mercantil ou industrial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5918', 'Devolução de mercadoria recebida em consignação mercantil ou');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5919', 'Devolução simbólica de mercadoria vendida ou utilizada em pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5920', 'Remessa de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5921', 'Devolução de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5922', 'Lançamento efetuado a título de simples faturamento decorren');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5923', 'Remessa de mercadoria por conta e ordem de terceiros- em ven');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5924', 'Remessa para industrialização por conta e ordem do adquirent');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5925', 'Retorno de mercadoria recebida para industrialização por con');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5926', 'Lançamento efetuado a título de reclassificação de mercadori');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5928', 'Lançamento efetuado a título de baixa de estoque decorrente');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5929', 'Lançamento efetuado em decorrência de emissão de documento f');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5931', 'Lançamento efetuado em decorrência da responsabilidade de re');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5932', 'Prestação de serviço de transporte iniciada em unidade da Fe');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5933', 'Prestação de serviço tributado pelo ISSQN');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('5949', 'Outra saída de mercadoria ou prestação de serviço não especi');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA OUTROS ESTADOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6101', 'Venda de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6102', 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6103', 'Venda de produção do estabelecimento- efetuada fora do estab');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6104', 'Venda de mercadoria adquirida ou recebida de terceiros- efet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6105', 'Venda de produção do estabelecimento que não deva por ele tr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6106', 'Venda de mercadoria adquirida ou recebida de terceiros- que');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6107', 'Venda de produção do estabelecimento- destinada a não contri');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6108', 'Venda de mercadoria adquirida ou recebida de terceiros- dest');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6109', 'Venda de produção do estabelecimento- destinada à Zona Franc');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6110', 'Venda de mercadoria adquirida ou recebida de terceiros- dest');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6111', 'Venda de produção do estabelecimento remetida anteriormente');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6112', 'Venda de mercadoria adquirida ou recebida de Terceiros remet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6113', 'Venda de produção do estabelecimento remetida anteriormente');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6114', 'Venda de mercadoria adquirida ou recebida de terceiros remet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6115', 'Venda de mercadoria adquirida ou recebida de terceiros- rece');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6116', 'Venda de produção do estabelecimento originada de encomenda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6117', 'Venda de mercadoria adquirida ou recebida de terceiros- orig');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6118', 'Venda de produção do estabelecimento entregue ao destinatári');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6119', 'Venda de mercadoria adquirida ou recebida de terceiros entre');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6120', 'Venda de mercadoria adquirida ou recebida de terceiros entre');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6122', 'Venda de produção do estabelecimento remetida para industria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6123', 'Venda de mercadoria adquirida ou recebida de terceiros remet');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6124', 'Industrialização efetuada para outra empresa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6125', 'Industrialização efetuada para outra empresa quando a mercad');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6150', 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6151', 'Transferência de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6152', 'Transferência de mercadoria adquirida ou recebida de terceir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6153', 'Transferência de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6155', 'Transferência de produção do estabelecimento- que não deva p');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6156', 'Transferência de mercadoria adquirida ou recebida de terceir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6201', 'Devolução de compra para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6202', 'Devolução de compra para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6205', 'Anulação de valor relativo a aquisição de serviço de comunic');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6206', 'Anulação de valor relativo a aquisição de serviço de transpo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6208', 'Devolução de mercadoria recebida em transferência para indus');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6209', 'Devolução de mercadoria recebida em transferência para comer');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6251', 'Venda de energia elétrica para distribuição ou comercializaç');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6252', 'Venda de energia elétrica para estabelecimento industrial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6253', 'Venda de energia elétrica para estabelecimento comercial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6254', 'Venda de energia elétrica para estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6255', 'Venda de energia elétrica para estabelecimento prestador de');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6256', 'Venda de energia elétrica para estabelecimento de produtor r');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6257', 'Venda de energia elétrica para consumo por demanda contratad');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6258', 'Venda de energia elétrica a não contribuinte');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6301', 'Prestação de serviço de comunicação para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6302', 'Prestação de serviço de comunicação a estabelecimento indust');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6303', 'Prestação de serviço de comunicação a estabelecimento comerc');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6304', 'Prestação de serviço de comunicação a estabelecimento de pre');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6305', 'Prestação de serviço de comunicação a estabelecimento de ger');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6306', 'Prestação de serviço de comunicação a estabelecimento de pro');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6307', 'Prestação de serviço de comunicação a não contribuinte');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6350', 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6351', 'Prestação de serviço de transporte para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6352', 'Prestação de serviço de transporte a estabelecimento industr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6353', 'Prestação de serviço de transporte a estabelecimento comerci');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6354', 'Prestação de serviço de transporte a estabelecimento de pres');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6355', 'Prestação de serviço de transporte a estabelecimento de gera');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6356', 'Prestação de serviço de transporte a estabelecimento de prod');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6357', 'Prestação de serviço de transporte a não contribuinte');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6359', 'Prestação de serviço de transporte a contribuinte ou a não c');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6400', 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRI');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6401', 'Venda de produção do estabelecimento em operação com produto');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6402', 'Venda de produção do estabelecimento de produto sujeito ao r');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6403', 'Venda de mercadoria adquirida ou recebida de terceiros em op');
COMMIT WORK;
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6404', 'Venda de mercadoria sujeita ao regime de substituição tribut');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6408', 'Transferência de produção do estabelecimento em operação com');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6409', 'Transferência de mercadoria adquirida ou recebida de terceir');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6410', 'Devolução de compra para industrialização em operação com me');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6411', 'Devolução de compra para comercialização em operação com mer');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6412', 'Devolução de bem do ativo imobilizado- em operação com merca');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6413', 'Devolução de mercadoria destinada ao uso ou consumo- em oper');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6414', 'Remessa de produção do estabelecimento para venda fora do es');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6415', 'Remessa de mercadoria adquirida ou recebida de terceiros par');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6500', 'REMESSAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLU');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6501', 'Remessa de produção do estabelecimento- com fim específico d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6502', 'Remessa de mercadoria adquirida ou recebida de terceiros- co');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6503', 'Devolução de mercadoria recebida com fim específico de expor');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6551', 'Venda de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6552', 'Transferência de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6554', 'Remessa de bem do ativo imobilizado para uso fora do estabel');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6555', 'Devolução de bem do ativo imobilizado de terceiro- recebido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6557', 'Transferência de material de uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6603', ' Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6650', 'SAÍDAS DE COMBUSTÍVEIS- DERIVADOS OU NÃO DE PETRÓLEO E LUBRI');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6651', 'Venda de combustível ou lubrificante de produção do estabele');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6652', 'Venda de combustível ou lubrificante de produção do estabele');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6653', 'Venda de combustível ou lubrificante de produção do estabele');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6654', 'Venda de combustível ou lubrificante adquirido ou recebido d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6655', 'Venda de combustível ou lubrificante adquirido ou recebido d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6656', 'Venda de combustível ou lubrificante adquirido ou recebido d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6657', 'Remessa de combustível ou lubrificante adquirido ou recebido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6658', 'Transferência de combustível ou lubrificante de produção do');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6659', 'Transferência de combustível ou lubrificante adquirido ou re');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6660', 'Devolução de compra de combustível ou lubrificante adquirido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6661', 'Devolução de compra de combustível ou lubrificante adquirido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6662', 'Devolução de compra de combustível ou lubrificante adquirido');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6663', 'Remessa para armazenagem de combustível ou lubrificante');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6664', 'Retorno de combustível ou lubrificante recebido para armazen');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6665', 'Retorno simbólico de combustível ou lubrificante recebido pa');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6666', 'Remessa por conta e ordem de terceiros de combustível ou lub');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6901', 'Remessa para industrialização por encomenda');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6902', 'Retorno de mercadoria utilizada na industrialização por enco');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6903', 'Retorno de mercadoria recebida para industrialização e não a');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6904', 'Remessa para venda fora do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6905', 'Remessa para depósito fechado ou armazém geral');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6906', 'Retorno de mercadoria depositada em depósito fechado ou arma');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6907', 'Retorno simbólico de mercadoria depositada em depósito fecha');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6908', 'Remessa de bem por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6909', 'Retorno de bem recebido por conta de contrato de comodato');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6910', 'Remessa em bonificação- doação ou brinde');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6911', 'Remessa de amostra grátis');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6912', 'Remessa de mercadoria ou bem para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6913', 'Retorno de mercadoria ou bem recebido para demonstração');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6914', 'Remessa de mercadoria ou bem para exposição ou feira');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6915', 'Remessa de mercadoria ou bem para conserto ou reparo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6916', 'Retorno de mercadoria ou bem recebido para conserto ou repar');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6917', 'Remessa de mercadoria em consignação mercantil ou industrial');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6918', 'Devolução de mercadoria recebida em consignação mercantil ou');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6919', 'Devolução simbólica de mercadoria vendida ou utilizada em pr');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6920', 'Remessa de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6921', 'Devolução de vasilhame ou sacaria');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6922', 'Lançamento efetuado a título de simples faturamento decorren');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6923', 'Remessa de mercadoria por conta e ordem de terceiros- em ven');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6924', 'Remessa para industrialização por conta e ordem do adquirent');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6925', 'Retorno de mercadoria recebida para industrialização por con');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6929', 'Lançamento efetuado em decorrência de emissão de documento f');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6931', 'Lançamento efetuado em decorrência da responsabilidade de re');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6932', 'Prestação de serviço de transporte iniciada em unidade da Fe');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6933', 'Prestação de serviço tributado pelo ISSQN');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('6949', 'Outra saída de mercadoria ou prestação de serviço não especi');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O EXTERIOR');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7101', 'Venda de produção do estabelecimento');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7102', 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7105', 'Venda de produção do estabelecimento- que não deva por ele t');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7106', 'Venda de mercadoria adquirida ou recebida de terceiros- que');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7127', 'Venda de produção do estabelecimento sob o regime de "drawba');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO- COMERCIALIZAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7201', 'Devolução de compra para industrialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7202', 'Devolução de compra para comercialização');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7205', 'Anulação de valor relativo à aquisição de serviço de comunic');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7206', 'Anulação de valor relativo a aquisição de serviço de transpo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7211', 'Devolução de compras para industrialização sob o regime de d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7251', 'Venda de energia elétrica para o exterior');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7301', 'Prestação de serviço de comunicação para execução de serviço');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7350', 'PRESTAÇÕES DE SERVIÇO DE TRANSPORTE');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7358', 'Prestação de serviço de transporte');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7500', 'EXPORTAÇÃO DE MERCADORIAS RECEBIDAS COM FIM ESPECÍFICO DE EX');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7501', 'Exportação de mercadorias recebidas com fim específico de ex');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7551', 'Venda de bem do ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7650', 'SAÍDAS DE COMBUSTÍVEIS- DERIVADOS OU NÃO DE PETRÓLEO E LUBRI');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7651', 'Venda de combustível ou lubrificante de produção do estabele');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7654', 'Venda de combustível ou lubrificante adquirido ou recebido d');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7930', 'Lançamento efetuado a título de devolução de bem cuja entrad');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('7949', 'Outra saída de mercadoria ou prestação de serviço não especi');
INSERT INTO LFNATOPER (CODNAT, DESCNAT) VALUES ('9927', 'Lançamento efetuado a título de baixa de estoque decorrente');

COMMIT WORK;
