GRANT EXECUTE ON PROCEDURE PVSEQMOVCAIXASP TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE SPGERANUMPDV TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE VDADICITEMPDVSP TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE PVFECHAVENDASP TO ROLE ADM;
COMMIT WORK;

