/* Server version: LI-V6.3.2.26540 Firebird 2.5 
   SQLDialect: 3. ODS: 11.2. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 2048 (8192 Kb). Read-only: False. */
SET SQL DIALECT 3;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom251.2.6.6.fdb' USER 'SYSDBA' PASSWORD '123654';

SET AUTODDL ON;

/* Create(Add) Crant */
GRANT SELECT ON ATATENDIMENTOVW01 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW02 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW02 TO PROCEDURE ATRESUMOATENDOSP01;

GRANT SELECT ON ATATENDIMENTOVW02 TO PROCEDURE VDCONTRATOTOTSP;

GRANT SELECT ON ATATENDIMENTOVW03 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW04 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW05 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW06 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW08 TO ADM;

GRANT SELECT ON FNFLUXOCAIXAVW01 TO ADM;

GRANT SELECT ON FNRAZCLIVW01 TO ADM;

GRANT SELECT ON FNRAZFORVW01 TO ADM;


COMMIT WORK;
