#define DllImport  extern "C" __declspec(dllimport)

static int iReturn=0;

DllImport int STDCALL Bematech_FI_FechaPortaSerial(void);
DllImport int STDCALL Bematech_FI_VerificaImpressoraLigada(void);
DllImport int STDCALL Bematech_FI_RetornoImpressora(int* ACK, int* ST1, int* ST2);
DllImport int STDCALL Bematech_FI_AumentaDescricaoItem(char* Descricao);
DllImport int STDCALL Bematech_FI_AbrePortaSerial(void);
DllImport int STDCALL Bematech_FI_AlteraSimboloMoeda(char* Moeda);
DllImport int STDCALL Bematech_FI_ProgramaAliquota(char* Aliquota, int* Vinculo);
DllImport int STDCALL Bematech_FI_ProgramaHorarioVerao(void);
DllImport int STDCALL Bematech_FI_NomeiaTotalizadorNaoSujeitoIcms(int Indice, char* Totalizador);
DllImport int STDCALL Bematech_FI_ProgramaArredondamento(void);
DllImport int STDCALL Bematech_FI_ProgramaTruncamento(void);
DllImport int STDCALL Bematech_FI_NomeiaDepartamento(int Indice, char* Departamento);
DllImport int STDCALL Bematech_FI_LinhasEntreCupons(int* Linhas);
DllImport int STDCALL Bematech_FI_EspacoEntreLinhas(int Dots);
DllImport int STDCALL Bematech_FI_ForcaImpactoAgulhas (int* ForcaImpacto);
DllImport int STDCALL Bematech_FI_ResetaImpressora(void);
DllImport int STDCALL Bematech_FI_AbreCupom(char* CGC);
DllImport int STDCALL Bematech_FI_VendeItem(char* Codigo, char* Descricao, char* Aliquota,char* TipoQuantidade, char* Quantidade,short CasasDecimais,char* ValorUnitario,char* TipoDesconto, char* ValorDesconto );
DllImport int STDCALL Bematech_FI_VendeItemDepartamento(char* Codigo, char* Descricao,char* Aliquota, char* ValorUnitario,char* Quantidade, char* Acrescimo,char* Desconto, char* IndiceDepartamento,char* cUnidadeMedida);
DllImport int STDCALL Bematech_FI_CupomResumido(char* FormaPagamento,char* Mensagem);
DllImport int STDCALL Bematech_FI_CancelaCupom(void);
DllImport int STDCALL Bematech_FI_CancelaItemAnterior( void );
DllImport int STDCALL Bematech_FI_CancelaItemGenerico( char * NumeroItem );
DllImport int STDCALL Bematech_FI_FechaCupomResumido( char * FormaPagamento,char * Mensagem );
DllImport int STDCALL Bematech_FI_UsaUnidadeMedida(char* UnidadeMedida);
DllImport int STDCALL Bematech_FI_ReducaoZ(char* Data, char* Hora);
DllImport int STDCALL Bematech_FI_LeituraX(void);
DllImport int STDCALL Bematech_FI_LeituraXSerial(void);
DllImport int STDCALL Bematech_FI_LeituraMemoriaFiscalData(char* DataInicial, char* DataFinal);
DllImport int STDCALL Bematech_FI_LeituraMemoriaFiscalReducao(char* ReducaoInicial,char* ReducaoFinal);
DllImport int STDCALL Bematech_FI_LeituraMemoriaFiscalSerialData(char* DataInicial,char* DataFinal);
DllImport int STDCALL Bematech_FI_LeituraMemoriaFiscalSerialReducao(char* ReducaoInicial,char* ReducaoFinal);
DllImport int STDCALL Bematech_FI_RelatorioGerencial(char* Texto);
DllImport int STDCALL Bematech_FI_FechaRelatorioGerencial(void);
DllImport int STDCALL Bematech_FI_RecebimentoNaoFiscal(char* IndiceTotalizador,char* ValorRecebimento,char* FormaPagamento);
DllImport int STDCALL Bematech_FI_AbreComprovanteNaoFiscalVinculado(char* FormaPagamento,char* Valor,char* NumeroCupom);
DllImport int STDCALL Bematech_FI_IniciaFechamentoCupom( char * cAcrescimoDesconto,char * cTipoAcrescimoDesconto,char * cValorAcrescimoDesconto );
DllImport int STDCALL Bematech_FI_EfetuaFormaPagamentoDescricaoForma(char * cFormaPagamento,char * cValorFormaPagamento,char * cDescricaoForma );
DllImport int STDCALL Bematech_FI_EfetuaFormaPagamento( char * cFormaPagamento,char * cValorFormaPagamento );
DllImport int STDCALL Bematech_FI_TerminaFechamentoCupom( char * cMensagem );
DllImport int STDCALL Bematech_FI_UsaComprovanteNaoFiscalVinculado(char* Texto);
DllImport int STDCALL Bematech_FI_FechaComprovanteNaoFiscalVinculado(void);
DllImport int STDCALL Bematech_FI_Sangria(char* Valor);
DllImport int STDCALL Bematech_FI_Suprimento(char* Valor, char* FormaPagamento);
DllImport int STDCALL Bematech_FI_Autenticacao(void);
DllImport int STDCALL Bematech_FI_ProgramaCaracterAutenticacao(char* Coordenadas);
DllImport int STDCALL Bematech_FI_AcionaGaveta(void);
DllImport int STDCALL Bematech_FI_VerificaEstadoGaveta(short int* Estado);
DllImport int STDCALL Bematech_FI_VerificaEstadoImpressora(short int* ACK,short int* ST1,short int* ST2);
DllImport int STDCALL Bematech_FI_RetornoAliquotas(char* Aliquotas);
DllImport int STDCALL Bematech_FI_SubTotal(char* SubTotal);
DllImport int STDCALL Bematech_FI_MonitoramentoPapel(int* LinhasImpressas);
DllImport int STDCALL Bematech_FI_DadosUltimaReducao(char* DadosReducao);
DllImport int STDCALL Bematech_FI_NumeroSerie(char* NumeroSerie);
DllImport int STDCALL Bematech_FI_VersaoFirmware(char* VersaoFirmware);
DllImport int STDCALL Bematech_FI_CGC_IE(char* CGC, char* IE);
DllImport int STDCALL Bematech_FI_GrandeTotal(char* GrandeTotal);
DllImport int STDCALL Bematech_FI_Descontos(char* Descontos);
DllImport int STDCALL Bematech_FI_Cancelamentos(char* Cancelamentos);
DllImport int STDCALL Bematech_FI_NumeroCupom(char* NumeroCupom);
DllImport int STDCALL Bematech_FI_NumeroOperacoesNaoFiscais(char* Operacoes);
DllImport int STDCALL Bematech_FI_NumeroCuponsCancelados(char* CuponsCancelados);
DllImport int STDCALL Bematech_FI_NumeroReducoes(char* Reducoes);
DllImport int STDCALL Bematech_FI_NumeroIntervencoes(char* Intervencoes);
DllImport int STDCALL Bematech_FI_NumeroSubstituicoesProprietario(char* Substituicoes);
DllImport int STDCALL Bematech_FI_UltimoItemVendido(char* UltimoItem);
DllImport int STDCALL Bematech_FI_ClicheProprietario(char* ClicheProprietario);
DllImport int STDCALL Bematech_FI_NumeroCaixa(char* NumeroCaixa);
DllImport int STDCALL Bematech_FI_NumeroLoja(char* NumeroLoja);
DllImport int STDCALL Bematech_FI_SimboloMoeda(char* SimboloMoeda);
DllImport int STDCALL Bematech_FI_FlagsFiscais(int* FlagFiscal);
DllImport int STDCALL Bematech_FI_MinutosLigada(char* MinutosLigada);
DllImport int STDCALL Bematech_FI_MinutosImprimindo(char* MinutosImprimindo);
DllImport int STDCALL Bematech_FI_ModoOperacao(char* ModoOperacao);
DllImport int STDCALL Bematech_FI_VerificaEpromConectada(char* FlagEprom );
DllImport int STDCALL Bematech_FI_ValorPagoUltimoCupom(char* Valor);
DllImport int STDCALL Bematech_FI_DataHoraImpressora(char* Data, char* Hora);
DllImport int STDCALL Bematech_FI_ContadoresTotalizadoresNaoFiscais(char* Contadores);
DllImport int STDCALL Bematech_FI_VerificaTotalizadoresNaoFiscais(char* Totalizadores);
DllImport int STDCALL Bematech_FI_VerificaTotalizadoresParciais( char * cTotalizadores );
DllImport int STDCALL Bematech_FI_VerificaModoOperacao( char * cModo );
DllImport int STDCALL Bematech_FI_DataHoraReducao(char* DataReducao, char* HoraReducao);
DllImport int STDCALL Bematech_FI_VerificaIndiceAliquotasIss( char * cIndices );
DllImport int STDCALL Bematech_FI_VerificaFormasPagamento( char * cFormas );
DllImport int STDCALL Bematech_FI_VerificaDepartamentos( char * cDepartamentos );
DllImport int STDCALL Bematech_FI_UsaComprovanteNaoFiscalVinculado( char * cTexto );
DllImport int STDCALL Bematech_FI_DataMovimento(char* DataMovimento);
DllImport int STDCALL Bematech_FI_VerificaTruncamento(char* FlagTruncamento);
DllImport int STDCALL Bematech_FI_VerificaAliquotasIss(char* AliquotasIss);
DllImport int STDCALL Bematech_FI_Acrescimos(char* ValorAcrescimo);
DllImport int STDCALL Bematech_FI_ContadorBilhetePassagem(char* NumeroBilhetes);
DllImport int STDCALL Bematech_FI_VerificaFormasPagamento(char* FormasPagamento);
DllImport int STDCALL Bematech_FI_VerificaRecebimentoNaoFiscal(char* Recebimentos);
DllImport int STDCALL Bematech_FI_VerificaDepartamentos(char* Departamentos);
DllImport int STDCALL Bematech_FI_VerificaTipoImpressora(int* TipoImpressora );
DllImport int STDCALL Bematech_FI_ProgramaMoedaSingular(char* MoedaSingular);
DllImport int STDCALL Bematech_FI_ProgramaMoedaSingular(char* MoedaPlural);
DllImport int STDCALL Bematech_FI_VerificaStatusCheque(int StatusCheque);
DllImport int STDCALL Bematech_FI_CancelaImpressaoCheque(void);
DllImport int STDCALL Bematech_FI_ImprimeCheque(char* NumeroBanco, char* Valor,char* Favorecido, char* Cidade,char* Data, char*  Mensagem);
DllImport int STDCALL Bematech_FI_IncluiCidadeFavorecido(char* Cidade, char* Favorecido);
//******************Funções Restaurante*************************
DllImport int STDCALL Bematech_FIR_RegistraVenda(char* Mesa, char* Codigo, char* Descricao,char *  Aliquota,  char  *  Quantidade,char* ValorUnitario, char* FlagAcrescimoDesconto,char* ValorAcrescimoDesconto);
DllImport int STDCALL Bematech_FIR_CancelaVenda(char*,char*,char*,char*,char*,char*,char*,char*);
DllImport int STDCALL Bematech_FIR_AbreConferenciaMesa(char* Mesa);
DllImport int STDCALL Bematech_FIR_FechaConferenciaMesa(char* FlagAcrescimoDesconto,char* TipoAcrescimoDesconto,char* ValorAcrescimoDesconto);
DllImport int STDCALL Bematech_FIR_ConferenciaMesa(char* Mesa,char* FlagAcrescimoDesconto,char* TipoAcrescimoDesconto,char* ValorAcrescimoDesconto);
DllImport int STDCALL Bematech_FIR_TransferenciaMesa(char* MesaOrigem, char* MesaDestino);
DllImport int STDCALL Bematech_FIR_TransferenciaItem(char* MesaOrigem, char* Codigo,char* Descricao, char *  Aliquota,char* Quantidade,  char* ValorUnitario,char* FlagAcrescimoDesconto,char* ValorAcrescimoDesconto,char* MesaDestino);
DllImport int STDCALL Bematech_FIR_AbreCupomRestaurante(char* Mesa, char* CPF);
DllImport int STDCALL Bematech_FIR_FechaCupomRestaurante(char* FormaPagamento,char* AcrescimoDesconto,char* TipoAcrescimoDesconto,char* ValorAcrescimoDesconto,char* ValorPago,char* Mensagem);
DllImport int STDCALL Bematech_FIR_FechaCupomResumidoRestaurante(char* FormaPagamento,char* Mensagem);
DllImport int STDCALL Bematech_FIR_ContaDividida(char* NumeroCupons,  char* ValorPago,char* CPF);
DllImport int STDCALL Bematech_FIR_FechaCupomContaDividida(char* NumeroCupons,char* AcrescimoDesconto,char* TipoAcrescimoDesconto,char* ValorAcrescimoDesconto,char* FormaPagamento,char* ValorFormaPagamento,char* ValorPagoCliente,char* CPF);
DllImport int STDCALL Bematech_FIR_RelatorioMesasAbertas(int TipoRelatorio);
DllImport int STDCALL Bematech_FIR_RelatorioMesasAbertasSerial(void);
DllImport int STDCALL Bematech_FIR_ImprimeCardapio(void);
DllImport int STDCALL Bematech_FIR_CardapioPelaSerial(void);
DllImport int STDCALL Bematech_FIR_RegistroVendaSerial(char* Mesa);
DllImport int STDCALL Bematech_FIR_VerificaMemoriaLivre(char* Bytes);
DllImport int STDCALL Bematech_FIR_TransferenciaItem(char * cMesaOrigem,char * cCodigo,char * cDescricao,char * cAliquota,char * cQuantidade,char * cValorUnitario,char * cFlagAcrescimoDesconto,char * cValorAcrescimoDesconto,char * cMesaDestino );


