/* Server Version: LI-V6.3.4.4910 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.5.3.fdb' USER 'SYSDBA' PASSWORD '123654' ROLE 'ADM';

SET AUTODDL ON;

UPDATE RDB$FIELDS SET RDB$FIELD_LENGTH=80,RDB$CHARACTER_LENGTH=80,
 RDB$FIELD_TYPE=37
  WHERE RDB$FIELD_NAME=(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
  WHERE RDB$FIELD_NAME='NOMEUF' AND RDB$RELATION_NAME='SGUF');

ALTER TABLE PPESTRUTURA ADD DESPAUTO CHAR(1) DEFAULT 'N' NOT NULL;

ALTER TABLE PPESTRUTURA ADD BLOQQTDPROD CHAR(1) DEFAULT 'N' NOT NULL;

ALTER TABLE SGUF ADD NOMECURTO VARCHAR(40) DEFAULT '' NOT NULL;

/* Create Index... */
CREATE INDEX SGUFIDX01 ON SGUF(NOMEUF);

CREATE INDEX SGUFIDX02 ON SGUF(NOMECURTO);


/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
SET TERM ^ ;

ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.5.4 (17/09/2012)';
    suspend;
end
^

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.5.4 (17/09/2012)';
    suspend;
end
^

SET TERM ; ^

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=1
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='CODEMP';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=2
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='CODFILIAL';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=3
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='CODPROD';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=4
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='SEQEST';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=5
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='DESCEST';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=6
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='QTDEST';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=7
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='REFPROD';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=8
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='ATIVOEST';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=9
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='CODEMPML';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=10
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='CODFILIALML';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=11
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='CODMODLOTE';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=12
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='NRODIASVALID';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=13
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='GLOTEOPP';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=14
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='USADENSIDADEOP';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=15
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='OBSERVACAO';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=16
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='ESTDINAMICA';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=17
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='DESPAUTO';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=18
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='BLOQQTDPROD';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=19
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='DTINS';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=20
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='HINS';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=21
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='IDUSUINS';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=22
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='DTALT';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=23
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='HALT';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=24
 WHERE RDB$RELATION_NAME='PPESTRUTURA' AND RDB$FIELD_NAME='IDUSUALT';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=1
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='SIGLAUF';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=2
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='CODPAIS';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=3
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='NOMEUF';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=4
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='NOMECURTO';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=5
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='CODUF';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=6
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='REGIAOUF';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=7
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='DTINS';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=8
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='HINS';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=9
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='IDUSUINS';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=10
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='DTALT';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=11
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='HALT';

UPDATE RDB$RELATION_FIELDS SET RDB$FIELD_POSITION=12
 WHERE RDB$RELATION_NAME='SGUF' AND RDB$FIELD_NAME='IDUSUALT';


COMMIT WORK;
