SELECT 'ALTER TRIGGER '||RTRIM(RDB$TRIGGER_NAME)
||' INACTIVE ; '
FROM RDB$TRIGGERS
WHERE RDB$RELATION_NAME NOT LIKE 'RDB$%' AND
RDB$TRIGGER_NAME NOT LIKE 'CHECK%';

SELECT 'ALTER TABLE '||RTRIM(RDB$RELATION_NAME)||' DROP CONSTRAINT '||
RTRIM(RDB$CONSTRAINT_NAME)||'; '
FROM RDB$RELATION_CONSTRAINTS
WHERE RDB$CONSTRAINT_TYPE='FOREIGN KEY';

SELECT 'UPDATE '||RTRIM(RDB$RELATION_NAME)||
' SET '||RTRIM(RDB$FIELD_NAME)||
'=#CODEMP# WHERE '||RTRIM(RDB$FIELD_NAME)||'=99 ;'
FROM RDB$RELATION_FIELDS WHERE RDB$FIELD_NAME LIKE 'CODEMP%';

SELECT 'ALTER TRIGGER '||RTRIM(RDB$TRIGGER_NAME)
||' ACTIVE ; '
FROM RDB$TRIGGERS
WHERE RDB$RELATION_NAME NOT LIKE 'RDB$%' AND
RDB$TRIGGER_NAME NOT LIKE 'CHECK%';
