/* Server version: LI-V6.3.3.4870 Firebird 1.5 
   SQLDialect: 3. ODS: 10.1. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 75 (300 Kb). Read-only: False. */
SET SQL DIALECT 3;

SET AUTODDL ON;

ALTER TABLE VDCLIENTE ADD CODCNAE VARCHAR(15);

UPDATE RDB$RELATION_FIELDS SET RDB$DESCRIPTION = 
'Código da atividade principal, padrão CNAE.
'
WHERE RDB$RELATION_NAME = 'VDCLIENTE' AND RDB$FIELD_NAME = 'CODCNAE';

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
SET TERM ^ ;

ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.2.4 (18/06/2010)';
    suspend;
end
^

SET TERM ; ^

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCLI POSITION 3;

ALTER TABLE VDCLIENTE ALTER COLUMN RAZCLI POSITION 4;

ALTER TABLE VDCLIENTE ALTER COLUMN NOMECLI POSITION 5;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPCC POSITION 6;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALCC POSITION 7;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCLASCLI POSITION 8;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPVD POSITION 9;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALVD POSITION 10;

ALTER TABLE VDCLIENTE ALTER COLUMN CODVEND POSITION 11;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTC POSITION 12;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTC POSITION 13;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTIPOCOB POSITION 14;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPPG POSITION 15;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALPG POSITION 16;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPLANOPAG POSITION 17;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTN POSITION 18;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTN POSITION 19;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTRAN POSITION 20;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPBO POSITION 21;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALBO POSITION 22;

ALTER TABLE VDCLIENTE ALTER COLUMN CODBANCO POSITION 23;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPSR POSITION 24;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALSR POSITION 25;

ALTER TABLE VDCLIENTE ALTER COLUMN CODSETOR POSITION 26;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTI POSITION 27;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTI POSITION 28;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTIPOCLI POSITION 29;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTPCRED POSITION 30;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALTR POSITION 31;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPTR POSITION 32;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFISCCLI POSITION 33;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPFC POSITION 34;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALFC POSITION 35;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPEC POSITION 36;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALEC POSITION 37;

ALTER TABLE VDCLIENTE ALTER COLUMN CODTBEC POSITION 38;

ALTER TABLE VDCLIENTE ALTER COLUMN CODITTBEC POSITION 39;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPHP POSITION 40;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALHP POSITION 41;

ALTER TABLE VDCLIENTE ALTER COLUMN CODHIST POSITION 42;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPCB POSITION 43;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALCB POSITION 44;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCARTCOB POSITION 45;

ALTER TABLE VDCLIENTE ALTER COLUMN DATACLI POSITION 46;

ALTER TABLE VDCLIENTE ALTER COLUMN PESSOACLI POSITION 47;

ALTER TABLE VDCLIENTE ALTER COLUMN ATIVOCLI POSITION 48;

ALTER TABLE VDCLIENTE ALTER COLUMN CNPJCLI POSITION 49;

ALTER TABLE VDCLIENTE ALTER COLUMN INSCCLI POSITION 50;

ALTER TABLE VDCLIENTE ALTER COLUMN CPFCLI POSITION 51;

ALTER TABLE VDCLIENTE ALTER COLUMN RGCLI POSITION 52;

ALTER TABLE VDCLIENTE ALTER COLUMN SSPCLI POSITION 53;

ALTER TABLE VDCLIENTE ALTER COLUMN ENDCLI POSITION 54;

ALTER TABLE VDCLIENTE ALTER COLUMN NUMCLI POSITION 55;

ALTER TABLE VDCLIENTE ALTER COLUMN COMPLCLI POSITION 56;

ALTER TABLE VDCLIENTE ALTER COLUMN BAIRCLI POSITION 57;

ALTER TABLE VDCLIENTE ALTER COLUMN CIDCLI POSITION 58;

ALTER TABLE VDCLIENTE ALTER COLUMN UFCLI POSITION 59;

ALTER TABLE VDCLIENTE ALTER COLUMN CEPCLI POSITION 60;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDCLI POSITION 61;

ALTER TABLE VDCLIENTE ALTER COLUMN FONECLI POSITION 62;

ALTER TABLE VDCLIENTE ALTER COLUMN RAMALCLI POSITION 63;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFAXCLI POSITION 64;

ALTER TABLE VDCLIENTE ALTER COLUMN FAXCLI POSITION 65;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILCLI POSITION 66;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILCOB POSITION 67;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILENT POSITION 68;

ALTER TABLE VDCLIENTE ALTER COLUMN EMAILNFECLI POSITION 69;

ALTER TABLE VDCLIENTE ALTER COLUMN CONTCLI POSITION 70;

ALTER TABLE VDCLIENTE ALTER COLUMN ENDCOB POSITION 71;

ALTER TABLE VDCLIENTE ALTER COLUMN NUMCOB POSITION 72;

ALTER TABLE VDCLIENTE ALTER COLUMN COMPLCOB POSITION 73;

ALTER TABLE VDCLIENTE ALTER COLUMN BAIRCOB POSITION 74;

ALTER TABLE VDCLIENTE ALTER COLUMN CIDCOB POSITION 75;

ALTER TABLE VDCLIENTE ALTER COLUMN UFCOB POSITION 76;

ALTER TABLE VDCLIENTE ALTER COLUMN CEPCOB POSITION 77;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFONECOB POSITION 78;

ALTER TABLE VDCLIENTE ALTER COLUMN FONECOB POSITION 79;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFAXCOB POSITION 80;

ALTER TABLE VDCLIENTE ALTER COLUMN FAXCOB POSITION 81;

ALTER TABLE VDCLIENTE ALTER COLUMN ENDENT POSITION 82;

ALTER TABLE VDCLIENTE ALTER COLUMN NUMENT POSITION 83;

ALTER TABLE VDCLIENTE ALTER COLUMN COMPLENT POSITION 84;

ALTER TABLE VDCLIENTE ALTER COLUMN BAIRENT POSITION 85;

ALTER TABLE VDCLIENTE ALTER COLUMN CIDENT POSITION 86;

ALTER TABLE VDCLIENTE ALTER COLUMN UFENT POSITION 87;

ALTER TABLE VDCLIENTE ALTER COLUMN CEPENT POSITION 88;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFONEENT POSITION 89;

ALTER TABLE VDCLIENTE ALTER COLUMN FONEENT POSITION 90;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDFAXENT POSITION 91;

ALTER TABLE VDCLIENTE ALTER COLUMN FAXENT POSITION 92;

ALTER TABLE VDCLIENTE ALTER COLUMN OBSCLI POSITION 93;

ALTER TABLE VDCLIENTE ALTER COLUMN AGENCIACLI POSITION 94;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPPQ POSITION 95;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALPQ POSITION 96;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPESQ POSITION 97;

ALTER TABLE VDCLIENTE ALTER COLUMN INCRACLI POSITION 98;

ALTER TABLE VDCLIENTE ALTER COLUMN DTINITR POSITION 99;

ALTER TABLE VDCLIENTE ALTER COLUMN DTVENCTOTR POSITION 100;

ALTER TABLE VDCLIENTE ALTER COLUMN NIRFCLI POSITION 101;

ALTER TABLE VDCLIENTE ALTER COLUMN SIMPLESCLI POSITION 102;

ALTER TABLE VDCLIENTE ALTER COLUMN DDDCELCLI POSITION 103;

ALTER TABLE VDCLIENTE ALTER COLUMN CELCLI POSITION 104;

ALTER TABLE VDCLIENTE ALTER COLUMN NATCLI POSITION 105;

ALTER TABLE VDCLIENTE ALTER COLUMN UFNATCLI POSITION 106;

ALTER TABLE VDCLIENTE ALTER COLUMN TEMPORESCLI POSITION 107;

ALTER TABLE VDCLIENTE ALTER COLUMN APELIDOCLI POSITION 108;

ALTER TABLE VDCLIENTE ALTER COLUMN SITECLI POSITION 109;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCONTDEB POSITION 110;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCONTCRED POSITION 111;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCLICONTAB POSITION 112;

ALTER TABLE VDCLIENTE ALTER COLUMN FOTOCLI POSITION 113;

ALTER TABLE VDCLIENTE ALTER COLUMN IMGASSCLI POSITION 114;

ALTER TABLE VDCLIENTE ALTER COLUMN CODMUNIC POSITION 115;

ALTER TABLE VDCLIENTE ALTER COLUMN SIGLAUF POSITION 116;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPAIS POSITION 117;

ALTER TABLE VDCLIENTE ALTER COLUMN CODMUNICENT POSITION 118;

ALTER TABLE VDCLIENTE ALTER COLUMN SIGLAUFENT POSITION 119;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPAISENT POSITION 120;

ALTER TABLE VDCLIENTE ALTER COLUMN CODMUNICCOB POSITION 121;

ALTER TABLE VDCLIENTE ALTER COLUMN SIGLAUFCOB POSITION 122;

ALTER TABLE VDCLIENTE ALTER COLUMN CODPAISCOB POSITION 123;

ALTER TABLE VDCLIENTE ALTER COLUMN CODEMPUC POSITION 124;

ALTER TABLE VDCLIENTE ALTER COLUMN CODFILIALUC POSITION 125;

ALTER TABLE VDCLIENTE ALTER COLUMN CODUNIFCOD POSITION 126;

ALTER TABLE VDCLIENTE ALTER COLUMN SUFRAMACLI POSITION 127;

ALTER TABLE VDCLIENTE ALTER COLUMN PRODRURALCLI POSITION 128;

ALTER TABLE VDCLIENTE ALTER COLUMN CTOCLI POSITION 129;

ALTER TABLE VDCLIENTE ALTER COLUMN CODCNAE POSITION 130;

ALTER TABLE VDCLIENTE ALTER COLUMN DTINS POSITION 131;

ALTER TABLE VDCLIENTE ALTER COLUMN HINS POSITION 132;

ALTER TABLE VDCLIENTE ALTER COLUMN IDUSUINS POSITION 133;

ALTER TABLE VDCLIENTE ALTER COLUMN DTALT POSITION 134;

ALTER TABLE VDCLIENTE ALTER COLUMN HALT POSITION 135;

ALTER TABLE VDCLIENTE ALTER COLUMN IDUSUALT POSITION 136;

GRANT SELECT, INSERT, UPDATE, DELETE ON SGCNAE TO ROLE "ADM";

