/* Server Version: LI-V6.3.4.4910 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

SET AUTODDL ON;

/* Alter Field (Length): from 1 to 50... */
UPDATE RDB$FIELDS SET RDB$FIELD_LENGTH=50, RDB$CHARACTER_LENGTH=50
  WHERE RDB$FIELD_NAME=(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
  WHERE RDB$RELATION_NAME='FNCHEQUE' AND  RDB$FIELD_NAME='NOMEEMITCHEQ');

Update Rdb$Relation_Fields set Rdb$Description =
'Nome do emitente.'
where Rdb$Relation_Name='FNCHEQUE' and Rdb$Field_Name='NOMEEMITCHEQ';

CREATE DOMAIN IBCXXX VARCHAR(128) DEFAULT user NOT NULL;

UPDATE RDB$RELATION_FIELDS SET RDB$DEFAULT_SOURCE=
(SELECT RDB$DEFAULT_SOURCE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX'),
RDB$DEFAULT_VALUE=
(SELECT RDB$DEFAULT_VALUE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX')
WHERE RDB$FIELD_NAME='IDUSUINS' AND RDB$RELATION_NAME='FNCHEQUE';

DROP DOMAIN IBCXXX;

UPDATE RDB$FIELDS SET RDB$DEFAULT_VALUE = NULL,
RDB$DEFAULT_SOURCE = '' WHERE RDB$FIELD_NAME =
(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
WHERE RDB$FIELD_NAME = 'IDUSUINS' AND RDB$RELATION_NAME = 'FNCHEQUE');

Update Rdb$Relation_Fields set Rdb$Description =
'Ident. do usuário que inseriu.'
where Rdb$Relation_Name='FNCHEQUE' and Rdb$Field_Name='IDUSUINS';

CREATE DOMAIN IBCXXX VARCHAR(128) DEFAULT user NOT NULL;

UPDATE RDB$RELATION_FIELDS SET RDB$DEFAULT_SOURCE=
(SELECT RDB$DEFAULT_SOURCE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX'),
RDB$DEFAULT_VALUE=
(SELECT RDB$DEFAULT_VALUE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX')
WHERE RDB$FIELD_NAME='IDUSUALT' AND RDB$RELATION_NAME='FNCHEQUE';

DROP DOMAIN IBCXXX;

UPDATE RDB$FIELDS SET RDB$DEFAULT_VALUE = NULL,
RDB$DEFAULT_SOURCE = '' WHERE RDB$FIELD_NAME =
(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
WHERE RDB$FIELD_NAME = 'IDUSUALT' AND RDB$RELATION_NAME = 'FNCHEQUE');



