cp /dados/freedom/lib/freedomstd.jar /opt/freedom/lib/freedomstd.jar
cp /dados/freedom/lib/freedomatd.jar /opt/freedom/lib/freedomatd.jar
cp /dados/freedom/lib/freedomgms.jar /opt/freedom/lib/freedomgms.jar
cp /dados/freedom/lib/freedomtmk.jar /opt/freedom/lib/freedomtmk.jar
cp /dados/freedom/lib/freedomfnc.jar /opt/freedom/lib/freedomfnc.jar
cp /dados/freedom/lib/freedompcp.jar /opt/freedom/lib/freedompcp.jar
cp /dados/freedom/lib/freedomcfg.jar /opt/freedom/lib/freedomcfg.jar
cp /dados/freedom/lib/freedompdv.jar /opt/freedom/lib/freedompdv.jar
cp /dados/freedom/lib/firebirdsql-full.jar /opt/freedom/lib/firebirdsql-full.jar
cp /dados/freedom/lib/mail.jar /opt/freedom/lib/mail.jar
cp /dados/freedom/lib/itext-1.02b.jar /opt/freedom/lib/itext-1.02b.jar
cp /dados/freedom/lib/jcommon-0.8.7.jar /opt/freedom/lib/jcommon-0.8.7.jar
cp /dados/freedom/lib/jfreechart-0.9.12.jar /opt/freedom/lib/jfreechart-0.9.12.jar
cp /dados/freedom/lib/activation.jar /opt/freedom/lib/activation.jar
cp /dados/freedom/lib/nachocalendar-0.21.jar /opt/freedom/lib/nachocalendar-0.21.jar
cp /dados/freedom/lib/commons-logging.jar /opt/freedom/lib/commons-logging.jar
cp /dados/freedom/lib/jasperreports-0.6.7.jar /opt/freedom/lib/jasperreports-0.6.7.jar
cp /dados/freedom/exec/*.sh /opt/freedom/

