-- Banco do Brasil
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '00','Incluído no movimento');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '01','Aguardando retorno');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '02','Registrado (em ser)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '03','Registro rejeitado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '04','Registrado sem movimento');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '05','Baixado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '06','Liquidado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '07','Registrado (com ocorrência sacado)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '08','Protestado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '09','Pendente de impressão');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '10','Impresso - incluído no movimento');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '11','Impresso - sem registro no banco(em ser)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '12','Remetido a Cartorio (em ser)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '13','Retirado de Cartorio (em ser)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '14','Vencido');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '15','Instrução rejeitada');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '16','Baixado/Liquidado manualmente');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '17','A reembolsar');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '18','Reembolsado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '51','Tít. CBR454 envelopado e postado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '52','Tít. CBR454 aberto e devolvido Cedente');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '53','Tít. CBR454 envelopado e devolvido Cedente');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '54','Carnê semi-acabado e devolvido Cedente');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '55','Carnê envelopado e devolvido Cedente');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '56','Carnê não envelopado e devolvido Cedente');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '57','Carnê envelopado e postado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '58','Carnê com envelope plástico e postado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '59','Carnê não envelopado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '60','Carnê envelopado');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '61','Carnê com envelope plástico');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '62','Carnê não envelopado(remetido)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '63','Carnê envelopado(remetido)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '64','Carnê envelope plástico(remetido)');
insert into fnfbncodret (codemp,codfilial,codempbo,codfilialbo,codbanco,tipofebraban,codret,descret) values(#CODEMP#,1,#CODEMP#,1,'001','02', '90','Consultar BB');
-- Caixa Econômica
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '00', 'Débito/crédito efetuado.');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '01', 'Numero Remessa Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '02', 'Arquivo sem "HEADER"');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '03', 'Tipo Registro Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '04', 'Código Banco Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '05', 'Insuficiência de Fundos');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '06', 'Tipo Serviço Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '07', 'Código de convênio Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '08', 'Código de Remessa Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '09', 'Outras Restrições');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '10', 'Tipo de Operação inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '11', 'Agência Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '12', 'Número de Conta Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '13', 'Número de Lote Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '14', 'Códgo Segmento Inváido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '15', 'Tipo Movimento Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '16', 'Banco Favorecido Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '17', 'Nomde do Favorecido Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '18', 'Seu Número Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '19', 'Data de Pagamento Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '20', 'Tipo de Moeda Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '21', 'Quantidade de Moeda Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '22', 'Valor de Pagamento Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '23', 'Tipo de Inscrição Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '24', 'Número de Inscrição Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '25', 'Logradouro/Complemento Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '26', 'Num. Local do Favorecido Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '27', 'Código Documento Favorecido Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '28', 'Bairro do favorecido Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '29', 'Cidade doFavorecido Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '30', 'Num. CEP/Complemento Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '31', 'Estado do Favorecido Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '32', 'Código de barras Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '33', 'Nome do Cedente Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '34', 'Data de Vencimento Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '35', 'Valor do Titulo Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '36', 'Qtde Regist. Lote C/Diferença');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '37', 'Valor Regist. lote C/Diferença');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '38', 'Lote sem TRAILLER');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '39', 'Remessa sem TRAILLER');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '40', 'Total Registros do TRAILLER Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '41', 'Valor Total Registros do TRAILLER Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '42', 'Lote Fora de Seqüência');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '43', 'Nome Empresa Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '44', 'Num. Seq. De Registros Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '45', 'Nome do Banco Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '46', 'Data Movimento Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '47', 'Identificação Cliente Empresa Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '48', 'Código de Movimento Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '49', 'Tot. Lote no Arq C/Diferença');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '50', 'Convênio não Cadastrado');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '51', 'Parâmetro Trasmissão não Cadastrado');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '52', 'Compromisso não Cadastrado');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '53', 'Agência Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '54', 'Agendamento já Efetivado');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '55', 'Lote sem HEADER');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '56', 'Tipo de Operação Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '57', 'Agencia Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '58', 'Cadastramento Convênio Incompleto');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '59', 'Situação Atual Convênio não ativo');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '60', 'Conta a Debitar Inexistente no Cadastro de Optante');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '61', 'Conta Comp.Inválida."62"-Num Conv Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '63', 'Tipo de Compromisso Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '64', 'Número de Compromisso Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '65', 'Mais de 1 TRAILLER na Remessa');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '66', 'Remessa com Erro');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '67', 'Data Opção Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '68', 'Qtde Moeda Lote C/Diferença');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '69', 'Optante já cadastrato para este Convênio');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '70', 'Indicação de Aviso sem endereço');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '71', 'Cód. de Barras/Cód Banco Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '72', 'Cód. De Barras/Cód Moeda Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '73', 'Cód de Brras/ Digito Verificador Geral Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '74', 'Código de Barras/ Valor do Titulo Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '76', 'Quantidade deparcelas Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '77', 'Indicador Bloqueio Parcela Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '78', 'Cadastro de Optantes Inexistente');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '79', 'Opção de Aviso sem endereço');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '80', 'Opção de Doc/OP sem endereço');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '81', 'Conta não Cadastrada');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '82', 'Tipo de Conta Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '83', 'Tipo de Operação diverge de Tipo de Compromisso');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '84', 'Tipo de Operação diverge com Tipo de Serviço');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '85', 'Data Cancelamento Expirada');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '86', 'Agendamento não Encontrado');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '87', 'Valor do débito maior que o valor limite');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '88', 'Índice Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '89', 'Data Atual do Compromisso não Ativa');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '90', 'Histórico não Cadastrado');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '91', 'Registro ja Existente na Base');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '92', 'Forma Parcelamento/Periodo Inválido');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '93', 'Erro no acesso TAB parâmetro de Optantes');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '94', 'Convênio não cadastrado na TAB Parâmetro Optantes');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '95', 'Arquivo com data vcmto inferior a 03 dias úteis');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '96', 'Manutenção de Cadastro');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '97', 'Câmara de Compensação Inválida');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '99', 'Cancelamento Conforme Solicitado');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET) VALUES (#CODEMP#, 1, #CODEMP#, 1, '104', '01', '100', 'Código DOC Favorecido Inválido');

COMMIT WORK;
