JC=javac -g
FLAGS=-classpath /aplic/appjava

all: \
JTextFieldPad.class \
JPasswordFieldPad.class \
ListaCampos.class \
GuardaCampo.class \
JRadioGroup.class \
ImprimeOS.class \
Navegador.class \
Tabela.class \
Arvore.class \
JGroupField.class \
ImprimeLayout.class \
Painel.class

JTextFieldPad.class: JTextFieldPad.java
	$(JC) $(FLAGS) $^

JPasswordFieldPad.class: JPasswordFieldPad.java
	$(JC) $(FLAGS) $^

JTextAreadPad.class: JTextAreaPad.java
	$(JC) $(FLAGS) $^

GuardaCampo.class: GuardaCampo.java
	$(JC) $(FLAGS) $^

ListaCampos.class: ListaCampos.java
	$(JC) $(FLAGS) $^

JRadioGroup.class: JRadioGroup.java
	$(JC) $(FLAGS) $^

ImprimeOS.class: ImprimeOS.java
	$(JC) $(FLAGS) $^

Navegador.class: Navegador.java
	$(JC) $(FLAGS) $^

Tabela.class: Tabela.java
	$(JC) $(FLAGS) $^

Painel.class: Painel.java
	$(JC) $(FLAGS) $^

Arvore.class: Arvore.java
	$(JC) $(FLAGS) $^

JGroupField.class: JGroupField.java
	$(JC) $(FLAGS) $^

ImprimeLayout.class: ImprimeLayout.java
	$(JC) $(FLAGS) $^

.PHONY: all
