INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '00', 'OK', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '01', 'CODIGO DO BANCO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '02', 'CÓDIGO DO REGISTRO DETALHE INVÁLIDO.', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '03', 'CÓDIGO DO SEGMENTO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '04', 'CÓDIGO DO MOVIMENTO NÃO PERMITIDO PARA CARTEIRA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '05', 'CÓDIGO DO MOVIMENTO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '06', 'TIPO/NÚMERO DE INSCRIÇÃO DO CEDENTE INVÁLIDOS', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '07', 'AGÊNCIA/CONTA/DV INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '08', 'NOSSO NÚMERO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '09', 'NOSSO NÚMERO DUPLICADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '10', 'CARTEIRA INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '11', 'FORMA DE CADASTRAMENTO DO TÍTULO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '12', 'TIPO DE DOCUMENTO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '13', 'IDENTIFICAÇÃO DA EMISSÃO DO BLOQUETO INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '14', 'IDENTIFICAÇÃO DA DISTRIBUIÇÃO DO BLOQUETO INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '15', 'CARACTERÍSTICAS DA COBRANÇA INCOMPATÍVEIS', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '16', 'DATA DE VENCIMENTO INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '17', 'DATA DE VENCIMENTO ANTERIOR A DATA DE EMISSÃO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '18', 'VENCIMENTO FORA DO PRAZO DE OPERAÇÃO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '19', 'TÍT. A CARGO DE B. CORRESP. C/ VENC. INF. A XX DIA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '20', 'VALOR DO TÍTULO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '21', 'ESPÉCIE DO TÍTULO INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '22', 'ESPÉCIE NÃO PERMITIDA PARA A CARTEIRA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '23', 'ACEITE INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '24', 'DATA DA EMISSÃO INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '25', 'DATA DA EMISSÃO POSTERIOR A DATA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '26', 'CÓDIGO DE JUROS DE MORA INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '27', 'VALOR/TAXA DE JUROS DE MORA INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '28', 'CÓDIGO DO DESCONTO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '29', 'VALOR DO DESCONTO MAIOR OU IGUAL AO VALOR DO TÍTUL', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '30', 'DESCONTO A CONCEDER NÃO CONFERE', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '31', 'CONCESSÃO DE DESCONTO - JÁ EXISTE DESCONTO ANT.', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '32', 'VALOR DO IOF INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '33', 'VALOR DO ABATIMENTO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '34', 'VALOR DO ABATIMENTO MAIOR OU IGUAL AO VALOR TÍTULO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '35', 'ABATIMENTO A CONCEDER NÃO CONFERE', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '36', 'CONCESSÃO DE ABATIMENTO - JÁ EXISTE ABATIMENTO ANT', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '37', 'CÓDIGO PARA PROTESTO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '38', 'PRAZO PARA PROTESTO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '39', 'PEDIDO DE PROTESTO NÃO PERMITIDO PARA O TÍTULO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '40', 'TÍTULO COM ORDEM DE PROTESTO EMITIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '41', 'PEDIDO DE CANCELAMENTO/SUST. P/ TÍT. S/INSTR. PROT', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '42', 'CÓDIGO PARA BAIXA/DEVOLUÇÃO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '43', 'PRAZO PARA BAIXA/DEVOLUÇÃO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '44', 'CÓDIGO DA MOEDA INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '45', 'NOME DO SACADO NÃO INFORMADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '46', 'TIPO/NÚMERO DE INSCRIÇÃO DO SACADO INVÁLIDOS', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '47', 'ENDEREÇO DO SACADO NÃO INFORMADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '48', 'CEP INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '49', 'CEP SEM PRAÇA DE COBRANÇA/NÃO LOCALIZADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '50', 'CEP REFERENTE A UM BANCO CORRESPONDENTE', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '51', 'CEP INCOMPATÍVEL COM A UNIDADE DA FEDERAÇÃO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '52', 'UNIDADE DA FEDERAÇÃO INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '53', 'TIPO/NÚMERO DE INSCRIÇÃO DO SACADOR/AVALISTA INVÁL', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '54', 'SACADOR/AVALISTA NÃO INFORMADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '55', 'NOSSO NÚMERO NO BANCO CORRESPONDENTE NÃO INFORMADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '56', 'CÓDIGO DO BANCO CORRESPONDENTE NÃO INFORMADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '57', 'CÓDIGO DA MULTA INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '58', 'DATA DA MULTA INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '59', 'VALOR/PERCENTUAL DA MULTA INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '60', 'MOVIMENTO PARA TÍTULO NÃO CADASTRADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '61', 'ALTERAÇÃO DA AGENCIA COBRADORA/DV INVÁLIDA', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '62', 'TIPO DE IMPRESSÃO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '63', 'ENTRADA PARA TÍTULO JÁ CADASTRADO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '64', 'NÚMERO DA LINHA INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '65', 'CÓDIGO DO BANCO PARA DÉBITO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '66', 'AGENCIA/CONTA/DV PARA DÉBITO INVÁLIDO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '67', 'DADOS PARA DEBITO INCOMP. C/IDENT. DA EMIS. BOLETO', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '88', 'ARQUIVO EM DUPLICIDADE', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '99', 'CONTRATO INEXISTENTE', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '5300', 'Ocorrencia indefinida', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '02', 'Confirmacao de Entrada de Título', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '03', 'Comando recusado /ver posicao 087/088/', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '06', 'Liquidacao Normal', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '07', 'Liquidacao por Conta', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '08', 'Liquidacao por Saldo', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '09', 'Baixa de Titulo', 'IN');
INSERT INTO FNFBNCODRET (CODEMP, CODFILIAL, CODEMPBO, CODFILIALBO, CODBANCO, TIPOFEBRABAN, CODRET, DESCRET, TIPORET)
                 VALUES (#CODEMP#, 1, #CODEMP#, 1, '001', '02', '10', 'Baixa Solicitada', 'IN');

COMMIT WORK;
