/* Server Version: LI-V6.3.4.4910 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

SET AUTODDL ON;

/* Create Procedure... */
SET TERM ^ ;

CREATE PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
 BEGIN EXIT; END
^


/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.2.2 (08/06/2010)';
    suspend;
end
^

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.2.2 (08/06/2010)';
    suspend;
end
^

/* Create(Add) Crant */
SET TERM ; ^

GRANT DELETE, INSERT, SELECT, UPDATE ON CPDEVOLUCAO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CPFRETECP TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CPITCOMPRASERIE TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CRCHAMADO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CRTIPOCHAMADO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON EQCLIFOR TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON EQGUIATRAF TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON EQITRECMERCITOSITORC TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNBORDERO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNCARTCOB TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNCONTAUSU TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNFBNCLI TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNFBNCODRET TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNFBNREC TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNFINALIDADE TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNHISTPAD TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNITBORDERO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNITFBNCODRET TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON FNITMODBOLETO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFFRETECOMPRA TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFFRETEVENDA TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFNBM TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFNCM TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFNCMNBM TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFSEQSERIE TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFSEQSERIE TO PROCEDURE LFNOVODOCSP;

GRANT DELETE, INSERT, SELECT, UPDATE ON LFSERVICO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPESTRUANALISE TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPFOTOMTAN TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPITRETCP TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPOPACAOCORRET TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPOPCQ TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPOPITORC TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPRETCP TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON PPTIPOANALISE TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON RHCODGPS TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGFERIADO TO PROCEDURE SGCALCVENCSP;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGITPREFERE6 TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGMUNICIPIO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGPREFERE6 TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGPREFERE7 TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGTIPOAGENDA TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGUF TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON SGUNIFCOD TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKCAMPANHA TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKCAMPANHACTO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKCAMPANHACTO TO PROCEDURE TKGERACAMPANHACTO;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKCAMPANHAEMAIL TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKCONFEMAIL TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKCTOGRPINT TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKEMAIL TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKHISTORICO TO PROCEDURE TKGERACAMPANHACTO;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKORIGCONT TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKSITCAMP TO PROCEDURE TKGERACAMPANHACTO;

GRANT DELETE, INSERT, SELECT, UPDATE ON TKSITCAMPCL TO PROCEDURE TKGERACAMPANHACLI;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDCLIMETAVEND TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDCONTRATO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDITCONTRATO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDITCONTRATOAND TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDITCUSTOORC TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDITCUSTOVENDA TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDITREGRACOMIS TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDITVENDASERIE TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDPREVTRIBITORC TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDREGRACOMIS TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDTIPOVEND TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON VDVENDACOMIS TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON FNRESTRICAO TO ADM;

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON FNTIPORESTR TO ADM;

GRANT EXECUTE ON PROCEDURE ARREDDOUBLE TO ADM;

GRANT EXECUTE ON PROCEDURE ATADICATENDIMENTOCLISP TO ADM;

GRANT EXECUTE ON PROCEDURE CPADICITCOMPRAPEDSP TO ADM;

GRANT EXECUTE ON PROCEDURE CPADICITCOMPRARECMERCSP TO ADM;

GRANT EXECUTE ON PROCEDURE CPBLOQCOMPRASP TO ADM;

GRANT EXECUTE ON PROCEDURE CPGERADEVOLUCAOSP TO ADM;

GRANT EXECUTE ON PROCEDURE CPITCOMPRASERIESP TO ADM;

GRANT EXECUTE ON PROCEDURE CPUPCOMPRAPEDSP TO PROCEDURE CPADICCOMPRAPEDSP;

GRANT EXECUTE ON PROCEDURE EQCALCPEPSSP TO ADM;

GRANT EXECUTE ON PROCEDURE EQCUSTOPRODSP TO ADM;

GRANT EXECUTE ON PROCEDURE EQGERARMASP TO ADM;

GRANT EXECUTE ON PROCEDURE EQRELGIROPROD TO ADM;

GRANT EXECUTE ON PROCEDURE EQRELINVPRODSP TO ADM;

GRANT EXECUTE ON PROCEDURE LFBUSCAFISCALSP TO PROCEDURE CPADICCOMPRAPEDSP;

GRANT EXECUTE ON PROCEDURE LFBUSCAFISCALSP TO PROCEDURE LFBUSCAPREVTRIBORC;

GRANT EXECUTE ON PROCEDURE LFBUSCAFISCALSP02 TO PROCEDURE LFGERALFITCOMPRASP;

GRANT EXECUTE ON PROCEDURE LFBUSCAFISCALSP02 TO PROCEDURE LFGERALFITVENDASP;

GRANT EXECUTE ON PROCEDURE LFBUSCAICMSSP TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT EXECUTE ON PROCEDURE LFBUSCAICMSSP TO PROCEDURE LFGERALFITCOMPRASP;

GRANT EXECUTE ON PROCEDURE LFBUSCANATSP TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT EXECUTE ON PROCEDURE LFBUSCAPREVTRIBORC TO TRIGGER VDITORCAMENTOTGAI;

GRANT EXECUTE ON PROCEDURE LFBUSCAPREVTRIBORC TO TRIGGER VDITORCAMENTOTGAU;

GRANT EXECUTE ON PROCEDURE LFBUSCATRIBCOMPRA TO ADM;

GRANT EXECUTE ON PROCEDURE LFGERALFITCOMPRASP TO ADM;

GRANT EXECUTE ON PROCEDURE LFGERALFITCOMPRASP TO TRIGGER VDITCOMPRATGAI;

GRANT EXECUTE ON PROCEDURE LFGERALFITCOMPRASP TO TRIGGER VDITCOMPRATGAU;

GRANT EXECUTE ON PROCEDURE LFGERALFITVENDASP TO TRIGGER VDITVENDATGAI;

GRANT EXECUTE ON PROCEDURE LFGERALFITVENDASP TO TRIGGER VDITVENDATGAU;

GRANT EXECUTE ON PROCEDURE PPATUDISTOPSP TO ADM;

GRANT EXECUTE ON PROCEDURE PPGERAOPCQ TO ADM;

GRANT EXECUTE ON PROCEDURE PPITOPSP01 TO ADM;

GRANT EXECUTE ON PROCEDURE PPITOPSP02 TO ADM;

GRANT EXECUTE ON PROCEDURE PVADICMOVCAIXASP01 TO PROCEDURE PVSEQMOVCAIXASP;

GRANT EXECUTE ON PROCEDURE SGCALCVENCSP TO ADM;

GRANT EXECUTE ON PROCEDURE SGCALCVENCSP TO PROCEDURE FNGERAITRECEBERSP01;

GRANT EXECUTE ON PROCEDURE SGESTACAOIMPSP01 TO ADM;

GRANT EXECUTE ON PROCEDURE SGRETFILIAL TO PROCEDURE ATADICATENDIMENTOCLISP;

GRANT EXECUTE ON PROCEDURE SGRETFILIAL TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT EXECUTE ON PROCEDURE SGRETFILIAL TO PROCEDURE TKGERACAMPANHACTO;

GRANT EXECUTE ON PROCEDURE SGRETINFOUSU TO PROCEDURE TKGERACAMPANHACTO;

GRANT EXECUTE ON PROCEDURE SGRETMULTICOMISSP TO ADM;

GRANT EXECUTE ON PROCEDURE SGRETMULTICOMISSP TO PROCEDURE ATADICATENDIMENTOCLISP;

GRANT EXECUTE ON PROCEDURE SGRETMULTICOMISSP TO PROCEDURE VDGERACOMISSAOSP;

GRANT EXECUTE ON PROCEDURE SGRETVERSAO TO PUBLIC;

GRANT EXECUTE ON PROCEDURE SPGERANUM TO PROCEDURE ATADICATENDIMENTOCLISP;

GRANT EXECUTE ON PROCEDURE SPGERANUM TO PROCEDURE TKGERACAMPANHACTO;

GRANT EXECUTE ON PROCEDURE TKGERACAMPANHACTO TO ADM;

GRANT EXECUTE ON PROCEDURE VDATUDESCVENDAORCSP TO ADM;

GRANT EXECUTE ON PROCEDURE VDITVENDASERIESP TO ADM;

GRANT EXECUTE ON PROCEDURE VDUPVENDAORCSP TO ADM;

GRANT INSERT ON PPOPCQ TO PROCEDURE PPGERAOPCQ;

GRANT INSERT, SELECT ON CPITCOMPRA TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT INSERT, SELECT ON VDVENDA TO PROCEDURE VDATUDESCVENDAORCSP;

GRANT INSERT, SELECT, UPDATE ON LFITCOMPRA TO PROCEDURE LFGERALFITCOMPRASP;

GRANT INSERT, SELECT, UPDATE ON LFITVENDA TO PROCEDURE LFGERALFITVENDASP;

GRANT SELECT ON ATATENDENTE TO PROCEDURE TKGERACAMPANHACTO;

GRANT SELECT ON CPCOMPRA TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT SELECT ON CPCOMPRA TO PROCEDURE EQRELGIROPROD;

GRANT SELECT ON CPCOMPRA TO PROCEDURE LFGERALFITCOMPRASP;

GRANT SELECT ON CPFORNECED TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT SELECT ON CPFORNECED TO PROCEDURE LFGERALFITCOMPRASP;

GRANT SELECT ON CPITCOMPRA TO PROCEDURE EQRELGIROPROD;

GRANT SELECT ON CPITCOMPRA TO PROCEDURE LFGERALFITCOMPRASP;

GRANT SELECT ON EQCONFESTOQVW01 TO ADM;

GRANT SELECT ON EQLOTE TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT SELECT ON EQMOVPROD TO PROCEDURE EQRELGIROPROD;

GRANT SELECT ON EQPRODUTO TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT SELECT ON EQPRODUTO TO PROCEDURE EQRELGIROPROD;

GRANT SELECT ON EQPRODUTO TO PROCEDURE LFBUSCAPREVTRIBORC;

GRANT SELECT ON LFITCLFISCAL TO PROCEDURE LFBUSCAFISCALSP02;

GRANT SELECT ON LFITCLFISCAL TO PROCEDURE LFBUSCAPREVTRIBORC;

GRANT SELECT ON LFITCLFISCAL TO PROCEDURE LFGERALFITCOMPRASP;

GRANT SELECT ON LFITCLFISCAL TO PROCEDURE LFGERALFITVENDASP;

GRANT SELECT ON PPLISTAOPVW01 TO ADM;

GRANT SELECT ON SGFILIAL TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT SELECT ON SGFILIAL TO PROCEDURE LFBUSCAFISCALSP02;

GRANT SELECT ON SGFILIAL TO PROCEDURE LFBUSCAPREVTRIBORC;

GRANT SELECT ON SGPREFERE1 TO PROCEDURE CPADICITCOMPRAPEDSP;

GRANT SELECT ON VDITORCAMENTO TO PROCEDURE LFBUSCAPREVTRIBORC;

GRANT SELECT ON VDITVENDA TO PROCEDURE EQRELGIROPROD;

GRANT SELECT ON VDITVENDA TO PROCEDURE LFBUSCAFISCALSP02;

GRANT SELECT ON VDITVENDA TO PROCEDURE LFGERALFITVENDASP;

GRANT SELECT ON VDORCAMENTO TO PROCEDURE LFBUSCAPREVTRIBORC;

GRANT SELECT ON VDORCAMENTO TO PROCEDURE VDATUDESCVENDAORCSP;

GRANT SELECT ON VDVENDA TO PROCEDURE EQRELGIROPROD;

GRANT SELECT ON VWCUSTOPROJ01 TO ADM;



