INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1104', 'Contribuinte Individual - Recolhimento trimestral NIT/PIS/PASEP                 ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1007', 'Contribuinte Individual - Recolhimento mensal NIT/PIS/PASEP                     ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1120', 'Contribuinte Individual - recolhimento mensal com redução de 45% NIT/PIS/PASEP  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1201', 'GRC Contribuinte Individual - DEBCAD (Preenchimento exclusivo pelo INSS)        ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1457', 'Segurado facultativo - Recolhimento Trimestral NIT/PIS/PASEP                    ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1554', 'Segurado Especial - Recolhimento Trimestral NIT/PIS/PASEP                       ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1600', 'Empregado Doméstico - Recolhimento Mensal NIT/PIS/PASEP                         ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1651', 'Empregado Doméstico - Recolhimento Trimestral NIT/PIS/PASEP                     ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('1708', 'Reclamatória Trabalhista NIT/PIS/PASEP                                          ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2003', 'Empresas Optantes pelo simples CNPJ                                             ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2100', 'Empresas em geral CNPJ                                                          ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2119', 'Emp. em geral CNPJ, Recolhimento exclusivo para outras entidades (SESC,SESI etc ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2208', 'Empresas em geral CEI                                                           ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2216', 'Emp. em geral CNPJ, Recolhimento exclusivo para outras entidades(SESC,SESI, etc)');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2305', 'Entidades filantrópicas  com isenção total ou parcial CNPJ                      ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2321', 'Entidades filantrópicas com isenção total ou parcial CEI                        ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2402', 'Órgãos do poder público CNPJ                                                    ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2429', 'Órgãos do poder público CEI                                                     ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2437', 'OPP - CNPJ Recolhimento sobre aquisição de produto rural do Produtor pessoa fís ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2445', 'OPP - CNPJ Recolhimento sobre contratação de transportador Rodoviário Autônomo  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2500', 'Recolhimento sobre a Receita Bruta de Espetáculos Desportivos e Cont. Patrocínio');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2607', 'Recolhimento sobre a comercialização de produto Rural CNPJ                      ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2615', 'Recolh. sobre a comercialização de Produto Rural CNPJ p/ entidades (SENAR)      ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2631', 'Contribuição retida sobre a NF/Fatura da Empresa Prestadora de Serviço CNPJ     ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2640', 'Contribuição retida sobre NF/Fatura da Prestadora de Serviço CNPJ OPP Adm. Dir  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2658', 'Contribuição retida sobre a NF/Fatura da Empresa Prestadora de Serviço CEI      ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2682', 'Contribuição retida sobre a NF/Fatura da Prestadora de Serviço CEI OPP adm. dir ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2704', 'Recolhimento sobre a Comercialização de Produto Rural CEI                       ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2712', 'Recolhimento sobre a Comercialização de Produto Rural CEI exclusivo p/ entidades');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2801', 'Reclamatória Trabalhista CEI                                                    ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2810', 'Reclamatória  Trabalhista CEI Recolhiento exclusivo p/ entiades(SESC,SESI,SENAI)');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2909', 'Reclamatória Trabalhista  CNPJ                                                  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('2917', 'Reclamatória Trabalhista CNPJ Recolhimento p/ entidades(SESC,SESI,SENAI e etc.) ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('3000', 'ACAL CNPJ                                                                       ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('3107', 'ACAL CEI                                                                        ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('3204', 'GRC Contribuição de Empresa NOrmal DEBCAD(Preenchimento exclusivo pelo INSS)    ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('4006', 'Pagamento de Débito DEBCAD (Preenchimento exclusivo pelo INSS)                  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('4103', 'Pagamento de Débito CNPJ (Preenchimento exclusivo pelo INSS)                    ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('4200', 'Pagamento de Débito administrativo Número do Título de Cobrança (INSS)          ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('4308', 'Pagamento de Parcelamento Administrativo Número do Título de cobrança (INSS)    ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('4316', 'Pagamento de Parcelamento de Clube de Futebol CNPJ(5% da receita bruta ao clube)');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6009', 'Pagamento de Dívida Ativa Débito Referência (Preenchimento exclusivo pelo INSS) ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6106', 'Pagamento de Dívida Parcelamento ReferênciA (Preenchimento exclusivo pelo INSS) ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6203', 'Recebimento de Crédito ou de Dívida Ativa - Ação Judicial Referência            ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6300', 'Pagamento de Dívida Ativa, Cobrança Amigável Referência (INSS)                  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6408', 'Conversão em Receita de Depósito Judicial à Lei nº 9.703/98 CNPJ                ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6432', 'Conversão em Receita de Depósito Judicial à Lei nº 9.703/98 CEI                 ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6440', 'Conversão em Receita de Depósito Judicial à Lei nº 9.703/98 DEBCAD              ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6459', 'Conversão em Receita de Depósito Judicial à Lei nº 9.703/98 NB                  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('6467', 'Conversão em Receita de Depósito Judicial à Lei nº 9.703/98 NIT/PIS/PASEP       ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8001', 'Financiamento Imobiliário Referência (Preenchimento exclusivo pelo INSS)        ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8109', 'Aluguéis Referência (Preenchimento pelo INSS)                                   ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8133', 'Condomínio a Título de Reembolso Referência (Preenchimento pelo INSS)           ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8141', 'Parcelamento de Financiamento Imobiliário Referência (Preenchimento pelo INSS)  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8150', 'Parcelamento de Aluguéis Referência (Preenchimento pelo INSS)                   ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8168', 'Taxa de Ocupação Referência (Preenchimento pelo INSS)                           ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8176', 'Impostos e Taxas a Título de Reembolso Referência (Preenchiemento pelo INSS)    ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8206', 'Alienação de Bens Imóveis Referência (Preenchimento pelo INSS)                  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('8257', 'Alienação de Bens Móveis Referência ( Preenchimento pelo INSS)                  ');
INSERT INTO RHCODGPS (CODGPS, DESCGPS) VALUES ('9008', 'Devolução de Benefício NB (Preenchimento exclusivo pelo INSS)                   ');

COMMIT WORK;
