CREATE TABLE FNTALAOCHEQ (
    CODEMP INTEGER NOT NULL,
    CODFILIAL SMALLINT NOT NULL,
    NUMCONTA CHAR(10) NOT NULL,
    SEQTALAO SMALLINT NOT NULL,
    DTTALAO DATE DEFAULT 'today' NOT NULL,
    CHEQINITALAO INTEGER DEFAULT 0 NOT NULL,
    CHEQFIMTALAO INTEGER DEFAULT 1 NOT NULL ,
    CHEQATUALTALAO INTEGER NOT NULL,
    ATIVOTALAO CHAR(1) DEFAULT 'S' NOT NULL ,
    DTINS DATE DEFAULT 'today' NOT NULL ,
    HINS TIME DEFAULT 'now' NOT NULL,
    IDUSUINS VARCHAR(128) DEFAULT 'USER' NOT NULL,
    DTALT DATE DEFAULT 'today' NOT NULL,
    HALT TIME DEFAULT 'now' NOT NULL,
    IDUSUALT VARCHAR(128) DEFAULT 'USER' NOT NULL
);

ALTER TABLE FNTALAOCHEQ ADD CONSTRAINT FNTALAOCHEQPK
    PRIMARY KEY (NUMCONTA, SEQTALAO, CODFILIAL, CODEMP);
    
ALTER TABLE FNTALAOCHEQ ADD CONSTRAINT FNTALAOCHEQFKFNCON
    FOREIGN KEY (NUMCONTA, CODFILIAL, CODEMP)
    REFERENCES FNCONTA;

COMMIT WORK;
  


