SELECT P.CODPROD, CL.CODNBM, P.CODUNID, P.PESOBRUTPROD,P.REFPROD,  
(CASE WHEN TIPOPROD='P' THEN 1
      WHEN TIPOPROD='M' THEN 2
      WHEN TIPOPROD='F' THEN 5
      ELSE 99 END) TIPPROD 
FROM EQPRODUTO P, LFCLFISCAL CL
WHERE P.CODEMP=4 AND P.CODFILIAL=1 AND 
CL.CODEMP=P.CODEMPFC AND CL.CODFILIAL=P.CODEMPFC AND CL.CODFISC=P.CODFISC
