UPDATE VDITVENDA IV SET 
EMMANUT='S',
CODEMPAX=(SELECT CODEMPAX FROM EQPRODUTO P 
   WHERE P.CODPROD=IV.CODPROD AND P.CODEMP=IV.CODEMPPD AND 
   P.CODFILIAL=IV.CODFILIALPD),
CODFILIALAX=(SELECT CODFILIALAX FROM EQPRODUTO P 
   WHERE P.CODPROD=IV.CODPROD AND P.CODEMP=IV.CODEMPPD AND 
   P.CODFILIAL=IV.CODFILIALPD),   
CODALMOX=(SELECT CODALMOX FROM EQPRODUTO P 
   WHERE P.CODPROD=IV.CODPROD AND P.CODEMP=IV.CODEMPPD AND 
   P.CODFILIAL=IV.CODFILIALPD)
WHERE IV.CODALMOX IS NULL;
COMMIT WORK;
UPDATE VDITVENDA SET EMMANUT='N' WHERE EMMANUT='S';
COMMIT WORK;

UPDATE CPITCOMPRA IC SET 
EMMANUT='S',
CODEMPAX=(SELECT CODEMPAX FROM EQPRODUTO P 
   WHERE P.CODPROD=IC.CODPROD AND P.CODEMP=IC.CODEMPPD AND 
   P.CODFILIAL=IC.CODFILIALPD),
CODFILIALAX=(SELECT CODFILIALAX FROM EQPRODUTO P 
   WHERE P.CODPROD=IC.CODPROD AND P.CODEMP=IC.CODEMPPD AND 
   P.CODFILIAL=IC.CODFILIALPD),   
CODALMOX=(SELECT CODALMOX FROM EQPRODUTO P 
   WHERE P.CODPROD=IC.CODPROD AND P.CODEMP=IC.CODEMPPD AND 
   P.CODFILIAL=IC.CODFILIALPD)
WHERE IC.CODALMOX IS NULL;
COMMIT WORK;
UPDATE CPITCOMPRA SET EMMANUT='N' WHERE EMMANUT='S';
COMMIT WORK;

UPDATE EQMOVPROD MP SET 
EMMANUT='S',
CODEMPAX=(SELECT CODEMPAX FROM EQPRODUTO P 
   WHERE P.CODPROD=MP.CODPROD AND P.CODEMP=MP.CODEMPPD AND 
   P.CODFILIAL=MP.CODFILIALPD),
CODFILIALAX=(SELECT CODFILIALAX FROM EQPRODUTO P 
   WHERE P.CODPROD=MP.CODPROD AND P.CODEMP=MP.CODEMPPD AND 
   P.CODFILIAL=MP.CODFILIALPD),   
CODALMOX=(SELECT CODALMOX FROM EQPRODUTO P 
   WHERE P.CODPROD=MP.CODPROD AND P.CODEMP=MP.CODEMPPD AND 
   P.CODFILIAL=MP.CODFILIALPD)
WHERE MP.CODALMOX IS NULL;
COMMIT WORK;
UPDATE EQMOVPROD SET EMMANUT='N' WHERE EMMANUT='S';
COMMIT WORK;
UPDATE VDITORCAMENTO IO SET 
EMMANUT='S',
CODEMPAX=(SELECT CODEMPAX FROM EQPRODUTO P 
   WHERE P.CODPROD=IO.CODPROD AND P.CODEMP=IO.CODEMPPD AND 
   P.CODFILIAL=IO.CODFILIALPD),
CODFILIALAX=(SELECT CODFILIALAX FROM EQPRODUTO P 
   WHERE P.CODPROD=IO.CODPROD AND P.CODEMP=IO.CODEMPPD AND 
   P.CODFILIAL=IO.CODFILIALPD),   
CODALMOX=(SELECT CODALMOX FROM EQPRODUTO P 
   WHERE P.CODPROD=IO.CODPROD AND P.CODEMP=IO.CODEMPPD AND 
   P.CODFILIAL=IO.CODFILIALPD)
WHERE IO.CODALMOX IS NULL;
COMMIT WORK;
UPDATE VDITORCAMENTO SET EMMANUT='N' WHERE EMMANUT='S';
COMMIT WORK;
   