/* Server Version: LI-V6.3.4.4910 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.6.4.fdb' USER 'SYSDBA' PASSWORD '123654';

SET AUTODDL ON;

ALTER TABLE FNMOVIMENTO DROP CONSTRAINT FNMOVIMENTOFKFNREC;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.6.4.fdb' USER 'SYSDBA' PASSWORD '123654';

ALTER TABLE FNMOVIMENTO DROP CONSTRAINT FNMOVIMENTOFKFNPAG;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.6.4.fdb' USER 'SYSDBA' PASSWORD '123654';

/* Alter Field (Null / Not Null)... */
UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = 1 WHERE RDB$FIELD_NAME='LIBERACAMPOPESAGEM' AND RDB$RELATION_NAME='SGUSUARIO';

/* Alter Field (Null / Not Null)... */
UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = 1 WHERE RDB$FIELD_NAME='APROVORDCP' AND RDB$RELATION_NAME='SGUSUARIO';


ALTER TABLE SGPREFERE6 ADD SOBRESCREVEHIST CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTCADLOTE CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTRMA CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTQUALID CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTDISTR CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTFASE CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTCANC CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTSUBPROD CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTREMESSA CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPBTRETORNO CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGUSUARIO ADD ACESOPVERITENS CHAR(1) DEFAULT 'S' NOT NULL;

/* Alter Index (Drop, Create)... */
--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.6.4.fdb' USER 'SYSDBA' PASSWORD '123654';

DROP INDEX FNSUBLANCAIDXDTSUBLANCA;

CREATE INDEX FNSUBLANCAIDXDTSUBLANCA ON FNSUBLANCA(CODPLAN,DATASUBLANCA,CODLANCA,CODFILIAL,CODEMP);


/* Create Foreign Key... */
--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.6.4.fdb' USER 'SYSDBA' PASSWORD '123654';

ALTER TABLE FNMOVIMENTO ADD CONSTRAINT FNMOVIMENTOFKFNITPAG FOREIGN KEY (CODPAG,NPARCPAG,CODFILIALPG,CODEMPPG) REFERENCES FNITPAGAR(CODPAG,NPARCPAG,CODFILIAL,CODEMP);

ALTER TABLE FNMOVIMENTO ADD CONSTRAINT FNMOVIMENTOFKFNITREC FOREIGN KEY (CODREC,NPARCITREC,CODFILIALRC,CODEMPRC) REFERENCES FNITRECEBER(CODREC,NPARCITREC,CODFILIAL,CODEMP);

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
SET TERM ^ ;

ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.6.5 (17/08/2013)';
    suspend;
end
^

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.6.5 (17/08/2013)';
    suspend;
end
^

SET TERM ; ^

ALTER TABLE SGPREFERE6 ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE SGPREFERE6 ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE SGPREFERE6 ALTER COLUMN NOMEEMP POSITION 3;

ALTER TABLE SGPREFERE6 ALTER COLUMN NOMEEMPCNAB POSITION 4;

ALTER TABLE SGPREFERE6 ALTER COLUMN SOBRESCREVEHIST POSITION 5;

ALTER TABLE SGPREFERE6 ALTER COLUMN DTINS POSITION 6;

ALTER TABLE SGPREFERE6 ALTER COLUMN HINS POSITION 7;

ALTER TABLE SGPREFERE6 ALTER COLUMN IDUSUINS POSITION 8;

ALTER TABLE SGPREFERE6 ALTER COLUMN DTALT POSITION 9;

ALTER TABLE SGPREFERE6 ALTER COLUMN HALT POSITION 10;

ALTER TABLE SGPREFERE6 ALTER COLUMN IDUSUALT POSITION 11;

ALTER TABLE SGUSUARIO ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE SGUSUARIO ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE SGUSUARIO ALTER COLUMN IDUSU POSITION 3;

ALTER TABLE SGUSUARIO ALTER COLUMN NOMEUSU POSITION 4;

ALTER TABLE SGUSUARIO ALTER COLUMN CODEMPIG POSITION 5;

ALTER TABLE SGUSUARIO ALTER COLUMN CODFILIALIG POSITION 6;

ALTER TABLE SGUSUARIO ALTER COLUMN IDGRPUSU POSITION 7;

ALTER TABLE SGUSUARIO ALTER COLUMN CODEMPCC POSITION 8;

ALTER TABLE SGUSUARIO ALTER COLUMN CODFILIALCC POSITION 9;

ALTER TABLE SGUSUARIO ALTER COLUMN ANOCC POSITION 10;

ALTER TABLE SGUSUARIO ALTER COLUMN CODCC POSITION 11;

ALTER TABLE SGUSUARIO ALTER COLUMN PNOMEUSU POSITION 12;

ALTER TABLE SGUSUARIO ALTER COLUMN UNOMEUSU POSITION 13;

ALTER TABLE SGUSUARIO ALTER COLUMN COMENTUSU POSITION 14;

ALTER TABLE SGUSUARIO ALTER COLUMN BAIXOCUSTOUSU POSITION 15;

ALTER TABLE SGUSUARIO ALTER COLUMN CODALMOX POSITION 16;

ALTER TABLE SGUSUARIO ALTER COLUMN CODEMPAM POSITION 17;

ALTER TABLE SGUSUARIO ALTER COLUMN CODFILIALAM POSITION 18;

ALTER TABLE SGUSUARIO ALTER COLUMN ABREGAVETAUSU POSITION 19;

ALTER TABLE SGUSUARIO ALTER COLUMN APROVCPSOLICITACAOUSU POSITION 20;

ALTER TABLE SGUSUARIO ALTER COLUMN ALMOXARIFEUSU POSITION 21;

ALTER TABLE SGUSUARIO ALTER COLUMN CODEMPAE POSITION 22;

ALTER TABLE SGUSUARIO ALTER COLUMN CODFILIALAE POSITION 23;

ALTER TABLE SGUSUARIO ALTER COLUMN TIPOAGE POSITION 24;

ALTER TABLE SGUSUARIO ALTER COLUMN CODAGE POSITION 25;

ALTER TABLE SGUSUARIO ALTER COLUMN APROVRMAUSU POSITION 26;

ALTER TABLE SGUSUARIO ALTER COLUMN COMPRASUSU POSITION 27;

ALTER TABLE SGUSUARIO ALTER COLUMN ALTPARCVENDA POSITION 28;

ALTER TABLE SGUSUARIO ALTER COLUMN APROVRECEITA POSITION 29;

ALTER TABLE SGUSUARIO ALTER COLUMN ATIVCLI POSITION 30;

ALTER TABLE SGUSUARIO ALTER COLUMN LIBERACREDUSU POSITION 31;

ALTER TABLE SGUSUARIO ALTER COLUMN CORAGENDA POSITION 32;

ALTER TABLE SGUSUARIO ALTER COLUMN CODEMPCE POSITION 33;

ALTER TABLE SGUSUARIO ALTER COLUMN CODFILIALCE POSITION 34;

ALTER TABLE SGUSUARIO ALTER COLUMN CODCONFEMAIL POSITION 35;

ALTER TABLE SGUSUARIO ALTER COLUMN CANCELAOP POSITION 36;

ALTER TABLE SGUSUARIO ALTER COLUMN VENDAPATRIMUSU POSITION 37;

ALTER TABLE SGUSUARIO ALTER COLUMN RMAOUTCC POSITION 38;

ALTER TABLE SGUSUARIO ALTER COLUMN ATIVOUSU POSITION 39;

ALTER TABLE SGUSUARIO ALTER COLUMN VISUALIZALUCR POSITION 40;

ALTER TABLE SGUSUARIO ALTER COLUMN LIBERACAMPOPESAGEM POSITION 41;

ALTER TABLE SGUSUARIO ALTER COLUMN APROVORDCP POSITION 42;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTCADLOTE POSITION 43;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTRMA POSITION 44;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTQUALID POSITION 45;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTDISTR POSITION 46;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTFASE POSITION 47;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTCANC POSITION 48;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTSUBPROD POSITION 49;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTREMESSA POSITION 50;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPBTRETORNO POSITION 51;

ALTER TABLE SGUSUARIO ALTER COLUMN ACESOPVERITENS POSITION 52;

ALTER TABLE SGUSUARIO ALTER COLUMN DTINS POSITION 53;

ALTER TABLE SGUSUARIO ALTER COLUMN HINS POSITION 54;

ALTER TABLE SGUSUARIO ALTER COLUMN IDUSUINS POSITION 55;

ALTER TABLE SGUSUARIO ALTER COLUMN DTALT POSITION 56;

ALTER TABLE SGUSUARIO ALTER COLUMN HALT POSITION 57;

ALTER TABLE SGUSUARIO ALTER COLUMN IDUSUALT POSITION 58;


COMMIT WORK;
