package org.freedom.persist.entity;

// Generated 18/02/2014 15:53:28 by Hibernate Tools 4.0.0

/**
 * Atatendimentovw07 generated by hbm2java
 */
public class Atatendimentovw07 implements java.io.Serializable {

	private Atatendimentovw07Id id;

	public Atatendimentovw07() {
	}

	public Atatendimentovw07(Atatendimentovw07Id id) {
		this.id = id;
	}

	public Atatendimentovw07Id getId() {
		return this.id;
	}

	public void setId(Atatendimentovw07Id id) {
		this.id = id;
	}

}
