package org.freedom.persist.entity;

// Generated 14/04/2014 10:17:08 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Cphomologfor generated by hbm2java
 */
public class Cphomologfor implements java.io.Serializable {

	private CphomologforId id;
	private Cpforneced cpforneced;
	private char ishfor;
	private Date dthfor;
	private String obshfor;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Cphomologfor() {
	}

	public Cphomologfor(Cpforneced cpforneced, char ishfor, Date dthfor,
			String obshfor, Date dtins, Date hins, String idusuins) {
		this.cpforneced = cpforneced;
		this.ishfor = ishfor;
		this.dthfor = dthfor;
		this.obshfor = obshfor;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Cphomologfor(Cpforneced cpforneced, char ishfor, Date dthfor,
			String obshfor, Date dtins, Date hins, String idusuins, Date dtalt,
			Date halt, String idusualt) {
		this.cpforneced = cpforneced;
		this.ishfor = ishfor;
		this.dthfor = dthfor;
		this.obshfor = obshfor;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	public CphomologforId getId() {
		return this.id;
	}

	public void setId(CphomologforId id) {
		this.id = id;
	}

	public Cpforneced getCpforneced() {
		return this.cpforneced;
	}

	public void setCpforneced(Cpforneced cpforneced) {
		this.cpforneced = cpforneced;
	}

	public char getIshfor() {
		return this.ishfor;
	}

	public void setIshfor(char ishfor) {
		this.ishfor = ishfor;
	}

	public Date getDthfor() {
		return this.dthfor;
	}

	public void setDthfor(Date dthfor) {
		this.dthfor = dthfor;
	}

	public String getObshfor() {
		return this.obshfor;
	}

	public void setObshfor(String obshfor) {
		this.obshfor = obshfor;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
