package org.freedom.persist.entity;

// Generated 20/11/2013 10:59:59 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Crtarefa generated by hbm2java
 */
public class Crtarefa implements java.io.Serializable {

	private CrtarefaId id;
	private Crmarcador crmarcador;
	private Crtarefa crtarefa;
	private Crchamado crchamado;
	private Vditcontrato vditcontrato;
	private String desctarefa;
	private char tipotarefa;
	private char lanctotarefa;
	private String descdettarefa;
	private int indextarefa;
	private String tempoesttarefa;
	private BigDecimal tempodectarefa;
	private String notastarefa;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set atatendimentos = new HashSet(0);
	private Set crtarefapers = new HashSet(0);
	private Set crtarefas = new HashSet(0);

	public Crtarefa() {
	}

	public Crtarefa(CrtarefaId id, Vditcontrato vditcontrato,
			String desctarefa, char tipotarefa, char lanctotarefa,
			String descdettarefa, int indextarefa, String tempoesttarefa,
			BigDecimal tempodectarefa, Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.vditcontrato = vditcontrato;
		this.desctarefa = desctarefa;
		this.tipotarefa = tipotarefa;
		this.lanctotarefa = lanctotarefa;
		this.descdettarefa = descdettarefa;
		this.indextarefa = indextarefa;
		this.tempoesttarefa = tempoesttarefa;
		this.tempodectarefa = tempodectarefa;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Crtarefa(CrtarefaId id, Crmarcador crmarcador, Crtarefa crtarefa,
			Crchamado crchamado, Vditcontrato vditcontrato, String desctarefa,
			char tipotarefa, char lanctotarefa, String descdettarefa,
			int indextarefa, String tempoesttarefa, BigDecimal tempodectarefa,
			String notastarefa, Date dtins, Date hins, String idusuins,
			Date dtalt, Date halt, String idusualt, Set atatendimentos,
			Set crtarefapers, Set crtarefas) {
		this.id = id;
		this.crmarcador = crmarcador;
		this.crtarefa = crtarefa;
		this.crchamado = crchamado;
		this.vditcontrato = vditcontrato;
		this.desctarefa = desctarefa;
		this.tipotarefa = tipotarefa;
		this.lanctotarefa = lanctotarefa;
		this.descdettarefa = descdettarefa;
		this.indextarefa = indextarefa;
		this.tempoesttarefa = tempoesttarefa;
		this.tempodectarefa = tempodectarefa;
		this.notastarefa = notastarefa;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.atatendimentos = atatendimentos;
		this.crtarefapers = crtarefapers;
		this.crtarefas = crtarefas;
	}

	public CrtarefaId getId() {
		return this.id;
	}

	public void setId(CrtarefaId id) {
		this.id = id;
	}

	public Crmarcador getCrmarcador() {
		return this.crmarcador;
	}

	public void setCrmarcador(Crmarcador crmarcador) {
		this.crmarcador = crmarcador;
	}

	public Crtarefa getCrtarefa() {
		return this.crtarefa;
	}

	public void setCrtarefa(Crtarefa crtarefa) {
		this.crtarefa = crtarefa;
	}

	public Crchamado getCrchamado() {
		return this.crchamado;
	}

	public void setCrchamado(Crchamado crchamado) {
		this.crchamado = crchamado;
	}

	public Vditcontrato getVditcontrato() {
		return this.vditcontrato;
	}

	public void setVditcontrato(Vditcontrato vditcontrato) {
		this.vditcontrato = vditcontrato;
	}

	public String getDesctarefa() {
		return this.desctarefa;
	}

	public void setDesctarefa(String desctarefa) {
		this.desctarefa = desctarefa;
	}

	public char getTipotarefa() {
		return this.tipotarefa;
	}

	public void setTipotarefa(char tipotarefa) {
		this.tipotarefa = tipotarefa;
	}

	public char getLanctotarefa() {
		return this.lanctotarefa;
	}

	public void setLanctotarefa(char lanctotarefa) {
		this.lanctotarefa = lanctotarefa;
	}

	public String getDescdettarefa() {
		return this.descdettarefa;
	}

	public void setDescdettarefa(String descdettarefa) {
		this.descdettarefa = descdettarefa;
	}

	public int getIndextarefa() {
		return this.indextarefa;
	}

	public void setIndextarefa(int indextarefa) {
		this.indextarefa = indextarefa;
	}

	public String getTempoesttarefa() {
		return this.tempoesttarefa;
	}

	public void setTempoesttarefa(String tempoesttarefa) {
		this.tempoesttarefa = tempoesttarefa;
	}

	public BigDecimal getTempodectarefa() {
		return this.tempodectarefa;
	}

	public void setTempodectarefa(BigDecimal tempodectarefa) {
		this.tempodectarefa = tempodectarefa;
	}

	public String getNotastarefa() {
		return this.notastarefa;
	}

	public void setNotastarefa(String notastarefa) {
		this.notastarefa = notastarefa;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	public Set getAtatendimentos() {
		return this.atatendimentos;
	}

	public void setAtatendimentos(Set atatendimentos) {
		this.atatendimentos = atatendimentos;
	}

	public Set getCrtarefapers() {
		return this.crtarefapers;
	}

	public void setCrtarefapers(Set crtarefapers) {
		this.crtarefapers = crtarefapers;
	}

	public Set getCrtarefas() {
		return this.crtarefas;
	}

	public void setCrtarefas(Set crtarefas) {
		this.crtarefas = crtarefas;
	}

}
