package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eqalmox generated by hbm2java
 */
@Entity
@Table(name = "EQALMOX")
public class Eqalmox implements java.io.Serializable {

	private EqalmoxId id;
	private Sgfilial sgfilial;
	private String descalmox;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set eqmovprods = new HashSet(0);
	private Set sgusuarios = new HashSet(0);
	private Set eqrecmercs = new HashSet(0);
	private Set eqsaldoprods = new HashSet(0);
	private Set ppops = new HashSet(0);
	private Set eqinvprods = new HashSet(0);
	private Set cpitsolicitacaos = new HashSet(0);
	private Set eqalmoxfilials = new HashSet(0);
	private Set eqprodutos = new HashSet(0);
	private Set cpitcompras = new HashSet(0);
	private Set vditvendas = new HashSet(0);
	private Set eqsaldolotes = new HashSet(0);
	private Set eqexpedicaos = new HashSet(0);
	private Set eqitrmas = new HashSet(0);
	private Set vditorcamentos = new HashSet(0);

	public Eqalmox() {
	}

	public Eqalmox(EqalmoxId id, Sgfilial sgfilial, String descalmox,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.descalmox = descalmox;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Eqalmox(EqalmoxId id, Sgfilial sgfilial, String descalmox,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt, Set eqmovprods, Set sgusuarios, Set eqrecmercs,
			Set eqsaldoprods, Set ppops, Set eqinvprods, Set cpitsolicitacaos,
			Set eqalmoxfilials, Set eqprodutos, Set cpitcompras,
			Set vditvendas, Set eqsaldolotes, Set eqexpedicaos, Set eqitrmas,
			Set vditorcamentos) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.descalmox = descalmox;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.eqmovprods = eqmovprods;
		this.sgusuarios = sgusuarios;
		this.eqrecmercs = eqrecmercs;
		this.eqsaldoprods = eqsaldoprods;
		this.ppops = ppops;
		this.eqinvprods = eqinvprods;
		this.cpitsolicitacaos = cpitsolicitacaos;
		this.eqalmoxfilials = eqalmoxfilials;
		this.eqprodutos = eqprodutos;
		this.cpitcompras = cpitcompras;
		this.vditvendas = vditvendas;
		this.eqsaldolotes = eqsaldolotes;
		this.eqexpedicaos = eqexpedicaos;
		this.eqitrmas = eqitrmas;
		this.vditorcamentos = vditorcamentos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codalmox", column = @Column(name = "CODALMOX", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public EqalmoxId getId() {
		return this.id;
	}

	public void setId(EqalmoxId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Sgfilial getSgfilial() {
		return this.sgfilial;
	}

	public void setSgfilial(Sgfilial sgfilial) {
		this.sgfilial = sgfilial;
	}

	@Column(name = "DESCALMOX", nullable = false, length = 40)
	public String getDescalmox() {
		return this.descalmox;
	}

	public void setDescalmox(String descalmox) {
		this.descalmox = descalmox;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqmovprods() {
		return this.eqmovprods;
	}

	public void setEqmovprods(Set eqmovprods) {
		this.eqmovprods = eqmovprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getSgusuarios() {
		return this.sgusuarios;
	}

	public void setSgusuarios(Set sgusuarios) {
		this.sgusuarios = sgusuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqrecmercs() {
		return this.eqrecmercs;
	}

	public void setEqrecmercs(Set eqrecmercs) {
		this.eqrecmercs = eqrecmercs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqsaldoprods() {
		return this.eqsaldoprods;
	}

	public void setEqsaldoprods(Set eqsaldoprods) {
		this.eqsaldoprods = eqsaldoprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getPpops() {
		return this.ppops;
	}

	public void setPpops(Set ppops) {
		this.ppops = ppops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqinvprods() {
		return this.eqinvprods;
	}

	public void setEqinvprods(Set eqinvprods) {
		this.eqinvprods = eqinvprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getCpitsolicitacaos() {
		return this.cpitsolicitacaos;
	}

	public void setCpitsolicitacaos(Set cpitsolicitacaos) {
		this.cpitsolicitacaos = cpitsolicitacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqalmoxfilials() {
		return this.eqalmoxfilials;
	}

	public void setEqalmoxfilials(Set eqalmoxfilials) {
		this.eqalmoxfilials = eqalmoxfilials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqprodutos() {
		return this.eqprodutos;
	}

	public void setEqprodutos(Set eqprodutos) {
		this.eqprodutos = eqprodutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getCpitcompras() {
		return this.cpitcompras;
	}

	public void setCpitcompras(Set cpitcompras) {
		this.cpitcompras = cpitcompras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getVditvendas() {
		return this.vditvendas;
	}

	public void setVditvendas(Set vditvendas) {
		this.vditvendas = vditvendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqsaldolotes() {
		return this.eqsaldolotes;
	}

	public void setEqsaldolotes(Set eqsaldolotes) {
		this.eqsaldolotes = eqsaldolotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqexpedicaos() {
		return this.eqexpedicaos;
	}

	public void setEqexpedicaos(Set eqexpedicaos) {
		this.eqexpedicaos = eqexpedicaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getEqitrmas() {
		return this.eqitrmas;
	}

	public void setEqitrmas(Set eqitrmas) {
		this.eqitrmas = eqitrmas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eqalmox")
	public Set getVditorcamentos() {
		return this.vditorcamentos;
	}

	public void setVditorcamentos(Set vditorcamentos) {
		this.vditorcamentos = vditorcamentos;
	}
*/
}
