package org.freedom.persist.entity;

// Generated 14/04/2014 10:17:08 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Eqmarca generated by hbm2java
 */
public class Eqmarca implements java.io.Serializable {

	private EqmarcaId id;
	private Sgfilial sgfilial;
	private String descmarca;
	private String siglamarca;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set sgprefere1s = new HashSet(0);
	private Set eqprodutos = new HashSet(0);

	public Eqmarca() {
	}

	public Eqmarca(EqmarcaId id, Sgfilial sgfilial, String descmarca,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.descmarca = descmarca;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Eqmarca(EqmarcaId id, Sgfilial sgfilial, String descmarca,
			String siglamarca, Date dtins, Date hins, String idusuins,
			Date dtalt, Date halt, String idusualt, Set sgprefere1s,
			Set eqprodutos) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.descmarca = descmarca;
		this.siglamarca = siglamarca;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.sgprefere1s = sgprefere1s;
		this.eqprodutos = eqprodutos;
	}

	public EqmarcaId getId() {
		return this.id;
	}

	public void setId(EqmarcaId id) {
		this.id = id;
	}

	public Sgfilial getSgfilial() {
		return this.sgfilial;
	}

	public void setSgfilial(Sgfilial sgfilial) {
		this.sgfilial = sgfilial;
	}

	public String getDescmarca() {
		return this.descmarca;
	}

	public void setDescmarca(String descmarca) {
		this.descmarca = descmarca;
	}

	public String getSiglamarca() {
		return this.siglamarca;
	}

	public void setSiglamarca(String siglamarca) {
		this.siglamarca = siglamarca;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	public Set getSgprefere1s() {
		return this.sgprefere1s;
	}

	public void setSgprefere1s(Set sgprefere1s) {
		this.sgprefere1s = sgprefere1s;
	}

	public Set getEqprodutos() {
		return this.eqprodutos;
	}

	public void setEqprodutos(Set eqprodutos) {
		this.eqprodutos = eqprodutos;
	}

}
