package org.freedom.persist.entity;

// Generated 20/11/2013 10:59:59 by Hibernate Tools 4.0.0

/**
 * Eqprodutolog generated by hbm2java
 */
public class Eqprodutolog implements java.io.Serializable {

	private EqprodutologId id;

	public Eqprodutolog() {
	}

	public Eqprodutolog(EqprodutologId id) {
		this.id = id;
	}

	public EqprodutologId getId() {
		return this.id;
	}

	public void setId(EqprodutologId id) {
		this.id = id;
	}

}
