package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eqprevestoqlog generated by hbm2java
 */
@Entity
@Table(name = "EQPREVESTOQLOG")
public class Eqprevestoqlog implements java.io.Serializable {

	private long id;
	private Integer codemp;
	private Short codfilial;
	private Date dtini;
	private Date dtfim;
	private Integer codempgp;
	private Short codfilialgp;
	private String codgrup;
	private Integer codemppd;
	private Short codfilialpd;
	private Integer codprod;
	private char ordem;
	private char mercadoriaRevenda;
	private char materiaPrima;
	private char emProcesso;
	private char outros;
	private char subProduto;
	private char equipamento;
	private char materialConsumo;
	private char produtoIntermed;
	private char produtoAcabado;
	private char embalagem;
	private char outrosInsumos;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Eqprevestoqlog() {
	}

	public Eqprevestoqlog(long id, Date dtini, Date dtfim, char ordem,
			char mercadoriaRevenda, char materiaPrima, char emProcesso,
			char outros, char subProduto, char equipamento,
			char materialConsumo, char produtoIntermed, char produtoAcabado,
			char embalagem, char outrosInsumos, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt) {
		this.id = id;
		this.dtini = dtini;
		this.dtfim = dtfim;
		this.ordem = ordem;
		this.mercadoriaRevenda = mercadoriaRevenda;
		this.materiaPrima = materiaPrima;
		this.emProcesso = emProcesso;
		this.outros = outros;
		this.subProduto = subProduto;
		this.equipamento = equipamento;
		this.materialConsumo = materialConsumo;
		this.produtoIntermed = produtoIntermed;
		this.produtoAcabado = produtoAcabado;
		this.embalagem = embalagem;
		this.outrosInsumos = outrosInsumos;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	public Eqprevestoqlog(long id, Integer codemp, Short codfilial, Date dtini,
			Date dtfim, Integer codempgp, Short codfilialgp, String codgrup,
			Integer codemppd, Short codfilialpd, Integer codprod, char ordem,
			char mercadoriaRevenda, char materiaPrima, char emProcesso,
			char outros, char subProduto, char equipamento,
			char materialConsumo, char produtoIntermed, char produtoAcabado,
			char embalagem, char outrosInsumos, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt) {
		this.id = id;
		this.codemp = codemp;
		this.codfilial = codfilial;
		this.dtini = dtini;
		this.dtfim = dtfim;
		this.codempgp = codempgp;
		this.codfilialgp = codfilialgp;
		this.codgrup = codgrup;
		this.codemppd = codemppd;
		this.codfilialpd = codfilialpd;
		this.codprod = codprod;
		this.ordem = ordem;
		this.mercadoriaRevenda = mercadoriaRevenda;
		this.materiaPrima = materiaPrima;
		this.emProcesso = emProcesso;
		this.outros = outros;
		this.subProduto = subProduto;
		this.equipamento = equipamento;
		this.materialConsumo = materialConsumo;
		this.produtoIntermed = produtoIntermed;
		this.produtoAcabado = produtoAcabado;
		this.embalagem = embalagem;
		this.outrosInsumos = outrosInsumos;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "CODEMP")
	public Integer getCodemp() {
		return this.codemp;
	}

	public void setCodemp(Integer codemp) {
		this.codemp = codemp;
	}

	@Column(name = "CODFILIAL")
	public Short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(Short codfilial) {
		this.codfilial = codfilial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINI", nullable = false, length = 10)
	public Date getDtini() {
		return this.dtini;
	}

	public void setDtini(Date dtini) {
		this.dtini = dtini;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTFIM", nullable = false, length = 10)
	public Date getDtfim() {
		return this.dtfim;
	}

	public void setDtfim(Date dtfim) {
		this.dtfim = dtfim;
	}

	@Column(name = "CODEMPGP")
	public Integer getCodempgp() {
		return this.codempgp;
	}

	public void setCodempgp(Integer codempgp) {
		this.codempgp = codempgp;
	}

	@Column(name = "CODFILIALGP")
	public Short getCodfilialgp() {
		return this.codfilialgp;
	}

	public void setCodfilialgp(Short codfilialgp) {
		this.codfilialgp = codfilialgp;
	}

	@Column(name = "CODGRUP", length = 14)
	public String getCodgrup() {
		return this.codgrup;
	}

	public void setCodgrup(String codgrup) {
		this.codgrup = codgrup;
	}

	@Column(name = "CODEMPPD")
	public Integer getCodemppd() {
		return this.codemppd;
	}

	public void setCodemppd(Integer codemppd) {
		this.codemppd = codemppd;
	}

	@Column(name = "CODFILIALPD")
	public Short getCodfilialpd() {
		return this.codfilialpd;
	}

	public void setCodfilialpd(Short codfilialpd) {
		this.codfilialpd = codfilialpd;
	}

	@Column(name = "CODPROD")
	public Integer getCodprod() {
		return this.codprod;
	}

	public void setCodprod(Integer codprod) {
		this.codprod = codprod;
	}

	@Column(name = "ORDEM", nullable = false, length = 1)
	public char getOrdem() {
		return this.ordem;
	}

	public void setOrdem(char ordem) {
		this.ordem = ordem;
	}

	@Column(name = "MERCADORIA_REVENDA", nullable = false, length = 1)
	public char getMercadoriaRevenda() {
		return this.mercadoriaRevenda;
	}

	public void setMercadoriaRevenda(char mercadoriaRevenda) {
		this.mercadoriaRevenda = mercadoriaRevenda;
	}

	@Column(name = "MATERIA_PRIMA", nullable = false, length = 1)
	public char getMateriaPrima() {
		return this.materiaPrima;
	}

	public void setMateriaPrima(char materiaPrima) {
		this.materiaPrima = materiaPrima;
	}

	@Column(name = "EM_PROCESSO", nullable = false, length = 1)
	public char getEmProcesso() {
		return this.emProcesso;
	}

	public void setEmProcesso(char emProcesso) {
		this.emProcesso = emProcesso;
	}

	@Column(name = "OUTROS", nullable = false, length = 1)
	public char getOutros() {
		return this.outros;
	}

	public void setOutros(char outros) {
		this.outros = outros;
	}

	@Column(name = "SUB_PRODUTO", nullable = false, length = 1)
	public char getSubProduto() {
		return this.subProduto;
	}

	public void setSubProduto(char subProduto) {
		this.subProduto = subProduto;
	}

	@Column(name = "EQUIPAMENTO", nullable = false, length = 1)
	public char getEquipamento() {
		return this.equipamento;
	}

	public void setEquipamento(char equipamento) {
		this.equipamento = equipamento;
	}

	@Column(name = "MATERIAL_CONSUMO", nullable = false, length = 1)
	public char getMaterialConsumo() {
		return this.materialConsumo;
	}

	public void setMaterialConsumo(char materialConsumo) {
		this.materialConsumo = materialConsumo;
	}

	@Column(name = "PRODUTO_INTERMED", nullable = false, length = 1)
	public char getProdutoIntermed() {
		return this.produtoIntermed;
	}

	public void setProdutoIntermed(char produtoIntermed) {
		this.produtoIntermed = produtoIntermed;
	}

	@Column(name = "PRODUTO_ACABADO", nullable = false, length = 1)
	public char getProdutoAcabado() {
		return this.produtoAcabado;
	}

	public void setProdutoAcabado(char produtoAcabado) {
		this.produtoAcabado = produtoAcabado;
	}

	@Column(name = "EMBALAGEM", nullable = false, length = 1)
	public char getEmbalagem() {
		return this.embalagem;
	}

	public void setEmbalagem(char embalagem) {
		this.embalagem = embalagem;
	}

	@Column(name = "OUTROS_INSUMOS", nullable = false, length = 1)
	public char getOutrosInsumos() {
		return this.outrosInsumos;
	}

	public void setOutrosInsumos(char outrosInsumos) {
		this.outrosInsumos = outrosInsumos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 128)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", nullable = false, length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", nullable = false, length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", nullable = false, length = 128)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
