package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FncartcobId generated by hbm2java
 */
@Embeddable
public class FncartcobId implements java.io.Serializable {

	private String codcartcob;
	private short codfilial;
	private int codemp;
	private String codbanco;
	private short codfilialbo;
	private int codempbo;

	public FncartcobId() {
	}

	public FncartcobId(String codcartcob, short codfilial, int codemp,
			String codbanco, short codfilialbo, int codempbo) {
		this.codcartcob = codcartcob;
		this.codfilial = codfilial;
		this.codemp = codemp;
		this.codbanco = codbanco;
		this.codfilialbo = codfilialbo;
		this.codempbo = codempbo;
	}

	@Column(name = "CODCARTCOB", nullable = false, length = 3)
	public String getCodcartcob() {
		return this.codcartcob;
	}

	public void setCodcartcob(String codcartcob) {
		this.codcartcob = codcartcob;
	}

	@Column(name = "CODFILIAL", nullable = false)
	public short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(short codfilial) {
		this.codfilial = codfilial;
	}

	@Column(name = "CODEMP", nullable = false)
	public int getCodemp() {
		return this.codemp;
	}

	public void setCodemp(int codemp) {
		this.codemp = codemp;
	}

	@Column(name = "CODBANCO", nullable = false, length = 3)
	public String getCodbanco() {
		return this.codbanco;
	}

	public void setCodbanco(String codbanco) {
		this.codbanco = codbanco;
	}

	@Column(name = "CODFILIALBO", nullable = false)
	public short getCodfilialbo() {
		return this.codfilialbo;
	}

	public void setCodfilialbo(short codfilialbo) {
		this.codfilialbo = codfilialbo;
	}

	@Column(name = "CODEMPBO", nullable = false)
	public int getCodempbo() {
		return this.codempbo;
	}

	public void setCodempbo(int codempbo) {
		this.codempbo = codempbo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FncartcobId))
			return false;
		FncartcobId castOther = (FncartcobId) other;

		return ((this.getCodcartcob() == castOther.getCodcartcob()) || (this
				.getCodcartcob() != null && castOther.getCodcartcob() != null && this
				.getCodcartcob().equals(castOther.getCodcartcob())))
				&& (this.getCodfilial() == castOther.getCodfilial())
				&& (this.getCodemp() == castOther.getCodemp())
				&& ((this.getCodbanco() == castOther.getCodbanco()) || (this
						.getCodbanco() != null
						&& castOther.getCodbanco() != null && this
						.getCodbanco().equals(castOther.getCodbanco())))
				&& (this.getCodfilialbo() == castOther.getCodfilialbo())
				&& (this.getCodempbo() == castOther.getCodempbo());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodcartcob() == null ? 0 : this.getCodcartcob()
						.hashCode());
		result = 37 * result + this.getCodfilial();
		result = 37 * result + this.getCodemp();
		result = 37 * result
				+ (getCodbanco() == null ? 0 : this.getCodbanco().hashCode());
		result = 37 * result + this.getCodfilialbo();
		result = 37 * result + this.getCodempbo();
		return result;
	}

}
