package org.freedom.persist.entity;

// Generated 18/02/2014 15:53:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Fnfluxocaixavw01Id generated by hbm2java
 */
public class Fnfluxocaixavw01Id implements java.io.Serializable {

	private Short ordem;
	private Character tipolanca;
	private Character subtipo;
	private Integer codemp;
	private Short codfilial;
	private Integer codrecpaglanc;
	private Integer nparcrecpaglanc;
	private Date dtemissao;
	private Date dtcomp;
	private Date dtvenctorecpag;
	private String doc;
	private Integer codigo;
	private String razao;
	private String historico;
	private BigDecimal valor;

	public Fnfluxocaixavw01Id() {
	}

	public Fnfluxocaixavw01Id(Short ordem, Character tipolanca,
			Character subtipo, Integer codemp, Short codfilial,
			Integer codrecpaglanc, Integer nparcrecpaglanc, Date dtemissao,
			Date dtcomp, Date dtvenctorecpag, String doc, Integer codigo,
			String razao, String historico, BigDecimal valor) {
		this.ordem = ordem;
		this.tipolanca = tipolanca;
		this.subtipo = subtipo;
		this.codemp = codemp;
		this.codfilial = codfilial;
		this.codrecpaglanc = codrecpaglanc;
		this.nparcrecpaglanc = nparcrecpaglanc;
		this.dtemissao = dtemissao;
		this.dtcomp = dtcomp;
		this.dtvenctorecpag = dtvenctorecpag;
		this.doc = doc;
		this.codigo = codigo;
		this.razao = razao;
		this.historico = historico;
		this.valor = valor;
	}

	public Short getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Short ordem) {
		this.ordem = ordem;
	}

	public Character getTipolanca() {
		return this.tipolanca;
	}

	public void setTipolanca(Character tipolanca) {
		this.tipolanca = tipolanca;
	}

	public Character getSubtipo() {
		return this.subtipo;
	}

	public void setSubtipo(Character subtipo) {
		this.subtipo = subtipo;
	}

	public Integer getCodemp() {
		return this.codemp;
	}

	public void setCodemp(Integer codemp) {
		this.codemp = codemp;
	}

	public Short getCodfilial() {
		return this.codfilial;
	}

	public void setCodfilial(Short codfilial) {
		this.codfilial = codfilial;
	}

	public Integer getCodrecpaglanc() {
		return this.codrecpaglanc;
	}

	public void setCodrecpaglanc(Integer codrecpaglanc) {
		this.codrecpaglanc = codrecpaglanc;
	}

	public Integer getNparcrecpaglanc() {
		return this.nparcrecpaglanc;
	}

	public void setNparcrecpaglanc(Integer nparcrecpaglanc) {
		this.nparcrecpaglanc = nparcrecpaglanc;
	}

	public Date getDtemissao() {
		return this.dtemissao;
	}

	public void setDtemissao(Date dtemissao) {
		this.dtemissao = dtemissao;
	}

	public Date getDtcomp() {
		return this.dtcomp;
	}

	public void setDtcomp(Date dtcomp) {
		this.dtcomp = dtcomp;
	}

	public Date getDtvenctorecpag() {
		return this.dtvenctorecpag;
	}

	public void setDtvenctorecpag(Date dtvenctorecpag) {
		this.dtvenctorecpag = dtvenctorecpag;
	}

	public String getDoc() {
		return this.doc;
	}

	public void setDoc(String doc) {
		this.doc = doc;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getRazao() {
		return this.razao;
	}

	public void setRazao(String razao) {
		this.razao = razao;
	}

	public String getHistorico() {
		return this.historico;
	}

	public void setHistorico(String historico) {
		this.historico = historico;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Fnfluxocaixavw01Id))
			return false;
		Fnfluxocaixavw01Id castOther = (Fnfluxocaixavw01Id) other;

		return ((this.getOrdem() == castOther.getOrdem()) || (this.getOrdem() != null
				&& castOther.getOrdem() != null && this.getOrdem().equals(
				castOther.getOrdem())))
				&& ((this.getTipolanca() == castOther.getTipolanca()) || (this
						.getTipolanca() != null
						&& castOther.getTipolanca() != null && this
						.getTipolanca().equals(castOther.getTipolanca())))
				&& ((this.getSubtipo() == castOther.getSubtipo()) || (this
						.getSubtipo() != null && castOther.getSubtipo() != null && this
						.getSubtipo().equals(castOther.getSubtipo())))
				&& ((this.getCodemp() == castOther.getCodemp()) || (this
						.getCodemp() != null && castOther.getCodemp() != null && this
						.getCodemp().equals(castOther.getCodemp())))
				&& ((this.getCodfilial() == castOther.getCodfilial()) || (this
						.getCodfilial() != null
						&& castOther.getCodfilial() != null && this
						.getCodfilial().equals(castOther.getCodfilial())))
				&& ((this.getCodrecpaglanc() == castOther.getCodrecpaglanc()) || (this
						.getCodrecpaglanc() != null
						&& castOther.getCodrecpaglanc() != null && this
						.getCodrecpaglanc()
						.equals(castOther.getCodrecpaglanc())))
				&& ((this.getNparcrecpaglanc() == castOther
						.getNparcrecpaglanc()) || (this.getNparcrecpaglanc() != null
						&& castOther.getNparcrecpaglanc() != null && this
						.getNparcrecpaglanc().equals(
								castOther.getNparcrecpaglanc())))
				&& ((this.getDtemissao() == castOther.getDtemissao()) || (this
						.getDtemissao() != null
						&& castOther.getDtemissao() != null && this
						.getDtemissao().equals(castOther.getDtemissao())))
				&& ((this.getDtcomp() == castOther.getDtcomp()) || (this
						.getDtcomp() != null && castOther.getDtcomp() != null && this
						.getDtcomp().equals(castOther.getDtcomp())))
				&& ((this.getDtvenctorecpag() == castOther.getDtvenctorecpag()) || (this
						.getDtvenctorecpag() != null
						&& castOther.getDtvenctorecpag() != null && this
						.getDtvenctorecpag().equals(
								castOther.getDtvenctorecpag())))
				&& ((this.getDoc() == castOther.getDoc()) || (this.getDoc() != null
						&& castOther.getDoc() != null && this.getDoc().equals(
						castOther.getDoc())))
				&& ((this.getCodigo() == castOther.getCodigo()) || (this
						.getCodigo() != null && castOther.getCodigo() != null && this
						.getCodigo().equals(castOther.getCodigo())))
				&& ((this.getRazao() == castOther.getRazao()) || (this
						.getRazao() != null && castOther.getRazao() != null && this
						.getRazao().equals(castOther.getRazao())))
				&& ((this.getHistorico() == castOther.getHistorico()) || (this
						.getHistorico() != null
						&& castOther.getHistorico() != null && this
						.getHistorico().equals(castOther.getHistorico())))
				&& ((this.getValor() == castOther.getValor()) || (this
						.getValor() != null && castOther.getValor() != null && this
						.getValor().equals(castOther.getValor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrdem() == null ? 0 : this.getOrdem().hashCode());
		result = 37 * result
				+ (getTipolanca() == null ? 0 : this.getTipolanca().hashCode());
		result = 37 * result
				+ (getSubtipo() == null ? 0 : this.getSubtipo().hashCode());
		result = 37 * result
				+ (getCodemp() == null ? 0 : this.getCodemp().hashCode());
		result = 37 * result
				+ (getCodfilial() == null ? 0 : this.getCodfilial().hashCode());
		result = 37
				* result
				+ (getCodrecpaglanc() == null ? 0 : this.getCodrecpaglanc()
						.hashCode());
		result = 37
				* result
				+ (getNparcrecpaglanc() == null ? 0 : this.getNparcrecpaglanc()
						.hashCode());
		result = 37 * result
				+ (getDtemissao() == null ? 0 : this.getDtemissao().hashCode());
		result = 37 * result
				+ (getDtcomp() == null ? 0 : this.getDtcomp().hashCode());
		result = 37
				* result
				+ (getDtvenctorecpag() == null ? 0 : this.getDtvenctorecpag()
						.hashCode());
		result = 37 * result
				+ (getDoc() == null ? 0 : this.getDoc().hashCode());
		result = 37 * result
				+ (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result
				+ (getRazao() == null ? 0 : this.getRazao().hashCode());
		result = 37 * result
				+ (getHistorico() == null ? 0 : this.getHistorico().hashCode());
		result = 37 * result
				+ (getValor() == null ? 0 : this.getValor().hashCode());
		return result;
	}

}
