package org.freedom.persist.entity;

// Generated 30/01/2013 08:30:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lftrattrib generated by hbm2java
 */
@Entity
@Table(name = "LFTRATTRIB")
public class Lftrattrib implements java.io.Serializable {

	private LftrattribId id;
	private Sgfilial sgfilial;
	private String desctrattrib;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set<Vditvenda> vditvendas = new HashSet<Vditvenda>(0);
	private Set<Lfitclfiscal> lfitclfiscals = new HashSet<Lfitclfiscal>(0);
	private Set<Lffrete> lffretes = new HashSet<Lffrete>(0);

	public Lftrattrib() {
	}

	public Lftrattrib(LftrattribId id, Sgfilial sgfilial, String desctrattrib,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.desctrattrib = desctrattrib;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Lftrattrib(LftrattribId id, Sgfilial sgfilial, String desctrattrib,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt, Set<Vditvenda> vditvendas,
			Set<Lfitclfiscal> lfitclfiscals, Set<Lffrete> lffretes) {
		this.id = id;
		this.sgfilial = sgfilial;
		this.desctrattrib = desctrattrib;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.vditvendas = vditvendas;
		this.lfitclfiscals = lfitclfiscals;
		this.lffretes = lffretes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codtrattrib", column = @Column(name = "CODTRATTRIB", nullable = false, length = 2)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public LftrattribId getId() {
		return this.id;
	}

	public void setId(LftrattribId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Sgfilial getSgfilial() {
		return this.sgfilial;
	}

	public void setSgfilial(Sgfilial sgfilial) {
		this.sgfilial = sgfilial;
	}

	@Column(name = "DESCTRATTRIB", nullable = false, length = 60)
	public String getDesctrattrib() {
		return this.desctrattrib;
	}

	public void setDesctrattrib(String desctrattrib) {
		this.desctrattrib = desctrattrib;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lftrattrib")
	public Set<Vditvenda> getVditvendas() {
		return this.vditvendas;
	}

	public void setVditvendas(Set<Vditvenda> vditvendas) {
		this.vditvendas = vditvendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lftrattrib")
	public Set<Lfitclfiscal> getLfitclfiscals() {
		return this.lfitclfiscals;
	}

	public void setLfitclfiscals(Set<Lfitclfiscal> lfitclfiscals) {
		this.lfitclfiscals = lfitclfiscals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lftrattrib")
	public Set<Lffrete> getLffretes() {
		return this.lffretes;
	}

	public void setLffretes(Set<Lffrete> lffretes) {
		this.lffretes = lffretes;
	}

}
