package org.freedom.persist.entity;

// Generated 10/05/2014 10:27:15 by Hibernate Tools 4.0.0

/**
 * Pplistaopvw01 generated by hbm2java
 */
public class Pplistaopvw01 implements java.io.Serializable {

	private Pplistaopvw01Id id;

	public Pplistaopvw01() {
	}

	public Pplistaopvw01(Pplistaopvw01Id id) {
		this.id = id;
	}

	public Pplistaopvw01Id getId() {
		return this.id;
	}

	public void setId(Pplistaopvw01Id id) {
		this.id = id;
	}

}
