package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ppretcp generated by hbm2java
 */
@Entity
@Table(name = "PPRETCP")
public class Ppretcp implements java.io.Serializable {

	private PpretcpId id;
	private Ppop ppop;
	private Date dtretencao;
	private Date dtdescarte;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set ppitretcps = new HashSet(0);

	public Ppretcp() {
	}

	public Ppretcp(Ppop ppop, Date dtretencao, Date dtdescarte, Date dtins,
			String idusuins) {
		this.ppop = ppop;
		this.dtretencao = dtretencao;
		this.dtdescarte = dtdescarte;
		this.dtins = dtins;
		this.idusuins = idusuins;
	}

	public Ppretcp(Ppop ppop, Date dtretencao, Date dtdescarte, Date dtins,
			Date hins, String idusuins, Date dtalt, Date halt, String idusualt,
			Set ppitretcps) {
		this.ppop = ppop;
		this.dtretencao = dtretencao;
		this.dtdescarte = dtdescarte;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.ppitretcps = ppitretcps;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codop", column = @Column(name = "CODOP", nullable = false)),
			@AttributeOverride(name = "seqop", column = @Column(name = "SEQOP", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public PpretcpId getId() {
		return this.id;
	}

	public void setId(PpretcpId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Ppop getPpop() {
		return this.ppop;
	}

	public void setPpop(Ppop ppop) {
		this.ppop = ppop;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTRETENCAO", nullable = false, length = 10)
	public Date getDtretencao() {
		return this.dtretencao;
	}

	public void setDtretencao(Date dtretencao) {
		this.dtretencao = dtretencao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTDESCARTE", nullable = false, length = 10)
	public Date getDtdescarte() {
		return this.dtdescarte;
	}

	public void setDtdescarte(Date dtdescarte) {
		this.dtdescarte = dtdescarte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "ppretcp")
	public Set getPpitretcps() {
		return this.ppitretcps;
	}

	public void setPpitretcps(Set ppitretcps) {
		this.ppitretcps = ppitretcps;
	}
*/
}
