package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sgestacaobal generated by hbm2java
 */
@Entity
@Table(name = "SGESTACAOBAL")
public class Sgestacaobal implements java.io.Serializable {

	private SgestacaobalId id;
	private Sgestacao sgestacao;
	private String driverbal;
	private short portabal;
	private short speedbal;
	private short bitsbal;
	private short stopbitbal;
	private short paritybal;
	private String tipoprocrecmerc;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Sgestacaobal() {
	}

	public Sgestacaobal(SgestacaobalId id, Sgestacao sgestacao,
			String driverbal, short portabal, short speedbal, short bitsbal,
			short stopbitbal, short paritybal, String tipoprocrecmerc,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.sgestacao = sgestacao;
		this.driverbal = driverbal;
		this.portabal = portabal;
		this.speedbal = speedbal;
		this.bitsbal = bitsbal;
		this.stopbitbal = stopbitbal;
		this.paritybal = paritybal;
		this.tipoprocrecmerc = tipoprocrecmerc;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Sgestacaobal(SgestacaobalId id, Sgestacao sgestacao,
			String driverbal, short portabal, short speedbal, short bitsbal,
			short stopbitbal, short paritybal, String tipoprocrecmerc,
			Date dtins, Date hins, String idusuins, Date dtalt, Date halt,
			String idusualt) {
		this.id = id;
		this.sgestacao = sgestacao;
		this.driverbal = driverbal;
		this.portabal = portabal;
		this.speedbal = speedbal;
		this.bitsbal = bitsbal;
		this.stopbitbal = stopbitbal;
		this.paritybal = paritybal;
		this.tipoprocrecmerc = tipoprocrecmerc;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codest", column = @Column(name = "CODEST", nullable = false)),
			@AttributeOverride(name = "nrobal", column = @Column(name = "NROBAL", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public SgestacaobalId getId() {
		return this.id;
	}

	public void setId(SgestacaobalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODEST", referencedColumnName = "CODEST", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Sgestacao getSgestacao() {
		return this.sgestacao;
	}

	public void setSgestacao(Sgestacao sgestacao) {
		this.sgestacao = sgestacao;
	}

	@Column(name = "DRIVERBAL", nullable = false, length = 50)
	public String getDriverbal() {
		return this.driverbal;
	}

	public void setDriverbal(String driverbal) {
		this.driverbal = driverbal;
	}

	@Column(name = "PORTABAL", nullable = false)
	public short getPortabal() {
		return this.portabal;
	}

	public void setPortabal(short portabal) {
		this.portabal = portabal;
	}

	@Column(name = "SPEEDBAL", nullable = false)
	public short getSpeedbal() {
		return this.speedbal;
	}

	public void setSpeedbal(short speedbal) {
		this.speedbal = speedbal;
	}

	@Column(name = "BITSBAL", nullable = false)
	public short getBitsbal() {
		return this.bitsbal;
	}

	public void setBitsbal(short bitsbal) {
		this.bitsbal = bitsbal;
	}

	@Column(name = "STOPBITBAL", nullable = false)
	public short getStopbitbal() {
		return this.stopbitbal;
	}

	public void setStopbitbal(short stopbitbal) {
		this.stopbitbal = stopbitbal;
	}

	@Column(name = "PARITYBAL", nullable = false)
	public short getParitybal() {
		return this.paritybal;
	}

	public void setParitybal(short paritybal) {
		this.paritybal = paritybal;
	}

	@Column(name = "TIPOPROCRECMERC", nullable = false, length = 2)
	public String getTipoprocrecmerc() {
		return this.tipoprocrecmerc;
	}

	public void setTipoprocrecmerc(String tipoprocrecmerc) {
		this.tipoprocrecmerc = tipoprocrecmerc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
