package org.freedom.persist.entity;

// Generated 31/05/2013 12:00:37 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sgfilial generated by hbm2java
 */
@Entity
@Table(name = "SGFILIAL")
public class Sgfilial implements java.io.Serializable {

	private SgfilialId id;
	private Cpforneced cpforneced;
	private Sgunifcod sgunifcod;
	private Sgmunicipio sgmunicipio;
	private String razfilial;
	private String nomefilial;
	private char mzfilial;
	private String cnpjfilial;
	private String inscfilial;
	private String endfilial;
	private Integer numfilial;
	private String complfilial;
	private String bairfilial;
	private String cepfilial;
	private String cidfilial;
	private String uffilial;
	private String dddfilial;
	private String fonefilial;
	private String faxfilial;
	private String emailfilial;
	private String wwwfilial;
	private Integer coddistfilial;
	private BigDecimal percpisfilial;
	private BigDecimal perccofinsfilial;
	private BigDecimal percirfilial;
	private BigDecimal perccsocialfilial;
	private Character simplesfilial;
	private BigDecimal percsimplesfilial;
	private String inscmunfilial;
	private String cnaefilial;
	private BigDecimal percissfilial;
	private char contribipifilial;
	private byte[] timbrefilial;
	private Character perfilfilial;
	private Character indativfilial;
	private String indnatpjfilial;
	private String suframa;
	private Character codinctrib;
	private Character indaprocred;
	private Character codtipocont;
	private Character indregcum;
	private String unidfranqueada;
	private String marcafranqueadora;
	private String wwwfranqueadora;
	private String codreceita;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set<Vdromaneio> vdromaneios = new HashSet<Vdromaneio>(0);
	private Set<Eqserie> eqseries = new HashSet<Eqserie>(0);
	private Set<Vdtransp> vdtransps = new HashSet<Vdtransp>(0);
	private Set<Lfcsosn> lfcsosns = new HashSet<Lfcsosn>(0);
	private Set<Eqitrecmercitos> eqitrecmercitoses = new HashSet<Eqitrecmercitos>(
			0);
	private Set<Attipoatend> attipoatends = new HashSet<Attipoatend>(0);
	private Set<Vdtabpreco> vdtabprecos = new HashSet<Vdtabpreco>(0);
	private Set<Fnmoeda> fnmoedas = new HashSet<Fnmoeda>(0);
	private Set<Sggrauinst> sggrauinsts = new HashSet<Sggrauinst>(0);
	private Set<Atmodatendo> atmodatendos = new HashSet<Atmodatendo>(0);
	private Set<Eqalmoxfilial> eqalmoxfilials = new HashSet<Eqalmoxfilial>(0);
	private Set<Sgatribuicao> sgatribuicaos = new HashSet<Sgatribuicao>(0);
	private Set<Tktipocont> tktipoconts = new HashSet<Tktipocont>(0);
	private Set<Fnconta> fncontas = new HashSet<Fnconta>(0);
	private Set<Vdvendedor> vdvendedors = new HashSet<Vdvendedor>(0);
	private Set<Pprecurso> pprecursos = new HashSet<Pprecurso>(0);
	private Set<Vdregcomisdesc> vdregcomisdescs = new HashSet<Vdregcomisdesc>(0);
	private Set<Eqproduto> eqprodutos = new HashSet<Eqproduto>(0);
	private Set<Atatendimento> atatendimentos = new HashSet<Atatendimento>(0);
	private Set<Eqfatconv> eqfatconvs = new HashSet<Eqfatconv>(0);
	private Set<Lfclfiscal> lfclfiscals = new HashSet<Lfclfiscal>(0);
	private Set<Tkorigcont> tkorigconts = new HashSet<Tkorigcont>(0);
	private Set<Fnbordero> fnborderos = new HashSet<Fnbordero>(0);
	private Set<Vdsetor> vdsetors = new HashSet<Vdsetor>(0);
	private Set<Cptipofor> cptipofors = new HashSet<Cptipofor>(0);
	private Set<Fnlanca> fnlancas = new HashSet<Fnlanca>(0);
	private Set<Eqtipoexp> eqtipoexps = new HashSet<Eqtipoexp>(0);
	private Set<Fnplanopag> fnplanopags = new HashSet<Fnplanopag>(0);
	private Set<Lflivrofiscal> lflivrofiscals = new HashSet<Lflivrofiscal>(0);
	private Set<Lfsittrib> lfsittribs = new HashSet<Lfsittrib>(0);
	private Set<Sgconexao> sgconexaos = new HashSet<Sgconexao>(0);
	private Set<Cpsolicitacao> cpsolicitacaos = new HashSet<Cpsolicitacao>(0);
	private Set<Atencaminhador> atencaminhadors = new HashSet<Atencaminhador>(0);
	private Set<Ppestrufase> ppestrufases = new HashSet<Ppestrufase>(0);
	private Set<Cpforneced> cpforneceds = new HashSet<Cpforneced>(0);
	private Set<Ppfase> ppfases = new HashSet<Ppfase>(0);
	private Set<Sgsequencia> sgsequencias = new HashSet<Sgsequencia>(0);
	private Set<Sggrpusu> sggrpusus = new HashSet<Sggrpusu>(0);
	private Set<Sgusuario> sgusuarios = new HashSet<Sgusuario>(0);
	private Set<Sgacessomg> sgacessomgs = new HashSet<Sgacessomg>(0);
	private Set<Sgacessomu> sgacessomus = new HashSet<Sgacessomu>(0);
	private Set<Eqrecmerc> eqrecmercs = new HashSet<Eqrecmerc>(0);
	private Set<Eqprocrecmerc> eqprocrecmercs = new HashSet<Eqprocrecmerc>(0);
	private Sgprefere4 sgprefere4;
	private Set<Vdcliente> vdclientes = new HashSet<Vdcliente>(0);
	private Set<Fnpagar> fnpagars = new HashSet<Fnpagar>(0);
	private Set<Vdclascli> vdclasclis = new HashSet<Vdclascli>(0);
	private Set<Atclasatendo> atclasatendos = new HashSet<Atclasatendo>(0);
	private Set<Crmotivofb> crmotivofbs = new HashSet<Crmotivofb>(0);
	private Set<Attipoconv> attipoconvs = new HashSet<Attipoconv>(0);
	private Set<Fntbjuros> fntbjuroses = new HashSet<Fntbjuros>(0);
	private Set<Lfmodnota> lfmodnotas = new HashSet<Lfmodnota>(0);
	private Set<Eqtipomov> eqtipomovs = new HashSet<Eqtipomov>(0);
	private Set<Eqtiporecmerc> eqtiporecmercs = new HashSet<Eqtiporecmerc>(0);
	private Set<Eqalmox> eqalmoxes = new HashSet<Eqalmox>(0);
	private Set<Sgpapel> sgpapels = new HashSet<Sgpapel>(0);
	private Set<Crfeedback> crfeedbacks = new HashSet<Crfeedback>(0);
	private Set<Fnplanejamento> fnplanejamentos = new HashSet<Fnplanejamento>(0);
	private Set<Lfnatoper> lfnatopers = new HashSet<Lfnatoper>(0);
	private Set<Rhcurso> rhcursos = new HashSet<Rhcurso>(0);
	private Set<Fnlibcred> fnlibcreds = new HashSet<Fnlibcred>(0);
	private Set<Sgimpressora> sgimpressoras = new HashSet<Sgimpressora>(0);
	private Set<Rhnivelcurso> rhnivelcursos = new HashSet<Rhnivelcurso>(0);
	private Set<Eqmodgrade> eqmodgrades = new HashSet<Eqmodgrade>(0);
	private Set<Eqlocdescarga> eqlocdescargas = new HashSet<Eqlocdescarga>(0);
	private Set<Sgtabela> sgtabelas = new HashSet<Sgtabela>(0);
	private Set<Fncc> fnccs = new HashSet<Fncc>(0);
	private Set<Rharea> rhareas = new HashSet<Rharea>(0);
	private Set<Sgcatimg> sgcatimgs = new HashSet<Sgcatimg>(0);
	private Set<Vdvenda> vdvendas = new HashSet<Vdvenda>(0);
	private Set<Eqlanctoexp> eqlanctoexps = new HashSet<Eqlanctoexp>(0);
	private Set<Atconveniado> atconveniados = new HashSet<Atconveniado>(0);
	private Sgprefere5 sgprefere5;
	private Set<Eqinvprod> eqinvprods = new HashSet<Eqinvprod>(0);
	private Set<Lftrattrib> lftrattribs = new HashSet<Lftrattrib>(0);
	private Set<Fnsaldolanca> fnsaldolancas = new HashSet<Fnsaldolanca>(0);
	private Set<Equnidade> equnidades = new HashSet<Equnidade>(0);
	private Set<Fnreceber> fnrecebers = new HashSet<Fnreceber>(0);
	private Set<Fnbanco> fnbancos = new HashSet<Fnbanco>(0);
	private Set<Eqmovexp> eqmovexps = new HashSet<Eqmovexp>(0);
	private Set<Vdcomissao> vdcomissaos = new HashSet<Vdcomissao>(0);
	private Sgprefere1 sgprefere1;
	private Set<Eqgrupo> eqgrupos = new HashSet<Eqgrupo>(0);
	private Set<Eqmovserie> eqmovseries = new HashSet<Eqmovserie>(0);
	private Set<Sgacessoeu> sgacessoeus = new HashSet<Sgacessoeu>(0);
	private Set<Atatendente> atatendentes = new HashSet<Atatendente>(0);
	private Set<Rhcaracteristica> rhcaracteristicas = new HashSet<Rhcaracteristica>(
			0);
	private Set<Rhcandidato> rhcandidatos = new HashSet<Rhcandidato>(0);
	private Set<Sgestcivil> sgestcivils = new HashSet<Sgestcivil>(0);
	private Set<Cpcompra> cpcompras = new HashSet<Cpcompra>(0);
	private Set<Rhempregador> rhempregadors = new HashSet<Rhempregador>(0);
	private Set<Lfserie> lfseries = new HashSet<Lfserie>(0);
	private Set<Vdtipocli> vdtipoclis = new HashSet<Vdtipocli>(0);
	private Set<Attipoatendo> attipoatendos = new HashSet<Attipoatendo>(0);
	private Set<Lfregrafiscal> lfregrafiscals = new HashSet<Lfregrafiscal>(0);
	private Set<Eqmarca> eqmarcas = new HashSet<Eqmarca>(0);
	private Set<Eqlote> eqlotes = new HashSet<Eqlote>(0);
	private Set<Vdgruporc> vdgruporcs = new HashSet<Vdgruporc>(0);
	private Set<Fncotmoeda> fncotmoedas = new HashSet<Fncotmoeda>(0);
	private Set<Eqtipoexpedicao> eqtipoexpedicaos = new HashSet<Eqtipoexpedicao>(
			0);
	private Set<Eqitrecmerc> eqitrecmercs = new HashSet<Eqitrecmerc>(0);
	private Set<Eqvargrade> eqvargrades = new HashSet<Eqvargrade>(0);
	private Set<Atatribuicao> atatribuicaos = new HashSet<Atatribuicao>(0);
	private Set<Fntipocob> fntipocobs = new HashSet<Fntipocob>(0);
	private Set<Atsetor> atsetors = new HashSet<Atsetor>(0);
	private Set<Eqmovprod> eqmovprods = new HashSet<Eqmovprod>(0);
	private Set<Pptiporec> pptiporecs = new HashSet<Pptiporec>(0);
	private Set<Lfmoddocfisc> lfmoddocfiscs = new HashSet<Lfmoddocfisc>(0);
	private Set<Fnpagtocomi> fnpagtocomis = new HashSet<Fnpagtocomi>(0);
	private Set<Necontingencia> necontingencias = new HashSet<Necontingencia>(0);

	public Sgfilial() {
	}

	public Sgfilial(SgfilialId id, String razfilial, String nomefilial,
			char mzfilial, char contribipifilial, Date dtins, Date hins,
			String idusuins) {
		this.id = id;
		this.razfilial = razfilial;
		this.nomefilial = nomefilial;
		this.mzfilial = mzfilial;
		this.contribipifilial = contribipifilial;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Sgfilial(SgfilialId id, Cpforneced cpforneced, Sgunifcod sgunifcod,
			Sgmunicipio sgmunicipio, String razfilial, String nomefilial,
			char mzfilial, String cnpjfilial, String inscfilial,
			String endfilial, Integer numfilial, String complfilial,
			String bairfilial, String cepfilial, String cidfilial,
			String uffilial, String dddfilial, String fonefilial,
			String faxfilial, String emailfilial, String wwwfilial,
			Integer coddistfilial, BigDecimal percpisfilial,
			BigDecimal perccofinsfilial, BigDecimal percirfilial,
			BigDecimal perccsocialfilial, Character simplesfilial,
			BigDecimal percsimplesfilial, String inscmunfilial,
			String cnaefilial, BigDecimal percissfilial, char contribipifilial,
			byte[] timbrefilial, Character perfilfilial,
			Character indativfilial, String indnatpjfilial, String suframa,
			Character codinctrib, Character indaprocred, Character codtipocont,
			Character indregcum, String unidfranqueada,
			String marcafranqueadora, String wwwfranqueadora,
			String codreceita, Date dtins, Date hins, String idusuins,
			Date dtalt, Date halt, String idusualt,
			Set<Vdromaneio> vdromaneios, Set<Eqserie> eqseries,
			Set<Vdtransp> vdtransps, Set<Lfcsosn> lfcsosns,
			Set<Eqitrecmercitos> eqitrecmercitoses,
			Set<Attipoatend> attipoatends, Set<Vdtabpreco> vdtabprecos,
			Set<Fnmoeda> fnmoedas, Set<Sggrauinst> sggrauinsts,
			Set<Atmodatendo> atmodatendos, Set<Eqalmoxfilial> eqalmoxfilials,
			Set<Sgatribuicao> sgatribuicaos, Set<Tktipocont> tktipoconts,
			Set<Fnconta> fncontas, Set<Vdvendedor> vdvendedors,
			Set<Pprecurso> pprecursos, Set<Vdregcomisdesc> vdregcomisdescs,
			Set<Eqproduto> eqprodutos, Set<Atatendimento> atatendimentos,
			Set<Eqfatconv> eqfatconvs, Set<Lfclfiscal> lfclfiscals,
			Set<Tkorigcont> tkorigconts, Set<Fnbordero> fnborderos,
			Set<Vdsetor> vdsetors, Set<Cptipofor> cptipofors,
			Set<Fnlanca> fnlancas, Set<Eqtipoexp> eqtipoexps,
			Set<Fnplanopag> fnplanopags, Set<Lflivrofiscal> lflivrofiscals,
			Set<Lfsittrib> lfsittribs, Set<Sgconexao> sgconexaos,
			Set<Cpsolicitacao> cpsolicitacaos,
			Set<Atencaminhador> atencaminhadors, Set<Ppestrufase> ppestrufases,
			Set<Cpforneced> cpforneceds, Set<Ppfase> ppfases,
			Set<Sgsequencia> sgsequencias, Set<Sggrpusu> sggrpusus,
			Set<Sgusuario> sgusuarios, Set<Sgacessomg> sgacessomgs,
			Set<Sgacessomu> sgacessomus, Set<Eqrecmerc> eqrecmercs,
			Set<Eqprocrecmerc> eqprocrecmercs, Sgprefere4 sgprefere4,
			Set<Vdcliente> vdclientes, Set<Fnpagar> fnpagars,
			Set<Vdclascli> vdclasclis, Set<Atclasatendo> atclasatendos,
			Set<Crmotivofb> crmotivofbs, Set<Attipoconv> attipoconvs,
			Set<Fntbjuros> fntbjuroses, Set<Lfmodnota> lfmodnotas,
			Set<Eqtipomov> eqtipomovs, Set<Eqtiporecmerc> eqtiporecmercs,
			Set<Eqalmox> eqalmoxes, Set<Sgpapel> sgpapels,
			Set<Crfeedback> crfeedbacks, Set<Fnplanejamento> fnplanejamentos,
			Set<Lfnatoper> lfnatopers, Set<Rhcurso> rhcursos,
			Set<Fnlibcred> fnlibcreds, Set<Sgimpressora> sgimpressoras,
			Set<Rhnivelcurso> rhnivelcursos, Set<Eqmodgrade> eqmodgrades,
			Set<Eqlocdescarga> eqlocdescargas, Set<Sgtabela> sgtabelas,
			Set<Fncc> fnccs, Set<Rharea> rhareas, Set<Sgcatimg> sgcatimgs,
			Set<Vdvenda> vdvendas, Set<Eqlanctoexp> eqlanctoexps,
			Set<Atconveniado> atconveniados, Sgprefere5 sgprefere5,
			Set<Eqinvprod> eqinvprods, Set<Lftrattrib> lftrattribs,
			Set<Fnsaldolanca> fnsaldolancas, Set<Equnidade> equnidades,
			Set<Fnreceber> fnrecebers, Set<Fnbanco> fnbancos,
			Set<Eqmovexp> eqmovexps, Set<Vdcomissao> vdcomissaos,
			Sgprefere1 sgprefere1, Set<Eqgrupo> eqgrupos,
			Set<Eqmovserie> eqmovseries, Set<Sgacessoeu> sgacessoeus,
			Set<Atatendente> atatendentes,
			Set<Rhcaracteristica> rhcaracteristicas,
			Set<Rhcandidato> rhcandidatos, Set<Sgestcivil> sgestcivils,
			Set<Cpcompra> cpcompras, Set<Rhempregador> rhempregadors,
			Set<Lfserie> lfseries, Set<Vdtipocli> vdtipoclis,
			Set<Attipoatendo> attipoatendos, Set<Lfregrafiscal> lfregrafiscals,
			Set<Eqmarca> eqmarcas, Set<Eqlote> eqlotes,
			Set<Vdgruporc> vdgruporcs, Set<Fncotmoeda> fncotmoedas,
			Set<Eqtipoexpedicao> eqtipoexpedicaos,
			Set<Eqitrecmerc> eqitrecmercs, Set<Eqvargrade> eqvargrades,
			Set<Atatribuicao> atatribuicaos, Set<Fntipocob> fntipocobs,
			Set<Atsetor> atsetors, Set<Eqmovprod> eqmovprods,
			Set<Pptiporec> pptiporecs, Set<Lfmoddocfisc> lfmoddocfiscs,
			Set<Fnpagtocomi> fnpagtocomis, Set<Necontingencia> necontingencias) {
		this.id = id;
		this.cpforneced = cpforneced;
		this.sgunifcod = sgunifcod;
		this.sgmunicipio = sgmunicipio;
		this.razfilial = razfilial;
		this.nomefilial = nomefilial;
		this.mzfilial = mzfilial;
		this.cnpjfilial = cnpjfilial;
		this.inscfilial = inscfilial;
		this.endfilial = endfilial;
		this.numfilial = numfilial;
		this.complfilial = complfilial;
		this.bairfilial = bairfilial;
		this.cepfilial = cepfilial;
		this.cidfilial = cidfilial;
		this.uffilial = uffilial;
		this.dddfilial = dddfilial;
		this.fonefilial = fonefilial;
		this.faxfilial = faxfilial;
		this.emailfilial = emailfilial;
		this.wwwfilial = wwwfilial;
		this.coddistfilial = coddistfilial;
		this.percpisfilial = percpisfilial;
		this.perccofinsfilial = perccofinsfilial;
		this.percirfilial = percirfilial;
		this.perccsocialfilial = perccsocialfilial;
		this.simplesfilial = simplesfilial;
		this.percsimplesfilial = percsimplesfilial;
		this.inscmunfilial = inscmunfilial;
		this.cnaefilial = cnaefilial;
		this.percissfilial = percissfilial;
		this.contribipifilial = contribipifilial;
		this.timbrefilial = timbrefilial;
		this.perfilfilial = perfilfilial;
		this.indativfilial = indativfilial;
		this.indnatpjfilial = indnatpjfilial;
		this.suframa = suframa;
		this.codinctrib = codinctrib;
		this.indaprocred = indaprocred;
		this.codtipocont = codtipocont;
		this.indregcum = indregcum;
		this.unidfranqueada = unidfranqueada;
		this.marcafranqueadora = marcafranqueadora;
		this.wwwfranqueadora = wwwfranqueadora;
		this.codreceita = codreceita;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.vdromaneios = vdromaneios;
		this.eqseries = eqseries;
		this.vdtransps = vdtransps;
		this.lfcsosns = lfcsosns;
		this.eqitrecmercitoses = eqitrecmercitoses;
		this.attipoatends = attipoatends;
		this.vdtabprecos = vdtabprecos;
		this.fnmoedas = fnmoedas;
		this.sggrauinsts = sggrauinsts;
		this.atmodatendos = atmodatendos;
		this.eqalmoxfilials = eqalmoxfilials;
		this.sgatribuicaos = sgatribuicaos;
		this.tktipoconts = tktipoconts;
		this.fncontas = fncontas;
		this.vdvendedors = vdvendedors;
		this.pprecursos = pprecursos;
		this.vdregcomisdescs = vdregcomisdescs;
		this.eqprodutos = eqprodutos;
		this.atatendimentos = atatendimentos;
		this.eqfatconvs = eqfatconvs;
		this.lfclfiscals = lfclfiscals;
		this.tkorigconts = tkorigconts;
		this.fnborderos = fnborderos;
		this.vdsetors = vdsetors;
		this.cptipofors = cptipofors;
		this.fnlancas = fnlancas;
		this.eqtipoexps = eqtipoexps;
		this.fnplanopags = fnplanopags;
		this.lflivrofiscals = lflivrofiscals;
		this.lfsittribs = lfsittribs;
		this.sgconexaos = sgconexaos;
		this.cpsolicitacaos = cpsolicitacaos;
		this.atencaminhadors = atencaminhadors;
		this.ppestrufases = ppestrufases;
		this.cpforneceds = cpforneceds;
		this.ppfases = ppfases;
		this.sgsequencias = sgsequencias;
		this.sggrpusus = sggrpusus;
		this.sgusuarios = sgusuarios;
		this.sgacessomgs = sgacessomgs;
		this.sgacessomus = sgacessomus;
		this.eqrecmercs = eqrecmercs;
		this.eqprocrecmercs = eqprocrecmercs;
		this.sgprefere4 = sgprefere4;
		this.vdclientes = vdclientes;
		this.fnpagars = fnpagars;
		this.vdclasclis = vdclasclis;
		this.atclasatendos = atclasatendos;
		this.crmotivofbs = crmotivofbs;
		this.attipoconvs = attipoconvs;
		this.fntbjuroses = fntbjuroses;
		this.lfmodnotas = lfmodnotas;
		this.eqtipomovs = eqtipomovs;
		this.eqtiporecmercs = eqtiporecmercs;
		this.eqalmoxes = eqalmoxes;
		this.sgpapels = sgpapels;
		this.crfeedbacks = crfeedbacks;
		this.fnplanejamentos = fnplanejamentos;
		this.lfnatopers = lfnatopers;
		this.rhcursos = rhcursos;
		this.fnlibcreds = fnlibcreds;
		this.sgimpressoras = sgimpressoras;
		this.rhnivelcursos = rhnivelcursos;
		this.eqmodgrades = eqmodgrades;
		this.eqlocdescargas = eqlocdescargas;
		this.sgtabelas = sgtabelas;
		this.fnccs = fnccs;
		this.rhareas = rhareas;
		this.sgcatimgs = sgcatimgs;
		this.vdvendas = vdvendas;
		this.eqlanctoexps = eqlanctoexps;
		this.atconveniados = atconveniados;
		this.sgprefere5 = sgprefere5;
		this.eqinvprods = eqinvprods;
		this.lftrattribs = lftrattribs;
		this.fnsaldolancas = fnsaldolancas;
		this.equnidades = equnidades;
		this.fnrecebers = fnrecebers;
		this.fnbancos = fnbancos;
		this.eqmovexps = eqmovexps;
		this.vdcomissaos = vdcomissaos;
		this.sgprefere1 = sgprefere1;
		this.eqgrupos = eqgrupos;
		this.eqmovseries = eqmovseries;
		this.sgacessoeus = sgacessoeus;
		this.atatendentes = atatendentes;
		this.rhcaracteristicas = rhcaracteristicas;
		this.rhcandidatos = rhcandidatos;
		this.sgestcivils = sgestcivils;
		this.cpcompras = cpcompras;
		this.rhempregadors = rhempregadors;
		this.lfseries = lfseries;
		this.vdtipoclis = vdtipoclis;
		this.attipoatendos = attipoatendos;
		this.lfregrafiscals = lfregrafiscals;
		this.eqmarcas = eqmarcas;
		this.eqlotes = eqlotes;
		this.vdgruporcs = vdgruporcs;
		this.fncotmoedas = fncotmoedas;
		this.eqtipoexpedicaos = eqtipoexpedicaos;
		this.eqitrecmercs = eqitrecmercs;
		this.eqvargrades = eqvargrades;
		this.atatribuicaos = atatribuicaos;
		this.fntipocobs = fntipocobs;
		this.atsetors = atsetors;
		this.eqmovprods = eqmovprods;
		this.pptiporecs = pptiporecs;
		this.lfmoddocfiscs = lfmoddocfiscs;
		this.fnpagtocomis = fnpagtocomis;
		this.necontingencias = necontingencias;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public SgfilialId getId() {
		return this.id;
	}

	public void setId(SgfilialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODFOR", referencedColumnName = "CODFOR"),
			@JoinColumn(name = "CODFILIALCO", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPCO", referencedColumnName = "CODEMP") })
	public Cpforneced getCpforneced() {
		return this.cpforneced;
	}

	public void setCpforneced(Cpforneced cpforneced) {
		this.cpforneced = cpforneced;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODUNIFCOD", referencedColumnName = "CODUNIFCOD"),
			@JoinColumn(name = "CODFILIALUC", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPUC", referencedColumnName = "CODEMP") })
	public Sgunifcod getSgunifcod() {
		return this.sgunifcod;
	}

	public void setSgunifcod(Sgunifcod sgunifcod) {
		this.sgunifcod = sgunifcod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODMUNIC", referencedColumnName = "CODMUNIC"),
			@JoinColumn(name = "SIGLAUF", referencedColumnName = "SIGLAUF"),
			@JoinColumn(name = "CODPAIS", referencedColumnName = "CODPAIS") })
	public Sgmunicipio getSgmunicipio() {
		return this.sgmunicipio;
	}

	public void setSgmunicipio(Sgmunicipio sgmunicipio) {
		this.sgmunicipio = sgmunicipio;
	}

	@Column(name = "RAZFILIAL", nullable = false, length = 50)
	public String getRazfilial() {
		return this.razfilial;
	}

	public void setRazfilial(String razfilial) {
		this.razfilial = razfilial;
	}

	@Column(name = "NOMEFILIAL", nullable = false, length = 50)
	public String getNomefilial() {
		return this.nomefilial;
	}

	public void setNomefilial(String nomefilial) {
		this.nomefilial = nomefilial;
	}

	@Column(name = "MZFILIAL", nullable = false, length = 1)
	public char getMzfilial() {
		return this.mzfilial;
	}

	public void setMzfilial(char mzfilial) {
		this.mzfilial = mzfilial;
	}

	@Column(name = "CNPJFILIAL", length = 14)
	public String getCnpjfilial() {
		return this.cnpjfilial;
	}

	public void setCnpjfilial(String cnpjfilial) {
		this.cnpjfilial = cnpjfilial;
	}

	@Column(name = "INSCFILIAL", length = 20)
	public String getInscfilial() {
		return this.inscfilial;
	}

	public void setInscfilial(String inscfilial) {
		this.inscfilial = inscfilial;
	}

	@Column(name = "ENDFILIAL", length = 50)
	public String getEndfilial() {
		return this.endfilial;
	}

	public void setEndfilial(String endfilial) {
		this.endfilial = endfilial;
	}

	@Column(name = "NUMFILIAL")
	public Integer getNumfilial() {
		return this.numfilial;
	}

	public void setNumfilial(Integer numfilial) {
		this.numfilial = numfilial;
	}

	@Column(name = "COMPLFILIAL", length = 20)
	public String getComplfilial() {
		return this.complfilial;
	}

	public void setComplfilial(String complfilial) {
		this.complfilial = complfilial;
	}

	@Column(name = "BAIRFILIAL", length = 30)
	public String getBairfilial() {
		return this.bairfilial;
	}

	public void setBairfilial(String bairfilial) {
		this.bairfilial = bairfilial;
	}

	@Column(name = "CEPFILIAL", length = 8)
	public String getCepfilial() {
		return this.cepfilial;
	}

	public void setCepfilial(String cepfilial) {
		this.cepfilial = cepfilial;
	}

	@Column(name = "CIDFILIAL", length = 30)
	public String getCidfilial() {
		return this.cidfilial;
	}

	public void setCidfilial(String cidfilial) {
		this.cidfilial = cidfilial;
	}

	@Column(name = "UFFILIAL", length = 2)
	public String getUffilial() {
		return this.uffilial;
	}

	public void setUffilial(String uffilial) {
		this.uffilial = uffilial;
	}

	@Column(name = "DDDFILIAL", length = 4)
	public String getDddfilial() {
		return this.dddfilial;
	}

	public void setDddfilial(String dddfilial) {
		this.dddfilial = dddfilial;
	}

	@Column(name = "FONEFILIAL", length = 12)
	public String getFonefilial() {
		return this.fonefilial;
	}

	public void setFonefilial(String fonefilial) {
		this.fonefilial = fonefilial;
	}

	@Column(name = "FAXFILIAL", length = 9)
	public String getFaxfilial() {
		return this.faxfilial;
	}

	public void setFaxfilial(String faxfilial) {
		this.faxfilial = faxfilial;
	}

	@Column(name = "EMAILFILIAL", length = 50)
	public String getEmailfilial() {
		return this.emailfilial;
	}

	public void setEmailfilial(String emailfilial) {
		this.emailfilial = emailfilial;
	}

	@Column(name = "WWWFILIAL", length = 50)
	public String getWwwfilial() {
		return this.wwwfilial;
	}

	public void setWwwfilial(String wwwfilial) {
		this.wwwfilial = wwwfilial;
	}

	@Column(name = "CODDISTFILIAL")
	public Integer getCoddistfilial() {
		return this.coddistfilial;
	}

	public void setCoddistfilial(Integer coddistfilial) {
		this.coddistfilial = coddistfilial;
	}

	@Column(name = "PERCPISFILIAL", precision = 5)
	public BigDecimal getPercpisfilial() {
		return this.percpisfilial;
	}

	public void setPercpisfilial(BigDecimal percpisfilial) {
		this.percpisfilial = percpisfilial;
	}

	@Column(name = "PERCCOFINSFILIAL", precision = 5)
	public BigDecimal getPerccofinsfilial() {
		return this.perccofinsfilial;
	}

	public void setPerccofinsfilial(BigDecimal perccofinsfilial) {
		this.perccofinsfilial = perccofinsfilial;
	}

	@Column(name = "PERCIRFILIAL", precision = 5)
	public BigDecimal getPercirfilial() {
		return this.percirfilial;
	}

	public void setPercirfilial(BigDecimal percirfilial) {
		this.percirfilial = percirfilial;
	}

	@Column(name = "PERCCSOCIALFILIAL", precision = 5)
	public BigDecimal getPerccsocialfilial() {
		return this.perccsocialfilial;
	}

	public void setPerccsocialfilial(BigDecimal perccsocialfilial) {
		this.perccsocialfilial = perccsocialfilial;
	}

	@Column(name = "SIMPLESFILIAL", length = 1)
	public Character getSimplesfilial() {
		return this.simplesfilial;
	}

	public void setSimplesfilial(Character simplesfilial) {
		this.simplesfilial = simplesfilial;
	}

	@Column(name = "PERCSIMPLESFILIAL", precision = 9)
	public BigDecimal getPercsimplesfilial() {
		return this.percsimplesfilial;
	}

	public void setPercsimplesfilial(BigDecimal percsimplesfilial) {
		this.percsimplesfilial = percsimplesfilial;
	}

	@Column(name = "INSCMUNFILIAL", length = 15)
	public String getInscmunfilial() {
		return this.inscmunfilial;
	}

	public void setInscmunfilial(String inscmunfilial) {
		this.inscmunfilial = inscmunfilial;
	}

	@Column(name = "CNAEFILIAL", length = 7)
	public String getCnaefilial() {
		return this.cnaefilial;
	}

	public void setCnaefilial(String cnaefilial) {
		this.cnaefilial = cnaefilial;
	}

	@Column(name = "PERCISSFILIAL", precision = 5)
	public BigDecimal getPercissfilial() {
		return this.percissfilial;
	}

	public void setPercissfilial(BigDecimal percissfilial) {
		this.percissfilial = percissfilial;
	}

	@Column(name = "CONTRIBIPIFILIAL", nullable = false, length = 1)
	public char getContribipifilial() {
		return this.contribipifilial;
	}

	public void setContribipifilial(char contribipifilial) {
		this.contribipifilial = contribipifilial;
	}

	@Column(name = "TIMBREFILIAL")
	public byte[] getTimbrefilial() {
		return this.timbrefilial;
	}

	public void setTimbrefilial(byte[] timbrefilial) {
		this.timbrefilial = timbrefilial;
	}

	@Column(name = "PERFILFILIAL", length = 1)
	public Character getPerfilfilial() {
		return this.perfilfilial;
	}

	public void setPerfilfilial(Character perfilfilial) {
		this.perfilfilial = perfilfilial;
	}

	@Column(name = "INDATIVFILIAL", length = 1)
	public Character getIndativfilial() {
		return this.indativfilial;
	}

	public void setIndativfilial(Character indativfilial) {
		this.indativfilial = indativfilial;
	}

	@Column(name = "INDNATPJFILIAL", length = 2)
	public String getIndnatpjfilial() {
		return this.indnatpjfilial;
	}

	public void setIndnatpjfilial(String indnatpjfilial) {
		this.indnatpjfilial = indnatpjfilial;
	}

	@Column(name = "SUFRAMA", length = 9)
	public String getSuframa() {
		return this.suframa;
	}

	public void setSuframa(String suframa) {
		this.suframa = suframa;
	}

	@Column(name = "CODINCTRIB", length = 1)
	public Character getCodinctrib() {
		return this.codinctrib;
	}

	public void setCodinctrib(Character codinctrib) {
		this.codinctrib = codinctrib;
	}

	@Column(name = "INDAPROCRED", length = 1)
	public Character getIndaprocred() {
		return this.indaprocred;
	}

	public void setIndaprocred(Character indaprocred) {
		this.indaprocred = indaprocred;
	}

	@Column(name = "CODTIPOCONT", length = 1)
	public Character getCodtipocont() {
		return this.codtipocont;
	}

	public void setCodtipocont(Character codtipocont) {
		this.codtipocont = codtipocont;
	}

	@Column(name = "INDREGCUM", length = 1)
	public Character getIndregcum() {
		return this.indregcum;
	}

	public void setIndregcum(Character indregcum) {
		this.indregcum = indregcum;
	}

	@Column(name = "UNIDFRANQUEADA", length = 30)
	public String getUnidfranqueada() {
		return this.unidfranqueada;
	}

	public void setUnidfranqueada(String unidfranqueada) {
		this.unidfranqueada = unidfranqueada;
	}

	@Column(name = "MARCAFRANQUEADORA", length = 30)
	public String getMarcafranqueadora() {
		return this.marcafranqueadora;
	}

	public void setMarcafranqueadora(String marcafranqueadora) {
		this.marcafranqueadora = marcafranqueadora;
	}

	@Column(name = "WWWFRANQUEADORA", length = 50)
	public String getWwwfranqueadora() {
		return this.wwwfranqueadora;
	}

	public void setWwwfranqueadora(String wwwfranqueadora) {
		this.wwwfranqueadora = wwwfranqueadora;
	}

	@Column(name = "CODRECEITA", length = 20)
	public String getCodreceita() {
		return this.codreceita;
	}

	public void setCodreceita(String codreceita) {
		this.codreceita = codreceita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdromaneio> getVdromaneios() {
		return this.vdromaneios;
	}

	public void setVdromaneios(Set<Vdromaneio> vdromaneios) {
		this.vdromaneios = vdromaneios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqserie> getEqseries() {
		return this.eqseries;
	}

	public void setEqseries(Set<Eqserie> eqseries) {
		this.eqseries = eqseries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdtransp> getVdtransps() {
		return this.vdtransps;
	}

	public void setVdtransps(Set<Vdtransp> vdtransps) {
		this.vdtransps = vdtransps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfcsosn> getLfcsosns() {
		return this.lfcsosns;
	}

	public void setLfcsosns(Set<Lfcsosn> lfcsosns) {
		this.lfcsosns = lfcsosns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqitrecmercitos> getEqitrecmercitoses() {
		return this.eqitrecmercitoses;
	}

	public void setEqitrecmercitoses(Set<Eqitrecmercitos> eqitrecmercitoses) {
		this.eqitrecmercitoses = eqitrecmercitoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Attipoatend> getAttipoatends() {
		return this.attipoatends;
	}

	public void setAttipoatends(Set<Attipoatend> attipoatends) {
		this.attipoatends = attipoatends;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdtabpreco> getVdtabprecos() {
		return this.vdtabprecos;
	}

	public void setVdtabprecos(Set<Vdtabpreco> vdtabprecos) {
		this.vdtabprecos = vdtabprecos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnmoeda> getFnmoedas() {
		return this.fnmoedas;
	}

	public void setFnmoedas(Set<Fnmoeda> fnmoedas) {
		this.fnmoedas = fnmoedas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sggrauinst> getSggrauinsts() {
		return this.sggrauinsts;
	}

	public void setSggrauinsts(Set<Sggrauinst> sggrauinsts) {
		this.sggrauinsts = sggrauinsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atmodatendo> getAtmodatendos() {
		return this.atmodatendos;
	}

	public void setAtmodatendos(Set<Atmodatendo> atmodatendos) {
		this.atmodatendos = atmodatendos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqalmoxfilial> getEqalmoxfilials() {
		return this.eqalmoxfilials;
	}

	public void setEqalmoxfilials(Set<Eqalmoxfilial> eqalmoxfilials) {
		this.eqalmoxfilials = eqalmoxfilials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgatribuicao> getSgatribuicaos() {
		return this.sgatribuicaos;
	}

	public void setSgatribuicaos(Set<Sgatribuicao> sgatribuicaos) {
		this.sgatribuicaos = sgatribuicaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Tktipocont> getTktipoconts() {
		return this.tktipoconts;
	}

	public void setTktipoconts(Set<Tktipocont> tktipoconts) {
		this.tktipoconts = tktipoconts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnconta> getFncontas() {
		return this.fncontas;
	}

	public void setFncontas(Set<Fnconta> fncontas) {
		this.fncontas = fncontas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdvendedor> getVdvendedors() {
		return this.vdvendedors;
	}

	public void setVdvendedors(Set<Vdvendedor> vdvendedors) {
		this.vdvendedors = vdvendedors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Pprecurso> getPprecursos() {
		return this.pprecursos;
	}

	public void setPprecursos(Set<Pprecurso> pprecursos) {
		this.pprecursos = pprecursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdregcomisdesc> getVdregcomisdescs() {
		return this.vdregcomisdescs;
	}

	public void setVdregcomisdescs(Set<Vdregcomisdesc> vdregcomisdescs) {
		this.vdregcomisdescs = vdregcomisdescs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqproduto> getEqprodutos() {
		return this.eqprodutos;
	}

	public void setEqprodutos(Set<Eqproduto> eqprodutos) {
		this.eqprodutos = eqprodutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atatendimento> getAtatendimentos() {
		return this.atatendimentos;
	}

	public void setAtatendimentos(Set<Atatendimento> atatendimentos) {
		this.atatendimentos = atatendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqfatconv> getEqfatconvs() {
		return this.eqfatconvs;
	}

	public void setEqfatconvs(Set<Eqfatconv> eqfatconvs) {
		this.eqfatconvs = eqfatconvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfclfiscal> getLfclfiscals() {
		return this.lfclfiscals;
	}

	public void setLfclfiscals(Set<Lfclfiscal> lfclfiscals) {
		this.lfclfiscals = lfclfiscals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Tkorigcont> getTkorigconts() {
		return this.tkorigconts;
	}

	public void setTkorigconts(Set<Tkorigcont> tkorigconts) {
		this.tkorigconts = tkorigconts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnbordero> getFnborderos() {
		return this.fnborderos;
	}

	public void setFnborderos(Set<Fnbordero> fnborderos) {
		this.fnborderos = fnborderos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdsetor> getVdsetors() {
		return this.vdsetors;
	}

	public void setVdsetors(Set<Vdsetor> vdsetors) {
		this.vdsetors = vdsetors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Cptipofor> getCptipofors() {
		return this.cptipofors;
	}

	public void setCptipofors(Set<Cptipofor> cptipofors) {
		this.cptipofors = cptipofors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnlanca> getFnlancas() {
		return this.fnlancas;
	}

	public void setFnlancas(Set<Fnlanca> fnlancas) {
		this.fnlancas = fnlancas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqtipoexp> getEqtipoexps() {
		return this.eqtipoexps;
	}

	public void setEqtipoexps(Set<Eqtipoexp> eqtipoexps) {
		this.eqtipoexps = eqtipoexps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnplanopag> getFnplanopags() {
		return this.fnplanopags;
	}

	public void setFnplanopags(Set<Fnplanopag> fnplanopags) {
		this.fnplanopags = fnplanopags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lflivrofiscal> getLflivrofiscals() {
		return this.lflivrofiscals;
	}

	public void setLflivrofiscals(Set<Lflivrofiscal> lflivrofiscals) {
		this.lflivrofiscals = lflivrofiscals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfsittrib> getLfsittribs() {
		return this.lfsittribs;
	}

	public void setLfsittribs(Set<Lfsittrib> lfsittribs) {
		this.lfsittribs = lfsittribs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgconexao> getSgconexaos() {
		return this.sgconexaos;
	}

	public void setSgconexaos(Set<Sgconexao> sgconexaos) {
		this.sgconexaos = sgconexaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Cpsolicitacao> getCpsolicitacaos() {
		return this.cpsolicitacaos;
	}

	public void setCpsolicitacaos(Set<Cpsolicitacao> cpsolicitacaos) {
		this.cpsolicitacaos = cpsolicitacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atencaminhador> getAtencaminhadors() {
		return this.atencaminhadors;
	}

	public void setAtencaminhadors(Set<Atencaminhador> atencaminhadors) {
		this.atencaminhadors = atencaminhadors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Ppestrufase> getPpestrufases() {
		return this.ppestrufases;
	}

	public void setPpestrufases(Set<Ppestrufase> ppestrufases) {
		this.ppestrufases = ppestrufases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Cpforneced> getCpforneceds() {
		return this.cpforneceds;
	}

	public void setCpforneceds(Set<Cpforneced> cpforneceds) {
		this.cpforneceds = cpforneceds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Ppfase> getPpfases() {
		return this.ppfases;
	}

	public void setPpfases(Set<Ppfase> ppfases) {
		this.ppfases = ppfases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgsequencia> getSgsequencias() {
		return this.sgsequencias;
	}

	public void setSgsequencias(Set<Sgsequencia> sgsequencias) {
		this.sgsequencias = sgsequencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sggrpusu> getSggrpusus() {
		return this.sggrpusus;
	}

	public void setSggrpusus(Set<Sggrpusu> sggrpusus) {
		this.sggrpusus = sggrpusus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgusuario> getSgusuarios() {
		return this.sgusuarios;
	}

	public void setSgusuarios(Set<Sgusuario> sgusuarios) {
		this.sgusuarios = sgusuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgacessomg> getSgacessomgs() {
		return this.sgacessomgs;
	}

	public void setSgacessomgs(Set<Sgacessomg> sgacessomgs) {
		this.sgacessomgs = sgacessomgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgacessomu> getSgacessomus() {
		return this.sgacessomus;
	}

	public void setSgacessomus(Set<Sgacessomu> sgacessomus) {
		this.sgacessomus = sgacessomus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqrecmerc> getEqrecmercs() {
		return this.eqrecmercs;
	}

	public void setEqrecmercs(Set<Eqrecmerc> eqrecmercs) {
		this.eqrecmercs = eqrecmercs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqprocrecmerc> getEqprocrecmercs() {
		return this.eqprocrecmercs;
	}

	public void setEqprocrecmercs(Set<Eqprocrecmerc> eqprocrecmercs) {
		this.eqprocrecmercs = eqprocrecmercs;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Sgprefere4 getSgprefere4() {
		return this.sgprefere4;
	}

	public void setSgprefere4(Sgprefere4 sgprefere4) {
		this.sgprefere4 = sgprefere4;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdcliente> getVdclientes() {
		return this.vdclientes;
	}

	public void setVdclientes(Set<Vdcliente> vdclientes) {
		this.vdclientes = vdclientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnpagar> getFnpagars() {
		return this.fnpagars;
	}

	public void setFnpagars(Set<Fnpagar> fnpagars) {
		this.fnpagars = fnpagars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdclascli> getVdclasclis() {
		return this.vdclasclis;
	}

	public void setVdclasclis(Set<Vdclascli> vdclasclis) {
		this.vdclasclis = vdclasclis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atclasatendo> getAtclasatendos() {
		return this.atclasatendos;
	}

	public void setAtclasatendos(Set<Atclasatendo> atclasatendos) {
		this.atclasatendos = atclasatendos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Crmotivofb> getCrmotivofbs() {
		return this.crmotivofbs;
	}

	public void setCrmotivofbs(Set<Crmotivofb> crmotivofbs) {
		this.crmotivofbs = crmotivofbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Attipoconv> getAttipoconvs() {
		return this.attipoconvs;
	}

	public void setAttipoconvs(Set<Attipoconv> attipoconvs) {
		this.attipoconvs = attipoconvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fntbjuros> getFntbjuroses() {
		return this.fntbjuroses;
	}

	public void setFntbjuroses(Set<Fntbjuros> fntbjuroses) {
		this.fntbjuroses = fntbjuroses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfmodnota> getLfmodnotas() {
		return this.lfmodnotas;
	}

	public void setLfmodnotas(Set<Lfmodnota> lfmodnotas) {
		this.lfmodnotas = lfmodnotas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqtipomov> getEqtipomovs() {
		return this.eqtipomovs;
	}

	public void setEqtipomovs(Set<Eqtipomov> eqtipomovs) {
		this.eqtipomovs = eqtipomovs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqtiporecmerc> getEqtiporecmercs() {
		return this.eqtiporecmercs;
	}

	public void setEqtiporecmercs(Set<Eqtiporecmerc> eqtiporecmercs) {
		this.eqtiporecmercs = eqtiporecmercs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqalmox> getEqalmoxes() {
		return this.eqalmoxes;
	}

	public void setEqalmoxes(Set<Eqalmox> eqalmoxes) {
		this.eqalmoxes = eqalmoxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgpapel> getSgpapels() {
		return this.sgpapels;
	}

	public void setSgpapels(Set<Sgpapel> sgpapels) {
		this.sgpapels = sgpapels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Crfeedback> getCrfeedbacks() {
		return this.crfeedbacks;
	}

	public void setCrfeedbacks(Set<Crfeedback> crfeedbacks) {
		this.crfeedbacks = crfeedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnplanejamento> getFnplanejamentos() {
		return this.fnplanejamentos;
	}

	public void setFnplanejamentos(Set<Fnplanejamento> fnplanejamentos) {
		this.fnplanejamentos = fnplanejamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfnatoper> getLfnatopers() {
		return this.lfnatopers;
	}

	public void setLfnatopers(Set<Lfnatoper> lfnatopers) {
		this.lfnatopers = lfnatopers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Rhcurso> getRhcursos() {
		return this.rhcursos;
	}

	public void setRhcursos(Set<Rhcurso> rhcursos) {
		this.rhcursos = rhcursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnlibcred> getFnlibcreds() {
		return this.fnlibcreds;
	}

	public void setFnlibcreds(Set<Fnlibcred> fnlibcreds) {
		this.fnlibcreds = fnlibcreds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgimpressora> getSgimpressoras() {
		return this.sgimpressoras;
	}

	public void setSgimpressoras(Set<Sgimpressora> sgimpressoras) {
		this.sgimpressoras = sgimpressoras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Rhnivelcurso> getRhnivelcursos() {
		return this.rhnivelcursos;
	}

	public void setRhnivelcursos(Set<Rhnivelcurso> rhnivelcursos) {
		this.rhnivelcursos = rhnivelcursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqmodgrade> getEqmodgrades() {
		return this.eqmodgrades;
	}

	public void setEqmodgrades(Set<Eqmodgrade> eqmodgrades) {
		this.eqmodgrades = eqmodgrades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqlocdescarga> getEqlocdescargas() {
		return this.eqlocdescargas;
	}

	public void setEqlocdescargas(Set<Eqlocdescarga> eqlocdescargas) {
		this.eqlocdescargas = eqlocdescargas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgtabela> getSgtabelas() {
		return this.sgtabelas;
	}

	public void setSgtabelas(Set<Sgtabela> sgtabelas) {
		this.sgtabelas = sgtabelas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fncc> getFnccs() {
		return this.fnccs;
	}

	public void setFnccs(Set<Fncc> fnccs) {
		this.fnccs = fnccs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Rharea> getRhareas() {
		return this.rhareas;
	}

	public void setRhareas(Set<Rharea> rhareas) {
		this.rhareas = rhareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgcatimg> getSgcatimgs() {
		return this.sgcatimgs;
	}

	public void setSgcatimgs(Set<Sgcatimg> sgcatimgs) {
		this.sgcatimgs = sgcatimgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdvenda> getVdvendas() {
		return this.vdvendas;
	}

	public void setVdvendas(Set<Vdvenda> vdvendas) {
		this.vdvendas = vdvendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqlanctoexp> getEqlanctoexps() {
		return this.eqlanctoexps;
	}

	public void setEqlanctoexps(Set<Eqlanctoexp> eqlanctoexps) {
		this.eqlanctoexps = eqlanctoexps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atconveniado> getAtconveniados() {
		return this.atconveniados;
	}

	public void setAtconveniados(Set<Atconveniado> atconveniados) {
		this.atconveniados = atconveniados;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Sgprefere5 getSgprefere5() {
		return this.sgprefere5;
	}

	public void setSgprefere5(Sgprefere5 sgprefere5) {
		this.sgprefere5 = sgprefere5;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqinvprod> getEqinvprods() {
		return this.eqinvprods;
	}

	public void setEqinvprods(Set<Eqinvprod> eqinvprods) {
		this.eqinvprods = eqinvprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lftrattrib> getLftrattribs() {
		return this.lftrattribs;
	}

	public void setLftrattribs(Set<Lftrattrib> lftrattribs) {
		this.lftrattribs = lftrattribs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnsaldolanca> getFnsaldolancas() {
		return this.fnsaldolancas;
	}

	public void setFnsaldolancas(Set<Fnsaldolanca> fnsaldolancas) {
		this.fnsaldolancas = fnsaldolancas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Equnidade> getEqunidades() {
		return this.equnidades;
	}

	public void setEqunidades(Set<Equnidade> equnidades) {
		this.equnidades = equnidades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnreceber> getFnrecebers() {
		return this.fnrecebers;
	}

	public void setFnrecebers(Set<Fnreceber> fnrecebers) {
		this.fnrecebers = fnrecebers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnbanco> getFnbancos() {
		return this.fnbancos;
	}

	public void setFnbancos(Set<Fnbanco> fnbancos) {
		this.fnbancos = fnbancos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqmovexp> getEqmovexps() {
		return this.eqmovexps;
	}

	public void setEqmovexps(Set<Eqmovexp> eqmovexps) {
		this.eqmovexps = eqmovexps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdcomissao> getVdcomissaos() {
		return this.vdcomissaos;
	}

	public void setVdcomissaos(Set<Vdcomissao> vdcomissaos) {
		this.vdcomissaos = vdcomissaos;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Sgprefere1 getSgprefere1() {
		return this.sgprefere1;
	}

	public void setSgprefere1(Sgprefere1 sgprefere1) {
		this.sgprefere1 = sgprefere1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqgrupo> getEqgrupos() {
		return this.eqgrupos;
	}

	public void setEqgrupos(Set<Eqgrupo> eqgrupos) {
		this.eqgrupos = eqgrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqmovserie> getEqmovseries() {
		return this.eqmovseries;
	}

	public void setEqmovseries(Set<Eqmovserie> eqmovseries) {
		this.eqmovseries = eqmovseries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgacessoeu> getSgacessoeus() {
		return this.sgacessoeus;
	}

	public void setSgacessoeus(Set<Sgacessoeu> sgacessoeus) {
		this.sgacessoeus = sgacessoeus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atatendente> getAtatendentes() {
		return this.atatendentes;
	}

	public void setAtatendentes(Set<Atatendente> atatendentes) {
		this.atatendentes = atatendentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Rhcaracteristica> getRhcaracteristicas() {
		return this.rhcaracteristicas;
	}

	public void setRhcaracteristicas(Set<Rhcaracteristica> rhcaracteristicas) {
		this.rhcaracteristicas = rhcaracteristicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Rhcandidato> getRhcandidatos() {
		return this.rhcandidatos;
	}

	public void setRhcandidatos(Set<Rhcandidato> rhcandidatos) {
		this.rhcandidatos = rhcandidatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Sgestcivil> getSgestcivils() {
		return this.sgestcivils;
	}

	public void setSgestcivils(Set<Sgestcivil> sgestcivils) {
		this.sgestcivils = sgestcivils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Cpcompra> getCpcompras() {
		return this.cpcompras;
	}

	public void setCpcompras(Set<Cpcompra> cpcompras) {
		this.cpcompras = cpcompras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Rhempregador> getRhempregadors() {
		return this.rhempregadors;
	}

	public void setRhempregadors(Set<Rhempregador> rhempregadors) {
		this.rhempregadors = rhempregadors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfserie> getLfseries() {
		return this.lfseries;
	}

	public void setLfseries(Set<Lfserie> lfseries) {
		this.lfseries = lfseries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdtipocli> getVdtipoclis() {
		return this.vdtipoclis;
	}

	public void setVdtipoclis(Set<Vdtipocli> vdtipoclis) {
		this.vdtipoclis = vdtipoclis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Attipoatendo> getAttipoatendos() {
		return this.attipoatendos;
	}

	public void setAttipoatendos(Set<Attipoatendo> attipoatendos) {
		this.attipoatendos = attipoatendos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfregrafiscal> getLfregrafiscals() {
		return this.lfregrafiscals;
	}

	public void setLfregrafiscals(Set<Lfregrafiscal> lfregrafiscals) {
		this.lfregrafiscals = lfregrafiscals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqmarca> getEqmarcas() {
		return this.eqmarcas;
	}

	public void setEqmarcas(Set<Eqmarca> eqmarcas) {
		this.eqmarcas = eqmarcas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqlote> getEqlotes() {
		return this.eqlotes;
	}

	public void setEqlotes(Set<Eqlote> eqlotes) {
		this.eqlotes = eqlotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Vdgruporc> getVdgruporcs() {
		return this.vdgruporcs;
	}

	public void setVdgruporcs(Set<Vdgruporc> vdgruporcs) {
		this.vdgruporcs = vdgruporcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fncotmoeda> getFncotmoedas() {
		return this.fncotmoedas;
	}

	public void setFncotmoedas(Set<Fncotmoeda> fncotmoedas) {
		this.fncotmoedas = fncotmoedas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqtipoexpedicao> getEqtipoexpedicaos() {
		return this.eqtipoexpedicaos;
	}

	public void setEqtipoexpedicaos(Set<Eqtipoexpedicao> eqtipoexpedicaos) {
		this.eqtipoexpedicaos = eqtipoexpedicaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqitrecmerc> getEqitrecmercs() {
		return this.eqitrecmercs;
	}

	public void setEqitrecmercs(Set<Eqitrecmerc> eqitrecmercs) {
		this.eqitrecmercs = eqitrecmercs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqvargrade> getEqvargrades() {
		return this.eqvargrades;
	}

	public void setEqvargrades(Set<Eqvargrade> eqvargrades) {
		this.eqvargrades = eqvargrades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atatribuicao> getAtatribuicaos() {
		return this.atatribuicaos;
	}

	public void setAtatribuicaos(Set<Atatribuicao> atatribuicaos) {
		this.atatribuicaos = atatribuicaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fntipocob> getFntipocobs() {
		return this.fntipocobs;
	}

	public void setFntipocobs(Set<Fntipocob> fntipocobs) {
		this.fntipocobs = fntipocobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Atsetor> getAtsetors() {
		return this.atsetors;
	}

	public void setAtsetors(Set<Atsetor> atsetors) {
		this.atsetors = atsetors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Eqmovprod> getEqmovprods() {
		return this.eqmovprods;
	}

	public void setEqmovprods(Set<Eqmovprod> eqmovprods) {
		this.eqmovprods = eqmovprods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Pptiporec> getPptiporecs() {
		return this.pptiporecs;
	}

	public void setPptiporecs(Set<Pptiporec> pptiporecs) {
		this.pptiporecs = pptiporecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Lfmoddocfisc> getLfmoddocfiscs() {
		return this.lfmoddocfiscs;
	}

	public void setLfmoddocfiscs(Set<Lfmoddocfisc> lfmoddocfiscs) {
		this.lfmoddocfiscs = lfmoddocfiscs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Fnpagtocomi> getFnpagtocomis() {
		return this.fnpagtocomis;
	}

	public void setFnpagtocomis(Set<Fnpagtocomi> fnpagtocomis) {
		this.fnpagtocomis = fnpagtocomis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgfilial")
	public Set<Necontingencia> getNecontingencias() {
		return this.necontingencias;
	}

	public void setNecontingencias(Set<Necontingencia> necontingencias) {
		this.necontingencias = necontingencias;
	}

}
