package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sgunifcod generated by hbm2java
 */
@Entity
@Table(name = "SGUNIFCOD")
public class Sgunifcod implements java.io.Serializable {

	private SgunifcodId id;
	private char tipounifcod;
	private String descunifcod;
	private Integer codtmp;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set vdtransps = new HashSet(0);
	private Set lffretesForLffretefksgunifcodd = new HashSet(0);
	private Set lffretesForLffretefksgunifcodr = new HashSet(0);
	private Set sgfilials = new HashSet(0);
	private Set vdclientes = new HashSet(0);
	private Set cpforneceds = new HashSet(0);

	public Sgunifcod() {
	}

	public Sgunifcod(SgunifcodId id, char tipounifcod, String descunifcod,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.tipounifcod = tipounifcod;
		this.descunifcod = descunifcod;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Sgunifcod(SgunifcodId id, char tipounifcod, String descunifcod,
			Integer codtmp, Date dtins, Date hins, String idusuins, Date dtalt,
			Date halt, String idusualt, Set vdtransps,
			Set lffretesForLffretefksgunifcodd,
			Set lffretesForLffretefksgunifcodr, Set sgfilials, Set vdclientes,
			Set cpforneceds) {
		this.id = id;
		this.tipounifcod = tipounifcod;
		this.descunifcod = descunifcod;
		this.codtmp = codtmp;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.vdtransps = vdtransps;
		this.lffretesForLffretefksgunifcodd = lffretesForLffretefksgunifcodd;
		this.lffretesForLffretefksgunifcodr = lffretesForLffretefksgunifcodr;
		this.sgfilials = sgfilials;
		this.vdclientes = vdclientes;
		this.cpforneceds = cpforneceds;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codunifcod", column = @Column(name = "CODUNIFCOD", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public SgunifcodId getId() {
		return this.id;
	}

	public void setId(SgunifcodId id) {
		this.id = id;
	}

	@Column(name = "TIPOUNIFCOD", nullable = false, length = 1)
	public char getTipounifcod() {
		return this.tipounifcod;
	}

	public void setTipounifcod(char tipounifcod) {
		this.tipounifcod = tipounifcod;
	}

	@Column(name = "DESCUNIFCOD", nullable = false, length = 80)
	public String getDescunifcod() {
		return this.descunifcod;
	}

	public void setDescunifcod(String descunifcod) {
		this.descunifcod = descunifcod;
	}

	@Column(name = "CODTMP")
	public Integer getCodtmp() {
		return this.codtmp;
	}

	public void setCodtmp(Integer codtmp) {
		this.codtmp = codtmp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgunifcod")
	public Set getVdtransps() {
		return this.vdtransps;
	}

	public void setVdtransps(Set vdtransps) {
		this.vdtransps = vdtransps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgunifcodByLffretefksgunifcodd")
	public Set getLffretesForLffretefksgunifcodd() {
		return this.lffretesForLffretefksgunifcodd;
	}

	public void setLffretesForLffretefksgunifcodd(
			Set lffretesForLffretefksgunifcodd) {
		this.lffretesForLffretefksgunifcodd = lffretesForLffretefksgunifcodd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgunifcodByLffretefksgunifcodr")
	public Set getLffretesForLffretefksgunifcodr() {
		return this.lffretesForLffretefksgunifcodr;
	}

	public void setLffretesForLffretefksgunifcodr(
			Set lffretesForLffretefksgunifcodr) {
		this.lffretesForLffretefksgunifcodr = lffretesForLffretefksgunifcodr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgunifcod")
	public Set getSgfilials() {
		return this.sgfilials;
	}

	public void setSgfilials(Set sgfilials) {
		this.sgfilials = sgfilials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgunifcod")
	public Set getVdclientes() {
		return this.vdclientes;
	}

	public void setVdclientes(Set vdclientes) {
		this.vdclientes = vdclientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgunifcod")
	public Set getCpforneceds() {
		return this.cpforneceds;
	}

	public void setCpforneceds(Set cpforneceds) {
		this.cpforneceds = cpforneceds;
	}
*/
}
