package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Svos generated by hbm2java
 */
@Entity
@Table(name = "SVOS")
public class Svos implements java.io.Serializable {

	private SvosId id;
	private Vdcliente vdcliente;
	private Atconveniado atconveniado;
	private Date dtentos;
	private String sitos;
	private Date dtprevos;
	private Date dtsaios;
	private String descos;
	private String obsos;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;
	private Set svitoses = new HashSet(0);

	public Svos() {
	}

	public Svos(SvosId id, Vdcliente vdcliente, Date dtentos, String sitos,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.vdcliente = vdcliente;
		this.dtentos = dtentos;
		this.sitos = sitos;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Svos(SvosId id, Vdcliente vdcliente, Atconveniado atconveniado,
			Date dtentos, String sitos, Date dtprevos, Date dtsaios,
			String descos, String obsos, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, String idusualt,
			Set svitoses) {
		this.id = id;
		this.vdcliente = vdcliente;
		this.atconveniado = atconveniado;
		this.dtentos = dtentos;
		this.sitos = sitos;
		this.dtprevos = dtprevos;
		this.dtsaios = dtsaios;
		this.descos = descos;
		this.obsos = obsos;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
		this.svitoses = svitoses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codos", column = @Column(name = "CODOS", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public SvosId getId() {
		return this.id;
	}

	public void setId(SvosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODCLI", referencedColumnName = "CODCLI", nullable = false),
			@JoinColumn(name = "CODFILIALCL", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPCL", referencedColumnName = "CODEMP", nullable = false) })
	public Vdcliente getVdcliente() {
		return this.vdcliente;
	}

	public void setVdcliente(Vdcliente vdcliente) {
		this.vdcliente = vdcliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODCONV", referencedColumnName = "CODCONV"),
			@JoinColumn(name = "CODFILIALCV", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPCV", referencedColumnName = "CODEMP") })
	public Atconveniado getAtconveniado() {
		return this.atconveniado;
	}

	public void setAtconveniado(Atconveniado atconveniado) {
		this.atconveniado = atconveniado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTENTOS", nullable = false, length = 10)
	public Date getDtentos() {
		return this.dtentos;
	}

	public void setDtentos(Date dtentos) {
		this.dtentos = dtentos;
	}

	@Column(name = "SITOS", nullable = false, length = 2)
	public String getSitos() {
		return this.sitos;
	}

	public void setSitos(String sitos) {
		this.sitos = sitos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTPREVOS", length = 10)
	public Date getDtprevos() {
		return this.dtprevos;
	}

	public void setDtprevos(Date dtprevos) {
		this.dtprevos = dtprevos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTSAIOS", length = 10)
	public Date getDtsaios() {
		return this.dtsaios;
	}

	public void setDtsaios(Date dtsaios) {
		this.dtsaios = dtsaios;
	}

	@Column(name = "DESCOS", length = 1000)
	public String getDescos() {
		return this.descos;
	}

	public void setDescos(String descos) {
		this.descos = descos;
	}

	@Column(name = "OBSOS", length = 1000)
	public String getObsos() {
		return this.obsos;
	}

	public void setObsos(String obsos) {
		this.obsos = obsos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "svos")
	public Set getSvitoses() {
		return this.svitoses;
	}

	public void setSvitoses(Set svitoses) {
		this.svitoses = svitoses;
	}
*/
}
