package org.freedom.persist.entity;

// Generated 10/05/2014 10:27:15 by Hibernate Tools 4.0.0

/**
 * VditcontratoforId generated by hbm2java
 */
public class VditcontratoforId implements java.io.Serializable {

	private int codcontr;
	private short coditcontr;
	private short seqicf;

	public VditcontratoforId() {
	}

	public VditcontratoforId(int codcontr, short coditcontr, short seqicf) {
		this.codcontr = codcontr;
		this.coditcontr = coditcontr;
		this.seqicf = seqicf;
	}

	public int getCodcontr() {
		return this.codcontr;
	}

	public void setCodcontr(int codcontr) {
		this.codcontr = codcontr;
	}

	public short getCoditcontr() {
		return this.coditcontr;
	}

	public void setCoditcontr(short coditcontr) {
		this.coditcontr = coditcontr;
	}

	public short getSeqicf() {
		return this.seqicf;
	}

	public void setSeqicf(short seqicf) {
		this.seqicf = seqicf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VditcontratoforId))
			return false;
		VditcontratoforId castOther = (VditcontratoforId) other;

		return (this.getCodcontr() == castOther.getCodcontr())
				&& (this.getCoditcontr() == castOther.getCoditcontr())
				&& (this.getSeqicf() == castOther.getSeqicf());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodcontr();
		result = 37 * result + this.getCoditcontr();
		result = 37 * result + this.getSeqicf();
		return result;
	}

}
