package org.freedom.persist.entity;

// Generated 20/11/2013 10:59:59 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vditregracomis generated by hbm2java
 */
public class Vditregracomis implements java.io.Serializable {

	private VditregracomisId id;
	private Vdregracomis vdregracomis;
	private Vdvendedor vdvendedor;
	private Vdtipovend vdtipovend;
	private char obrigitrc;
	private BigDecimal perccomisitrc;
	private String idusualt;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private Set vdvendacomises = new HashSet(0);

	public Vditregracomis() {
	}

	public Vditregracomis(VditregracomisId id, Vdregracomis vdregracomis,
			Vdtipovend vdtipovend, char obrigitrc, BigDecimal perccomisitrc,
			String idusualt, Date dtins, Date hins, String idusuins,
			Date dtalt, Date halt) {
		this.id = id;
		this.vdregracomis = vdregracomis;
		this.vdtipovend = vdtipovend;
		this.obrigitrc = obrigitrc;
		this.perccomisitrc = perccomisitrc;
		this.idusualt = idusualt;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
	}

	public Vditregracomis(VditregracomisId id, Vdregracomis vdregracomis,
			Vdvendedor vdvendedor, Vdtipovend vdtipovend, char obrigitrc,
			BigDecimal perccomisitrc, String idusualt, Date dtins, Date hins,
			String idusuins, Date dtalt, Date halt, Set vdvendacomises) {
		this.id = id;
		this.vdregracomis = vdregracomis;
		this.vdvendedor = vdvendedor;
		this.vdtipovend = vdtipovend;
		this.obrigitrc = obrigitrc;
		this.perccomisitrc = perccomisitrc;
		this.idusualt = idusualt;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.vdvendacomises = vdvendacomises;
	}

	public VditregracomisId getId() {
		return this.id;
	}

	public void setId(VditregracomisId id) {
		this.id = id;
	}

	public Vdregracomis getVdregracomis() {
		return this.vdregracomis;
	}

	public void setVdregracomis(Vdregracomis vdregracomis) {
		this.vdregracomis = vdregracomis;
	}

	public Vdvendedor getVdvendedor() {
		return this.vdvendedor;
	}

	public void setVdvendedor(Vdvendedor vdvendedor) {
		this.vdvendedor = vdvendedor;
	}

	public Vdtipovend getVdtipovend() {
		return this.vdtipovend;
	}

	public void setVdtipovend(Vdtipovend vdtipovend) {
		this.vdtipovend = vdtipovend;
	}

	public char getObrigitrc() {
		return this.obrigitrc;
	}

	public void setObrigitrc(char obrigitrc) {
		this.obrigitrc = obrigitrc;
	}

	public BigDecimal getPerccomisitrc() {
		return this.perccomisitrc;
	}

	public void setPerccomisitrc(BigDecimal perccomisitrc) {
		this.perccomisitrc = perccomisitrc;
	}

	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	public Set getVdvendacomises() {
		return this.vdvendacomises;
	}

	public void setVdvendacomises(Set vdvendacomises) {
		this.vdvendacomises = vdvendacomises;
	}

}
