package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vdprecoprod generated by hbm2java
 */
@Entity
@Table(name = "VDPRECOPROD")
public class Vdprecoprod implements java.io.Serializable {

	private VdprecoprodId id;
	private Eqproduto eqproduto;
	private Vdtabpreco vdtabpreco;
	private Fnplanopag fnplanopag;
	private Vdclascli vdclascli;
	private BigDecimal precoprod;
	private Character tipoprecoprod;
	private Date dtaltpreco;
	private Date haltpreco;
	private BigDecimal precoant;
	private String idusualtpreco;
	private char ativoprecoprod;
	private Date dtins;
	private Date hins;
	private String idusuins;
	private Date dtalt;
	private Date halt;
	private String idusualt;

	public Vdprecoprod() {
	}

	public Vdprecoprod(VdprecoprodId id, Eqproduto eqproduto,
			Vdtabpreco vdtabpreco, BigDecimal precoprod, char ativoprecoprod,
			Date dtins, Date hins, String idusuins) {
		this.id = id;
		this.eqproduto = eqproduto;
		this.vdtabpreco = vdtabpreco;
		this.precoprod = precoprod;
		this.ativoprecoprod = ativoprecoprod;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
	}

	public Vdprecoprod(VdprecoprodId id, Eqproduto eqproduto,
			Vdtabpreco vdtabpreco, Fnplanopag fnplanopag, Vdclascli vdclascli,
			BigDecimal precoprod, Character tipoprecoprod, Date dtaltpreco,
			Date haltpreco, BigDecimal precoant, String idusualtpreco,
			char ativoprecoprod, Date dtins, Date hins, String idusuins,
			Date dtalt, Date halt, String idusualt) {
		this.id = id;
		this.eqproduto = eqproduto;
		this.vdtabpreco = vdtabpreco;
		this.fnplanopag = fnplanopag;
		this.vdclascli = vdclascli;
		this.precoprod = precoprod;
		this.tipoprecoprod = tipoprecoprod;
		this.dtaltpreco = dtaltpreco;
		this.haltpreco = haltpreco;
		this.precoant = precoant;
		this.idusualtpreco = idusualtpreco;
		this.ativoprecoprod = ativoprecoprod;
		this.dtins = dtins;
		this.hins = hins;
		this.idusuins = idusuins;
		this.dtalt = dtalt;
		this.halt = halt;
		this.idusualt = idusualt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codprecoprod", column = @Column(name = "CODPRECOPROD", nullable = false)),
			@AttributeOverride(name = "codprod", column = @Column(name = "CODPROD", nullable = false)),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL", nullable = false)),
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP", nullable = false)) })
	public VdprecoprodId getId() {
		return this.id;
	}

	public void setId(VdprecoprodId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODPROD", referencedColumnName = "CODPROD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODFILIAL", referencedColumnName = "CODFILIAL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CODEMP", referencedColumnName = "CODEMP", nullable = false, insertable = false, updatable = false) })
	public Eqproduto getEqproduto() {
		return this.eqproduto;
	}

	public void setEqproduto(Eqproduto eqproduto) {
		this.eqproduto = eqproduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODTAB", referencedColumnName = "CODTAB", nullable = false),
			@JoinColumn(name = "CODFILIALTB", referencedColumnName = "CODFILIAL", nullable = false),
			@JoinColumn(name = "CODEMPTB", referencedColumnName = "CODEMP", nullable = false) })
	public Vdtabpreco getVdtabpreco() {
		return this.vdtabpreco;
	}

	public void setVdtabpreco(Vdtabpreco vdtabpreco) {
		this.vdtabpreco = vdtabpreco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODPLANOPAG", referencedColumnName = "CODPLANOPAG"),
			@JoinColumn(name = "CODFILIALPG", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPPG", referencedColumnName = "CODEMP") })
	public Fnplanopag getFnplanopag() {
		return this.fnplanopag;
	}

	public void setFnplanopag(Fnplanopag fnplanopag) {
		this.fnplanopag = fnplanopag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CODCLASCLI", referencedColumnName = "CODCLASCLI"),
			@JoinColumn(name = "CODFILIALCC", referencedColumnName = "CODFILIAL"),
			@JoinColumn(name = "CODEMPCC", referencedColumnName = "CODEMP") })
	public Vdclascli getVdclascli() {
		return this.vdclascli;
	}

	public void setVdclascli(Vdclascli vdclascli) {
		this.vdclascli = vdclascli;
	}

	@Column(name = "PRECOPROD", nullable = false, precision = 15, scale = 5)
	public BigDecimal getPrecoprod() {
		return this.precoprod;
	}

	public void setPrecoprod(BigDecimal precoprod) {
		this.precoprod = precoprod;
	}

	@Column(name = "TIPOPRECOPROD", length = 1)
	public Character getTipoprecoprod() {
		return this.tipoprecoprod;
	}

	public void setTipoprecoprod(Character tipoprecoprod) {
		this.tipoprecoprod = tipoprecoprod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALTPRECO", length = 10)
	public Date getDtaltpreco() {
		return this.dtaltpreco;
	}

	public void setDtaltpreco(Date dtaltpreco) {
		this.dtaltpreco = dtaltpreco;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALTPRECO", length = 8)
	public Date getHaltpreco() {
		return this.haltpreco;
	}

	public void setHaltpreco(Date haltpreco) {
		this.haltpreco = haltpreco;
	}

	@Column(name = "PRECOANT", precision = 15, scale = 5)
	public BigDecimal getPrecoant() {
		return this.precoant;
	}

	public void setPrecoant(BigDecimal precoant) {
		this.precoant = precoant;
	}

	@Column(name = "IDUSUALTPRECO", length = 8)
	public String getIdusualtpreco() {
		return this.idusualtpreco;
	}

	public void setIdusualtpreco(String idusualtpreco) {
		this.idusualtpreco = idusualtpreco;
	}

	@Column(name = "ATIVOPRECOPROD", nullable = false, length = 1)
	public char getAtivoprecoprod() {
		return this.ativoprecoprod;
	}

	public void setAtivoprecoprod(char ativoprecoprod) {
		this.ativoprecoprod = ativoprecoprod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTINS", nullable = false, length = 10)
	public Date getDtins() {
		return this.dtins;
	}

	public void setDtins(Date dtins) {
		this.dtins = dtins;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HINS", nullable = false, length = 8)
	public Date getHins() {
		return this.hins;
	}

	public void setHins(Date hins) {
		this.hins = hins;
	}

	@Column(name = "IDUSUINS", nullable = false, length = 8)
	public String getIdusuins() {
		return this.idusuins;
	}

	public void setIdusuins(String idusuins) {
		this.idusuins = idusuins;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTALT", length = 10)
	public Date getDtalt() {
		return this.dtalt;
	}

	public void setDtalt(Date dtalt) {
		this.dtalt = dtalt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HALT", length = 8)
	public Date getHalt() {
		return this.halt;
	}

	public void setHalt(Date halt) {
		this.halt = halt;
	}

	@Column(name = "IDUSUALT", length = 8)
	public String getIdusualt() {
		return this.idusualt;
	}

	public void setIdusualt(String idusualt) {
		this.idusualt = idusualt;
	}

}
