package org.freedom.persist.entity;

// Generated 12/05/2014 09:11:34 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vwtmpcustoitrma generated by hbm2java
 */
@Entity
@Table(name = "VWTMPCUSTOITRMA")
public class Vwtmpcustoitrma implements java.io.Serializable {

	private VwtmpcustoitrmaId id;

	public Vwtmpcustoitrma() {
	}

	public Vwtmpcustoitrma(VwtmpcustoitrmaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codemp", column = @Column(name = "CODEMP")),
			@AttributeOverride(name = "codfilial", column = @Column(name = "CODFILIAL")),
			@AttributeOverride(name = "codrma", column = @Column(name = "CODRMA")),
			@AttributeOverride(name = "coditrma", column = @Column(name = "CODITRMA")),
			@AttributeOverride(name = "codprod", column = @Column(name = "CODPROD")),
			@AttributeOverride(name = "custodata", column = @Column(name = "CUSTODATA", precision = 0, scale = 5)) })
	public VwtmpcustoitrmaId getId() {
		return this.id;
	}

	public void setId(VwtmpcustoitrmaId id) {
		this.id = id;
	}

}
