insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '01', 'Nota Fiscal');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '1B', 'Nota Fiscal Avulsa');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '02', 'Nota Fiscal de Venda a Consumidor');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '2D', 'Cupom Fiscal emitido por ECF');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '2E', 'Bilhete de Passagem emitido por ECF');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '04', 'Nota Fiscal de Produtor');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '06', 'Nota Fiscal/Conta de Energia Eletrica');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '07', 'Nota Fiscal de Servicoo de Transporte');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '08', 'Conhecimento de Transporte Rodoviario de Cargas');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '8B', 'Conhecimento de Transporte de Cargas Avulso');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '09', 'Conhecimento de Transporte Aquaviario de Cargas');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '10', 'Conhecimento Aereo');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '11', 'Conhecimento de Transporte Ferroviario de Cargas');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '13', 'Bilhete de Passagem Rodoviario');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '14', 'Bilhete de Passagem Aquaviario');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '15', 'Bilhete de Passagem e Nota de Bagagem');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '17', 'Despacho de Transporte');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '16', 'Bilhete de Passagem Ferroviario');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '18', 'Resumo de Movimento Diario');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '20', 'Ordem de Coleta de Cargas');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '21', 'Nota Fiscal de Servico de Comunicacao');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '22', 'Nota Fiscal de Servico de Telecomunicacao');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '23', 'GNRE');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '24', 'Autorizacao de Carregamento e Transporte');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '25', 'Manifesto de Carga');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '26', 'Conhecimento de Transporte Multimodal de Cargas');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '27', 'Nota Fiscal de Transporte Ferroviario de Cargas');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '28', 'Nota Fiscal/Conta de Fornecimento de Gas Canalizado');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '29', 'Nota Fiscal/Conta de Fornecimento de Agua Canalizada');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '30', 'Bilhete/Recibo do Passageiro');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '55', 'Nota Fiscal Eletronica');
insert into lfmoddocfisc(codemp, codfilial, codmoddocfisc, descmoddocfisc) values ( #CODEMP#, #CODFILIAL#, '57', 'Conhecimento de Transporte Eletronico CT-e');

