/* Server Version: LI-V6.3.4.4910 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.6.3.fdb' USER 'SYSDBA' PASSWORD '123654' ROLE 'ADM';

SET AUTODDL ON;

CREATE DOMAIN IBCXXX CHAR(1) DEFAULT 'N' NOT NULL;

UPDATE RDB$RELATION_FIELDS SET RDB$DEFAULT_SOURCE=
(SELECT RDB$DEFAULT_SOURCE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX'),
RDB$DEFAULT_VALUE=
(SELECT RDB$DEFAULT_VALUE FROM RDB$FIELDS where RDB$FIELD_NAME='IBCXXX')
WHERE RDB$FIELD_NAME='BLOQATENDIMENTO' AND RDB$RELATION_NAME='SGPREFERE3';

DROP DOMAIN IBCXXX;

UPDATE RDB$FIELDS SET RDB$DEFAULT_VALUE = NULL,
RDB$DEFAULT_SOURCE = '' WHERE RDB$FIELD_NAME =
(SELECT RDB$FIELD_SOURCE FROM RDB$RELATION_FIELDS
WHERE RDB$FIELD_NAME = 'BLOQATENDIMENTO' AND RDB$RELATION_NAME = 'SGPREFERE3');

ALTER TABLE ATATENDENTE ADD ACESTROCOMIS CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE ATATENDENTE ADD ACESTROCOMISOUT CHAR(1) DEFAULT 'S' NOT NULL;

ALTER TABLE SGPREFERE3 ADD CONTROLEACESATEND CHAR(1) DEFAULT 'N' NOT NULL;

ALTER TABLE SGPREFERE3 ADD AGENDAOBRIGORC CHAR(1) DEFAULT 'N' NOT NULL;

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
SET TERM ^ ;

ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.6.4 (02/07/2013)';
    suspend;
end
^

/* Alter Procedure... */
/* Alter (SGRETVERSAO) */
ALTER PROCEDURE SGRETVERSAO RETURNS(VERSAO VARCHAR(30))
 AS
begin
    versao = '1.2.6.4 (02/07/2013)';
    suspend;
end
^

SET TERM ; ^

ALTER TABLE ATATENDENTE ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE ATATENDENTE ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE ATATENDENTE ALTER COLUMN CODATEND POSITION 3;

ALTER TABLE ATATENDENTE ALTER COLUMN NOMEATEND POSITION 4;

ALTER TABLE ATATENDENTE ALTER COLUMN CODEMPTA POSITION 5;

ALTER TABLE ATATENDENTE ALTER COLUMN CODFILIALTA POSITION 6;

ALTER TABLE ATATENDENTE ALTER COLUMN CODTPATEND POSITION 7;

ALTER TABLE ATATENDENTE ALTER COLUMN RGATEND POSITION 8;

ALTER TABLE ATATENDENTE ALTER COLUMN ENDATEND POSITION 9;

ALTER TABLE ATATENDENTE ALTER COLUMN BAIRATEND POSITION 10;

ALTER TABLE ATATENDENTE ALTER COLUMN CIDATEND POSITION 11;

ALTER TABLE ATATENDENTE ALTER COLUMN CEPATEND POSITION 12;

ALTER TABLE ATATENDENTE ALTER COLUMN FONEATEND POSITION 13;

ALTER TABLE ATATENDENTE ALTER COLUMN FAXATEND POSITION 14;

ALTER TABLE ATATENDENTE ALTER COLUMN EMAILATEND POSITION 15;

ALTER TABLE ATATENDENTE ALTER COLUMN NUMATEND POSITION 16;

ALTER TABLE ATATENDENTE ALTER COLUMN UFATEND POSITION 17;

ALTER TABLE ATATENDENTE ALTER COLUMN CELATEND POSITION 18;

ALTER TABLE ATATENDENTE ALTER COLUMN IDENTIFICATEND POSITION 19;

ALTER TABLE ATATENDENTE ALTER COLUMN CODEMPUS POSITION 20;

ALTER TABLE ATATENDENTE ALTER COLUMN CODFILIALUS POSITION 21;

ALTER TABLE ATATENDENTE ALTER COLUMN IDUSU POSITION 22;

ALTER TABLE ATATENDENTE ALTER COLUMN CPFATEND POSITION 23;

ALTER TABLE ATATENDENTE ALTER COLUMN CODVEND POSITION 24;

ALTER TABLE ATATENDENTE ALTER COLUMN CODEMPVE POSITION 25;

ALTER TABLE ATATENDENTE ALTER COLUMN CODFILIALVE POSITION 26;

ALTER TABLE ATATENDENTE ALTER COLUMN CODEMPEP POSITION 27;

ALTER TABLE ATATENDENTE ALTER COLUMN CODFILIALEP POSITION 28;

ALTER TABLE ATATENDENTE ALTER COLUMN MATEMPR POSITION 29;

ALTER TABLE ATATENDENTE ALTER COLUMN METAATEND POSITION 30;

ALTER TABLE ATATENDENTE ALTER COLUMN PARTPREMIATEND POSITION 31;

ALTER TABLE ATATENDENTE ALTER COLUMN ACESATDOLEROUT POSITION 32;

ALTER TABLE ATATENDENTE ALTER COLUMN ACESATDOALTOUT POSITION 33;

ALTER TABLE ATATENDENTE ALTER COLUMN ACESATDODELLAN POSITION 34;

ALTER TABLE ATATENDENTE ALTER COLUMN ACESATDODELOUT POSITION 35;

ALTER TABLE ATATENDENTE ALTER COLUMN ACESRELESTOUT POSITION 36;

ALTER TABLE ATATENDENTE ALTER COLUMN ACESTROCOMIS POSITION 37;

ALTER TABLE ATATENDENTE ALTER COLUMN ACESTROCOMISOUT POSITION 38;

ALTER TABLE ATATENDENTE ALTER COLUMN DTINS POSITION 39;

ALTER TABLE ATATENDENTE ALTER COLUMN IDUSUINS POSITION 40;

ALTER TABLE ATATENDENTE ALTER COLUMN DTALT POSITION 41;

ALTER TABLE ATATENDENTE ALTER COLUMN IDUSUALT POSITION 42;

ALTER TABLE ATATENDENTE ALTER COLUMN HINS POSITION 43;

ALTER TABLE ATATENDENTE ALTER COLUMN HALT POSITION 44;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMP POSITION 1;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIAL POSITION 2;

ALTER TABLE SGPREFERE3 ALTER COLUMN SMTPMAIL POSITION 3;

ALTER TABLE SGPREFERE3 ALTER COLUMN SMTPSSLMAIL POSITION 4;

ALTER TABLE SGPREFERE3 ALTER COLUMN SMTPAUTMAIL POSITION 5;

ALTER TABLE SGPREFERE3 ALTER COLUMN PORTAMAIL POSITION 6;

ALTER TABLE SGPREFERE3 ALTER COLUMN USERMAIL POSITION 7;

ALTER TABLE SGPREFERE3 ALTER COLUMN PASSMAIL POSITION 8;

ALTER TABLE SGPREFERE3 ALTER COLUMN ENDMAIL POSITION 9;

ALTER TABLE SGPREFERE3 ALTER COLUMN AUTOHORATEND POSITION 10;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPCE POSITION 11;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALCE POSITION 12;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODATIVCE POSITION 13;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPTE POSITION 14;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALTE POSITION 15;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODATIVTE POSITION 16;

ALTER TABLE SGPREFERE3 ALTER COLUMN BLOQATENDCLIATRASO POSITION 17;

ALTER TABLE SGPREFERE3 ALTER COLUMN MOSTRACLIATRASO POSITION 18;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPNC POSITION 19;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALNC POSITION 20;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMAILNC POSITION 21;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPAO POSITION 22;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALAO POSITION 23;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODATENDO POSITION 24;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPMI POSITION 25;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALMI POSITION 26;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODMODELMI POSITION 27;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPME POSITION 28;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALME POSITION 29;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODMODELME POSITION 30;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPFI POSITION 31;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALFI POSITION 32;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODMODELFI POSITION 33;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPFJ POSITION 34;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALFJ POSITION 35;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODMODELFJ POSITION 36;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPAP POSITION 37;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALAP POSITION 38;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODMODELAP POSITION 39;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPOR POSITION 40;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALOR POSITION 41;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODMODELOR POSITION 42;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPMC POSITION 43;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALMC POSITION 44;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODMODELMC POSITION 45;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPEC POSITION 46;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALEC POSITION 47;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMAILEC POSITION 48;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPEA POSITION 49;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALEA POSITION 50;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMAILEA POSITION 51;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPT1 POSITION 52;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALT1 POSITION 53;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODTIPOCONT1 POSITION 54;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPT2 POSITION 55;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALT2 POSITION 56;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODTIPOCONT2 POSITION 57;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPCF POSITION 58;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALCF POSITION 59;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODCONFEMAIL POSITION 60;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPC2 POSITION 61;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALC2 POSITION 62;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODCONFEMAIL2 POSITION 63;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPEN POSITION 64;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALEN POSITION 65;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMAILEN POSITION 66;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPE2 POSITION 67;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALE2 POSITION 68;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMAILEN2 POSITION 69;

ALTER TABLE SGPREFERE3 ALTER COLUMN EMAILNOTIF1 POSITION 70;

ALTER TABLE SGPREFERE3 ALTER COLUMN EMAILNOTIF2 POSITION 71;

ALTER TABLE SGPREFERE3 ALTER COLUMN TEMPOMAXINT POSITION 72;

ALTER TABLE SGPREFERE3 ALTER COLUMN LANCAPONTOAF POSITION 73;

ALTER TABLE SGPREFERE3 ALTER COLUMN TOLREGPONTO POSITION 74;

ALTER TABLE SGPREFERE3 ALTER COLUMN USACTOSEQ POSITION 75;

ALTER TABLE SGPREFERE3 ALTER COLUMN LAYOUTFICHAAVAL POSITION 76;

ALTER TABLE SGPREFERE3 ALTER COLUMN LAYOUTPREFICHAAVAL POSITION 77;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV1 POSITION 78;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV1 POSITION 79;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG1 POSITION 80;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV2 POSITION 81;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV2 POSITION 82;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG2 POSITION 83;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV3 POSITION 84;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV3 POSITION 85;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG3 POSITION 86;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV4 POSITION 87;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV4 POSITION 88;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG4 POSITION 89;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV5 POSITION 90;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV5 POSITION 91;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG5 POSITION 92;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV6 POSITION 93;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV6 POSITION 94;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG6 POSITION 95;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV7 POSITION 96;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV7 POSITION 97;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG7 POSITION 98;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPV8 POSITION 99;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALV8 POSITION 100;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODVARG8 POSITION 101;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODEMPSR POSITION 102;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODFILIALSR POSITION 103;

ALTER TABLE SGPREFERE3 ALTER COLUMN CODSETOR POSITION 104;

ALTER TABLE SGPREFERE3 ALTER COLUMN BLOQATENDIMENTO POSITION 105;

ALTER TABLE SGPREFERE3 ALTER COLUMN PERIODOBLOQ POSITION 106;

ALTER TABLE SGPREFERE3 ALTER COLUMN CONTROLEACESATEND POSITION 107;

ALTER TABLE SGPREFERE3 ALTER COLUMN AGENDAOBRIGORC POSITION 108;

ALTER TABLE SGPREFERE3 ALTER COLUMN DTINS POSITION 109;

ALTER TABLE SGPREFERE3 ALTER COLUMN HINS POSITION 110;

ALTER TABLE SGPREFERE3 ALTER COLUMN IDUSUINS POSITION 111;

ALTER TABLE SGPREFERE3 ALTER COLUMN DTALT POSITION 112;

ALTER TABLE SGPREFERE3 ALTER COLUMN HALT POSITION 113;

ALTER TABLE SGPREFERE3 ALTER COLUMN IDUSUALT POSITION 114;


COMMIT WORK;
