INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '01', 'PI', 'Operação Tributável (alíquota normal)');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '02', 'PI', 'Operação Tributável (alíquota diferenciada)');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '03', 'PI', 'Operação Tributável ( alíquota por unidade )');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '04', 'PI', 'Operação Tributável ( tributação monofásica (alíquota zero))');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '06', 'PI', 'Operação Tributável (alíquota zero)');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '07', 'PI', 'Operação Isenta da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '08', 'PI', 'Operação sem Incidência da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '09', 'PI', 'Operação com Suspensão da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '49', 'PI', 'Outras Operações de Saída');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '50', 'PI', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '51', 'PI', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '52', 'PI', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '53', 'PI', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '54', 'PI', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '55', 'PI', 'Operação com Direito a Crédito - Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '56', 'PI', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '60', 'PI', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '61', 'PI', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '62', 'PI', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '63', 'PI', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '64', 'PI', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '65', 'PI', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '66', 'PI', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '67', 'PI', 'Crédito Presumido - Outras Operações');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '70', 'PI', 'Operação de Aquisição sem Direito a Crédito');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '71', 'PI', 'Operação de Aquisição com Isenção');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '72', 'PI', 'Operação de Aquisição com Suspensão');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '73', 'PI', 'Operação de Aquisição a Alíquota Zero');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '74', 'PI', 'Operação de Aquisição sem Incidência da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '75', 'PI', 'Operação de Aquisição por Substituição Tributária');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '98', 'PI', 'Outras Operações de Entrada');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '99', 'PI', 'Outras Operações');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '01', 'CO', 'Operação Tributável (alíquota normal)');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '02', 'CO', 'Operação Tributável (alíquota diferenciada)');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '03', 'CO', 'Operação Tributável ( alíquota por unidade )');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '04', 'CO', 'Operação Tributável ( tributação monofásica (alíquota zero))');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '06', 'CO', 'Operação Tributável (alíquota zero)');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '07', 'CO', 'Operação Isenta da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '08', 'CO', 'Operação sem Incidência da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '09', 'CO', 'Operação com Suspensão da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '49', 'CO', 'Outras Operações de Saída');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '50', 'CO', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '51', 'CO', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '52', 'CO', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '53', 'CO', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '54', 'CO', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '55', 'CO', 'Operação com Direito a Crédito - Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '56', 'CO', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '60', 'CO', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '61', 'CO', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '62', 'CO', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '63', 'CO', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '64', 'CO', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '65', 'CO', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '66', 'CO', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '67', 'CO', 'Crédito Presumido - Outras Operações');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '70', 'CO', 'Operação de Aquisição sem Direito a Crédito');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '71', 'CO', 'Operação de Aquisição com Isenção');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '72', 'CO', 'Operação de Aquisição com Suspensão');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '73', 'CO', 'Operação de Aquisição a Alíquota Zero');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '74', 'CO', 'Operação de Aquisição sem Incidência da Contribuição');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '75', 'CO', 'Operação de Aquisição por Substituição Tributária');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '98', 'CO', 'Outras Operações de Entrada');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '99', 'CO', 'Outras Operações');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '00', 'IP', 'Entrada com recuperação de crédito ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '01', 'IP', 'Entrada tributada com alíquota zero ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '02', 'IP', 'Entrada isenta '); 
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '03', 'IP', 'Entrada não-tributada ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '04', 'IP', 'Entrada imune ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '05', 'IP', 'Entrada com suspensão ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '49', 'IP', 'Outras entradas ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '50', 'IP', 'Saída tributada ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '51', 'IP', 'Saída tributada com alíquota zero ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '52', 'IP', 'Saída isenta');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '53', 'IP', 'Saída não-tributada');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '54', 'IP', 'Saída imune');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '55', 'IP', 'Saída com suspensão ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '60', 'IP', 'ICMS cobrado anteriormente por substituição tributária ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '70', 'IP', 'Saída com suspensão ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '90', 'IP', 'Outras ');
INSERT INTO LFSITTRIB (CODEMP, CODFILIAL, CODSITTRIB, IMPSITTRIB, DESCSITTRIB) VALUES (#CODEMP#, 1, '99', 'IP', 'Com redução de base de cálculo e cobrança do ICMS por substituição tributária '); 

COMMIT WORK;
