/* Server version: LI-V6.3.3.4870 Firebird 1.5 
   SQLDialect: 3. ODS: 10.1. Forced writes: On. Sweep inteval: 20000.
   Page size: 4096. Cache pages: 75 (300 Kb). Read-only: False. */
SET SQL DIALECT 3;

SET AUTODDL ON;

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da empresa do cliente ou fornecedor'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODEMPCF';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da filial do cliente ou fornecedor'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODFILIALCF';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código do cliente ou fornecedor'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODCF';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Indica se a busca é para VD venda ou CP compra'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'TIPOBUSCA';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da empresa do item de classificação fiscal '
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODEMPIFP';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da filial do ítem de classificação fiscal'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODFILIALIFP';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da classificação fiscal'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODFISCP';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código do ítem de classficiação fiscal'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODITFISCP';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da empresa do cliente ou fornecedor'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODEMPCF';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da filial do cliente ou fornecedor'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODFILIALCF';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código do cliente ou fornecedor'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODCF';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Indica se a busca é para VD venda ou CP compra'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'TIPOBUSCA';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da empresa do item de classificação fiscal '
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODEMPIFP';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da filial do ítem de classificação fiscal'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODFILIALIFP';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código da classificação fiscal'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODFISCP';

UPDATE RDB$PROCEDURE_PARAMETERS SET RDB$DESCRIPTION = 
'Código do ítem de classficiação fiscal'
WHERE RDB$PROCEDURE_NAME = 'LFBUSCAFISCALSP' AND RDB$PARAMETER_NAME = 'CODITFISCP';

