INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('RV', 'Receitas S/V', 'E', 'O');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('ER', 'Estorno de receitas', 'S', 'O');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('CV', 'Custos variáveis', 'S', 'N');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('CF', 'Custos fixos', 'S', 'O');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('I', 'Investimentos', 'S', 'N');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('RF', 'Receitas financeiras', 'E', 'N');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('CS', 'Contribuição social', 'S', 'N');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('IR', 'IRPJ', 'S', 'N');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('OR', 'Outras receitas', 'E', 'N');
INSERT INTO FNFINALIDADE (CODFIN, DESCFIN, ESFIN, CLASFIN) VALUES ('OD', 'Outras despesas', 'S', 'N');

COMMIT WORK;
