GRANT EXECUTE ON PROCEDURE PVSEQMOVCAIXASP TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE SPGERANUMPDV TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE VDADICITEMPDVSP TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE PVFECHAVENDASP TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE VDUPVENDAORCSP TO ROLE ADM;
GRANT EXECUTE ON PROCEDURE PVFECHACAIXASP TO ROLE ADM;
GRANT SELECT, INSERT, UPDATE ON TABLE PVCAIXA TO ROLE ADM;
GRANT SELECT, INSERT, UPDATE ON TABLE PVSEQUENCIA TO ROLE ADM;
COMMIT WORK;

