/* Server Version: LI-V6.3.4.4910 Firebird 1.5.  ODS Version: 10.1. */
SET NAMES NONE;

SET SQL DIALECT 3;

--CONNECT 'localhost:/opt/firebird/dados/desenv/freedom1.2.4.9.fdb' USER 'SYSDBA' PASSWORD '123654';

SET AUTODDL ON;

/* Create(Add) Crant */
GRANT SELECT ON ATATENDIMENTOVW01 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW02 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW02 TO PROCEDURE VDCONTRATOTOTSP;

GRANT SELECT ON ATATENDIMENTOVW03 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW04 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW06 TO ADM;

GRANT SELECT ON ATATENDIMENTOVW08 TO ADM;

GRANT SELECT ON FNFLUXOCAIXAVW01 TO ADM;

GRANT SELECT ON TKCONTCLIVW01 TO ADM;

GRANT SELECT ON VWCUSTOPROJ01 TO ADM;



COMMIT WORK;
