package org.freedom.modulos.crm.business.object;


public class ContratoVW {
	
	public enum EColContr { 
		TIPO, INDICE, DESCRICAO, TOTALPREVGERAL, TOTALGERAL, TOTALCOBCLIGERAL, TOTALANT, TOTALCOBCLIANT, TOTALPER, TOTALCOBCLIPER , IDX, CODCONTR, CODCONTRSC, CODITCONTR, CODTAREFA, CODTAREFAST,
		 
	}

}
