/* Após o processamento do estoque */
UPDATE EQSALDOPROD SP 
  SET SLDPROD=(SELECT P.SLDPROD FROM EQPRODUTO P
    WHERE P.CODPROD=SP.CODPROD AND P.CODEMP=SP.CODEMP AND 
       P.CODFILIAL=SP.CODFILIAL);
       
COMMIT WORK;
       